In [2]:
#Okay tric here would be sure to locate files and be sure of where are and then inspect them 
# lets do that then what we get will determine our game plan

from pathlib import Path
import pandas as pd


RAW_DIR = Path(
    r"C:\Users\Student\Downloads\Big Data\SPU-TEAM-DIRISA"
    r"\data\raw\KZN_Local_Goverment_elections_2011-21"
)

files = [
    RAW_DIR / "KZN_2011.csv",
    RAW_DIR / "KZN_2016.csv",
    RAW_DIR / "KZN_2021.csv",
]


# ---------------------------------------------------------
# ENCODING DETECTION
# ---------------------------------------------------------

def detect_encoding(file_path):
    """
    Detect common encodings using BOM first,
    then try common Windows/Unicode encodings.
    """
    
    with open(file_path, "rb") as f:
        raw = f.read(4)

    # Byte Order Marks
    if raw.startswith(b"\xff\xfe"):
        return "utf-16"
    
    if raw.startswith(b"\xfe\xff"):
        return "utf-16"
    
    if raw.startswith(b"\xef\xbb\xbf"):
        return "utf-8-sig"

    # No BOM: test common encodings
    for encoding in ["utf-8", "cp1252", "latin1"]:
        try:
            with open(file_path, "r", encoding=encoding) as f:
                f.read(5000)
            return encoding
        except UnicodeDecodeError:
            continue

    return "unknown"


# ---------------------------------------------------------
# INSPECT EACH FILE
# ---------------------------------------------------------

for file in files:

    print("=" * 90)
    print(f"FILE: {file.name}")
    print("=" * 90)

    if not file.exists():
        print("WARNING: File not found")
        continue

    encoding = detect_encoding(file)

    print(f"Detected encoding: {encoding}")

    if encoding == "unknown":
        print("Could not determine encoding safely.")
        continue

    # Try reading the CSV
    try:
        df = pd.read_csv(
            file,
            encoding=encoding
        )

        print(f"Rows: {len(df):,}")
        print(f"Columns: {len(df.columns)}")

        print("\nColumns:")
        print(df.columns.tolist())

        print("\nFirst 5 rows:")
        display(df.head())

        print("\nData types:")
        print(df.dtypes)

        print("\nMissing values:")
        print(df.isna().sum())

        print("\nDuplicate rows:")
        print(df.duplicated().sum())

    except Exception as e:
        print(f"READ ERROR: {type(e).__name__}: {e}")

    print()

==========================================================================================
FILE: KZN_2011.csv
==========================================================================================
Detected encoding: utf-16
Rows: 90,500
Columns: 11

Columns:
['Province', 'Municipality', 'Ward', 'VotingDistrict', 'VotingStationName', 'RegisteredVoters', 'BallotType', 'SpoiltVotes', 'PartyName', 'TotalValidVotes', 'DateGenerated']

First 5 rows:

,Province,Municipality,Ward,VotingDistrict,VotingStationName,RegisteredVoters,BallotType,SpoiltVotes,PartyName,TotalValidVotes,DateGenerated
0,KwaZulu-Natal,ETH - eThekwini [Durban Metro],Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1438,PR,26,AFRICAN CHRISTIAN ALLIANCE-AFRIKANER CHRISTEN ...,1,5/26/2011 4:36:55 PM
1,KwaZulu-Natal,ETH - eThekwini [Durban Metro],Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1438,PR,26,AFRICAN CHRISTIAN DEMOCRATIC PARTY,0,5/26/2011 4:36:55 PM
2,KwaZulu-Natal,ETH - eThekwini [Durban Metro],Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1438,PR,26,AFRICAN NATIONAL CONGRESS,973,5/26/2011 4:36:55 PM
3,KwaZulu-Natal,ETH - eThekwini [Durban Metro],Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1438,PR,26,AFRICAN PEOPLE'S CONVENTION,2,5/26/2011 4:36:55 PM
4,KwaZulu-Natal,ETH - eThekwini [Durban Metro],Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1438,PR,26,AZANIAN PEOPLE'S ORGANISATION,1,5/26/2011 4:36:55 PM

Data types:
Province             object
Municipality         object
Ward                 object
VotingDistrict        int64
VotingStationName    object
RegisteredVoters      int64
BallotType           object
SpoiltVotes           int64
PartyName            object
TotalValidVotes       int64
DateGenerated        object
dtype: object

Missing values:
Province             0
Municipality         0
Ward                 0
VotingDistrict       0
VotingStationName    0
RegisteredVoters     0
BallotType           0
SpoiltVotes          0
PartyName            0
TotalValidVotes      0
DateGenerated        0
dtype: int64

Duplicate rows:
0

==========================================================================================
FILE: KZN_2016.csv
==========================================================================================
Detected encoding: utf-8-sig
Rows: 117,987
Columns: 11

Columns:
['Province', 'Municipality', 'Ward', 'VotingDistrict', 'VotingStationName', 'RegisteredVoters', 'BallotType', 'SpoiltVotes', 'PartyName', 'TotalValidVotes', 'DateGenerated']

First 5 rows:

,Province,Municipality,Ward,VotingDistrict,VotingStationName,RegisteredVoters,BallotType,SpoiltVotes,PartyName,TotalValidVotes,DateGenerated
0,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,ACADEMIC CONGRESS UNION,0,8/11/2016 4:23:02 PM
1,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,AFRICAN CHRISTIAN DEMOCRATIC PARTY,0,8/11/2016 4:23:02 PM
2,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,AFRICAN INDEPENDENT CONGRESS,19,8/11/2016 4:23:02 PM
3,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,AFRICAN MANTUNGWA COMMUNITY,0,8/11/2016 4:23:02 PM
4,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,AFRICAN NATIONAL CONGRESS,1157,8/11/2016 4:23:02 PM

Data types:
Province             object
Municipality         object
Ward                 object
VotingDistrict        int64
VotingStationName    object
RegisteredVoters      int64
BallotType           object
SpoiltVotes           int64
PartyName            object
TotalValidVotes       int64
DateGenerated        object
dtype: object

Missing values:
Province             0
Municipality         0
Ward                 0
VotingDistrict       0
VotingStationName    0
RegisteredVoters     0
BallotType           0
SpoiltVotes          0
PartyName            0
TotalValidVotes      0
DateGenerated        0
dtype: int64

Duplicate rows:
0

==========================================================================================
FILE: KZN_2021.csv
==========================================================================================
Detected encoding: utf-8-sig
Rows: 251,001
Columns: 11

Columns:
['Province', 'Municipality', 'Ward', 'VotingDistrict', 'VotingStationName', 'RegisteredVoters', 'BallotType', 'SpoiltVotes', 'PartyName', 'TotalValidVotes', 'DateGenerated']

First 5 rows:

,Province,Municipality,Ward,VotingDistrict,VotingStationName,RegisteredVoters,BallotType,SpoiltVotes,PartyName,TotalValidVotes,DateGenerated
0,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,2365,PR,12,ABANTU BATHO CONGRESS,14,11/23/2021 4:42:14 PM
1,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,2365,PR,12,ACADEMIC CONGRESS UNION,0,11/23/2021 4:42:14 PM
2,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,2365,PR,12,ACTIONSA,0,11/23/2021 4:42:14 PM
3,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,2365,PR,12,ACTIVE CITIZENS COALITION,0,11/23/2021 4:42:14 PM
4,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,2365,PR,12,ACTIVISTS MOVEMENT OF SOUTH AFRICA,0,11/23/2021 4:42:14 PM

Data types:
Province             object
Municipality         object
Ward                 object
VotingDistrict        int64
VotingStationName    object
RegisteredVoters      int64
BallotType           object
SpoiltVotes           int64
PartyName            object
TotalValidVotes       int64
DateGenerated        object
dtype: object

Missing values:
Province             0
Municipality         0
Ward                 0
VotingDistrict       0
VotingStationName    0
RegisteredVoters     0
BallotType           0
SpoiltVotes          0
PartyName            0
TotalValidVotes      0
DateGenerated        0
dtype: int64

Duplicate rows:
0

In [3]:
from pathlib import Path
import pandas as pd

# Set the raw and cleaned data folders
BASE_DIR = Path(r"C:\Users\Student\Downloads\Big Data\SPU-TEAM-DIRISA")
RAW_DIR = BASE_DIR / "data" / "raw" / "KZN_Local_Goverment_elections_2011-21"
CLEAN_DIR = BASE_DIR / "data" / "interim" / "KZN_Local_Goverment_elections_2011-21 Cleaned"

CLEAN_DIR.mkdir(parents=True, exist_ok=True)

# Read each election year using its detected encoding
files = {
    2011: ("KZN_2011.csv", "utf-16"),
    2016: ("KZN_2016.csv", "utf-8-sig"),
    2021: ("KZN_2021.csv", "utf-8-sig")
}

data = {}

for year, (filename, encoding) in files.items():
    data[year] = pd.read_csv(
        RAW_DIR / filename,
        encoding=encoding,
        low_memory=False
    )
    print(f"{year}: {len(data[year]):,} rows loaded")

2011: 90,500 rows loaded
2016: 117,987 rows loaded
2021: 251,001 rows loaded

In [4]:
# Okay now lets begin our data cleaning


# Clean column names and text fields without changing their meaning
# This keeps party, municipality, station and ward values consistent

text_columns = [
    "Province",
    "Municipality",
    "Ward",
    "VotingStationName",
    "BallotType",
    "PartyName"
]

for year, df in data.items():

    # Clean column names
    df.columns = (
        df.columns
        .str.replace("\ufeff", "", regex=False)
        .str.strip()
    )

    # Clean text values
    for column in text_columns:
        df[column] = (
            df[column]
            .astype("string")
            .str.replace("\u00a0", " ", regex=False)
            .str.replace(r"\s+", " ", regex=True)
            .str.strip()
        )

    print(f"\n{year}")
    print("Columns:", df.columns.tolist())
    print("Text fields cleaned successfully")

2011
Columns: ['Province', 'Municipality', 'Ward', 'VotingDistrict', 'VotingStationName', 'RegisteredVoters', 'BallotType', 'SpoiltVotes', 'PartyName', 'TotalValidVotes', 'DateGenerated']
Text fields cleaned successfully

2016
Columns: ['Province', 'Municipality', 'Ward', 'VotingDistrict', 'VotingStationName', 'RegisteredVoters', 'BallotType', 'SpoiltVotes', 'PartyName', 'TotalValidVotes', 'DateGenerated']
Text fields cleaned successfully

2021
Columns: ['Province', 'Municipality', 'Ward', 'VotingDistrict', 'VotingStationName', 'RegisteredVoters', 'BallotType', 'SpoiltVotes', 'PartyName', 'TotalValidVotes', 'DateGenerated']
Text fields cleaned successfully

In [5]:
# Check election counts for invalid, negative or missing values
# We keep the original values untouched until the checks are complete

numeric_columns = [
    "RegisteredVoters",
    "SpoiltVotes",
    "TotalValidVotes"
]

for year, df in data.items():

    print("\n" + "=" * 70)
    print(f"KZN {year} — NUMERIC DATA CHECK")
    print("=" * 70)

    for column in numeric_columns:

        # Convert only for checking; the dataset is not changed here
        values = pd.to_numeric(df[column], errors="coerce")

        print(f"\n{column}")
        print(f"  Missing: {values.isna().sum():,}")
        print(f"  Negative: {(values < 0).sum():,}")
        print(f"  Minimum: {values.min()}")
        print(f"  Maximum: {values.max()}")

    # Check whether valid votes exceed registered voters
    registered = pd.to_numeric(
        df["RegisteredVoters"],
        errors="coerce"
    )

    valid = pd.to_numeric(
        df["TotalValidVotes"],
        errors="coerce"
    )

    over_registered = valid > registered

    print(
        f"\nValid votes greater than registered voters: "
        f"{over_registered.sum():,}"
    )

======================================================================
KZN 2011 — NUMERIC DATA CHECK
======================================================================

RegisteredVoters
  Missing: 0
  Negative: 0
  Minimum: 24
  Maximum: 7712

SpoiltVotes
  Missing: 0
  Negative: 0
  Minimum: 0
  Maximum: 654

TotalValidVotes
  Missing: 0
  Negative: 0
  Minimum: 0
  Maximum: 3577

Valid votes greater than registered voters: 6

======================================================================
KZN 2016 — NUMERIC DATA CHECK
======================================================================

RegisteredVoters
  Missing: 0
  Negative: 0
  Minimum: 23
  Maximum: 8099

SpoiltVotes
  Missing: 0
  Negative: 0
  Minimum: 0
  Maximum: 993

TotalValidVotes
  Missing: 0
  Negative: 0
  Minimum: 0
  Maximum: 4175

Valid votes greater than registered voters: 4

======================================================================
KZN 2021 — NUMERIC DATA CHECK
======================================================================

RegisteredVoters
  Missing: 0
  Negative: 0
  Minimum: 8
  Maximum: 7910

SpoiltVotes
  Missing: 0
  Negative: 0
  Minimum: 0
  Maximum: 267

TotalValidVotes
  Missing: 0
  Negative: 0
  Minimum: 0
  Maximum: 3163

Valid votes greater than registered voters: 12

In [6]:
# Inspect records where valid votes exceed registered voters
# These records will not be deleted until we understand why they occur

for year, df in data.items():

    registered = pd.to_numeric(
        df["RegisteredVoters"],
        errors="coerce"
    )

    valid = pd.to_numeric(
        df["TotalValidVotes"],
        errors="coerce"
    )

    suspicious = df.loc[
        valid > registered,
        [
            "Province",
            "Municipality",
            "Ward",
            "VotingDistrict",
            "VotingStationName",
            "RegisteredVoters",
            "SpoiltVotes",
            "PartyName",
            "TotalValidVotes"
        ]
    ]

    print("\n" + "=" * 90)
    print(f"KZN {year} — SUSPICIOUS VOTE RECORDS")
    print("=" * 90)
    print(f"Records found: {len(suspicious):,}")

    display(suspicious)

==========================================================================================
KZN 2011 — SUSPICIOUS VOTE RECORDS
==========================================================================================
Records found: 6

,Province,Municipality,Ward,VotingDistrict,VotingStationName,RegisteredVoters,SpoiltVotes,PartyName,TotalValidVotes
51371,KwaZulu-Natal,KZN244 - Msinga [Pomeroy],Ward 52404011,43625684,NTABENDE COMBINED PRIMARY SCHOOL,517,8,INKATHA FREEDOM PARTY,914
51376,KwaZulu-Natal,KZN244 - Msinga [Pomeroy],Ward 52404011,43625684,NTABENDE COMBINED PRIMARY SCHOOL,517,21,INKATHA FREEDOM PARTY,914
51381,KwaZulu-Natal,KZN244 - Msinga [Pomeroy],Ward 52404011,43625684,NTABENDE COMBINED PRIMARY SCHOOL,517,21,INKATHA FREEDOM PARTY,914
83023,KwaZulu-Natal,KZN293 - Ndwedwe [Ndwedwe],Ward 52903016,43581911,CIBANE TRIBAL COURT,539,37,AFRICAN NATIONAL CONGRESS,603
83029,KwaZulu-Natal,KZN293 - Ndwedwe [Ndwedwe],Ward 52903016,43581911,CIBANE TRIBAL COURT,539,37,AFRICAN NATIONAL CONGRESS,603
83037,KwaZulu-Natal,KZN293 - Ndwedwe [Ndwedwe],Ward 52903016,43581911,CIBANE TRIBAL COURT,539,37,AFRICAN NATIONAL CONGRESS,603

==========================================================================================
KZN 2016 — SUSPICIOUS VOTE RECORDS
==========================================================================================
Records found: 4

,Province,Municipality,Ward,VotingDistrict,VotingStationName,RegisteredVoters,SpoiltVotes,PartyName,TotalValidVotes
24750,KwaZulu-Natal,ETH - eThekwini,Ward 59500069,43371592,OCEANVIEW PRIMARY SCHOOL,1619,0,DEMOCRATIC ALLIANCE,1726
24775,KwaZulu-Natal,ETH - eThekwini,Ward 59500069,43371592,OCEANVIEW PRIMARY SCHOOL,1619,0,DEMOCRATIC ALLIANCE,1726
109371,KwaZulu-Natal,KZN293 - Ndwedwe,Ward 52903016,43581832,KWAMKHUMBUZI SCHOOL,277,5,AFRICAN NATIONAL CONGRESS,350
109379,KwaZulu-Natal,KZN293 - Ndwedwe,Ward 52903016,43581832,KWAMKHUMBUZI SCHOOL,277,3,AFRICAN NATIONAL CONGRESS,351

==========================================================================================
KZN 2021 — SUSPICIOUS VOTE RECORDS
==========================================================================================
Records found: 12

,Province,Municipality,Ward,VotingDistrict,VotingStationName,RegisteredVoters,SpoiltVotes,PartyName,TotalValidVotes
110404,KwaZulu-Natal,KZN225 - Msunduzi,Ward 52205018,43951451,TENT AT INTABA RIDGE OPEN SPACE,68,0,DEMOCRATIC ALLIANCE,84
110426,KwaZulu-Natal,KZN225 - Msunduzi,Ward 52205018,43951451,TENT AT INTABA RIDGE OPEN SPACE,68,0,DEMOCRATIC ALLIANCE,86
110451,KwaZulu-Natal,KZN225 - Msunduzi,Ward 52205018,43951451,TENT AT INTABA RIDGE OPEN SPACE,68,0,DEMOCRATIC ALLIANCE,87
133919,KwaZulu-Natal,KZN238 - Alfred Duma,Ward 52308018,43690293,KWAPHAYIKENI HIGH SCHOOL,399,10,AFRICAN NATIONAL CONGRESS,438
146258,KwaZulu-Natal,KZN244 - uMsinga,Ward 52404005,43626214,OSUTHU PRIMARY SCHOOL,48,3,INKATHA FREEDOM PARTY,51
146270,KwaZulu-Natal,KZN244 - uMsinga,Ward 52404005,43626214,OSUTHU PRIMARY SCHOOL,48,3,INKATHA FREEDOM PARTY,52
146281,KwaZulu-Natal,KZN244 - uMsinga,Ward 52404005,43626214,OSUTHU PRIMARY SCHOOL,48,2,INKATHA FREEDOM PARTY,52
147263,KwaZulu-Natal,KZN244 - uMsinga,Ward 52404010,43620195,DUMAKUDE PRIMARY SCHOOL,519,37,INKATHA FREEDOM PARTY,609
182810,KwaZulu-Natal,KZN266 - Ulundi,Ward 52606005,43505311,NTAMBONDE CRECHE,79,3,INKATHA FREEDOM PARTY,134
182825,KwaZulu-Natal,KZN266 - Ulundi,Ward 52606005,43505311,NTAMBONDE CRECHE,79,4,INKATHA FREEDOM PARTY,132
182833,KwaZulu-Natal,KZN266 - Ulundi,Ward 52606005,43505311,NTAMBONDE CRECHE,79,2,INKATHA FREEDOM PARTY,132
241205,KwaZulu-Natal,KZN433 - Greater Kokstad,Ward 54303002,43775578,NTSIMBINI PRIMARY SCHOOL,98,7,AFRICAN NATIONAL CONGRESS,117

In [7]:
# Check for repeated electoral records within each election year
# Duplicates are reviewed before any records are removed

duplicate_columns = [
    "Municipality",
    "Ward",
    "VotingDistrict",
    "VotingStationName",
    "BallotType",
    "PartyName",
    "TotalValidVotes"
]

for year, df in data.items():

    duplicates = df[df.duplicated(
        subset=duplicate_columns,
        keep=False
    )].sort_values(duplicate_columns)

    print("\n" + "=" * 80)
    print(f"KZN {year} — DUPLICATE RECORD CHECK")
    print("=" * 80)
    print(f"Duplicate records found: {len(duplicates):,}")

    if len(duplicates) > 0:
        display(duplicates.head(30))

================================================================================
KZN 2011 — DUPLICATE RECORD CHECK
================================================================================
Duplicate records found: 0

================================================================================
KZN 2016 — DUPLICATE RECORD CHECK
================================================================================
Duplicate records found: 0

================================================================================
KZN 2021 — DUPLICATE RECORD CHECK
================================================================================
Duplicate records found: 0

In [8]:
# Check vote-count columns for formatting and data-type issues
# This identifies values that need conversion before the final clean save

vote_columns = [
    "RegisteredVoters",
    "SpoiltVotes",
    "TotalValidVotes"
]

for year, df in data.items():

    print("\n" + "=" * 80)
    print(f"KZN {year} — VOTE COUNT FORMAT CHECK")
    print("=" * 80)

    for column in vote_columns:

        numeric_check = pd.to_numeric(
            df[column],
            errors="coerce"
        )

        print(f"\n{column}")
        print(f"  Original type: {df[column].dtype}")
        print(f"  Non-numeric values: {numeric_check.isna().sum():,}")
        print(f"  Unique values: {df[column].nunique():,}")

================================================================================
KZN 2011 — VOTE COUNT FORMAT CHECK
================================================================================

RegisteredVoters
  Original type: int64
  Non-numeric values: 0
  Unique values: 2,013

SpoiltVotes
  Original type: int64
  Non-numeric values: 0
  Unique values: 139

TotalValidVotes
  Original type: int64
  Non-numeric values: 0
  Unique values: 1,654

================================================================================
KZN 2016 — VOTE COUNT FORMAT CHECK
================================================================================

RegisteredVoters
  Original type: int64
  Non-numeric values: 0
  Unique values: 2,171

SpoiltVotes
  Original type: int64
  Non-numeric values: 0
  Unique values: 176

TotalValidVotes
  Original type: int64
  Non-numeric values: 0
  Unique values: 1,714

================================================================================
KZN 2021 — VOTE COUNT FORMAT CHECK
================================================================================

RegisteredVoters
  Original type: int64
  Non-numeric values: 0
  Unique values: 2,177

SpoiltVotes
  Original type: int64
  Non-numeric values: 0
  Unique values: 135

TotalValidVotes
  Original type: int64
  Non-numeric values: 0
  Unique values: 1,176

In [9]:
# Check ward-code formatting and leading-zero preservation
# Ward values are inspected before any formatting changes are made

for year, df in data.items():

    print("\n" + "=" * 80)
    print(f"KZN {year} — WARD CODE FORMAT CHECK")
    print("=" * 80)

    ward_values = df["Ward"].astype("string").str.strip()

    print(f"Unique ward values: {ward_values.nunique():,}")
    print(f"Missing ward values: {ward_values.isna().sum():,}")

    # Check ward values that do not follow the expected "Ward XXXXXXXX" format
    invalid_wards = ward_values[
        ~ward_values.str.match(r"^Ward \d+$", na=False)
    ]

    print(f"Unexpected ward formats: {len(invalid_wards):,}")

    if len(invalid_wards) > 0:
        display(
            pd.DataFrame({
                "Ward": invalid_wards.drop_duplicates()
            }).head(30)
        )

================================================================================
KZN 2011 — WARD CODE FORMAT CHECK
================================================================================
Unique ward values: 828
Missing ward values: 0
Unexpected ward formats: 0

================================================================================
KZN 2016 — WARD CODE FORMAT CHECK
================================================================================
Unique ward values: 870
Missing ward values: 0
Unexpected ward formats: 0

================================================================================
KZN 2021 — WARD CODE FORMAT CHECK
================================================================================
Unique ward values: 901
Missing ward values: 0
Unexpected ward formats: 0

In [10]:
# Check party-name consistency within each election year
# This identifies spelling and formatting variations before standardization

for year, df in data.items():

    print("\n" + "=" * 80)
    print(f"KZN {year} — PARTY NAME CHECK")
    print("=" * 80)

    party_names = (
        df["PartyName"]
        .dropna()
        .astype("string")
        .str.strip()
    )

    print(f"Unique party names: {party_names.nunique():,}")

    display(
        pd.DataFrame({
            "PartyName": sorted(party_names.unique())
        })
    )

================================================================================
KZN 2011 — PARTY NAME CHECK
================================================================================
Unique party names: 28

                                            PartyName
0   AFRICAN CHRISTIAN ALLIANCE-AFRIKANER CHRISTEN ...
1                  AFRICAN CHRISTIAN DEMOCRATIC PARTY
2                        AFRICAN INDEPENDENT CONGRESS
3                           AFRICAN NATIONAL CONGRESS
4                         AFRICAN PEOPLE'S CONVENTION
5                       AZANIAN PEOPLE'S ORGANISATION
6                           BLACK CONSCIOUSNESS PARTY
7                              CONGRESS OF THE PEOPLE
8          DEMOCRATIC ALLIANCE/DEMOKRATIESE ALLIANSIE
9                                    FEDERAL CONGRESS
10                     GREAT KONGRESS OF SOUTH AFRICA
11                                        INDEPENDENT
12                              INKATHA FREEDOM PARTY
13                                     MINORITY FRONT
14                     NATIONAL DEMOCRATIC CONVENTION
15                             NATIONAL FREEDOM PARTY
16                      OWETHU RESIDENTS ORGANISATION
17                  PAN AFRICANIST CONGRESS OF AZANIA
18                               ROYAL LOYAL PROGRESS
19                          SOCIALIST GREEN COALITION
20                                   SOLIDARITY PARTY
21                  SOUTH AFRICAN DEMOCRATIC CONGRESS
22                SOUTH AFRICAN DETERMINED VOLUNTEERS
23                                     TRULY ALLIANCE
24                                UNITED ACTION FRONT
25                         UNITED DEMOCRATIC MOVEMENT
26                             UNITED RESIDENTS FRONT
27                                 VRYHEIDSFRONT PLUS

================================================================================
KZN 2016 — PARTY NAME CHECK
================================================================================
Unique party names: 39

                                   PartyName
0                    ACADEMIC CONGRESS UNION
1         AFRICAN CHRISTIAN DEMOCRATIC PARTY
2               AFRICAN INDEPENDENT CONGRESS
3                AFRICAN MANTUNGWA COMMUNITY
4                  AFRICAN NATIONAL CONGRESS
5                AFRICAN PEOPLE'S CONVENTION
6                                 AL JAMA-AH
7                 ALLIED MOVEMENT FOR CHANGE
8              AZANIAN PEOPLE'S ORGANISATION
9                 CHRISTIAN DEMOCRATIC PARTY
10                    CONGRESS OF THE PEOPLE
11                       DEMOCRATIC ALLIANCE
12               DEMOCRATIC LIBERAL CONGRESS
13                 ECONOMIC FREEDOM FIGHTERS
14                               INDEPENDENT
15                INDEPENDENT PEOPLE'S PARTY
16  INDEPENDENT RATEPAYERS ASSOCIATION OF SA
17                     INKATHA FREEDOM PARTY
18       ISITHUNZI SOM-AFRIKA ECONO FIGHTERS
19               KINGDOM GOVERNANCE MOVEMENT
20                MINORITIES OF SOUTH AFRICA
21                            MINORITY FRONT
22            NATIONAL DEMOCRATIC CONVENTION
23                    NATIONAL FREEDOM PARTY
24              NATIONAL PEOPLES AMBASSADORS
25         PAN AFRICANIST CONGRESS OF AZANIA
26           PEOPLE'S REVOLUTIONARY MOVEMENT
27                          PEOPLES ALLIANCE
28                      ROYAL LOYAL PROGRESS
29             SOUTH AFRICAN POLITICAL PARTY
30                      STRENGTH OF HUMANITY
31                    THE PROMISE OF FREEDOM
32                            TRULY ALLIANCE
33               UBUMBANO LWESIZWE SABANGONI
34                UNITED DEMOCRATIC MOVEMENT
35                      UNITED PEOPLES PARTY
36                    UNITED RESIDENTS FRONT
37                        VRYHEIDSFRONT PLUS
38                       ZULU ROYAL PROPERTY

================================================================================
KZN 2021 — PARTY NAME CHECK
================================================================================
Unique party names: 79

                             PartyName
0   ABAHLALI BASE MKHANYAKUDE MOVEMENT
1                ABANTU BATHO CONGRESS
2              ACADEMIC CONGRESS UNION
3                             ACTIONSA
4            ACTIVE CITIZENS COALITION
..                                 ...
74            UNITED CULTURAL MOVEMENT
75          UNITED DEMOCRATIC MOVEMENT
76         UNITED INDEPENDENT MOVEMENT
77                  VRYHEIDSFRONT PLUS
78                 ZULU ROYAL PROPERTY

[79 rows x 1 columns]

In [11]:
# Check for hidden party-name variations after text normalization
# Genuine historical party names are kept unchanged

for year, df in data.items():

    normalized = (
        df["PartyName"]
        .astype("string")
        .str.upper()
        .str.replace(r"\s+", " ", regex=True)
        .str.strip()
    )

    check = pd.DataFrame({
        "Original": df["PartyName"],
        "Normalized": normalized
    }).drop_duplicates()

    variations = check[
        check.duplicated("Normalized", keep=False)
    ].sort_values("Normalized")

    print("\n" + "=" * 80)
    print(f"KZN {year} — NORMALIZED PARTY NAME CHECK")
    print("=" * 80)
    print(f"Hidden variations found: {len(variations):,}")

    if len(variations) > 0:
        display(variations)

================================================================================
KZN 2011 — NORMALIZED PARTY NAME CHECK
================================================================================
Hidden variations found: 0

================================================================================
KZN 2016 — NORMALIZED PARTY NAME CHECK
================================================================================
Hidden variations found: 0

================================================================================
KZN 2021 — NORMALIZED PARTY NAME CHECK
================================================================================
Hidden variations found: 0

In [12]:
# Apply confirmed cleaning changes and save the interim datasets
# Raw files remain untouched and only cleaned copies are written

for year, df in data.items():

    clean_df = df.copy()

    # Standardize text fields without changing their meaning
    for column in text_columns:
        clean_df[column] = (
            clean_df[column]
            .astype("string")
            .str.replace("\u00a0", " ", regex=False)
            .str.replace(r"\s+", " ", regex=True)
            .str.strip()
        )

    # Keep vote-count columns as numeric integers
    for column in numeric_columns:
        clean_df[column] = pd.to_numeric(
            clean_df[column],
            errors="raise"
        ).astype("int64")

    # Validate the cleaned dataset before saving
    assert clean_df.columns.tolist() == [
        "Province",
        "Municipality",
        "Ward",
        "VotingDistrict",
        "VotingStationName",
        "RegisteredVoters",
        "BallotType",
        "SpoiltVotes",
        "PartyName",
        "TotalValidVotes",
        "DateGenerated"
    ]

    assert clean_df.isna().sum().sum() == 0
    assert clean_df.duplicated().sum() == 0

    output_file = CLEAN_DIR / f"KZN_{year}_clean.csv"

    clean_df.to_csv(
        output_file,
        index=False,
        encoding="utf-8-sig"
    )

    print(
        f"KZN {year}: {len(clean_df):,} rows saved -> "
        f"{output_file.name}"
    )

KZN 2011: 90,500 rows saved -> KZN_2011_clean.csv
KZN 2016: 117,987 rows saved -> KZN_2016_clean.csv
KZN 2021: 251,001 rows saved -> KZN_2021_clean.csv

In [13]:
# Verify that all cleaned files exist and retain the expected row counts
# This confirms the interim cleaning outputs are ready for the next dataset

expected_rows = {
    2011: 90_500,
    2016: 117_987,
    2021: 251_001
}

for year, expected in expected_rows.items():

    output_file = CLEAN_DIR / f"KZN_{year}_clean.csv"

    check_df = pd.read_csv(
        output_file,
        encoding="utf-8-sig",
        low_memory=False
    )

    print(
        f"KZN {year}: "
        f"{len(check_df):,} rows | "
        f"{len(check_df.columns)} columns | "
        f"File exists: {output_file.exists()} | "
        f"Row count correct: {len(check_df) == expected}"
    )

KZN 2011: 90,500 rows | 11 columns | File exists: True | Row count correct: True
KZN 2016: 117,987 rows | 11 columns | File exists: True | Row count correct: True
KZN 2021: 251,001 rows | 11 columns | File exists: True | Row count correct: True