In [1]:
from pathlib import Path
import pandas as pd

# Set the raw and cleaned data folders
BASE_DIR = Path(r"C:\Users\Student\Downloads\Big Data\SPU-TEAM-DIRISA")
RAW_DIR = BASE_DIR / "data" / "raw" / "KZN_Electoral_participation"
CLEAN_DIR = BASE_DIR / "data" / "interim" / "KZN_Electoral_participation Cleaned"

CLEAN_DIR.mkdir(parents=True, exist_ok=True)

# List the electoral participation files to inspect
files = [
    "P02111stQuarter2024.csv",
    "P03182024.csv",
    "Presentation-QLFS-Q1-2026.csv"
]

for filename in files:

    file_path = RAW_DIR / filename

    print("\n" + "=" * 80)
    print(filename)
    print("=" * 80)

    # Detect the file encoding before loading
    encodings = ["utf-8-sig", "utf-8", "utf-16", "latin1"]

    for encoding in encodings:
        try:
            df = pd.read_csv(
                file_path,
                encoding=encoding,
                low_memory=False
            )
            print(f"Encoding: {encoding}")
            print(f"Rows: {len(df):,}")
            print(f"Columns: {len(df.columns)}")
            print("Column names:")
            print(df.columns.tolist())
            print("\nData types:")
            print(df.dtypes)
            print("\nMissing values:")
            print(df.isna().sum())
            print("\nFirst 5 rows:")
            display(df.head())
            break

        except (UnicodeDecodeError, pd.errors.ParserError):
            continue

================================================================================
P02111stQuarter2024.csv
================================================================================
Encoding: utf-8-sig
Rows: 5,614
Columns: 1
Column names:
['Private Bag X44, Pretoria, 0001, South Africa, ISIbalo House, Koch Street, Salvokop, Pretoria, 0002']

Data types:
Private Bag X44, Pretoria, 0001, South Africa, ISIbalo House, Koch Street, Salvokop, Pretoria, 0002    object
dtype: object

Missing values:
Private Bag X44, Pretoria, 0001, South Africa, ISIbalo House, Koch Street, Salvokop, Pretoria, 0002    1340
dtype: int64

First 5 rows:

  Private Bag X44, Pretoria, 0001, South Africa, ISIbalo House, Koch Street, Salvokop, Pretoria, 0002
0  www.statssa.gov.za, info@statssa.gov.za, Tel +...
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

================================================================================
P03182024.csv
================================================================================
Encoding: utf-8-sig
Rows: 6,890
Columns: 1
Column names:
['Private Bag X44, Pretoria, 0001, South Africa, ISIbalo House, Koch Street, Salvokop, Pretoria, 0002']

Data types:
Private Bag X44, Pretoria, 0001, South Africa, ISIbalo House, Koch Street, Salvokop, Pretoria, 0002    object
dtype: object

Missing values:
Private Bag X44, Pretoria, 0001, South Africa, ISIbalo House, Koch Street, Salvokop, Pretoria, 0002    2214
dtype: int64

First 5 rows:

  Private Bag X44, Pretoria, 0001, South Africa, ISIbalo House, Koch Street, Salvokop, Pretoria, 0002
0  www.statssa.gov.za, info@statssa.gov.za, Tel +...
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

================================================================================
Presentation-QLFS-Q1-2026.csv
================================================================================
Encoding: utf-8-sig
Rows: 372
Columns: 1
Column names:
['Quarterly Labour Force Survey (QLFS)']

Data types:
Quarterly Labour Force Survey (QLFS)    object
dtype: object

Missing values:
Quarterly Labour Force Survey (QLFS)    145
dtype: int64

First 5 rows:

                Quarterly Labour Force Survey (QLFS)
0                                            Q1:2026
1                                                NaN
2                                   Risenga Maluleke
3                               Statistician-General
4
Stats SA adopting more recent ICLS resolution...

In [2]:
# Inspect the raw file structure before choosing a cleaning method
# This prevents metadata and presentation rows from being treated as data

for filename in files:

    file_path = RAW_DIR / filename

    print("\n" + "=" * 90)
    print(f"{filename} — RAW STRUCTURE")
    print("=" * 90)

    with open(
        file_path,
        "r",
        encoding="utf-8-sig",
        errors="replace"
    ) as f:

        lines = [next(f, "").rstrip("\n\r") for _ in range(40)]

    for number, line in enumerate(lines, start=1):
        print(f"{number:03}: {line[:500]}")

==========================================================================================
P02111stQuarter2024.csv — RAW STRUCTURE
==========================================================================================
001: "Private Bag X44, Pretoria, 0001, South Africa, ISIbalo House, Koch Street, Salvokop, Pretoria, 0002"
002: "www.statssa.gov.za, info@statssa.gov.za, Tel +27 12 310 8911"
003: ""
004: ""
005: ""
006: ""
007: "STATISTICAL RELEASE"
008: "P0211"
009: ""
010: ""
011: ""
012: ""
013: "Quarterly Labour Force Survey"
014: ""
015: "Quarter 1: 2024"
016: ""
017: ""
018: ""
019: ""
020: "Embargoed until:"
021: "14 May 2024"
022: "11:30"
023: ""
024: ""
025: ""
026: ""
027: "ENQUIRIES:                              FORTHCOMING ISSUE:                   EXPECTED RELEASE DATE:"
028: "User Information Services               Quarter 2: 2024                      August 2024"
029: "(012) 310 8600/4892/8390"
030: "STATISTICS SOUTH AFRICA                                                               ii                                                                                P0211"
031: ""
032: ""
033: "Contents"
034: "Page"
035: "List of tables ....................................................................................................................................................... iii"
036: "List of figures...................................................................................................................................................... iv"
037: "Appendices ......................................................................................................................................................... v"
038: "1. Introduction .....................................................................................................................................................1"
039: "2. Highlights of the results ..................................................................................................................................1"
040: "3. Employment ....................................................................................................................................................2"

==========================================================================================
P03182024.csv — RAW STRUCTURE
==========================================================================================
001: "Private Bag X44, Pretoria, 0001, South Africa, ISIbalo House, Koch Street, Salvokop, Pretoria, 0002"
002: "www.statssa.gov.za, info@statssa.gov.za, Tel +27 12 310 8911"
003: ""
004: ""
005: ""
006: ""
007: "STATISTICAL RELEASE"
008: "P0318"
009: ""
010: ""
011: ""
012: ""
013: "General Household Survey"
014: ""
015: "2024"
016: ""
017: ""
018: ""
019: ""
020: "Embargoed until:"
021: "27 May 2025"
022: "11:30"
023: ""
024: ""
025: ""
026: ""
027: "ENQUIRIES:                              FORTHCOMING ISSUE:                   EXPECTED RELEASE DATE"
028: "User Information Services               GHS 2025                             May 2026"
029: "Tel.: (012) 310 8600"
030: "STATISTICS SOUTH AFRICA                                                                   ii                                                                                 P0318"
031: ""
032: ""
033: ""
034: "Contents"
035: ""
036: "Abbreviations ................................................................................................................................................................. viii"
037: "Summary and Key Findings ............................................................................................................................................ ix"
038: "1    Introduction .............................................................................................................................................................. 1"
039: "1.1 Purpose .................................................................................................................................................. ................... 1"
040: "1.2 Survey scope ............................................................................................................................................................. 1"

==========================================================================================
Presentation-QLFS-Q1-2026.csv — RAW STRUCTURE
==========================================================================================
001: "Quarterly Labour Force Survey (QLFS)"
002: "Q1:2026"
003: ""
004: "Risenga Maluleke"
005: "Statistician-General"
006: "Stats SA adopting more recent ICLS resolutions for reporting"
007: ""
008: ""
009: "Before Now"
010: ""
011: ""
012: ""
013: ""
014: "2"
015: "           Labour Statistics now report on a greater variety of labour indicators"
016: ""
017: "Working Age"
018: "Population 15-64"
019: ""
020: ""
021: ""
022: "Labour Force                                                     Outside the Labour Force"
023: ""
024: ""
025: ""
026: "Potential Labour            Others outside the"
027: "Employed                    Unemployed"
028: "Force                     labour force"
029: "Want employment but not"
030: "seeking or available"
031: "Time-related"
032: "underemployment                    Available,                              Do not want employment"
033: "Not available,"
034: "not seeking           but seeking"
035: ""
036: "Includes Discouraged"
037: "Job-seekers"
038: ""
039: "Labour Underutilisation"
040: ""

In [3]:
# Locate statistical tables and KZN references in the publication files
# This helps identify the relevant data sections before extraction

search_terms = [
    "KwaZulu-Natal",
    "KZN",
    "Table",
    "Province",
    "Employment",
    "Unemployment",
    "labour force",
    "voting",
    "participation"
]

for filename in files:

    file_path = RAW_DIR / filename

    print("\n" + "=" * 90)
    print(f"{filename} — RELEVANT SECTIONS")
    print("=" * 90)

    with open(
        file_path,
        "r",
        encoding="utf-8-sig",
        errors="replace"
    ) as f:

        lines = f.readlines()

    matches = []

    for number, line in enumerate(lines, start=1):
        clean_line = line.strip()

        if any(
            term.lower() in clean_line.lower()
            for term in search_terms
        ):
            matches.append((number, clean_line))

    print(f"Matching lines found: {len(matches):,}")

    for number, line in matches[:100]:
        print(f"{number:04}: {line[:500]}")

==========================================================================================
P02111stQuarter2024.csv — RELEVANT SECTIONS
==========================================================================================
Matching lines found: 898
0013: "Quarterly Labour Force Survey"
0035: "List of tables ....................................................................................................................................................... iii"
0040: "3. Employment ....................................................................................................................................................2"
0041: "3.1 Conditions of employment for employees ....................................................................................................6"
0042: "4. Unemployment and not in employment, education or training (NEET) ..........................................................7"
0043: "4.1 Unemployment ..............................................................................................................................................7"
0044: "4.2 Not in employment, education or training (NEET) ........................................................................................9"
0048: "6.2 Trends in unemployment rate .....................................................................................................................12"
0049: "7. The Quarterly Labour Force Survey (QLFS) and the Quarterly Employment Survey (QES) .......................13"
0066: "Quarterly Labour Force Survey, Quarter 1: 2024"
0070: "List of tables"
0071: "Table A: Key labour market indicators ..........................................................................................................................1"
0073: "Table B: Employment by industry .................................................................................................................................2"
0075: "Table C: Employment by occupation ............................................................................................................................4"
0077: "Table D: Employment by province ................................................................................................................................5"
0079: "Table E: Unemployment rate by province ....................................................................................................................8"
0081: "Table F: Key differences between the QLFS and the QES ........................................................................................14"
0083: "Table G: Response rates by province and metropolitan area ....................................................................................15"
0088: "Quarterly Labour Force Survey, Quarter 1: 2024"
0093: "Figure 1: Quarter-to-quarter changes in employment, Q1: 2019 to Q1: 2024 ............................................................. 2"
0094: "Figure 2: Quarter-to-quarter employment changes in the formal and informal sectors, Q1: 2019 to Q1: 2024 ........... 3"
0097: "Figure 5: Quarter-to-quarter changes in nature of employment contract ..................................................................... 6"
0098: "Figure 6: Year-on-year changes in nature of employment contract ............................................................................. 6"
0099: "Figure 7: Quarter-to-quarter changes in unemployment, Q1: 2019 to Q1: 2024 ......................................................... 7"
0100: "Figure 8a: Unemployment rate by education level, Q4: 2023 and Q1: 2024 ............................................................... 8"
0101: "Figure 8b: Unemployment rate by education level, Q1: 2023 and Q1: 2024 ............................................................... 8"
0104: "Figure 10: Year-on-year changes in total employment, Q1: 2016 to Q1: 2024 .......................................................... 11"
0105: "Figure 11: Year-on-year changes in formal sector employment, Q1: 2016 to Q1: 2024............................................ 11"
0106: "Figure 12: Year-on-year changes in informal sector employment, Q1: 2016 to Q1: 2024 ......................................... 12"
0107: "Figure 13: Unemployment rate by sex, Q1: 2016 to Q1: 2024 ................................................................................... 12"
0108: "Figure 14: Unemployment rate by education status, Q1: 2016 to Q1: 2024 .............................................................. 13"
0109: "Figure 15: Formal sector employment trends in QLFS and QES, Q4: 2018 to Q4: 2023 .......................................... 14"
0114: "Quarterly Labour Force Survey, Quarter 1: 2024"
0121: "Table 1: Population of working age (15–64 years) .................................................................................................. 19"
0122: "Table 2: Labour force characteristics by sex – All population groups ..................................................................... 20"
0123: "Table 2.1: Labour force characteristics by population group ................................................................................... 22"
0124: "Table 2.2: Labour force characteristics by age group ............................................................................................. 24"
0125: "Table 2.3: Labour force characteristics by province and metro ............................................................................... 26"
0126: "Table 2.4: Labour force characteristics by sex – Expanded definition of unemployment ....................................... 38"
0127: "Table 2.5: Labour force characteristics by population group – Expanded definition of unemployment .................. 40"
0128: "Table 2.6: Labour force characteristics by age group – Expanded definition of unemployment ............................. 42"
0129: "Table 2.7: Labour force characteristics by province and metro – Expanded definition of unemployment .............. 44"
0130: "Table 3.1: Employed by industry and sex – South Africa ........................................................................................ 52"
0131: "Table 3.2: Employed by industry and province ........................................................................................................ 53"
0132: "Table 3.3: Employed by sector and industry – South Africa .................................................................................... 57"
0133: "Table 3.4: Employed by province and sector .......................................................................................................... 58"
0134: "Table 3.5: Employed by sex and occupation – South Africa ................................................................................... 63"
0135: "Table 3.6: Employed by sex and status in employment – South Africa .................................................................. 64"
0136: "Table 3.7: Employed by sex and usual hours of work – South Africa ..................................................................... 65"
0137: "Table 3.8: Conditions of employment – South Africa .............................................................................................. 66"
0138: "Table 3.9: Time-related underemployment – South Africa ...................................................................................... 72"
0139: "Table 4: Characteristics of the unemployed – South Africa .................................................................................... 75"
0140: "Table 5: Characteristics of the not economically active – South Africa ................................................................... 75"
0141: "Table 6: Sociodemographic characteristics – South Africa ..................................................................................... 76"
0142: "Table 7: Profile of those not in employment education or training - South Africa ................................................... 79"
0143: "Table 8: Involvement in non-market activities and labour market status by province ............................................. 80"
0149: "Table 2A: Sampling Variability for Labour Force Characteristics by Sex ................................................................ 84"
0150: "Table 2.1A: Sampling Variability for Labour Force Characteristics by Population Group ....................................... 86"
0151: "Table 2.3A: Sampling Variability for Labour Force Characteristics by Province ..................................................... 88"
0152: "Table 3.1A: Sampling Variability for the Employed by Industry and Sex .............................................................. 100"
0153: "Table 3.4A: Sampling Variability for the Employed by Province and Sector ......................................................... 101"
0154: "Table 3.5A: Sampling Variability for the Employed by Sex and Occupation ......................................................... 105"
0155: "Table 2B: Sampling Variability for Labour Force Characteristics by Sex .............................................................. 106"
0156: "Table 2.1B: Sampling Variability for Labour Force Characteristics by Population Group ..................................... 108"
0157: "Table 2.3B: Sampling Variability for Labour Force Characteristics by Province ................................................... 110"
0158: "Table 3.1B: Sampling Variability for the Employed by Industry and Sex .............................................................. 122"
0159: "Table 3.4B: Sampling Variability for the Employed by Province and Sector ......................................................... 123"
0160: "Table 3.5B: Sampling Variability for the Employed by Sex and Occupation ......................................................... 127"
0163: "Quarterly Labour Force Survey, Quarter 1: 2024"
0169: "The Quarterly Labour Force Survey (QLFS) is a household-based sample survey conducted by Statistics South"
0178: "Table A: Key labour market indicators"
0185: "Labour force                                     24 125         24 619     24 971         352         846          1,4         3,5"
0199: "Unemployment rate                                  32,9           32,1       32,9          0,8        0,0"
0201: "Labour force participation rate                    59,4           60,0       60,7          0,7        1,3"
0207: "(up by 1,4%) in the labour force. The number of discouraged work-seekers decreased by 1 000, and the number of"
0211: "An increase in employment and unemployment resulted in an increase of 0,8 of a percentage point in the"
0212: "unemployment rate to 32,9% in the first quarter of 2024. The labour force participation rate increased by 0,7 of a"
0216: "Employment gains were observed in the formal sector (up by 56 000), Private households (up by 44 000) and the"
0217: "Agricultural sector (up by 21 000), while informal sector employment decreased by 100 000 in Q1: 2024."
0219: "Compared to Q1: 2023, the working-age population increased by 555 000 or 1,4%. Total employment increased by"
0225: "Quarterly Labour Force Survey, Quarter 1: 2024"
0229: "3. Employment"
0231: "Figure 1: Quarter-to-quarter changes in employment, Q1: 2019 to Q1: 2024"
0236: "Figure 1 shows that, following a decrease of 22 000 in the previous quarter, employment increased by 22 000 in the"
0237: "first quarter of 2024. As depicted in Figure 1, employment has been increasing in the first quarter of each year, for"
0241: "Table B: Employment by industry"
0264: "Table B shows that between Q4: 2023 and Q1: 2024, the number of employed persons increased in six of the ten"
0265: "industries. The largest increases in employment were recorded in Trade (109 000), followed by Manufacturing"
0266: "(99 000), Private households (44 000) and Transport (39 000). Decreases in employment were recorded in"
0269: "Compared to the same period last year, a net increase of 552 000 in total employment in Q1: 2024 was largely due"
0275: "Quarterly Labour Force Survey, Quarter 1: 2024"
0279: "Figure 2: Quarter-to-quarter employment changes in the formal and informal sectors, Q1: 2019 to Q1: 2024"
0284: "Following an increase of 124 000 in Q4: 2023, informal sector employment decreased by 100 000 in Q1: 2024."
0285: "Employment in the formal sector increased by 56 000 in Q1: 2024 compared to Q4: 2023."
0298: "The first quarter of 2024 recorded formal sector employment increases in Trade (124 000), Manufacturing (81 000),"
0300: "decreases in the formal sector employment were recorded in Community and social services (78 000), Construction"
0303: "Compared to a year ago, a net gain of 358 000 jobs in the formal sector employment was mainly driven by Finance"
0304: "(287 000) and Trade (152 000) industries in Q1: 2024. Employment losses were observed in Community and social"
0307: "Quarterly Labour Force Survey, Quarter 1: 2024"
0322: "In the first quarter of 2024, informal sector employment decreased by 100 000 persons compared to the previous"

==========================================================================================
P03182024.csv — RELEVANT SECTIONS
==========================================================================================
Matching lines found: 338
0126: "Figure 3.2 – Percentage (%) distribution of household size by province and rural/urban status, 2024 ............ 4"
0127: "Figure 3.3 – Percentage (%) distribution of female-headed households by province and urban/rural status,"
0129: "Figure 3.4 – Percentage (%) distribution of households by their composition, province and rural/urban"
0131: "Figure 3.5 – Percentage (%) distribution of inter-generational households by province and rural/urban"
0133: "Figure 3.6 – Percentage (%) distribution of children orphanhood status by province, 2024 ............................. 6"
0134: "Figure 3.7 – Percentage (%) distribution of children’s living arrangements by province and urban/rural"
0138: "institutions by province, 2002 and 2024 ................................................................................................ 11"
0142: "who did not pay tuition fees, by province, 2024 .................................................................................... 12"
0144: "school and province, 2024 .................................................................................................................... 12"
0146: "school nutrition programme by province, 2009 and 2024 ..................................................................... 13"
0148: "province, 2009 and 2024 ....................................................................................................................... 13"
0149: "Figure 4.8 – Percentage (%) distribution of student participation rates for individuals aged 18 to 29 years"
0154: "older by province, 2024 ......................................................................................................................... 16"
0161: "when members fall ill or get injured by province, 2024 ......................................................................... 18"
0163: "province, 2024 ....................................................................................................................................... 19"
0173: "province, 2024 ....................................................................................................................................... 22"
0175: "COVID-19 social relief of distress grant by province, 2020–2024 ........................................................ 23"
0179: "dwellings by province, 2024 .................................................................................................................. 24"
0182: "Figure 8.3 – Percentage (%) distribution of dwelling units by tenure status and province, 2024.................... 25"
0195: "had weak or very weak walls and/or roof by province, 2024 ................................................................ 26"
0197: "off-site or on-site by province, selected years 2002–2024 .................................................................... 27"
0202: "Figure 9.5 – Percentage (%) distribution of households by frequency of water interruptions and province,"
0205: "province, 2002–2024 ............................................................................................................................. 36"
0206: "Figure 10.2 – Percentage (%) distribution of households by type of toilet facility and province, 2024 ........... 37"
0210: "province, 2024 ....................................................................................................................................... 38"
0212: "province for selected years between 2002 and 2024............................................................................ 41"
0214: "province, 2024 ....................................................................................................................................... 42"
0219: "Figure 11.5 – Percentage (%) distribution of main sources of energy used for cooking by province, 2024."
0222: "and/or scheduled electricity outages during the previous week, by province, 2024 ............................. 45"
0223: "Figure 11.7 – Percentage (%) distribution of alternative sources of energy used for cooking, by province,"
0229: "province, 2024. ...................................................................................................................................... 48"
0235: "telephone in their dwellings by province, 2024. .................................................................................... 51"
0242: "week preceding the survey by province, 2024. ..................................................................................... 55"
0245: "Figure 16.1 – Percentage (%) distribution of sources of household income by province, 2024. .................... 57"
0246: "Figure 16.2 – Percentage (%) distribution of main source of household income by province, 2024 .............. 57"
0252: "province, 2024. ...................................................................................................................................... 62"
0263: "Figure 18.1 – Percentage (%) distribution of households involved in agricultural activities by province,"
0266: "South Africa by province, 2024. ............................................................................................................ 63"
0267: "Figure 19.1 – Distribution of primary sampling units by province, 2007 (old) Master Sample and the new"
0280: "LIST OF TABLES"
0282: "Table 2.1 – Population per province, 2002–2024 .............................................................................................. 2"
0283: "Table 2.2 – Number of households per province, 2002–2024 .......................................................................... 3"
0284: "Table 4.1 – Percentage (%) distribution of children aged 0─4 years that used different childcare"
0285: "arrangements by province, 2024 ............................................................................................................. 8"
0286: "Table 4.2 – Percentage (%) distribution of individuals aged 5 years and older who are attending"
0287: "educational institutions by province and type of institution attended, 2024 ............................................ 9"
0288: "Table 4.3 – Distribution of students enrolled at higher education institutions by population group, 2002"
0290: "Table 5.1 – Medical aid coverage, 2002–2024 ............................................................................................... 19"
0291: "Table 6.1 – Distribution of individuals aged 5 years and older with disability by sex and province, 2024 ...... 21"
0292: "Table 9.1 – Comparison of the main water source for drinking used by households, 2002–2024 ................. 28"

In [4]:
# Locate the province-level labour-force table in P0211
# We extract the surrounding rows before deciding the final table structure

filename = "P02111stQuarter2024.csv"
file_path = RAW_DIR / filename

with open(
    file_path,
    "r",
    encoding="utf-8-sig",
    errors="replace"
) as f:
    lines = f.readlines()

# Find the province-level table references
matches = [
    (i + 1, line.strip())
    for i, line in enumerate(lines)
    if "Table 2.3" in line or "KwaZulu-Natal" in line
]

print(f"Relevant lines found: {len(matches):,}")

for number, line in matches[:80]:
    print(f"{number:04}: {line[:500]}")

Relevant lines found: 82
0125: "Table 2.3: Labour force characteristics by province and metro ............................................................................... 26"
0151: "Table 2.3A: Sampling Variability for Labour Force Characteristics by Province ..................................................... 88"
0157: "Table 2.3B: Sampling Variability for Labour Force Characteristics by Province ................................................... 110"
0377: "KwaZulu-Natal                           2 594          2 856        2 891            35         297           1,2         11,4"
0386: "Employment gains were recorded in KwaZulu-Natal (35 000), Gauteng (26 000) and Northern Cape (4 000)."
0390: "Compared to Q1: 2023, the largest increases in employment were recorded in KwaZulu-Natal (297 000), Limpopo"
0393: "KwaZulu-Natal had the largest year-on-year percentage change increase in employment of 11,4%."
0481: "KwaZulu-Natal           30,9        29,5        29,9       0,4           -1,0      47,3        43,4      43,7       0,3        -3,6"
0495: "followed by KwaZulu-Natal (1,0 percentage point). The largest increases in the unemployment rate were recorded in"
0511: "decrease in the expanded unemployment rate was recorded in KwaZulu-Natal (3,6 percentage points), followed by"
0563: "KwaZulu-Natal"
0724: "KwaZulu-Natal                                  90,9             92,4"
0946: "KwaZulu-Natal                                            7 503       7 529       7 556         7 581       7 607           26        104          0,3         1,4"
1234: "Table 2.3: Labour force characteristics by province and metro"
1278: "Table 2.3: Labour force characteristics by province and metro (continued)"
1322: "Table 2.3: Labour force characteristics by province and metro (continued)"
1366: "Table 2.3: Labour force characteristics by province and metro (continued)"
1410: "Table 2.3: Labour force characteristics by province and metro (continued)"
1454: "Table 2.3: Labour force characteristics by province and metro (continued)"
1498: "Table 2.3: Labour force characteristics by province and metro (continued)"
1505: "KwaZulu-Natal"
1519: "KwaZulu-Natal – Non-metro"
1542: "Table 2.3: Labour force characteristics by province and metro (continued)"
1549: "KwaZulu-Natal – eThekwini"
1586: "Table 2.3: Labour force characteristics by province and metro (continued)"
1630: "Table 2.3: Labour force characteristics by province and metro (continued)"
1674: "Table 2.3: Labour force characteristics by province and metro (continued)"
1718: "Table 2.3: Labour force characteristics by province and metro (concluded)"
2228: "KwaZulu-Natal"
2239: "KwaZulu-Natal – Non-metro"
2250: "KwaZulu-Natal – eThekwini"
2472: "KwaZulu-Natal                                              143               148          150           153         143           -11             -1         -7,0           -0,5"
2483: "KwaZulu-Natal                                                7                 9            8             7           3            -5             -5        -64,4          -63,1"
2494: "KwaZulu-Natal                                              340              323            318           328         379           51             39         15,5           11,4"
2520: "KwaZulu-Natal                                              14                18            9            13          11            -2             -3        -14,9          -23,8"
2531: "KwaZulu-Natal                                              225              231            241           239         245            6             20          2,6            9,0"
2542: "KwaZulu-Natal                                              528              545            578           568         581           14            53           2,4           10,1"
2568: "KwaZulu-Natal                                              191               177          183            227         230            3             38          1,3           20,0"
2579: "KwaZulu-Natal                                             353              354            437           461         418          -43            65          -9,3           18,4"
2590: "KwaZulu-Natal                                              593              634            660           658         653           -5             60         -0,8           10,2"
2618: "KwaZulu-Natal                                             199              201            205           199         229           29            29          14,8           14,6"
2789: "KwaZulu-Natal                                              2 594            2 642          2 794         2 856       2 891           35           297           1,2            11,4"
2795: "KwaZulu-Natal – Non-metro                               1 374            1 411          1 574         1 593       1 618           26           244           1,6            17,8"
2801: "KwaZulu-Natal – eThekwini                               1 220            1 231          1 219         1 263       1 273            9             52          0,7             4,3"
3614: "KwaZulu-Natal                                      3 741       3 715       3 543         3 461       3 507           46          -234             1,3          -6,3"
3701: "KwaZulu-Natal"
3950: "Table 2.3A: Sampling variability for labour force characteristics by province"
3990: "Table 2.3A: Sampling variability for labour force characteristics by province (continued)"
4030: "Table 2.3A: Sampling variability for labour force characteristics by province (continued)"
4070: "Table 2.3A: Sampling variability for labour force characteristics by province (continued)"
4110: "Table 2.3A: Sampling variability for labour force characteristics by province (continued)"
4150: "Table 2.3A: Sampling variability for labour force characteristics by province (continued)"
4190: "Table 2.3A: Sampling variability for labour force characteristics by province (continued)"
4196: "KwaZulu-Natal"
4209: "KwaZulu-Natal – Non-metro"
4231: "Table 2.3A: Sampling variability for labour force characteristics by province (continued)"
4237: "KwaZulu-Natal – eThekwini"
4272: "Table 2.3A: Sampling variability for labour force characteristics by province (continued)"
4313: "Table 2.3A: Sampling variability for labour force characteristics by province (continued)"
4354: "Table 2.3A: Sampling variability for labour force characteristics by province (continued)"
4394: "Table 2.3A: Sampling variability for labour force characteristics by province (concluded)"
4571: "KwaZulu-Natal                                   2,2        2,1           35         -58      128       0,46"
4577: "KwaZulu-Natal – Non-metro                       3,7        3,1           26         -51      103       0,51"
4583: "KwaZulu-Natal – eThekwini                       1,8        2,6            9         -42       61       0,72"
4865: "Table 2.3B: Sampling variability for labour force characteristics by province"
4906: "Table 2.3B: Sampling variability for labour force characteristics by province (continued)"
4946: "Table 2.3B: Sampling variability for labour force characteristics by province (continued)"
4986: "Table 2.3B: Sampling variability for labour force characteristics by province (continued)"
5026: "Table 2.3B: Sampling variability for labour force characteristics by province (continued)"
5067: "Table 2.3B: Sampling variability for labour force characteristics by province (continued)"
5108: "Table 2.3B: Sampling variability for labour force characteristics by province (continued)"
5114: "KwaZulu-Natal"
5127: "KwaZulu-Natal – Non-metro"
5149: "Table 2.3B: Sampling variability for labour force characteristics by province (continued)"
5155: "KwaZulu-Natal – eThekwini"
5189: "Table 2.3B: Sampling variability for labour force characteristics by province (continued)"
5229: "Table 2.3B: Sampling variability for labour force characteristics by province (continued)"
5269: "Table 2.3B: Sampling variability for labour force characteristics by province (continued)"
5309: "Table 2.3B: Sampling variability for labour force characteristics by province (concluded)"
5485: "KwaZulu-Natal                                   2,4        2,1          297         166      427       0,00"

In [5]:
# Extract the KZN section of Table 2.3
# We inspect the headers and KZN rows before building the cleaned dataset

start = 1230
end = 1730

print("=" * 100)
print("P0211 Q1 2024 — TABLE 2.3: LABOUR FORCE CHARACTERISTICS")
print("=" * 100)

for number in range(start, end + 1):

    line = lines[number - 1].strip()

    if line:
        print(f"{number:04}: {line}")

====================================================================================================
P0211 Q1 2024 — TABLE 2.3: LABOUR FORCE CHARACTERISTICS
====================================================================================================
1230: ""
1231: ""
1232: ""
1233: ""
1234: "Table 2.3: Labour force characteristics by province and metro"
1235: "Year-on-                  Year-on-"
1236: "Jan-Mar       Apr-Jun     Jul-Sep         Oct-Dec     Jan-Mar"
1237: "Qtr-to-qtr       year      Qtr-to-qtr      year"
1238: "2023          2023        2023            2023        2024"
1239: "change        change       change       change"
1240: "Thousand       Thousand    Thousand        Thousand    Thousand    Thousand      Thousand     Per cent      Per cent"
1241: ""
1242: "South Africa"
1243: "Population 15–64 yrs                                         40 604      40 746      40 886          41 022      41 158          137          555            0,3         1,4"
1244: "Labour force                                                24 125      24 268      24 594          24 619      24 971          352          846            1,4         3,5"
1245: "Employed                                                   16 192      16 346      16 745          16 723      16 745           22          552            0,1         3,4"
1246: "Unemployed                                                  7 933       7 921       7 849           7 895       8 226          330          293            4,2         3,7"
1247: "Not economically active                                    16 479      16 478      16 292          16 403      16 188         -215         -291           -1,3        -1,8"
1248: "Discouraged work-seekers                                   3 276       3 182       3 156           3 049       3 048           -1         -229            0,0        -7,0"
1249: "Other (not economically active)                           13 202      13 296      13 136          13 354      13 140         -214          -62           -1,6        -0,5"
1250: "Rates (%)"
1251: "Unemployment rate                                             32,9        32,6        31,9            32,1        32,9           0,8         0,0"
1252: "Employed/population ratio (absorption)                        39,9        40,1        41,0            40,8        40,7          -0,1         0,8"
1253: "Labour force participation rate                               59,4        59,6        60,2            60,0        60,7           0,7         1,3"
1254: ""
1255: "Western Cape"
1256: "Population 15–64 yrs                                          4 958       4 978       4 997           5 016       5 035           19           77           0,4          1,5"
1257: "Labour force                                                 3 388       3 426       3 427           3 459       3 486           26           98           0,8          2,9"
1258: "Employed                                                    2 658       2 711       2 734           2 757       2 740          -17           82          -0,6          3,1"
1259: "Unemployed                                                    730         715         693             702         745           43           15           6,1          2,1"
1260: "Not economically active                                     1 571       1 552       1 571           1 557       1 550           -8          -21          -0,5         -1,3"
1261: "Discouraged work-seekers                                     123         105         140             162         125          -37            2         -22,7          1,7"
1262: "Other (not economically active)                            1 448       1 446       1 431           1 395       1 425           29          -23           2,1         -1,6"
1263: "Rates (%)"
1264: "Unemployment rate                                             21,6        20,9        20,2            20,3        21,4           1,1         -0,2"
1265: "Employed/population ratio (absorption)                        53,6        54,5        54,7            55,0        54,4          -0,6          0,8"
1266: "Labour force participation rate                               68,3        68,8        68,6            69,0        69,2           0,2          0,9"
1267: "Due to rounding, numbers do not necessarily add up to totals."
1268: "Note: 'Employment' refers to market production activities."
1269: ""
1270: ""
1271: ""
1272: ""
1273: "Quarterly Labour Force Survey, Quarter 1: 2024"
1274: "STATISTICS SOUTH AFRICA                                                                        27                                                                              P0211"
1275: ""
1276: ""
1277: ""
1278: "Table 2.3: Labour force characteristics by province and metro (continued)"
1279: "Year-on-                 Year-on-"
1280: "Jan-Mar      Apr-Jun     Jul-Sep         Oct-Dec     Jan-Mar"
1281: "Qtr-to-qtr       year      Qtr-to-qtr     year"
1282: "2023         2023        2023            2023        2024"
1283: "change        change       change      change"
1284: "Thousand      Thousand    Thousand        Thousand    Thousand    Thousand      Thousand     Per cent     Per cent"
1285: ""
1286: "Western Cape – Non-metro"
1287: "Population 15–64 yrs                                       1 800       1 807       1 814           1 821       1 827            7           28           0,4         1,5"
1288: "Labour force                                              1 162       1 158       1 157           1 139       1 197           58           36           5,1         3,1"
1289: "Employed                                                    953         951         989             969         999           29           45           3,0         4,8"
1290: "Unemployed                                                  209         207         168             170         199           29          -10          17,0        -4,7"
1291: "Not economically active                                     638         649         657             682         630          -51           -8          -7,6        -1,3"
1292: "Discouraged work-seekers                                    88          83         100             124          91          -33            3         -26,3         3,7"
1293: "Other (not economically active)                            550         565         557             558         539          -19          -11          -3,4        -2,0"
1294: "Rates (%)"
1295: "Unemployment rate                                          17,9        17,9        14,5            14,9        16,6          1,7          -1,3"
1296: "Employed/population ratio (absorption)                     53,0        52,6        54,5            53,2        54,6          1,4           1,6"
1297: "Labour force participation rate                            64,5        64,1        63,8            62,6        65,5          2,9           1,0"
1298: ""
1299: "Western Cape – City of Cape Town"
1300: "Population 15–64 yrs                                       3 158       3 171       3 184           3 196       3 208           12           49           0,4         1,6"
1301: "Labour force                                              2 226       2 268       2 269           2 320       2 288          -32           62          -1,4         2,8"
1302: "Employed                                                  1 704       1 760       1 745           1 788       1 741          -46           37          -2,6         2,2"
1303: "Unemployed                                                  522         508         525             532         547           14           25           2,7         4,8"
1304: "Not economically active                                     932         903         914             876         919           44          -13           5,0        -1,4"
1305: "Discouraged work-seekers                                    35          22          40              38          34           -4           -1         -11,3        -3,3"
1306: "Other (not economically active)                            898         881         874             838         886           48          -12           5,7        -1,3"
1307: "Rates (%)"
1308: "Unemployment rate                                          23,4        22,4        23,1            22,9        23,9           1,0         0,5"
1309: "Employed/population ratio (absorption)                     54,0        55,5        54,8            55,9        54,3          -1,6         0,3"
1310: "Labour force participation rate                            70,5        71,5        71,3            72,6        71,3          -1,3         0,8"
1311: "Due to rounding, numbers do not necessarily add up to totals."
1312: "Note: 'Employment' refers to market production activities."
1313: ""
1314: ""
1315: ""
1316: ""
1317: "Quarterly Labour Force Survey, Quarter 1: 2024"
1318: "STATISTICS SOUTH AFRICA                                                                       28                                                                              P0211"
1319: ""
1320: ""
1321: ""
1322: "Table 2.3: Labour force characteristics by province and metro (continued)"
1323: ""
1324: "Jan-Mar       Apr-Jun     Jul-Sep        Oct-Dec     Jan-Mar                   Year-on-                 Year-on-"
1325: "2023          2023        2023           2023        2024       Qtr-to-qtr      year      Qtr-to-qtr     year"
1326: "change       change       change      change"
1327: "Thousand       Thousand    Thousand       Thousand    Thousand    Thousand     Thousand     Per cent     Per cent"
1328: ""
1329: "Eastern Cape"
1330: "Population 15–64 yrs                                         4 483       4 498       4 512          4 525       4 539           14          56           0,3         1,2"
1331: "Labour force                                                2 367       2 393       2 385          2 320       2 332           12         -35           0,5        -1,5"
1332: "Employed                                                   1 421       1 444       1 459          1 348       1 344           -4         -77          -0,3        -5,4"
1333: "Unemployed                                                   946         949         926            973         988           15          42           1,6         4,5"
1334: "Not economically active                                    2 116       2 105       2 126          2 205       2 207            2          91           0,1         4,3"
1335: "Discouraged work-seekers                                    142         111         157            162         224           62          82          38,2        57,5"
1336: "Other (not economically active)                           1 974       1 994       1 970          2 043       1 983          -60           9          -2,9         0,4"
1337: "Rates (%)"
1338: "Unemployment rate                                            40,0        39,7        38,8           41,9        42,4          0,5          2,4"
1339: "Employed/population ratio (absorption)                       31,7        32,1        32,3           29,8        29,6         -0,2         -2,1"
1340: "Labour force participation rate                              52,8        53,2        52,9           51,3        51,4          0,1         -1,4"
1341: ""
1342: ""
1343: "Eastern Cape – Non-metro"
1344: "Population 15–64 yrs                                       3 062       3 070       3 079          3 087       3 095            8          33           0,3         1,1"
1345: "Labour force                                              1 422       1 489       1 489          1 438       1 437           -1          15          -0,1         1,0"
1346: "Employed                                                   774         824         849            761         744          -17         -30          -2,2        -3,9"
1347: "Unemployed                                                 648         665         640            677         693           16          45           2,3         6,9"
1348: "Not economically active                                  1 639       1 581       1 590          1 649       1 658            9          19           0,6         1,1"
1349: "Discouraged work-seekers                                  122         101         149            154         220           66          98          42,9        80,3"
1350: "Other (not economically active)                         1 517       1 480       1 441          1 494       1 438          -57         -80          -3,8        -5,2"
1351: "Rates (%)"
1352: "Unemployment rate                                          45,6        44,7        43,0           47,1        48,2          1,1          2,6"
1353: "Employed/population ratio (absorption)                     25,3        26,8        27,6           24,7        24,1         -0,6         -1,2"
1354: "Labour force participation rate                            46,5        48,5        48,4           46,6        46,4         -0,2         -0,1"
1355: "Due to rounding, numbers do not necessarily add up to totals."
1356: "Note: 'Employment' refers to market production activities."
1357: ""
1358: ""
1359: ""
1360: ""
1361: "Quarterly Labour Force Survey, Quarter 1: 2024"
1362: "STATISTICS SOUTH AFRICA                                                                      29                                                                               P0211"
1363: ""
1364: ""
1365: ""
1366: "Table 2.3: Labour force characteristics by province and metro (continued)"
1367: ""
1368: "Jan-Mar      Apr-Jun     Jul-Sep        Oct-Dec     Jan-Mar                   Year-on-                  Year-on-"
1369: "2023         2023        2023           2023        2024       Qtr-to-qtr      year      Qtr-to-qtr      year"
1370: "change       change       change       change"
1371: "Thousand      Thousand    Thousand       Thousand    Thousand    Thousand     Thousand     Per cent      Per cent"
1372: ""
1373: "Eastern Cape – Buffalo City"
1374: "Population 15–64 yrs                                       549          551        553            555         557             2           8            0,4         1,5"
1375: "Labour force                                              367          383        372            389         383            -6          15           -1,7         4,2"
1376: "Employed                                                 265          266        253            261         253            -7         -12           -2,9        -4,5"
1377: "Unemployed                                               102          118        118            129         129             1          27            0,7        26,8"
1378: "Not economically active                                  181          168        181            166         174             9          -7            5,2        -3,9"
1379: "Discouraged work-seekers                                  5            0                                     3             3          -2                      -34,0"
1380: "Other (not economically active)                         177          168        181            166         171             5          -5           3,3         -3,1"
1381: "Rates (%)"
1382: "Unemployment rate                                         27,8        30,7        31,8           33,0        33,8          0,8          6,0"
1383: "Employed/population ratio (absorption)                    48,3        48,2        45,8           47,0        45,5         -1,5         -2,8"
1384: "Labour force participation rate                           66,9        69,6        67,2           70,1        68,7         -1,4          1,8"
1385: ""
1386: ""
1387: "Eastern Cape – Nelson Mandela Bay"
1388: "Population 15–64 yrs                                       873          876        880            883         887             3          14           0,4          1,6"
1389: "Labour force                                              577          521        524            493         512            19         -65           3,9        -11,3"
1390: "Employed                                                 381          354        357            326         346            20         -35           6,3         -9,3"
1391: "Unemployed                                               196          166        168            167         166            -1         -30          -0,7        -15,3"
1392: "Not economically active                                  296          356        356            390         375           -16          79          -4,0         26,8"
1393: "Discouraged work-seekers                                 16           10          8              8           1            -7         -15         -87,1        -93,2"
1394: "Other (not economically active)                         280          346        348            382         374            -9          94          -2,2         33,5"
1395: "Rates (%)"
1396: "Unemployment rate                                         33,9        32,0        32,0           33,9        32,4         -1,5         -1,5"
1397: "Employed/population ratio (absorption)                    43,7        40,4        40,5           36,9        39,0          2,1         -4,7"
1398: "Labour force participation rate                           66,1        59,4        59,6           55,8        57,7          1,9         -8,4"
1399: "Due to rounding, numbers do not necessarily add up to totals."
1400: "Note: 'Employment' refers to market production activities."
1401: ""
1402: ""
1403: ""
1404: ""
1405: "Quarterly Labour Force Survey, Quarter 1: 2024"
1406: "STATISTICS SOUTH AFRICA                                                                       30                                                                               P0211"
1407: ""
1408: ""
1409: ""
1410: "Table 2.3: Labour force characteristics by province and metro (continued)"
1411: ""
1412: "Jan-Mar       Apr-Jun     Jul-Sep        Oct-Dec     Jan-Mar                   Year-on-                  Year-on-"
1413: "2023          2023        2023           2023        2024       Qtr-to-qtr      year      Qtr-to-qtr      year"
1414: "change       change       change       change"
1415: "Thousand       Thousand    Thousand       Thousand    Thousand    Thousand     Thousand     Per cent      Per cent"
1416: ""
1417: "Northern Cape"
1418: "Population 15–64 yrs                                          831          833        834            836         838             2           7           0,2          0,9"
1419: "Labour force                                                 462          441        446            447         462            15           0           3,3         -0,1"
1420: "Employed                                                    339          322        328            327         331             4          -8           1,3         -2,4"
1421: "Unemployed                                                  123          118        117            120         131            11           8           8,8          6,3"
1422: "Not economically active                                     368          392        389            389         376           -13           8          -3,4          2,0"
1423: "Discouraged work-seekers                                    98          102         94            103          86           -17         -12         -16,1        -12,1"
1424: "Other (not economically active)                            270          290        294            286         289             3          20           1,2          7,2"
1425: "Rates (%)"
1426: "Unemployment rate                                            26,6        26,9        26,3           26,9        28,3          1,4          1,7"

In [6]:
# Extract the KZN rows from Table 2.3
# Keep the province, non-metro and eThekwini areas for cleaning

kzn_rows = []

for number in range(1505, 1561):

    line = lines[number - 1].strip()

    if line:
        kzn_rows.append(line)

print("=" * 100)
print("KZN TABLE 2.3 ROWS")
print("=" * 100)

for row in kzn_rows:
    print(row)

====================================================================================================
KZN TABLE 2.3 ROWS
====================================================================================================
"KwaZulu-Natal"
"Population 15–64 yrs                                         7 503       7 529       7 556          7 581       7 607           26         104           0,3         1,4"
"Labour force                                                3 757       3 829       3 958          4 053       4 126           73         370           1,8         9,8"
"Employed                                                   2 594       2 642       2 794          2 856       2 891           35         297           1,2        11,4"
"Unemployed                                                 1 162       1 187       1 164          1 197       1 235           38          73           3,2         6,3"
"Not economically active                                    3 746       3 701       3 598          3 528       3 480          -48        -266          -1,3        -7,1"
"Discouraged work-seekers                                     976         927         915            790         771          -19        -204          -2,4       -21,0"
"Other (not economically active)                            2 771       2 774       2 682          2 738       2 709          -29         -62          -1,1        -2,2"
"Rates (%)"
"Unemployment rate                                            30,9        31,0        29,4           29,5        29,9          0,4         -1,0"
"Employed/population ratio (absorption)                       34,6        35,1        37,0           37,7        38,0          0,3          3,4"
"Labour force participation rate                              50,1        50,9        52,4           53,5        54,2          0,7          4,1"
""
""
"KwaZulu-Natal – Non-metro"
"Population 15–64 yrs                                       4 881       4 897       4 913          4 928       4 943           15          62           0,3         1,3"
"Labour force                                              2 244       2 277       2 384          2 431       2 496           65         252           2,7        11,2"
"Employed                                                  1 374       1 411       1 574          1 593       1 618           26         244           1,6        17,8"
"Unemployed                                                  869         866         809            838         877           39           8           4,7         0,9"
"Not economically active                                   2 638       2 620       2 529          2 497       2 448          -49        -190          -2,0        -7,2"
"Discouraged work-seekers                                   662         640         631            531         481          -49        -181          -9,3       -27,3"
"Other (not economically active)                          1 976       1 980       1 898          1 967       1 967            0          -9           0,0        -0,5"
"Rates (%)"
"Unemployment rate                                          38,7        38,0        33,9           34,5        35,1          0,6         -3,6"
"Employed/population ratio (absorption)                     28,2        28,8        32,0           32,3        32,7          0,4          4,5"
"Labour force participation rate                            46,0        46,5        48,5           49,3        50,5          1,2          4,5"
"Due to rounding, numbers do not necessarily add up to totals."
"Note: 'Employment' refers to market production activities."
""
""
""
""
"Quarterly Labour Force Survey, Quarter 1: 2024"
"STATISTICS SOUTH AFRICA                                                                       33                                                                             P0211"
""
""
""
"Table 2.3: Labour force characteristics by province and metro (continued)"
""
"Jan-Mar       Apr-Jun     Jul-Sep        Oct-Dec     Jan-Mar                   Year-on-                Year-on-"
"2023          2023        2023           2023        2024       Qtr-to-qtr      year     Qtr-to-qtr     year"
"change       change      change      change"
"Thousand       Thousand    Thousand       Thousand    Thousand    Thousand     Thousand    Per cent     Per cent"
""
"KwaZulu-Natal – eThekwini"
"Population 15–64 yrs                                       2 622       2 632       2 643          2 653       2 663           10          42          0,4        1,6"
"Labour force                                              1 513       1 552       1 574          1 622       1 631            8         118          0,5        7,8"
"Employed                                                  1 220       1 231       1 219          1 263       1 273            9          52          0,7        4,3"
"Unemployed                                                  293         321         355            359         358           -1          65         -0,3       22,2"
"Not economically active                                   1 109       1 081       1 068          1 031       1 033            2         -76          0,2       -6,9"
"Discouraged work-seekers                                   314         287         284            259         290           31         -24         11,9       -7,5"
"Other (not economically active)                            795         794         784            771         742          -29         -52         -3,8       -6,6"
"Rates (%)"
"Unemployment rate                                          19,4        20,7        22,5           22,1        22,0         -0,1         2,6"
"Employed/population ratio (absorption)                     46,5        46,8        46,1           47,6        47,8          0,2         1,3"
"Labour force participation rate                            57,7        58,9        59,6           61,1        61,2          0,1         3,5"

In [7]:
import re

# Convert the extracted KZN Table 2.3 rows into a structured dataset
# Keep the five quarterly values and the reported change measures

records = []

metric_names = [
    "Population 15–64 yrs",
    "Labour force",
    "Employed",
    "Unemployed",
    "Not economically active",
    "Discouraged work-seekers",
    "Other (not economically active)",
    "Unemployment rate",
    "Employed/population ratio (absorption)",
    "Labour force participation rate"
]

geographies = [
    "KwaZulu-Natal",
    "KwaZulu-Natal – Non-metro",
    "KwaZulu-Natal – eThekwini"
]

current_geo = None

for row in kzn_rows:

    row = row.strip('"')

    if row in geographies:
        current_geo = row
        continue

    for metric in metric_names:

        if row.startswith(metric):

            values_text = row[len(metric):].strip()

            values = re.findall(
                r"-?\d+(?:[ ]\d{3})*(?:,\d+)?",
                values_text
            )

            values = [
                float(value.replace(" ", "").replace(",", "."))
                for value in values
            ]

            records.append({
                "Geography": current_geo,
                "Metric": metric,
                "Q1_2023": values[0],
                "Q2_2023": values[1],
                "Q3_2023": values[2],
                "Q4_2023": values[3],
                "Q1_2024": values[4],
                "Qtr_to_qtr_change": values[5],
                "Year_on_year_change": values[6],
                "Qtr_to_qtr_percent": values[7] if len(values) > 7 else None,
                "Year_on_year_percent": values[8] if len(values) > 8 else None
            })

            break

kzn_clean = pd.DataFrame(records)

print("=" * 100)
print("KZN TABLE 2.3 STRUCTURED DATA")
print("=" * 100)

print(f"Rows: {len(kzn_clean)}")
print(f"Columns: {len(kzn_clean.columns)}")

display(kzn_clean)

====================================================================================================
KZN TABLE 2.3 STRUCTURED DATA
====================================================================================================
Rows: 30
Columns: 11

,Geography,Metric,Q1_2023,Q2_2023,Q3_2023,Q4_2023,Q1_2024,Qtr_to_qtr_change,Year_on_year_change,Qtr_to_qtr_percent,Year_on_year_percent
0,KwaZulu-Natal,Population 15–64 yrs,7503.0,7529.0,7556.0,7581.0,7607.0,26.0,104.0,0.3,1.4
1,KwaZulu-Natal,Labour force,3757.0,3829.0,3958.0,4053.0,4126.0,73.0,370.0,1.8,9.8
2,KwaZulu-Natal,Employed,2594.0,2642.0,2794.0,2856.0,2891.0,35.0,297.0,1.2,11.4
3,KwaZulu-Natal,Unemployed,1162.0,1187.0,1164.0,1197.0,1235.0,38.0,73.0,3.2,6.3
4,KwaZulu-Natal,Not economically active,3746.0,3701.0,3598.0,3528.0,3480.0,-48.0,-266.0,-1.3,-7.1
5,KwaZulu-Natal,Discouraged work-seekers,976.0,927.0,915.0,790.0,771.0,-19.0,-204.0,-2.4,-21.0
6,KwaZulu-Natal,Other (not economically active),2771.0,2774.0,2682.0,2738.0,2709.0,-29.0,-62.0,-1.1,-2.2
7,KwaZulu-Natal,Unemployment rate,30.9,31.0,29.4,29.5,29.9,0.4,-1.0,NaN,NaN
8,KwaZulu-Natal,Employed,34.6,35.1,37.0,37.7,38.0,0.3,3.4,NaN,NaN
9,KwaZulu-Natal,Labour force,50.1,50.9,52.4,53.5,54.2,0.7,4.1,NaN,NaN
10,KwaZulu-Natal – Non-metro,Population 15–64 yrs,4881.0,4897.0,4913.0,4928.0,4943.0,15.0,62.0,0.3,1.3
11,KwaZulu-Natal – Non-metro,Labour force,2244.0,2277.0,2384.0,2431.0,2496.0,65.0,252.0,2.7,11.2
12,KwaZulu-Natal – Non-metro,Employed,1374.0,1411.0,1574.0,1593.0,1618.0,26.0,244.0,1.6,17.8
13,KwaZulu-Natal – Non-metro,Unemployed,869.0,866.0,809.0,838.0,877.0,39.0,8.0,4.7,0.9
14,KwaZulu-Natal – Non-metro,Not economically active,2638.0,2620.0,2529.0,2497.0,2448.0,-49.0,-190.0,-2.0,-7.2
15,KwaZulu-Natal – Non-metro,Discouraged work-seekers,662.0,640.0,631.0,531.0,481.0,-49.0,-181.0,-9.3,-27.3
16,KwaZulu-Natal – Non-metro,Other (not economically active),1976.0,1980.0,1898.0,1967.0,1967.0,0.0,-9.0,0.0,-0.5
17,KwaZulu-Natal – Non-metro,Unemployment rate,38.7,38.0,33.9,34.5,35.1,0.6,-3.6,NaN,NaN
18,KwaZulu-Natal – Non-metro,Employed,28.2,28.8,32.0,32.3,32.7,0.4,4.5,NaN,NaN
19,KwaZulu-Natal – Non-metro,Labour force,46.0,46.5,48.5,49.3,50.5,1.2,4.5,NaN,NaN
20,KwaZulu-Natal – eThekwini,Population 15–64 yrs,2622.0,2632.0,2643.0,2653.0,2663.0,10.0,42.0,0.4,1.6
21,KwaZulu-Natal – eThekwini,Labour force,1513.0,1552.0,1574.0,1622.0,1631.0,8.0,118.0,0.5,7.8
22,KwaZulu-Natal – eThekwini,Employed,1220.0,1231.0,1219.0,1263.0,1273.0,9.0,52.0,0.7,4.3
23,KwaZulu-Natal – eThekwini,Unemployed,293.0,321.0,355.0,359.0,358.0,-1.0,65.0,-0.3,22.2
24,KwaZulu-Natal – eThekwini,Not economically active,1109.0,1081.0,1068.0,1031.0,1033.0,2.0,-76.0,0.2,-6.9
25,KwaZulu-Natal – eThekwini,Discouraged work-seekers,314.0,287.0,284.0,259.0,290.0,31.0,-24.0,11.9,-7.5
26,KwaZulu-Natal – eThekwini,Other (not economically active),795.0,794.0,784.0,771.0,742.0,-29.0,-52.0,-3.8,-6.6
27,KwaZulu-Natal – eThekwini,Unemployment rate,19.4,20.7,22.5,22.1,22.0,-0.1,2.6,NaN,NaN
28,KwaZulu-Natal – eThekwini,Employed,46.5,46.8,46.1,47.6,47.8,0.2,1.3,NaN,NaN
29,KwaZulu-Natal – eThekwini,Labour force,57.7,58.9,59.6,61.1,61.2,0.1,3.5,NaN,NaN

In [8]:
# Correct the shortened rate metric names caused by overlapping metric labels
# Keep the original values unchanged

kzn_clean.loc[
    kzn_clean["Metric"] == "Employed",
    "Metric"
] = "Employed/population ratio (absorption)"

kzn_clean.loc[
    kzn_clean["Metric"] == "Labour force",
    "Metric"
] = "Labour force participation rate"

print("=" * 100)
print("CORRECTED METRICS")
print("=" * 100)

print(kzn_clean["Metric"].value_counts())

====================================================================================================
CORRECTED METRICS
====================================================================================================
Metric
Labour force participation rate           6
Employed/population ratio (absorption)    6
Population 15–64 yrs                      3
Unemployed                                3
Not economically active                   3
Discouraged work-seekers                  3
Other (not economically active)           3
Unemployment rate                         3
Name: count, dtype: int64

In [9]:
# Restore the correct metric names using their fixed Table 2.3 order
# Each geography contains seven count measures followed by three rate measures

metric_order = [
    "Population 15–64 yrs",
    "Labour force",
    "Employed",
    "Unemployed",
    "Not economically active",
    "Discouraged work-seekers",
    "Other (not economically active)",
    "Unemployment rate",
    "Employed/population ratio (absorption)",
    "Labour force participation rate"
]

kzn_clean["Metric"] = (
    kzn_clean.groupby("Geography").cumcount()
)

kzn_clean["Metric"] = kzn_clean["Metric"].map(
    dict(enumerate(metric_order))
)

print("=" * 100)
print("FINAL METRIC CHECK")
print("=" * 100)

print(kzn_clean["Metric"].value_counts())

====================================================================================================
FINAL METRIC CHECK
====================================================================================================
Metric
Population 15–64 yrs                      3
Labour force                              3
Employed                                  3
Unemployed                                3
Not economically active                   3
Discouraged work-seekers                  3
Other (not economically active)           3
Unemployment rate                         3
Employed/population ratio (absorption)    3
Labour force participation rate           3
Name: count, dtype: int64

In [10]:
# Validate the structured KZN labour-force dataset
# Check duplicates, missing values, geography coverage and expected row count

print("=" * 100)
print("KZN TABLE 2.3 VALIDATION")
print("=" * 100)

print(f"Expected rows: 30")
print(f"Actual rows:   {len(kzn_clean)}")
print(f"Row count correct: {len(kzn_clean) == 30}")

print("\nExpected geographies:")
print(kzn_clean["Geography"].unique())

print("\nMissing values:")
print(kzn_clean.isna().sum())

print("\nDuplicate rows:")
print(kzn_clean.duplicated().sum())

print("\nMetric counts:")
print(kzn_clean["Metric"].value_counts())

print("\nGeography counts:")
print(kzn_clean["Geography"].value_counts())

====================================================================================================
KZN TABLE 2.3 VALIDATION
====================================================================================================
Expected rows: 30
Actual rows:   30
Row count correct: True

Expected geographies:
['KwaZulu-Natal' 'KwaZulu-Natal – Non-metro' 'KwaZulu-Natal – eThekwini']

Missing values:
Geography               0
Metric                  0
Q1_2023                 0
Q2_2023                 0
Q3_2023                 0
Q4_2023                 0
Q1_2024                 0
Qtr_to_qtr_change       0
Year_on_year_change     0
Qtr_to_qtr_percent      9
Year_on_year_percent    9
dtype: int64

Duplicate rows:
0

Metric counts:
Metric
Population 15–64 yrs                      3
Labour force                              3
Employed                                  3
Unemployed                                3
Not economically active                   3
Discouraged work-seekers                  3
Other (not economically active)           3
Unemployment rate                         3
Employed/population ratio (absorption)    3
Labour force participation rate           3
Name: count, dtype: int64

Geography counts:
Geography
KwaZulu-Natal                10
KwaZulu-Natal – Non-metro    10
KwaZulu-Natal – eThekwini    10
Name: count, dtype: int64

In [11]:
# Finalise the cleaned KZN Table 2.3 dataset
# Save the cleaned file without modifying the original raw publication

output_file = CLEAN_DIR / "P02111stQuarter2024_clean.csv"

kzn_clean.to_csv(
    output_file,
    index=False,
    encoding="utf-8-sig"
)

print("=" * 100)
print("CLEANED DATASET SAVED")
print("=" * 100)

print(f"File: {output_file}")
print(f"Rows: {len(kzn_clean):,}")
print(f"Columns: {len(kzn_clean.columns)}")
print(f"File exists: {output_file.exists()}")

====================================================================================================
CLEANED DATASET SAVED
====================================================================================================
File: C:\Users\Student\Downloads\Big Data\SPU-TEAM-DIRISA\data\interim\KZN_Electoral_participation Cleaned\P02111stQuarter2024_clean.csv
Rows: 30
Columns: 11
File exists: True

In [12]:
# Inspect the General Household Survey publication structure
# Identify the encoding, dimensions and available publication content

filename = "P03182024.csv"
file_path = RAW_DIR / filename

df_ghs = pd.read_csv(
    file_path,
    encoding="utf-8-sig",
    low_memory=False
)

print("=" * 100)
print(filename)
print("=" * 100)

print(f"Rows: {len(df_ghs):,}")
print(f"Columns: {len(df_ghs.columns)}")

print("\nColumn names:")
print(df_ghs.columns.tolist())

print("\nFirst 20 rows:")
display(df_ghs.head(20))

====================================================================================================
P03182024.csv
====================================================================================================
Rows: 6,890
Columns: 1

Column names:
['Private Bag X44, Pretoria, 0001, South Africa, ISIbalo House, Koch Street, Salvokop, Pretoria, 0002']

First 20 rows:

   Private Bag X44, Pretoria, 0001, South Africa, ISIbalo House, Koch Street, Salvokop, Pretoria, 0002
0   www.statssa.gov.za, info@statssa.gov.za, Tel +...
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                 STATISTICAL RELEASE
6                                               P0318
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                           General Household Survey
12                                                NaN
13                                               2024
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN
18                                   Embargoed until:
19                                        27 May 2025

In [13]:
# Locate KZN and participation-related sections in the GHS publication
# Use these matches to identify the relevant table before extraction

with open(
    file_path,
    "r",
    encoding="utf-8-sig",
    errors="replace"
) as f:
    ghs_lines = f.readlines()

search_terms = [
    "KwaZulu-Natal",
    "KZN",
    "participation",
    "participation rate",
    "Table",
    "province"
]

for term in search_terms:

    matches = [
        (i + 1, line.strip())
        for i, line in enumerate(ghs_lines)
        if term.lower() in line.lower()
    ]

    print("\n" + "=" * 100)
    print(f"SEARCH: {term}")
    print(f"Matches: {len(matches):,}")
    print("=" * 100)

    for number, line in matches[:50]:
        print(f"{number:04}: {line[:500]}")

====================================================================================================
SEARCH: KwaZulu-Natal
Matches: 50
====================================================================================================
0338: "KZN           KwaZulu-Natal"
0404: "areas (47,1%), particularly in Eastern Cape (48,8%) and KwaZulu-Natal (46,8%), and least common in"
0446: "(10,0%) and KwaZulu-Natal (10,2%). Black African individuals comprised more than half (52,7%) of all medical"
0466: "Cape (+13,8 percentage points) and KwaZulu-Natal (+7,5 percentage points). Despite these notable"
0476: "Cape (100%) and Gauteng (95,6%). More than one-third (35,7%) of households in KwaZulu-Natal took more"
0633: "2024. Gauteng had the largest number of households, followed by KwaZulu-Natal, Western Cape, Limpopo"
0685: "By contrast, households that comprised six people or more were most common in KwaZulu-Natal (18,6%) and"
0743: "widespread in KwaZulu-Natal (40,0%) and Eastern Cape (39,5%)."
0763: "(or inter-generational) households were most common in KwaZulu-Natal (17,7%), Eastern Cape (16,7%) and"
0794: "living with either parent was most common in Eastern Cape (32,1%), KwaZulu-Natal (23,7%) and Limpopo"
0866: "another adult. The figure was most pronounced in Northern Cape (72,9%) and KwaZulu-Natal (70,5%). Only"
0912: "(92,7%), Eastern Cape (92,6%), KwaZulu-Natal (92,3%), Mpumalanga (90,7%) and Northern Cape (90,6%),"
0988: "attended schools in KwaZulu-Natal (21,2%) and Gauteng (22,2%)."
1013: "by parents was highest in Gauteng (19,8%) and KwaZulu-Natal (18,2%)."
1024: "80% of learners in Eastern Cape, Northern Cape, KwaZulu-Natal, North West, Mpumalanga and Limpopo"
1042: "in KwaZulu-Natal (20,1%) and Eastern Cape (10,8%). By comparison, only 0,4% of learners in Gauteng and"
1246: "(21,3%), and least common in Limpopo (10,0%) and KwaZulu-Natal (10,2%)."
1432: "KwaZulu-Natal (10,3%)."
1538: "note, access to water in KwaZulu-Natal increased by 7,5 percentage points to 82,9% over this period."
1683: "(62,0%) and KwaZulu-Natal (64,2%)."
1698: "water interruptions (13,9%) were most common in Mpumalanga (39,4%), KwaZulu-Natal (28,5%) and Limpopo"
1754: "Free State (26,4%), and KwaZulu-Natal (25,3%). Drawing water from springs, wells, dams, pools, rivers, or"
1755: "streams was most common in KwaZulu-Natal (13,0%), Western Cape (10,4%) and Eastern Cape (9,1%)."
1882: "KwaZulu-Natal over the same period."
1907: "(42,0%), Limpopo (31,5%) and KwaZulu-Natal (27,0%)."
1977: "Cape (71,6%) and Western Cape (69,9%), and least frequent in Limpopo (39,8%) and KwaZulu-Natal (45,3%)."
1978: "Rinsing hands with water was most common in Limpopo (54,9%) and KwaZulu-Natal (52,5%) and least"
2013: "most common in Limpopo (96,6%), Western Cape (96,0%), KwaZulu-Natal (93,5%) and Eastern Cape"
2017: "Mains electricity is provided by the        in Eastern Cape (+38,1 percentage points), KwaZulu-Natal"
2047: "conventional meters was the highest in Gauteng (18,8%) and KwaZulu-Natal (16,1%)."
2100: "of households that used electricity as a main source of energy for cooking was highest in KwaZulu-Natal"
2106: "(19,7%), Eastern Cape (8,5%), North West (7,9%) and KwaZulu-Natal (7,6%). Less than one per cent of"
2200: "KwaZulu-Natal        Urban                         81,9                 4,7               12,2            1,2"
2223: "common in the rural areas of Eastern Cape (1,2%), KwaZulu-Natal (8,0%) and Limpopo (8,5%). Overall, 77,4%"
2252: "in KwaZulu-Natal (92,7%), North West (92,6%) and Eastern Cape (91,9%). Nationally, 24,0 % of households"
2456: "general and less than one per cent of rural households in KwaZulu-Natal (0,4%). A large percentage of"
2459: "while only 4,5% of households in Limpopo and 5,9% in KwaZulu-Natal accessed the internet at work."
2546: "KwaZulu-Natal (34,3%). By comparison, only 4,0% of South African households used a bus during the"
2915: "KwaZulu-Natal                                    89,23"
2986: "GHS estimates. In particular, the sample sizes increased most notably in Gauteng, KwaZulu-Natal and Eastern"
3897: "KwaZulu-Natal              5 176       5 652     10 828           47         41          87         411         416      828         171         182     354     5 805    6 292   12 096"
4648: "KwaZulu-Natal                                                                    335                                               831                 1 166"
4822: "KwaZulu-Natal                                                                                                                                                      12 096"
5413: "KwaZulu-Natal                                      542                40                 86                 9             2 139               544         13            15      3 387"
5799: "Western Cape       Eastern Cape        Northern Cape       Free State     KwaZulu-Natal        North West          Gauteng      Mpumalanga   Limpopo   South Africa"
5935: "Western Cape      Eastern Cape Northern Cape            Free State KwaZulu-Natal          North West          Gauteng         Mpumalanga   Limpopo   South Africa"
6666: "Western Cape      Eastern Cape     Northern Cape      Free State   KwaZulu-Natal      North West     Gauteng     Mpumalanga         Limpopo   South Africa"
6735: "Western Cape     Eastern Cape     Northern Cape       Free State   KwaZulu-Natal     North West     Gauteng       Mpumalanga    Limpopo    South Africa"
6767: "Western Cape      Eastern Cape      Northern Cape      Free State     KwaZulu-Natal     North West      Gauteng       Mpumalanga    Limpopo    South Africa"
6795: "Western Cape     Eastern Cape      Northern Cape     Free State    KwaZulu-Natal     North West     Gauteng     Mpumalanga   Limpopo   South Africa"

====================================================================================================
SEARCH: KZN
Matches: 12
====================================================================================================
0338: "KZN           KwaZulu-Natal"
0552: "WC         EC        NC       FS         KZN        NW            GP      MP      LP      RSA"
0605: "WC         EC        NC      FS       KZN          NW      GP         MP       LP       RSA"
0721: "EC     KZN    MP     LP     NC     FS         RSA    WC     NW     GP     Urban Rural"
0840: "aged 0─4 years                     WC      EC      NC          FS      KZN      NW      GP       MP      LP      RSA"
0890: "Type of institution         WC        EC         NC        FS           KZN       NW        GP      MP      LP         RSA"
1315: "Sex              WC         EC        NC        FS        KZN        NW      GP       MP        LP        RSA"
1769: "source                WC        EC      NC      FS      KZN        NW         GP      MP      LP      RSA"
1833: "quality         (Thousands)     WC      EC      NC     FS     KZN       NW      GP       MP       LP      RSA"
2363: "Type of internet access      WC        EC       NC        FS         KZN          NW          GP          MP            LP          RSA"
2426: "accessed      status      WC      EC     NC       FS          KZN     NW       GP     MP       LP       RSA"
2862: "Production activity (Thousands)             WC        EC      NC        FS     KZN       NW       GP       MP       LP      SA"

====================================================================================================
SEARCH: participation
Matches: 6
====================================================================================================
0149: "Figure 4.8 – Percentage (%) distribution of student participation rates for individuals aged 18 to 29 years"
0414: "There were approximately 15,6 million learners at school in 2024. Participation in education institutions was"
0833: "The survey shows that access to and participation in ECD activities among children aged 0–4 has overall"
1068: "Even though most students are black African, the education participation rate of this population group remained"
1071: "Figure 4.8 – Percentage (%) distribution of student participation rates for individuals aged 18 to 29"
2848: "Participation in agriculture to generate an extra source of income was most common in Northern Cape (20,5%)"

====================================================================================================
SEARCH: participation rate
Matches: 3
====================================================================================================
0149: "Figure 4.8 – Percentage (%) distribution of student participation rates for individuals aged 18 to 29 years"
1068: "Even though most students are black African, the education participation rate of this population group remained"
1071: "Figure 4.8 – Percentage (%) distribution of student participation rates for individuals aged 18 to 29"

====================================================================================================
SEARCH: Table
Matches: 109
====================================================================================================
0280: "LIST OF TABLES"
0282: "Table 2.1 – Population per province, 2002–2024 .............................................................................................. 2"
0283: "Table 2.2 – Number of households per province, 2002–2024 .......................................................................... 3"
0284: "Table 4.1 – Percentage (%) distribution of children aged 0─4 years that used different childcare"
0286: "Table 4.2 – Percentage (%) distribution of individuals aged 5 years and older who are attending"
0288: "Table 4.3 – Distribution of students enrolled at higher education institutions by population group, 2002"
0290: "Table 5.1 – Medical aid coverage, 2002–2024 ............................................................................................... 19"
0291: "Table 6.1 – Distribution of individuals aged 5 years and older with disability by sex and province, 2024 ...... 21"
0292: "Table 9.1 – Comparison of the main water source for drinking used by households, 2002–2024 ................. 28"
0293: "Table 9.2 – Percentage (%) distribution of households by alternative water sources used during water"
0295: "Table 9.3 – Perceptions of households regarding the quality of the water they drink per province, 2024 ...... 35"
0296: "Table 12.1 – Household refuse removal by province and urban/rural status, 2024 ........................................ 47"
0297: "Table 14.1 – Percentage (%) distribution of households with access to the Internet by province and type"
0299: "Table 14.2 – Percentage (%) distribution of households with access to the Internet by metro and type of"
0301: "Table 14.3 – Households’ access to the Internet by place of access, urban/rural status and province,"
0303: "Table 15.1 – Mode of transport used by household members to travel to school and work, 2024 ................. 55"
0304: "Table 16.1 – Percentage (%) distribution of household ownership of selected assets by urban/rural status,"
0306: "Table 18.1 – Nature of agricultural production activities per province, 2024 .................................................. 64"
0307: "Table 19.1 – Response rates per province, GHS 2024 ................................................................................... 65"
0308: "Table 19.2 – Comparison between the 2007 (old) Master Sample and the new Master Sample (designed"
0310: "Table 19.3 – Measures of precision for relationship to the household head, 2024 ......................................... 75"
0311: "Table 19.4 – Measures of precision for marital status, 2024........................................................................... 75"
0312: "Table 19.5 – Measures of precision for educational institution attended, 2024 .............................................. 75"
0313: "Table 19.6 – Measures of precision for highest level of education, 2024 ....................................................... 76"
0314: "Table 19.7 – Measures of precision for disability status, 2024 ....................................................................... 76"
0315: "Table 19.8 – Measures of precision for medical aid coverage, 2024 .............................................................. 76"
0316: "Table 19.9 – Measures of precision for Main Dwelling, 2024.......................................................................... 77"
0317: "Table 19.10 – Measures of precision for type of toilet facility, 2024 ............................................................... 77"
0318: "Table 19.11 – Measures of precision for main source of water for household use, 2024 ............................... 78"
0319: "Table 19.12 – Measures of precision for tenure status, 2024 ......................................................................... 78"
0320: "Table 19.13 – Measures of precision for refuse removal, 2024 ...................................................................... 78"
0321: "Table 19.14 – Measures of precision for main source of energy used for cooking, 2024 ............................... 79"
0322: "Table 19.15 – Measures of precision for main source of energy used for lighting, 2024 ................................ 79"
0323: "Table 19.16 – Measures of precision for health facility used by households, 2024 ........................................ 79"
0417: "exit grade 12. A notable percentage of learners, however, remained in primary and secondary schools long"
0465: "between 2002 and 2024 (growing from 84,4% to 87,7%). The increases were particularly notable in Eastern"
0466: "Cape (+13,8 percentage points) and KwaZulu-Natal (+7,5 percentage points). Despite these notable"
0547: "The population figures in Table 2.1 are based on mid-year population estimates produced for 2024 using the"
0550: "Table 2.1 – Population per province, 2002–2024"
0590: "Table 2.2 outlines the estimated number of households to which the GHS data were benchmarked in each"
0602: "Table 2.2 – Number of households per province, 2002–2024"
0836: "Table 4.1 – Percentage (%) distribution of children aged 0─4 years that used different childcare"
0863: "Table 4.1 summarises the attendance of young children aged 0–4 years at different types of ECD facilities or"
0874: "Table 4.2 shows that, nationally, 86,9% of these individuals attended primary or secondary schools, while a"
0886: "Table 4.2 – Percentage (%) distribution of individuals aged five years and older who were attending"
1047: "Table 4.3 shows that the total number of students enrolled at higher education institutions increased by 59,7%"
1052: "Table 4.3 – Distribution of students enrolled at higher education institutions by population group, 2002"
1214: "Despite some minor fluctuations over the period, Table 5.1 shows that the percentage of individuals who were"
1216: "15,9% to 15,5%. It is, however, notable that the number of individuals who were covered by a medical aid"
1219: "Table 5.1 – Medical aid coverage, 2002–2024"

====================================================================================================
SEARCH: province
Matches: 179
====================================================================================================
0126: "Figure 3.2 – Percentage (%) distribution of household size by province and rural/urban status, 2024 ............ 4"
0127: "Figure 3.3 – Percentage (%) distribution of female-headed households by province and urban/rural status,"
0129: "Figure 3.4 – Percentage (%) distribution of households by their composition, province and rural/urban"
0131: "Figure 3.5 – Percentage (%) distribution of inter-generational households by province and rural/urban"
0133: "Figure 3.6 – Percentage (%) distribution of children orphanhood status by province, 2024 ............................. 6"
0134: "Figure 3.7 – Percentage (%) distribution of children’s living arrangements by province and urban/rural"
0138: "institutions by province, 2002 and 2024 ................................................................................................ 11"
0142: "who did not pay tuition fees, by province, 2024 .................................................................................... 12"
0144: "school and province, 2024 .................................................................................................................... 12"
0146: "school nutrition programme by province, 2009 and 2024 ..................................................................... 13"
0148: "province, 2009 and 2024 ....................................................................................................................... 13"
0154: "older by province, 2024 ......................................................................................................................... 16"
0161: "when members fall ill or get injured by province, 2024 ......................................................................... 18"
0163: "province, 2024 ....................................................................................................................................... 19"
0173: "province, 2024 ....................................................................................................................................... 22"
0175: "COVID-19 social relief of distress grant by province, 2020–2024 ........................................................ 23"
0179: "dwellings by province, 2024 .................................................................................................................. 24"
0182: "Figure 8.3 – Percentage (%) distribution of dwelling units by tenure status and province, 2024.................... 25"
0195: "had weak or very weak walls and/or roof by province, 2024 ................................................................ 26"
0197: "off-site or on-site by province, selected years 2002–2024 .................................................................... 27"
0202: "Figure 9.5 – Percentage (%) distribution of households by frequency of water interruptions and province,"
0205: "province, 2002–2024 ............................................................................................................................. 36"
0206: "Figure 10.2 – Percentage (%) distribution of households by type of toilet facility and province, 2024 ........... 37"
0210: "province, 2024 ....................................................................................................................................... 38"
0212: "province for selected years between 2002 and 2024............................................................................ 41"
0214: "province, 2024 ....................................................................................................................................... 42"
0219: "Figure 11.5 – Percentage (%) distribution of main sources of energy used for cooking by province, 2024."
0222: "and/or scheduled electricity outages during the previous week, by province, 2024 ............................. 45"
0223: "Figure 11.7 – Percentage (%) distribution of alternative sources of energy used for cooking, by province,"
0229: "province, 2024. ...................................................................................................................................... 48"
0235: "telephone in their dwellings by province, 2024. .................................................................................... 51"
0242: "week preceding the survey by province, 2024. ..................................................................................... 55"
0245: "Figure 16.1 – Percentage (%) distribution of sources of household income by province, 2024. .................... 57"
0246: "Figure 16.2 – Percentage (%) distribution of main source of household income by province, 2024 .............. 57"

In [14]:
# Inspect the education participation tables in the GHS publication
# Extract the surrounding lines for Table 4.2 and Figure 4.8

start_line = 880
end_line = 1090

print("=" * 100)
print("GHS 2024 EDUCATION PARTICIPATION SECTION")
print("=" * 100)

for number in range(start_line, end_line + 1):

    line = ghs_lines[number - 1].strip()

    if line:
        print(f"{number:04}: {line[:700]}")

====================================================================================================
GHS 2024 EDUCATION PARTICIPATION SECTION
====================================================================================================
0880: ""
0881: "General Household Survey, 2024"
0882: "STATISTICS SOUTH AFRICA                                          9                                                     P0318"
0883: ""
0884: ""
0885: ""
0886: "Table 4.2 – Percentage (%) distribution of individuals aged five years and older who were attending"
0887: "educational institutions by province and type of institution attended, 2024"
0888: "Province (per cent)"
0889: ""
0890: "Type of institution         WC        EC         NC        FS           KZN       NW        GP      MP      LP         RSA"
0891: ""
0892: "Pre-school                     3,7       2,4        2,7         3,0        1,8       1,7      3,5     2,1        1,2      2,5"
0893: ""
0894: "School                        82,0      92,6      90,6       88,0         92,3      89,7     76,9    90,7    92,7        86,9"
0895: "Higher education"
0896: "institutions                   7,7       2,6        2,5         4,7        3,4       4,2     10,0     3,2        3,4      5,5"
0897: ""
0898: "TVET                           2,7       1,5        2,1         2,9        1,5       2,5      3,2     1,9        2,4      2,3"
0899: ""
0900: "Other colleges                 1,6       0,6        0,9         1,1        0,5       0,7      4,6     1,4        0,2      1,7"
0901: ""
0902: "Home Schooling                 1,0       0,1        0,6         0,1        0,0       0,2      0,5     0,1        0,0      0,3"
0903: ""
0904: "Other                          1,3       0,3        0,6         0,3        0,4       0,9      1,4     0,6        0,2      0,8"
0905: ""
0906: "Total (Thousands)           1 786      2 014       343       900         3 567     1 156    4 484   1 493   2 155      17 899"
0907: "Unspecified was excluded from the denominator when calculating percentages"
0908: ""
0909: ""
0910: ""
0911: "The percentage of individuals aged five years and older who attended school was the highest in Limpopo"
0912: "(92,7%), Eastern Cape (92,6%), KwaZulu-Natal (92,3%), Mpumalanga (90,7%) and Northern Cape (90,6%),"
0913: "and lowest in Gauteng (76,9%). Attendance of higher education institutions was most common in Gauteng"
0914: "(10,0%) and Western Cape (7,7%) and least common in Eastern Cape (2,6%) and Northern Cape (2,5%)."
0915: ""
0916: "The percentage of individuals aged 5–24 years that attended educational institutions by single ages is"
0917: "presented in Figure 4.1. The figure shows very high school attendance (primary and secondary school) in the"
0918: "age group 7–16 years, after which the attendance of educational facilities drops sharply. By the age of 24"
0919: "years, approximately 10,7% of individuals were still attending an educational facility. The figure also shows a"
0920: "noticeable representation of learners who were older than the ideal completion age in primary and secondary"
0921: "schools."
0922: ""
0923: ""
0924: ""
0925: ""
0926: "General Household Survey, 2024"
0927: "STATISTICS SOUTH AFRICA                                                    10                P0318"
0928: ""
0929: ""
0930: ""
0931: "Figure 4.1 – Type of educational institution attended by individuals aged 5─24 years, 2024"
0932: ""
0933: ""
0934: ""
0935: ""
0936: "General Household Survey, 2024"
0937: "STATISTICS SOUTH AFRICA                               11                                                 P0318"
0938: ""
0939: ""
0940: ""
0941: "Figure 4.2 – Percentage (%) distribution of individuals aged 7 to 24 years who attended educational"
0942: "institutions by province, 2002 and 2024"
0943: ""
0944: ""
0945: ""
0946: ""
0947: "Figure 4.2 shows that, nationally, the percentage of persons aged 7–24 years who attended educational"
0948: "institutions increased from 73,1% in 2002 to 75,1% in 2024. Attendance increased across most provinces"
0949: "between 2002 and 2024 with the highest increase observed in Northern Cape (+6,3 percentage points), and"
0950: "Free State (+5,1 percentage points). There is a decrease in Mpumalanga of 0,5 percentage points between"
0951: "2002 and 2024."
0952: ""
0953: "Figure 4.3 – Percentage (%) distribution of main reasons given by individuals aged 7 to 18 years for"
0954: "not attending an educational institution by sex, 2024"
0955: ""
0956: ""
0957: ""
0958: ""
0959: "The main reasons provided by males and females in the age group 7–18 years for not attending any"
0960: "educational institutions are depicted in Figure 4.3. Learners most commonly reported poor performance"
0961: "(25,7%), no money for fees (20,1%) and completed school (17,0%) as the main reason for not attending an"
0962: "educational institution. Less than one-fifth of individuals aged 7–18 years have indicated either other reasons"
0963: "(14,4%) or disability and illness (7,8%) as the main reason for not attending school. Although 5,6% of"
0964: "individuals left their studies as a result of family commitments (i.e. getting married, minding children and"
0965: "pregnancy), it more commonly applied to females (11,0%) than males (0,4%)."
0966: ""
0967: ""
0968: ""
0969: "General Household Survey, 2024"
0970: "STATISTICS SOUTH AFRICA                                           12                                    P0318"
0971: ""
0972: ""
0973: ""
0974: "Figure 4.4 – Percentage (%) distribution of individuals aged 5 years and older who attended schools"
0975: "and who did not pay tuition fees, by province, 2024"
0976: ""
0977: ""
0978: ""
0979: ""
0980: "Although inadequate access to money to pay for fees remains a major hurdle for learners, two-thirds (65,7%)"
0981: "of learners aged five years and older attended schools where no tuition fees were levied in 2024 (Figure 4.4)."
0982: "The attendance of no-fee schools was most common in Limpopo (89,8%), and least common in Western Cape"
0983: "(51,2%), and Gauteng (53,1%)."
0984: ""
0985: "4.3     School attendance"
0986: ""
0987: "There were approximately 15,6 million learners at school in 2024. The largest percentage of these learners"
0988: "attended schools in KwaZulu-Natal (21,2%) and Gauteng (22,2%)."
0989: ""
0990: "Figure 4.5 – Percentage (%) distribution of learners who attended school by main mode of transport to"
0991: "school and province, 2024"
0992: ""
0993: ""
0994: ""
0995: ""
0996: "Note: School bus refers to “Minibus/bus provided by institution/government and not paid for”"
0997: "Other includes “bicycle/motorcycle”, “train” and “other” categories"
0998: ""
0999: ""
1000: ""
1001: ""
1002: "General Household Survey, 2024"
1003: "STATISTICS SOUTH AFRICA                              13                                                P0318"
1004: ""
1005: ""
1006: ""
1007: "Figure 4.5 shows that 63,9% of learners walked to school. Another 15,2% of learners were transported to"
1008: "school by vehicles hired by parents, while 9,1% were transported there using private vehicles. Although 4,9%"
1009: "used buses or minibuses provided by the school, 1,3% used public buses. Walking to school was most"
1010: "common in Free State (76,7%), Limpopo (73,3%) and Mpumalanga (71,7%) and least common in Gauteng"
1011: "(50,3%). Almost one-fifth (22,3%) of learners in Western Cape and 15,7% of learners in Gauteng were"
1012: "transported to school by private vehicles, compared to 3,8% of learners in Limpopo. The use of vehicles hired"
1013: "by parents was highest in Gauteng (19,8%) and KwaZulu-Natal (18,2%)."
1014: ""
1015: "Figure 4.6 – Percentage (%) distribution of learners attending public schools who benefited from the"
1016: "school nutrition programme by province, 2009 and 2024"
1017: ""
1018: ""
1019: ""
1020: ""
1021: "Figure 4.6 presents the percentage of learners who attended public schools and who benefited from a school"
1022: "nutrition programme in each province in 2009 and 2024. More than three-quarters (78,4%) of learners who"
1023: "attended public schools benefitted from school feeding schemes in 2024, compared to 63,1% in 2009. Over"
1024: "80% of learners in Eastern Cape, Northern Cape, KwaZulu-Natal, North West, Mpumalanga and Limpopo"
1025: "benefitted from school nutrition programmes at public schools. Learners in Limpopo (91,7%) and Eastern Cape"
1026: "(89,3%) benefitted mostly from this programme, while only 58,0% of learners in Western Cape and 60,9% in"
1027: "Gauteng benefitted from this type of programme."
1028: ""
1029: "Figure 4.7 – Percentage (%) distribution of learners who experienced corporal punishment at school"
1030: "by province, 2009 and 2024"
1031: ""
1032: ""
1033: ""
1034: ""
1035: "General Household Survey, 2024"
1036: "STATISTICS SOUTH AFRICA                                    14                                            P0318"
1037: ""
1038: ""
1039: ""
1040: "Figure 4.7 shows that, nationally, the percentage of learners who experienced corporal punishment at school"
1041: "has decreased from 16,6% in 2009 to 6,7% in 2024.Corporal punishment was most prevalent amongst learners"
1042: "in KwaZulu-Natal (20,1%) and Eastern Cape (10,8%). By comparison, only 0,4% of learners in Gauteng and"
1043: "0,5% of learners in Western Cape stated that they received this sort of punishment in 2024."
1044: ""
1045: "4.4      Attendance of institutions of higher education"
1046: ""
1047: "Table 4.3 shows that the total number of students enrolled at higher education institutions increased by 59,7%"
1048: "between 2002 and 2024, growing to 980 000. Black African students comprised more than three-quarters"
1049: "(77,0%) of all students in 2024 (up from 60,2% in 2002). White students comprised 10,3% of all students in"
1050: "2024, down from 27,5% a few decades earlier."
1051: ""
1052: "Table 4.3 – Distribution of students enrolled at higher education institutions by population group, 2002"
1053: "and 2024"
1054: "2002           2024"
1055: ""
1056: "Black African                       60,2           77,0"
1057: ""
1058: "Coloured                             6,6            6,5"
1059: ""
1060: "Indian/Asian                         5,8            6,2"
1061: ""
1062: "White                               27,5           10,3"
1063: ""
1064: "Total per cent                     100,0          100,0"
1065: ""
1066: "Total Number (‘000)                 613            980"
1067: ""
1068: "Even though most students are black African, the education participation rate of this population group remained"
1069: "proportionally low in comparison with the Indian/Asian and white population groups."
1070: ""
1071: "Figure 4.8 – Percentage (%) distribution of student participation rates for individuals aged 18 to 29"
1072: "years by population group, 2002 and 2024"
1073: ""
1074: ""
1075: ""
1076: ""
1077: "Figure 4.8 shows that the percentage of persons aged 18 to 29 years that were enrolled at an institution of"
1078: "higher education in the country increased from 4,3% in 2002 to 5,3% in 2024. Enrolment at a higher education"
1079: "institution was most common among Indian/Asians (21,1%) and whites (14,5%). By comparison, 4,5% of the"
1080: "coloured and 4,6% of the black African population groups were enrolled in institutions of higher education."
1081: ""
1082: ""
1083: ""
1084: ""
1085: "General Household Survey, 2024"
1086: "STATISTICS SOUTH AFRICA                                                                            15                                                               P0318"
1087: ""
1088: ""
1089: ""
1090: "Figure 4.9 – Percentage (%) distribution of educational attainment for individuals aged 20 years and older, 2002–2024"

For our project, Table 4.2 is usable as supplementary participation/context data, but it is education participation, not electoral participation. It gives us a clean KZN-specific provincial measure and can help contextualise participation-related socioeconomic conditions.

The useful KZN values are:

Pre-school: 1.8%
School: 92.3%
Higher education institutions: 3.4%
TVET: 1.5%
Other colleges: 0.5%
Home schooling: 0.0%
Other: 0.4%
Total: 3.567 million individuals aged 5+ attending educational institutions.

However, we should not mix these into the QLFS labour-participation table. We'll make a separate clean dataset from this source.

In [15]:
# Extract the KZN education participation figures from GHS Table 4.2
# Keep the institution type, KZN percentage and total attending population

education_rows = {
    "Pre-school": (1.8, None),
    "School": (92.3, None),
    "Higher education institutions": (3.4, None),
    "TVET": (1.5, None),
    "Other colleges": (0.5, None),
    "Home Schooling": (0.0, None),
    "Other": (0.4, None),
    "Total": (None, 3567)
}

ghs_kzn_clean = pd.DataFrame(
    [
        {
            "Province": "KwaZulu-Natal",
            "Institution_type": institution,
            "Percentage": percentage,
            "Total_attending_thousand": total
        }
        for institution, (percentage, total) in education_rows.items()
    ]
)

print("=" * 100)
print("GHS 2024 KZN EDUCATION PARTICIPATION")
print("=" * 100)

print(f"Rows: {len(ghs_kzn_clean)}")
print(f"Columns: {len(ghs_kzn_clean.columns)}")

display(ghs_kzn_clean)

====================================================================================================
GHS 2024 KZN EDUCATION PARTICIPATION
====================================================================================================
Rows: 8
Columns: 4

,Province,Institution_type,Percentage,Total_attending_thousand
0,KwaZulu-Natal,Pre-school,1.8,NaN
1,KwaZulu-Natal,School,92.3,NaN
2,KwaZulu-Natal,Higher education institutions,3.4,NaN
3,KwaZulu-Natal,TVET,1.5,NaN
4,KwaZulu-Natal,Other colleges,0.5,NaN
5,KwaZulu-Natal,Home Schooling,0.0,NaN
6,KwaZulu-Natal,Other,0.4,NaN
7,KwaZulu-Natal,Total,NaN,3567.0

In [16]:
# Validate the extracted GHS 2024 KZN education participation data
# Check missing values, duplicates and expected institution categories

print("=" * 100)
print("GHS 2024 KZN EDUCATION PARTICIPATION VALIDATION")
print("=" * 100)

expected_types = [
    "Pre-school",
    "School",
    "Higher education institutions",
    "TVET",
    "Other colleges",
    "Home Schooling",
    "Other",
    "Total"
]

print(f"Rows correct: {len(ghs_kzn_clean) == 8}")
print(f"Columns correct: {list(ghs_kzn_clean.columns) == ['Province', 'Institution_type', 'Percentage', 'Total_attending_thousand']}")
print(f"Province correct: {ghs_kzn_clean['Province'].eq('KwaZulu-Natal').all()}")
print(f"Institution types correct: {ghs_kzn_clean['Institution_type'].tolist() == expected_types}")
print(f"Duplicates: {ghs_kzn_clean.duplicated().sum()}")

print("\nMissing values:")
print(ghs_kzn_clean.isna().sum())

print("\nPercentage range check:")
percentage_values = ghs_kzn_clean["Percentage"].dropna()
print(f"Minimum: {percentage_values.min()}")
print(f"Maximum: {percentage_values.max()}")

print("\nTotal attending population (thousand):")
print(ghs_kzn_clean.loc[
    ghs_kzn_clean["Institution_type"] == "Total",
    "Total_attending_thousand"
].iloc[0])

====================================================================================================
GHS 2024 KZN EDUCATION PARTICIPATION VALIDATION
====================================================================================================
Rows correct: True
Columns correct: True
Province correct: True
Institution types correct: True
Duplicates: 0

Missing values:
Province                    0
Institution_type            0
Percentage                  1
Total_attending_thousand    7
dtype: int64

Percentage range check:
Minimum: 0.0
Maximum: 92.3

Total attending population (thousand):
3567.0

In [17]:
# Save the cleaned GHS 2024 KZN education participation dataset
# Keep the raw source untouched and store the cleaned version in interim

output_path = r"C:\Users\Student\Downloads\Big Data\SPU-TEAM-DIRISA\data\interim\KZN_Electoral_participation Cleaned\P03182024_clean.csv"

ghs_kzn_clean.to_csv(output_path, index=False, encoding="utf-8")

print("=" * 100)
print("GHS 2024 KZN EDUCATION PARTICIPATION SAVED")
print("=" * 100)

print(f"Output: {output_path}")
print(f"Rows saved: {len(ghs_kzn_clean)}")
print(f"Columns saved: {len(ghs_kzn_clean.columns)}")
print(f"File exists: {os.path.exists(output_path)}")

====================================================================================================
GHS 2024 KZN EDUCATION PARTICIPATION SAVED
====================================================================================================
Output: C:\Users\Student\Downloads\Big Data\SPU-TEAM-DIRISA\data\interim\KZN_Electoral_participation Cleaned\P03182024_clean.csv
Rows saved: 8
Columns saved: 4

NameError: name 'os' is not defined

In [18]:
# Inspect the QLFS Q1 2026 source file before extracting KZN data
# Check the structure, encoding and first few rows

qlfs_2026_path = r"C:\Users\Student\Downloads\Big Data\SPU-TEAM-DIRISA\data\raw\KZN_Electoral_participation\Presentation-QLFS-Q1-2026.csv"

qlfs_2026 = pd.read_csv(
    qlfs_2026_path,
    header=None,
    encoding="utf-8-sig"
)

print("=" * 100)
print("QLFS Q1 2026 SOURCE INSPECTION")
print("=" * 100)

print(f"Rows: {len(qlfs_2026)}")
print(f"Columns: {len(qlfs_2026.columns)}")

print("\nFirst 20 rows:")
display(qlfs_2026.head(20))

====================================================================================================
QLFS Q1 2026 SOURCE INSPECTION
====================================================================================================
Rows: 373
Columns: 1

First 20 rows:

                                                    0
0                Quarterly Labour Force Survey (QLFS)
1                                             Q1:2026
2                                                 NaN
3                                    Risenga Maluleke
4                                Statistician-General
5
Stats SA adopting more recent ICLS resolution...
6                                                 NaN
7                                                 NaN
8                                          Before Now
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                  2
14
           Labour Statistics now report on a ...
15                                                NaN
16                                        Working Age
17                                   Population 15-64
18                                                NaN
19                                                NaN

In [19]:
# Search the QLFS Q1 2026 source for KZN and participation-related tables
# This helps identify the relevant province-level figures before extraction

source_text = qlfs_2026[0].fillna("").astype(str)

print("=" * 100)
print("QLFS Q1 2026 RELEVANT SOURCE LINES")
print("=" * 100)

search_terms = [
    "KwaZulu-Natal",
    "KZN",
    "participation",
    "participation rate",
    "Table",
    "province"
]

for term in search_terms:
    matches = source_text[source_text.str.contains(term, case=False, na=False)]
    print(f"\n{term}: {len(matches)} matches")
    print(matches.head(15).to_string())

====================================================================================================
QLFS Q1 2026 RELEVANT SOURCE LINES
====================================================================================================

KwaZulu-Natal: 0 matches
Series([], )

KZN: 0 matches
Series([], )

participation: 3 matches
254    The labour force participation rate and Absor...
256    Labour force participation and absorption rate...
260    Labour force participation rate is the proport...

participation rate: 2 matches
254    The labour force participation rate and Absor...
260    Labour force participation rate is the proport...

Table: 0 matches
Series([], )

province: 0 matches
Series([], )

In [20]:
# Inspect the labour-force participation section of the QLFS Q1 2026 presentation
# Check the surrounding lines to identify the available indicators and their values

for start, end in [(245, 275), (275, 310)]:
    print("=" * 100)
    print(f"QLFS Q1 2026 LINES {start}-{end}")
    print("=" * 100)
    print(qlfs_2026.iloc[start:end].to_string(index=True))

====================================================================================================
QLFS Q1 2026 LINES 245-275
====================================================================================================
                                                                                                                                                                                                                              0
245                                                                                                                                                                                                                      19 000
246                                                                                                                                                                                                                         NaN
247                                                                                                                                                                                  Other                8,8%     1,2% point
248                                                                                                                                                                                                                     222 000
249                                                                                                                                                                                                                         NaN
250                                                                                                                                                                                                                         NaN
251                                                                                                                                                                                                                         NaN
252                                                                                                                                                                                                                         NaN
253                                                                                                                                                                                                                           9
254                                                                                                                           The labour force participation rate and Absorption rate decreased by 0,3 and 0,9 of a percentage
255                                                                                                                                                      point to 59,0% and 39,7% in Q1:2026 respectively, compared to Q4:2025.
256                                                                                                                                                             Labour force participation and absorption rates Q1:2016-Q1:2026
257                                                                                                                                                                                                                         NaN
258                                                                                                                                                                                                                         NaN
259                                                                                                                                                                                                                         NaN
260                                                                                                                                                           Labour force participation rate is the proportion of the working-
261                                                                                                                                                                        age population that is either employed or unemployed
262                                                                                                                                                                                                                       59,3%
263  58,7%                                                                                                                                                                                                                59,0%
264                                                                                                                                                                                                                         NaN
265                                                                                                                                                                                                                         NaN
266                                                                                                                                                                                                                         NaN
267                                                                                                                                                                                                                15,7% Points
268              difference                                                                                                                                                                             19,3% Points difference
269                                                                                                                                                                                                                         NaN
270                                                                                                                                                                                                                         NaN
271                                                                                                                                                                                                                       47,3%
272                                                                                                                                                                                                                       40,6%
273                                                                                                                                                                                                                       43,0%
274                                                                                                                                                                                                                         NaN
====================================================================================================
QLFS Q1 2026 LINES 275-310
====================================================================================================
                                                                                                                                                                                                                                     0
275                              Absorption rate is the proportion of                                                                                                                                                            39,7%
276                                                                                                                                                                                        the working-age population that is employed
277                                                                                                                                                                                                                               36,3
278                                                                                                                                                                                                                                NaN
279  2016                  2017                  2018                  2019                  2020                   2021                  2022                  2023                  2024                  2025                  2026
280                                                                                                                                                                                                                                NaN
281    Q1    Q2   Q3   Q4   Q1     Q2   Q3   Q4   Q1     Q2   Q3   Q4   Q1     Q2   Q3   Q4   Q1     Q2    Q3   Q4   Q1     Q2   Q3   Q4   Q1     Q2   Q3   Q4   Q1     Q2   Q3   Q4   Q1     Q2   Q3   Q4   Q1     Q2   Q3   Q4    Q1
282                                                                                                                                                                                                                                NaN
283                                                                                                                                                                                                                                NaN
284                                                                                                                                                                                                                                NaN
285                                                                                                                                                                                                                                NaN
286                                                                                                                                                                                                                                 10
287                                                                                                                        In addition to Unemployment, the 19th ICLS resolution introduces other measures of Labour Underutilisation
288                                                                                                                                                                                                                                NaN
289                                                                                                                                                                                                                        Working Age
290                                                                                                                                                                                                                   Population 15-64
291                                                                                                                                                                                                                                NaN
292                                                                                                                                                                                                                                NaN
293                                                                                                                                                                                                                                NaN
294                                                                                                                                          Labour Force                                                     Outside the Labour Force
295                                                                                                                                                                                                                                NaN
296                                                                                                                                                                                                                                NaN
297                                                                                                                                                                                                                                NaN
298                                                                                                                                                                                     Potential Labour            Others outside the
299                                                                                                                                                                                             Employed                    Unemployed
300                                                                                                                                                                                             Force                     labour force
301                                                                                                                                                                                                            Want employment but not
302                                                                                                                                                                                                               seeking or available
303                                                                                                                                                                                                                       Time-related
304                                                                                                                                  underemployment                    Available,                              Do not want employment
305                                                                                                                                                                                                                     Not available,
306                                                                                                                                                                                                  not seeking           but seeking
307                                                                                                                                                                                                                                NaN
308                                                                                                                                                                                                               Includes Discouraged
309                                                                                                                                                                                                                        Job-seekers

In [21]:
# Extract the visible QLFS labour-force participation figures from the presentation
# Check the surrounding lines for the historical participation-rate values

print("=" * 100)
print("QLFS Q1 2026 PARTICIPATION RATE FIGURES")
print("=" * 100)

for i in range(260, 285):
    value = qlfs_2026.iloc[i, 0]
    if pd.notna(value) and str(value).strip():
        print(f"{i}: {value}")

====================================================================================================
QLFS Q1 2026 PARTICIPATION RATE FIGURES
====================================================================================================
260: Labour force participation rate is the proportion of the working-
261: age population that is either employed or unemployed
262: 59,3%
263: 58,7%                                                                                                                                                                                                                59,0%
267: 15,7% Points
268: difference                                                                                                                                                                             19,3% Points difference
271: 47,3%
272: 40,6%
273: 43,0%
275: Absorption rate is the proportion of                                                                                                                                                            39,7%
276: the working-age population that is employed
277: 36,3
279: 2016                  2017                  2018                  2019                  2020                   2021                  2022                  2023                  2024                  2025                  2026
281: Q1    Q2   Q3   Q4   Q1     Q2   Q3   Q4   Q1     Q2   Q3   Q4   Q1     Q2   Q3   Q4   Q1     Q2    Q3   Q4   Q1     Q2   Q3   Q4   Q1     Q2   Q3   Q4   Q1     Q2   Q3   Q4   Q1     Q2   Q3   Q4   Q1     Q2   Q3   Q4    Q1

In [23]:
# Create a clean national QLFS Q1 2026 participation dataset
# Keep only figures that are explicitly identifiable in the source

qlfs_2026_clean = pd.DataFrame([
    {
        "Geography": "South Africa",
        "Period": "Q1:2026",
        "Indicator": "Labour force participation rate",
        "Value_percent": 59.0,
        "Change_from_previous_quarter_percentage_points": -0.3
    },
    {
        "Geography": "South Africa",
        "Period": "Q1:2026",
        "Indicator": "Absorption rate",
        "Value_percent": 39.7,
        "Change_from_previous_quarter_percentage_points": -0.9
    }
])

print("=" * 100)
print("QLFS Q1 2026 NATIONAL PARTICIPATION DATA")
print("=" * 100)

print(f"Rows: {len(qlfs_2026_clean)}")
print(f"Columns: {len(qlfs_2026_clean.columns)}")

display(qlfs_2026_clean)

====================================================================================================
QLFS Q1 2026 NATIONAL PARTICIPATION DATA
====================================================================================================
Rows: 2
Columns: 5

,Geography,Period,Indicator,Value_percent,Change_from_previous_quarter_percentage_points
0,South Africa,Q1:2026,Labour force participation rate,59.0,-0.3
1,South Africa,Q1:2026,Absorption rate,39.7,-0.9

In [24]:
# Validate the QLFS Q1 2026 national participation dataset
# Check structure, values, missing data and duplicates

print("=" * 100)
print("QLFS Q1 2026 NATIONAL PARTICIPATION VALIDATION")
print("=" * 100)

print(f"Rows correct: {len(qlfs_2026_clean) == 2}")
print(f"Columns correct: {len(qlfs_2026_clean.columns) == 5}")
print(f"Geography correct: {qlfs_2026_clean['Geography'].eq('South Africa').all()}")
print(f"Period correct: {qlfs_2026_clean['Period'].eq('Q1:2026').all()}")
print(f"Duplicates: {qlfs_2026_clean.duplicated().sum()}")

print("\nMissing values:")
print(qlfs_2026_clean.isna().sum())

print("\nValue range:")
print(f"Minimum: {qlfs_2026_clean['Value_percent'].min()}%")
print(f"Maximum: {qlfs_2026_clean['Value_percent'].max()}%")

print("\nIndicators:")
print(qlfs_2026_clean["Indicator"].tolist())

====================================================================================================
QLFS Q1 2026 NATIONAL PARTICIPATION VALIDATION
====================================================================================================
Rows correct: True
Columns correct: True
Geography correct: True
Period correct: True
Duplicates: 0

Missing values:
Geography                                         0
Period                                            0
Indicator                                         0
Value_percent                                     0
Change_from_previous_quarter_percentage_points    0
dtype: int64

Value range:
Minimum: 39.7%
Maximum: 59.0%

Indicators:
['Labour force participation rate', 'Absorption rate']

In [25]:
# Save the cleaned QLFS Q1 2026 participation dataset
# Keep the raw presentation untouched and store the cleaned version in interim

output_path = r"C:\Users\Student\Downloads\Big Data\SPU-TEAM-DIRISA\data\interim\KZN_Electoral_participation Cleaned\Presentation-QLFS-Q1-2026_clean.csv"

qlfs_2026_clean.to_csv(output_path, index=False, encoding="utf-8")

print("=" * 100)
print("QLFS Q1 2026 PARTICIPATION DATASET SAVED")
print("=" * 100)

print(f"Output: {output_path}")
print(f"Rows saved: {len(qlfs_2026_clean)}")
print(f"Columns saved: {len(qlfs_2026_clean.columns)}")

====================================================================================================
QLFS Q1 2026 PARTICIPATION DATASET SAVED
====================================================================================================
Output: C:\Users\Student\Downloads\Big Data\SPU-TEAM-DIRISA\data\interim\KZN_Electoral_participation Cleaned\Presentation-QLFS-Q1-2026_clean.csv
Rows saved: 2
Columns saved: 5