In [14]:
import pandas as pd

print("Pandas version:", pd.__version__)

Pandas version: 3.0.6

In [15]:
from pathlib import Path
import numpy as np

print("Libraries loaded successfully!")

Libraries loaded successfully!

In [16]:
BASE_DIR = Path(r"C:\Users\Admin\PycharmProjects\SPU-TEAM-DIRISA")

RAW_DIR = BASE_DIR / "data" / "raw"
PROCESSED_DIR = BASE_DIR / "data" / "processed"
OUTPUT_DIR = BASE_DIR / "output"

print("Project:", BASE_DIR)
print("Raw folder exists:", RAW_DIR.exists())

Project: C:\Users\Admin\PycharmProjects\SPU-TEAM-DIRISA
Raw folder exists: True

In [17]:
print("Files in raw folder:")

for file in RAW_DIR.iterdir():
    print(file.name)

Files in raw folder:
.gitkeep
IEC_2016_Municipal_Results.csv
IEC_2021_Municipal_Results.xls
iec_kzn_ethekwini_ward_registration_2026.csv
StatsSA_Ward_Product_2022.xlsx

In [18]:
iec_2016_path = RAW_DIR / "IEC_2016_Municipal_Results.csv"

iec_2016 = pd.read_csv(iec_2016_path)

print("IEC 2016 loaded successfully!")
print("Rows:", len(iec_2016))
print("Columns:", len(iec_2016.columns))

IEC 2016 loaded successfully!
Rows: 40706
Columns: 11

In [6]:
print("Files in raw folder:")

for file in RAW_DIR.iterdir():
    print(file.name)

Files in raw folder:
.gitkeep
IEC_2016_Municipal_Results.csv
IEC_2021_Municipal_Results.xls
iec_kzn_ethekwini_ward_registration_2026.csv
StatsSA_Ward_Product_2022.xlsx

In [19]:
print(iec_2016.columns.tolist())

['Province', 'Municipality', 'Ward', 'VotingDistrict', 'VotingStationName', 'RegisteredVoters', 'BallotType', 'SpoiltVotes', 'PartyName', 'TotalValidVotes', 'DateGenerated']

In [20]:
iec_2016.head()

,Province,Municipality,Ward,VotingDistrict,VotingStationName,RegisteredVoters,BallotType,SpoiltVotes,PartyName,TotalValidVotes,DateGenerated
0,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,ACADEMIC CONGRESS UNION,0,8/11/2016 3:58:48 PM
1,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,AFRICAN CHRISTIAN DEMOCRATIC PARTY,0,8/11/2016 3:58:48 PM
2,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,AFRICAN INDEPENDENT CONGRESS,19,8/11/2016 3:58:48 PM
3,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,AFRICAN MANTUNGWA COMMUNITY,0,8/11/2016 3:58:48 PM
4,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,AFRICAN NATIONAL CONGRESS,1157,8/11/2016 3:58:48 PM

In [21]:
print("DataFrame type:", type(iec_2016))
print("Number of rows:", len(iec_2016))
print("Number of columns:", len(iec_2016.columns))
print("Column names:")
print(iec_2016.columns.tolist())

DataFrame type: <class 'pandas.DataFrame'>
Number of rows: 40706
Number of columns: 11
Column names:
['Province', 'Municipality', 'Ward', 'VotingDistrict', 'VotingStationName', 'RegisteredVoters', 'BallotType', 'SpoiltVotes', 'PartyName', 'TotalValidVotes', 'DateGenerated']

In [22]:
print(iec_2016.iloc[:5].to_string())

        Province     Municipality           Ward  VotingDistrict          VotingStationName  RegisteredVoters BallotType  SpoiltVotes                           PartyName  TotalValidVotes         DateGenerated
0  KwaZulu-Natal  ETH - eThekwini  Ward 59500001        43400179  NOMFIHLELA PRIMARY SCHOOL              1607         PR           72             ACADEMIC CONGRESS UNION                0  8/11/2016 3:58:48 PM
1  KwaZulu-Natal  ETH - eThekwini  Ward 59500001        43400179  NOMFIHLELA PRIMARY SCHOOL              1607         PR           72  AFRICAN CHRISTIAN DEMOCRATIC PARTY                0  8/11/2016 3:58:48 PM
2  KwaZulu-Natal  ETH - eThekwini  Ward 59500001        43400179  NOMFIHLELA PRIMARY SCHOOL              1607         PR           72        AFRICAN INDEPENDENT CONGRESS               19  8/11/2016 3:58:48 PM
3  KwaZulu-Natal  ETH - eThekwini  Ward 59500001        43400179  NOMFIHLELA PRIMARY SCHOOL              1607         PR           72         AFRICAN MANTUNGWA COMMUNITY                0  8/11/2016 3:58:48 PM
4  KwaZulu-Natal  ETH - eThekwini  Ward 59500001        43400179  NOMFIHLELA PRIMARY SCHOOL              1607         PR           72           AFRICAN NATIONAL CONGRESS             1157  8/11/2016 3:58:48 PM

In [23]:
print("Unique provinces:", iec_2016["Province"].nunique())
print("Unique municipalities:", iec_2016["Municipality"].nunique())
print("Unique wards:", iec_2016["Ward"].nunique())
print("Unique voting districts:", iec_2016["VotingDistrict"].nunique())
print("Unique parties:", iec_2016["PartyName"].nunique())

Unique provinces: 1
Unique municipalities: 1
Unique wards: 110
Unique voting districts: 866
Unique parties: 28

In [24]:
print(iec_2016["Province"].unique())

<StringArray>
['KwaZulu-Natal']
Length: 1, dtype: str

In [25]:
kzn_2016 = iec_2016[
    iec_2016["Province"].str.strip().str.lower() == "kwaZulu-Natal".lower()
].copy()

print("KZN rows:", len(kzn_2016))
print("KZN wards:", kzn_2016["Ward"].nunique())
print("KZN municipalities:", kzn_2016["Municipality"].nunique())

KZN rows: 40706
KZN wards: 110
KZN municipalities: 1

In [26]:
kzn_2016[["Municipality", "Ward"]].drop_duplicates().head(20)

         Municipality           Ward
0     ETH - eThekwini  Ward 59500001
576   ETH - eThekwini  Ward 59500002
1488  ETH - eThekwini  Ward 59500003
2112  ETH - eThekwini  Ward 59500004
2592  ETH - eThekwini  Ward 59500005
2832  ETH - eThekwini  Ward 59500006
3200  ETH - eThekwini  Ward 59500007
3488  ETH - eThekwini  Ward 59500008
4086  ETH - eThekwini  Ward 59500009
4581  ETH - eThekwini  Ward 59500010
4896  ETH - eThekwini  Ward 59500011
5239  ETH - eThekwini  Ward 59500012
5575  ETH - eThekwini  Ward 59500013
5869  ETH - eThekwini  Ward 59500014
6253  ETH - eThekwini  Ward 59500015
6596  ETH - eThekwini  Ward 59500016
6918  ETH - eThekwini  Ward 59500017
7268  ETH - eThekwini  Ward 59500018
7488  ETH - eThekwini  Ward 59500019
7856  ETH - eThekwini  Ward 59500020

In [27]:
print(kzn_2016["Municipality"].unique())

<StringArray>
['ETH - eThekwini']
Length: 1, dtype: str

In [28]:
print(kzn_2016["Ward"].unique()[:20])

<StringArray>
['Ward 59500001', 'Ward 59500002', 'Ward 59500003', 'Ward 59500004',
 'Ward 59500005', 'Ward 59500006', 'Ward 59500007', 'Ward 59500008',
 'Ward 59500009', 'Ward 59500010', 'Ward 59500011', 'Ward 59500012',
 'Ward 59500013', 'Ward 59500014', 'Ward 59500015', 'Ward 59500016',
 'Ward 59500017', 'Ward 59500018', 'Ward 59500019', 'Ward 59500020']
Length: 20, dtype: str

In [29]:
print(kzn_2016.groupby("Municipality")["Ward"].nunique())

Municipality
ETH - eThekwini    110
Name: Ward, dtype: int64

In [32]:
print("Files currently in data/raw:")
for file in RAW_DIR.iterdir():
    print(repr(file.name))

Files currently in data/raw:
'.gitkeep'
'IEC_2016_Municipal_Results.csv'
'IEC_2021_Municipal_Results.xls'
'iec_kzn_ethekwini_ward_registration_2026.csv'
'StatsSA_Ward_Product_2022.xlsx'

In [34]:
iec_2021_path = RAW_DIR / "IEC_2021_Municipal_Results.xls"

iec_2021 = pd.read_excel(iec_2021_path)

print("IEC 2021 loaded successfully!")
print("Rows:", len(iec_2021))
print("Columns:", len(iec_2021.columns))
print("Column names:")
print(iec_2021.columns.tolist())

WARNING *** file size (24512) not 512 + multiple of sector size (512)
IEC 2021 loaded successfully!
Rows: 37
Columns: 18
Column names:
['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17']

In [35]:
print(iec_2021.to_string())

    Unnamed: 0                          Unnamed: 1  Unnamed: 2  Unnamed: 3 Unnamed: 4                             Unnamed: 5                 Unnamed: 6        Unnamed: 7            Unnamed: 8  Unnamed: 9                     Unnamed: 10          Unnamed: 11           Unnamed: 12          Unnamed: 13           Unnamed: 14  Unnamed: 15                Unnamed: 16           Unnamed: 17
0          NaN                                 NaN         NaN         NaN        NaN                                    NaN                        NaN               NaN                   NaN         NaN                             NaN                  NaN                   NaN                  NaN                   NaN          NaN                        NaN                   NaN
1          NaN                                 NaN         NaN         NaN        NaN                                    NaN                        NaN               NaN                   NaN         NaN                             NaN                  NaN                   NaN                  NaN                   NaN          NaN                        NaN                   NaN
2          NaN                                 NaN         NaN         NaN        NaN  Detailed DC 40% Ballot Results Report                        NaN               NaN                   NaN         NaN                             NaN                  NaN                   NaN                  NaN                   NaN          NaN                        NaN                   NaN
3          NaN                                 NaN         NaN         NaN        NaN        Printed on: 2021/11/22 16:19:57                        NaN               NaN                   NaN         NaN                             NaN                  NaN                   NaN                  NaN                   NaN          NaN                        NaN                   NaN
4          NaN                                 NaN         NaN         NaN        NaN                                    NaN                        NaN               NaN                   NaN         NaN                             NaN                  NaN                   NaN                  NaN                   NaN          NaN                        NaN                   NaN
5          NaN                                 NaN         NaN         NaN        NaN                                    NaN                        NaN  Electoral Event:                   NaN         NaN  LOCAL GOVERNMENT ELECTION 2021                  NaN                   NaN                  NaN                   NaN          NaN                        NaN                   NaN
6          NaN                                 NaN         NaN         NaN        NaN                                    NaN                        NaN               NaN                   NaN         NaN                             NaN                  NaN                   NaN                  NaN                   NaN          NaN                        NaN                   NaN
7          NaN                                 NaN         NaN         NaN        NaN                                    NaN                        NaN         Province:                   NaN         NaN                   KwaZulu-Natal                  NaN                   NaN                  NaN                   NaN          NaN                        NaN                   NaN
8          NaN                                 NaN         NaN         NaN        NaN                                    NaN                        NaN               NaN                   NaN         NaN                             NaN                  NaN                   NaN                  NaN                   NaN          NaN                        NaN                   NaN
9          NaN                                 NaN         NaN         NaN        NaN                                    NaN                        NaN     Municipality:                   NaN         NaN             DC27 - uMkhanyakude                  NaN                   NaN                  NaN                   NaN          NaN                        NaN                   NaN
10         NaN                                 NaN         NaN         NaN        NaN                                    NaN                        NaN               NaN                   NaN         NaN                             NaN                  NaN                   NaN                  NaN                   NaN          NaN                        NaN                   NaN
11         NaN                                 NaN         NaN         NaN        NaN                                    NaN                        NaN      Ballot Type:                   NaN         NaN                          DC 40%                  NaN                   NaN                  NaN                   NaN          NaN                        NaN                   NaN
12         NaN                                 NaN         NaN         NaN        NaN                                    NaN                        NaN               NaN                   NaN         NaN                             NaN                  NaN                   NaN                  NaN                   NaN          NaN                        NaN                   NaN
13         NaN                                 NaN         NaN         NaN        NaN                                    NaN                        NaN               NaN                   NaN         NaN                             NaN                  NaN                   NaN                  NaN                   NaN          NaN                        NaN                   NaN
14         NaN                          Party Name         NaN         NaN       Abbr                                    NaN  KZN271 - uMhlabuyalingana               NaN                   NaN         NaN                             NaN      KZN272 - Jozini                   NaN   KZN275 - Mtubatuba                   NaN          NaN  KZN276 - Big Five Hlabisa                   NaN
15         NaN                                 NaN         NaN         NaN        NaN                                    NaN        Total \nValid Votes               NaN  % Total\nValid Votes         NaN                             NaN  Total \nValid Votes  % Total\nValid Votes  Total \nValid Votes  % Total\nValid Votes          NaN        Total \nValid Votes  % Total\nValid Votes
16         NaN  ABAHLALI BASE MKHANYAKUDE MOVEMENT         NaN         NaN       ABMM                                    NaN                       1098               NaN              0.022932         NaN                             NaN                   37              0.000613                   38               0.00067          NaN                         24              0.000768
17         NaN               ABANTU BATHO CONGRESS         NaN         NaN        ABC                                    NaN                        607               NaN              0.012678         NaN                             NaN                  121              0.002004                  201              0.003543          NaN                         43              0.001376
18         NaN             ACADEMIC CONGRESS UNION         NaN         NaN        ACU                                    NaN                         28               NaN              0.000585         NaN                             NaN                  929              0.015383                   85              0.001498          NaN                         11              0.000352
19         NaN  AFRICAN CHRISTIAN DEMOCRATIC PARTY         NaN         NaN       ACDP                                    NaN                        651               NaN              0.013596         NaN                             NaN                   49              0.000811                 1198              0.021118          NaN                         37              0.001184
20         NaN        AFRICAN INDEPENDENT CONGRESS         NaN         NaN        AIC                                    NaN                        479               NaN              0.010004         NaN                             NaN                  453              0.007501                  613              0.010806          NaN                        186              0.005953
21         NaN           AFRICAN NATIONAL CONGRESS         NaN         NaN        ANC                                    NaN                      22823               NaN              0.476671         NaN                             NaN                21765              0.360395                20862              0.367742          NaN                      10444               0.33424
22         NaN           AFRICAN PEOPLE'S MOVEMENT         NaN         NaN      APEMO                                    NaN                         49               NaN              0.001023         NaN                             NaN                  123              0.002037                  308              0.005429          NaN                         10               0.00032
23         NaN     AFRICAN TRANSFORMATION MOVEMENT         NaN         NaN        ATM                                    NaN                         65               NaN              0.001358         NaN                             NaN                  206              0.003411                  125              0.002203          NaN                         25                0.0008
24         NaN                          AL JAMA-AH         NaN         NaN     ALJAMA                                    NaN                          8               NaN              0.000167         NaN                             NaN                   11              0.000182                  115              0.002027          NaN                          3              0.000096
25         NaN                 DEMOCRATIC ALLIANCE         NaN         NaN         DA                                    NaN                        894               NaN              0.018672         NaN                             NaN                  347              0.005746                 1074              0.018932          NaN                        347              0.011105
26         NaN               DEMOCRATIC UNION PLUS         NaN         NaN    DU PLUS                                    NaN                         10               NaN              0.000209         NaN                             NaN                   15              0.000248                   91              0.001604          NaN                          5               0.00016
27         NaN           ECONOMIC FREEDOM FIGHTERS         NaN         NaN        EFF                                    NaN                       2144               NaN              0.044779         NaN                             NaN                 2806              0.046463                 5112              0.090111          NaN                       1089              0.034851
28         NaN               INKATHA FREEDOM PARTY         NaN         NaN        IFP                                    NaN                      17787               NaN              0.371491         NaN                             NaN                32240              0.533846                25017              0.440984          NaN                      17933              0.573911
29         NaN        JUSTICE AND EMPLOYMENT PARTY         NaN         NaN        JEP                                    NaN                        202               NaN              0.004219         NaN                             NaN                  149              0.002467                  233              0.004107          NaN                        100                0.0032
30         NaN                    KZN INDEPENDENCE         NaN         NaN       KZNI                                    NaN                        196               NaN              0.004094         NaN                             NaN                  332              0.005497                  215               0.00379          NaN                        313              0.010017
31         NaN              NATIONAL FREEDOM PARTY         NaN         NaN        NFP                                    NaN                        718               NaN              0.014996         NaN                             NaN                  466              0.007716                  459              0.008091          NaN                        620              0.019842
32         NaN                  PATRIOTIC ALLIANCE         NaN         NaN         PA                                    NaN                         20               NaN              0.000418         NaN                             NaN                   24              0.000397                   39              0.000687          NaN                         10               0.00032
33         NaN   UNITED CHRISTIAN DEMOCRATIC PARTY         NaN         NaN       UCDP                                    NaN                         50               NaN              0.001044         NaN                             NaN                  214              0.003544                  452              0.007968          NaN                         28              0.000896
34         NaN          UNITED DEMOCRATIC MOVEMENT         NaN         NaN        UDM                                    NaN                         51               NaN              0.001065         NaN                             NaN                  105              0.001739                  493               0.00869          NaN                         19              0.000608
35         NaN                   Total Valid Votes         NaN         NaN        NaN                                    NaN                      47880               NaN                   1.0         NaN                             NaN                60392                   1.0                56730                   1.0          NaN                      31247                   1.0
36         NaN                        Spoilt Votes         NaN         NaN        NaN                                    NaN                       1544               NaN                   NaN         NaN                             NaN                 1437                   NaN                 1152                   NaN          NaN                        507                   NaN

In [36]:
print(iec_2021.iloc[:10, :].to_string(index=False, header=False))

NaN NaN NaN NaN NaN                                   NaN NaN              NaN NaN NaN                            NaN NaN NaN NaN NaN NaN NaN NaN
NaN NaN NaN NaN NaN                                   NaN NaN              NaN NaN NaN                            NaN NaN NaN NaN NaN NaN NaN NaN
NaN NaN NaN NaN NaN Detailed DC 40% Ballot Results Report NaN              NaN NaN NaN                            NaN NaN NaN NaN NaN NaN NaN NaN
NaN NaN NaN NaN NaN       Printed on: 2021/11/22 16:19:57 NaN              NaN NaN NaN                            NaN NaN NaN NaN NaN NaN NaN NaN
NaN NaN NaN NaN NaN                                   NaN NaN              NaN NaN NaN                            NaN NaN NaN NaN NaN NaN NaN NaN
NaN NaN NaN NaN NaN                                   NaN NaN Electoral Event: NaN NaN LOCAL GOVERNMENT ELECTION 2021 NaN NaN NaN NaN NaN NaN NaN
NaN NaN NaN NaN NaN                                   NaN NaN              NaN NaN NaN                            NaN NaN NaN NaN NaN NaN NaN NaN
NaN NaN NaN NaN NaN                                   NaN NaN        Province: NaN NaN                  KwaZulu-Natal NaN NaN NaN NaN NaN NaN NaN
NaN NaN NaN NaN NaN                                   NaN NaN              NaN NaN NaN                            NaN NaN NaN NaN NaN NaN NaN NaN
NaN NaN NaN NaN NaN                                   NaN NaN    Municipality: NaN NaN            DC27 - uMkhanyakude NaN NaN NaN NaN NaN NaN NaN

In [37]:
print("All files in data/raw:")
for file in RAW_DIR.iterdir():
    print(file.name)

All files in data/raw:
.gitkeep
IEC_2016_Municipal_Results.csv
IEC_2021_Municipal_Results.xls
iec_kzn_ethekwini_ward_registration_2026.csv
StatsSA_Ward_Product_2022.xlsx

In [40]:
for i, row in iec_2021.iterrows():
    values = [str(value) for value in row.tolist()]

    if any("Ward" in value for value in values):
        print("Possible Ward header at row:", i)
        print(values)

In [41]:
for i, row in iec_2021.iterrows():
    values = [str(value) for value in row.tolist()]

    if any(
        keyword in value
        for value in values
        for keyword in ["Voting", "Party", "Registered"]
    ):
        print("Possible header at row:", i)
        print(values)

Possible header at row: 14
['nan', 'Party Name', 'nan', 'nan', 'Abbr', 'nan', 'KZN271 - uMhlabuyalingana', 'nan', 'nan', 'nan', 'nan', 'KZN272 - Jozini', 'nan', 'KZN275 - Mtubatuba', 'nan', 'nan', 'KZN276 - Big Five Hlabisa', 'nan']

In [42]:
print(iec_2021.iloc[12:26].to_string(index=True, header=False))

12 NaN                                 NaN NaN NaN     NaN  NaN                        NaN  NaN                   NaN NaN  NaN                  NaN                   NaN                  NaN                   NaN NaN                        NaN                   NaN
13 NaN                                 NaN NaN NaN     NaN  NaN                        NaN  NaN                   NaN NaN  NaN                  NaN                   NaN                  NaN                   NaN NaN                        NaN                   NaN
14 NaN                          Party Name NaN NaN    Abbr  NaN  KZN271 - uMhlabuyalingana  NaN                   NaN NaN  NaN      KZN272 - Jozini                   NaN   KZN275 - Mtubatuba                   NaN NaN  KZN276 - Big Five Hlabisa                   NaN
15 NaN                                 NaN NaN NaN     NaN  NaN        Total \nValid Votes  NaN  % Total\nValid Votes NaN  NaN  Total \nValid Votes  % Total\nValid Votes  Total \nValid Votes  % Total\nValid Votes NaN        Total \nValid Votes  % Total\nValid Votes
16 NaN  ABAHLALI BASE MKHANYAKUDE MOVEMENT NaN NaN    ABMM  NaN                       1098  NaN              0.022932 NaN  NaN                   37              0.000613                   38               0.00067 NaN                         24              0.000768
17 NaN               ABANTU BATHO CONGRESS NaN NaN     ABC  NaN                        607  NaN              0.012678 NaN  NaN                  121              0.002004                  201              0.003543 NaN                         43              0.001376
18 NaN             ACADEMIC CONGRESS UNION NaN NaN     ACU  NaN                         28  NaN              0.000585 NaN  NaN                  929              0.015383                   85              0.001498 NaN                         11              0.000352
19 NaN  AFRICAN CHRISTIAN DEMOCRATIC PARTY NaN NaN    ACDP  NaN                        651  NaN              0.013596 NaN  NaN                   49              0.000811                 1198              0.021118 NaN                         37              0.001184
20 NaN        AFRICAN INDEPENDENT CONGRESS NaN NaN     AIC  NaN                        479  NaN              0.010004 NaN  NaN                  453              0.007501                  613              0.010806 NaN                        186              0.005953
21 NaN           AFRICAN NATIONAL CONGRESS NaN NaN     ANC  NaN                      22823  NaN              0.476671 NaN  NaN                21765              0.360395                20862              0.367742 NaN                      10444               0.33424
22 NaN           AFRICAN PEOPLE'S MOVEMENT NaN NaN   APEMO  NaN                         49  NaN              0.001023 NaN  NaN                  123              0.002037                  308              0.005429 NaN                         10               0.00032
23 NaN     AFRICAN TRANSFORMATION MOVEMENT NaN NaN     ATM  NaN                         65  NaN              0.001358 NaN  NaN                  206              0.003411                  125              0.002203 NaN                         25                0.0008
24 NaN                          AL JAMA-AH NaN NaN  ALJAMA  NaN                          8  NaN              0.000167 NaN  NaN                   11              0.000182                  115              0.002027 NaN                          3              0.000096
25 NaN                 DEMOCRATIC ALLIANCE NaN NaN      DA  NaN                        894  NaN              0.018672 NaN  NaN                  347              0.005746                 1074              0.018932 NaN                        347              0.011105

In [43]:
iec_2021_path = RAW_DIR / "IEC_2021_Municipal_Results.xlsx"

iec_2021 = pd.read_excel(iec_2021_path)

print("IEC 2021 loaded successfully!")
print("Rows:", len(iec_2021))
print("Columns:", len(iec_2021.columns))
print(iec_2021.columns.tolist())

IEC 2021 loaded successfully!
Rows: 72
Columns: 4
['November 2025', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']

In [44]:
excel_file = pd.ExcelFile(iec_2021_path)

print("Sheets:")
print(excel_file.sheet_names)

Sheets:
['Table 1', 'Table 2']

In [45]:
# Check the contents and dimensions of both sheets

for sheet in ["Table 1", "Table 2"]:
    df = pd.read_excel(iec_2021_path, sheet_name=sheet, header=None)

    print("\n" + "="*60)
    print(f"SHEET: {sheet}")
    print("="*60)
    print("Rows:", df.shape[0])
    print("Columns:", df.shape[1])
    print("\nFirst 15 rows:")
    display(df.head(15))

============================================================
SHEET: Table 1
============================================================
Rows: 73
Columns: 4

First 15 rows:

                                                    0    1    2    3
0                                       November 2025  NaN  NaN  NaN
1    Ward Level Small Area Population Estimates, 2022  NaN  NaN  NaN
2                                      Technical Note  NaN  NaN  NaN
3                                                 NaN  NaN  NaN  NaN
4                                                 NaN  NaN  NaN  NaN
5                                                 NaN  NaN  NaN  NaN
6                                            Contents  NaN  NaN  NaN
7   1. Introduction                               ...  NaN  NaN  NaN
8   1.1 Purpose of technical note                 ...  NaN  NaN  NaN
9   2. Ward product development processes         ...  NaN  NaN  NaN
10  2.1. Assessment of data below local municipali...  NaN  NaN  NaN
11  2.1.2 Ward layer data assessment              ...  NaN  NaN  NaN
12  2.1.3 Alignment of Census 2022 data to 2020 wa...  NaN  NaN  NaN
13  2.1.4 Ward layer indicator assessment         ...  NaN  NaN  NaN
14  2.2 Small area estimation methodology at ward ...  NaN  NaN  NaN

============================================================
SHEET: Table 2
============================================================
Rows: 35
Columns: 5

First 15 rows:

,0,1,2,3,4
0,The right-hand side portion of Figure 2 ...,NaN,NaN,NaN,NaN
1,Table 2: Overestimation of population size fro...,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN
3,Provinces,No. of\nwards,“Extra” persons added\nby first raking pass,Census\n2022,"Margin of error,\n%"
4,KwaZulu-Natal,40,67 970,12 423 907,"0,55"
5,Eastern Cape,25,54 781,7 230 204,"0,76"
6,Free State,20,44 419,2 964 412,"1,50"
7,Northern Cape,19,15 299,1 355 945,"1,13"
8,Mpumalanga,17,48 528,5 143 324,"0,94"
9,Limpopo,16,47 398,6 572 721,"0,72"
10,North West,15,57 208,3 804 547,"1,50"
11,Western Cape,8,48 990,7 433 020,"0,66"
12,Gauteng,7,43 084,15 099 423,"0,29"
13,TOTAL,167,427 677,62 027 503,"0,69"
14,The prevalence of this margin of error is also...,NaN,NaN,NaN,NaN

In [46]:
table1 = pd.read_excel(
    iec_2021_path,
    sheet_name="Table 1",
    header=None
)

print(table1.to_string())

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              0             1                   2                   3
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 November 2025           NaN                 NaN                 NaN
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Ward Level Small Area Population Estimates, 2022           NaN                 NaN                 NaN
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Technical Note           NaN                 NaN                 NaN
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           NaN           NaN                 NaN                 NaN
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           NaN           NaN                 NaN                 NaN
5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           NaN           NaN                 NaN                 NaN
6                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Contents           NaN                 NaN                 NaN
7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1. Introduction                                                                                                                         1           NaN                 NaN                 NaN
8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              1.1 Purpose of technical note                                                                                                  1           NaN                 NaN                 NaN
9                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            2. Ward product development processes                                                                            1           NaN                 NaN                 NaN
10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         2.1. Assessment of data below local municipality                                                                   1           NaN                 NaN                 NaN
11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         2.1.2 Ward layer data assessment                                                                                   1           NaN                 NaN                 NaN
12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    2.1.3 Alignment of Census 2022 data to 2020 wards                                                       1           NaN                 NaN                 NaN
13                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           2.1.4 Ward layer indicator assessment                                                                            2           NaN                 NaN                 NaN
14                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            2.2 Small area estimation methodology at ward level                                                             2           NaN                 NaN                 NaN
15                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      3. Main findings                                                                                                                      4           NaN                 NaN                 NaN

In [47]:
table2 = pd.read_excel(
    iec_2021_path,
    sheet_name="Table 2",
    header=None
)

print("\nRows:", table2.shape[0])
print("Columns:", table2.shape[1])
print(table2.to_string())

Rows: 35
Columns: 5
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                0              1                                            2             3                    4
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          The  right-hand  side  portion  of  Figure  2  above,  also  demonstrates that  no  convergence  is achieved by the first raking pass in the remaining 167 wards where the small area estimates of population size are higher from ward to ward compared to the corresponding Census 2022 figures. Here the SAEs in these wards overstate the population size found in Census 2022. This  extends  to  municipal  level,  and  further  to  provincial  and  national  levels  compared  to Census 2022. For reasons of compression, the overestimates are summed up by province, showing an overall margin of error of 0,69% nationally, ranging from a low of 0,29% to a high of 1,50% between the provinces. Table 2 below, gives a summary of the incidence of this error margin,  computed as the  percentage ratio between  the “extra”  persons added  by the first raking pass and the number of persons found in Census 2022.            NaN                                          NaN           NaN                  NaN
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Table 2: Overestimation of population size from first raking pass, by province            NaN                                          NaN           NaN                  NaN
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             NaN            NaN                                          NaN           NaN                  NaN
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Provinces  No. of\nwards  “Extra” persons added\nby first raking pass  Census\n2022  Margin of error,\n%
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   KwaZulu-Natal             40                                       67 970    12 423 907                 0,55
5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Eastern Cape             25                                       54 781     7 230 204                 0,76
6                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Free State             20                                       44 419     2 964 412                 1,50
7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Northern Cape             19                                       15 299     1 355 945                 1,13
8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Mpumalanga             17                                       48 528     5 143 324                 0,94
9                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Limpopo             16                                       47 398     6 572 721                 0,72
10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     North West             15                                       57 208     3 804 547                 1,50
11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Western Cape              8                                       48 990     7 433 020                 0,66

In [49]:
table1 = pd.read_excel(
    iec_2021_path,
    sheet_name="Table 1",
    header=None
)

display(table1)

                                                    0      1    2    3
0                                       November 2025    NaN  NaN  NaN
1    Ward Level Small Area Population Estimates, 2022    NaN  NaN  NaN
2                                      Technical Note    NaN  NaN  NaN
3                                                 NaN    NaN  NaN  NaN
4                                                 NaN    NaN  NaN  NaN
..                                                ...    ...  ...  ...
68                                              TOTAL  4 181  NaN  NaN
69  Note: “-” no correlation computed, as only one...    NaN  NaN  NaN
70  Of the 4 181 wards with resolved censal collec...    NaN  NaN  NaN
71  Turning to the 287 wards with unresolved censa...    NaN  NaN  NaN
72  Figure 2 below illustrates the distinctive cha...    NaN  NaN  NaN

[73 rows x 4 columns]

In [50]:
table2 = pd.read_excel(
    iec_2021_path,
    sheet_name="Table 2",
    header=None
)

display(table2)

,0,1,2,3,4
0,The right-hand side portion of Figure 2 ...,NaN,NaN,NaN,NaN
1,Table 2: Overestimation of population size fro...,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN
3,Provinces,No. of\nwards,“Extra” persons added\nby first raking pass,Census\n2022,"Margin of error,\n%"
4,KwaZulu-Natal,40,67 970,12 423 907,"0,55"
5,Eastern Cape,25,54 781,7 230 204,"0,76"
6,Free State,20,44 419,2 964 412,"1,50"
7,Northern Cape,19,15 299,1 355 945,"1,13"
8,Mpumalanga,17,48 528,5 143 324,"0,94"
9,Limpopo,16,47 398,6 572 721,"0,72"
10,North West,15,57 208,3 804 547,"1,50"
11,Western Cape,8,48 990,7 433 020,"0,66"
12,Gauteng,7,43 084,15 099 423,"0,29"
13,TOTAL,167,427 677,62 027 503,"0,69"
14,The prevalence of this margin of error is also...,NaN,NaN,NaN,NaN
15,"As shown in Figure 3 below, after the second r...",NaN,NaN,NaN,NaN
16,Figure 3 also shows how the remaining 119 ward...,NaN,NaN,NaN,NaN
17,"Essentially, the result of the second raking p...",NaN,NaN,NaN,NaN
18,The final step of raking is to collate ...,NaN,NaN,NaN,NaN
19,4. Conclusion\nThis technical note outlines th...,NaN,NaN,NaN,NaN
20,Population group defining the population ...,NaN,NaN,NaN,NaN
21,It is important to note that for purpos...,NaN,NaN,NaN,NaN
22,The precision of the SAEs in the current case ...,NaN,NaN,NaN,NaN
23,5. How to access the ward data,NaN,NaN,NaN,NaN
24,The data may be accessed from the Stats...,NaN,NaN,NaN,NaN
25,"References\nABS, 2009. Population estimates...",NaN,NaN,NaN,NaN
26,"ADB, 2020. Introduction to small area estimati...",NaN,NaN,NaN,NaN
27,"Chen, H., 2022. Small area estimation for SDGs...",NaN,NaN,NaN,NaN
28,"Cole, T.J. and Altman, D.G., 2017. What is a p...",NaN,NaN,NaN,NaN
29,"Deming, W.E. and Stephan, F.F., 1940. On...",NaN,NaN,NaN,NaN
30,"Gomatam, S., Karr, A.F. and Sanil, A.P., 2005....",NaN,NaN,NaN,NaN
31,"Izrael, D., Hoaglin, D.C. and Battaglia, M.P.,...",NaN,NaN,NaN,NaN
32,"Lomax, N. and Norman, P., 2016. Estimating pop...",NaN,NaN,NaN,NaN
33,"Purcell, N.J. and Kish, L., 198...",NaN,NaN,NaN,NaN
34,"Wheeler, J.O., 2005. Geography, in Kempf-...",NaN,NaN,NaN,NaN

In [51]:
table1 = pd.read_excel(
    iec_2021_path,
    sheet_name="Table 1",
    header=None
)

print("TABLE 1")
print("Shape:", table1.shape)
print(table1.to_string(index=True, header=False))

TABLE 1
Shape: (73, 4)
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 November 2025           NaN                 NaN                 NaN
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Ward Level Small Area Population Estimates, 2022           NaN                 NaN                 NaN
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Technical Note           NaN                 NaN                 NaN
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           NaN           NaN                 NaN                 NaN
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           NaN           NaN                 NaN                 NaN
5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           NaN           NaN                 NaN                 NaN
6                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Contents           NaN                 NaN                 NaN
7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1. Introduction                                                                                                                         1           NaN                 NaN                 NaN
8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              1.1 Purpose of technical note                                                                                                  1           NaN                 NaN                 NaN
9                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            2. Ward product development processes                                                                            1           NaN                 NaN                 NaN
10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         2.1. Assessment of data below local municipality                                                                   1           NaN                 NaN                 NaN
11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         2.1.2 Ward layer data assessment                                                                                   1           NaN                 NaN                 NaN
12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    2.1.3 Alignment of Census 2022 data to 2020 wards                                                       1           NaN                 NaN                 NaN
13                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           2.1.4 Ward layer indicator assessment                                                                            2           NaN                 NaN                 NaN
14                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            2.2 Small area estimation methodology at ward level                                                             2           NaN                 NaN                 NaN
15                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      3. Main findings                                                                                                                      4           NaN                 NaN                 NaN
16                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     4. Conclusion                                                                                                                          8           NaN                 NaN                 NaN

In [52]:
table2 = pd.read_excel(
    iec_2021_path,
    sheet_name="Table 2",
    header=None
)

print("\nTABLE 2")
print("Shape:", table2.shape)
print(table2.to_string(index=True, header=False))

TABLE 2
Shape: (35, 5)
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          The  right-hand  side  portion  of  Figure  2  above,  also  demonstrates that  no  convergence  is achieved by the first raking pass in the remaining 167 wards where the small area estimates of population size are higher from ward to ward compared to the corresponding Census 2022 figures. Here the SAEs in these wards overstate the population size found in Census 2022. This  extends  to  municipal  level,  and  further  to  provincial  and  national  levels  compared  to Census 2022. For reasons of compression, the overestimates are summed up by province, showing an overall margin of error of 0,69% nationally, ranging from a low of 0,29% to a high of 1,50% between the provinces. Table 2 below, gives a summary of the incidence of this error margin,  computed as the  percentage ratio between  the “extra”  persons added  by the first raking pass and the number of persons found in Census 2022.            NaN                                          NaN           NaN                  NaN
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Table 2: Overestimation of population size from first raking pass, by province            NaN                                          NaN           NaN                  NaN
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             NaN            NaN                                          NaN           NaN                  NaN
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Provinces  No. of\nwards  “Extra” persons added\nby first raking pass  Census\n2022  Margin of error,\n%
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   KwaZulu-Natal             40                                       67 970    12 423 907                 0,55
5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Eastern Cape             25                                       54 781     7 230 204                 0,76
6                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Free State             20                                       44 419     2 964 412                 1,50
7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Northern Cape             19                                       15 299     1 355 945                 1,13
8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Mpumalanga             17                                       48 528     5 143 324                 0,94
9                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Limpopo             16                                       47 398     6 572 721                 0,72
10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     North West             15                                       57 208     3 804 547                 1,50
11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Western Cape              8                                       48 990     7 433 020                 0,66
12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Gauteng              7                                       43 084    15 099 423                 0,29

In [53]:
print("IEC path:", iec_2021_path)

excel_file = pd.ExcelFile(iec_2021_path)

print("\nSheets found:")
print(excel_file.sheet_names)

for sheet in excel_file.sheet_names:
    print("\n" + "=" * 50)
    print("SHEET:", sheet)
    print("=" * 50)

    df = pd.read_excel(
        iec_2021_path,
        sheet_name=sheet,
        header=None
    )

    print("Shape:", df.shape)
    print("First 10 rows:")

    for row in df.iloc[:10].values:
        print(row)

IEC path: C:\Users\Admin\PycharmProjects\SPU-TEAM-DIRISA\data\raw\IEC_2021_Municipal_Results.xlsx

Sheets found:
['Table 1', 'Table 2']

==================================================
SHEET: Table 1
==================================================
Shape: (73, 4)
First 10 rows:
['November 2025' nan nan nan]
['Ward Level Small Area Population Estimates, 2022' nan nan nan]
['Technical Note' nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
[nan nan nan nan]
['Contents' nan nan nan]
['1. Introduction                                                                                                                         1'
 nan nan nan]
['1.1 Purpose of technical note                                                                                                  1'
 nan nan nan]
['2. Ward product development processes                                                                            1'
 nan nan nan]

==================================================
SHEET: Table 2
==================================================
Shape: (35, 5)
First 10 rows:
['The  right-hand  side  portion  of  Figure  2  above,  also  demonstrates that  no  convergence  is achieved by the first raking pass in the remaining 167 wards where the small area estimates of population size are higher from ward to ward compared to the corresponding Census 2022 figures. Here the SAEs in these wards overstate the population size found in Census 2022. This  extends  to  municipal  level,  and  further  to  provincial  and  national  levels  compared  to Census 2022. For reasons of compression, the overestimates are summed up by province, showing an overall margin of error of 0,69% nationally, ranging from a low of 0,29% to a high of 1,50% between the provinces. Table 2 below, gives a summary of the incidence of this error margin,  computed as the  percentage ratio between  the “extra”  persons added  by the first raking pass and the number of persons found in Census 2022.'
 nan nan nan nan]
['Table 2: Overestimation of population size from first raking pass, by province'
 nan nan nan nan]
[nan nan nan nan nan]
['Provinces' 'No. of\nwards' '“Extra” persons added\nby first raking pass'
 'Census\n2022' 'Margin of error,\n%']
['KwaZulu-Natal' 40 '67 970' '12 423 907' '0,55']
['Eastern Cape' 25 '54 781' '7 230 204' '0,76']
['Free State' 20 '44 419' '2 964 412' '1,50']
['Northern Cape' 19 '15 299' '1 355 945' '1,13']
['Mpumalanga' 17 '48 528' '5 143 324' '0,94']
['Limpopo' 16 '47 398' '6 572 721' '0,72']

In [54]:
print("IEC path:", iec_2021_path)

excel_file = pd.ExcelFile(iec_2021_path)

print("\nSheets found:")
print(excel_file.sheet_names)

for sheet in excel_file.sheet_names:
    print("\n" + "=" * 60)
    print("SHEET:", sheet)
    print("=" * 60)

    df = pd.read_excel(
        iec_2021_path,
        sheet_name=sheet,
        header=None
    )

    print("Shape:", df.shape)
    print(df.head(15).to_string(index=False, header=False))

IEC path: C:\Users\Admin\PycharmProjects\SPU-TEAM-DIRISA\data\raw\IEC_2021_Municipal_Results.xlsx

Sheets found:
['Table 1', 'Table 2']

============================================================
SHEET: Table 1
============================================================
Shape: (73, 4)
                                                                                                                            November 2025 NaN NaN NaN
                                                                                         Ward Level Small Area Population Estimates, 2022 NaN NaN NaN
                                                                                                                           Technical Note NaN NaN NaN
                                                                                                                                      NaN NaN NaN NaN
                                                                                                                                      NaN NaN NaN NaN
                                                                                                                                      NaN NaN NaN NaN
                                                                                                                                 Contents NaN NaN NaN
1. Introduction                                                                                                                         1 NaN NaN NaN
         1.1 Purpose of technical note                                                                                                  1 NaN NaN NaN
                       2. Ward product development processes                                                                            1 NaN NaN NaN
                     2.1. Assessment of data below local municipality                                                                   1 NaN NaN NaN
                     2.1.2 Ward layer data assessment                                                                                   1 NaN NaN NaN
                                2.1.3 Alignment of Census 2022 data to 2020 wards                                                       1 NaN NaN NaN
                       2.1.4 Ward layer indicator assessment                                                                            2 NaN NaN NaN
                        2.2 Small area estimation methodology at ward level                                                             2 NaN NaN NaN

============================================================
SHEET: Table 2
============================================================
Shape: (35, 5)
                          The  right-hand  side  portion  of  Figure  2  above,  also  demonstrates that  no  convergence  is achieved by the first raking pass in the remaining 167 wards where the small area estimates of population size are higher from ward to ward compared to the corresponding Census 2022 figures. Here the SAEs in these wards overstate the population size found in Census 2022. This  extends  to  municipal  level,  and  further  to  provincial  and  national  levels  compared  to Census 2022. For reasons of compression, the overestimates are summed up by province, showing an overall margin of error of 0,69% nationally, ranging from a low of 0,29% to a high of 1,50% between the provinces. Table 2 below, gives a summary of the incidence of this error margin,  computed as the  percentage ratio between  the “extra”  persons added  by the first raking pass and the number of persons found in Census 2022.           NaN                                         NaN          NaN                 NaN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Table 2: Overestimation of population size from first raking pass, by province           NaN                                         NaN          NaN                 NaN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             NaN           NaN                                         NaN          NaN                 NaN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Provinces No. of\nwards “Extra” persons added\nby first raking pass Census\n2022 Margin of error,\n%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   KwaZulu-Natal            40                                      67 970   12 423 907                0,55
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Eastern Cape            25                                      54 781    7 230 204                0,76
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Free State            20                                      44 419    2 964 412                1,50
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Northern Cape            19                                      15 299    1 355 945                1,13
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Mpumalanga            17                                      48 528    5 143 324                0,94
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Limpopo            16                                      47 398    6 572 721                0,72
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      North West            15                                      57 208    3 804 547                1,50
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Western Cape             8                                      48 990    7 433 020                0,66
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Gauteng             7                                      43 084   15 099 423                0,29
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           TOTAL           167                                     427 677   62 027 503                0,69
The prevalence of this margin of error is also easy to check, by noting that the incidence of overestimation affects proportionately a higher number of wards (167) compared to that of underestimation (120 wards). To reduce this overestimation of population size introduced by the first raking pass a second raking pass is done, which is isolated to the subset of 167 wards to which it belongs. As per the iterative nature of raking, this second raking pass prorates the small area estimates of population size based on Age group, Sex, and Population group from the first pass of the subset, using its corresponding control totals from Census 2022. This is done while ensuring that the Census 2022 totals for population size remain intact for all 213 municipalities, all 9 provinces, and nationally.  Figure 3 below gives a replot of the symmetric percentage differences – this time – for the results from the second raking pass.           NaN                                         NaN          NaN                 NaN

In [55]:
print("Variables currently in memory:")
print([x for x in dir() if not x.startswith("_")])

Variables currently in memory:
['BASE_DIR', 'In', 'OUTPUT_DIR', 'Out', 'PROCESSED_DIR', 'Path', 'RAW_DIR', 'df', 'excel_file', 'exit', 'file', 'get_ipython', 'i', 'iec_2016', 'iec_2016_path', 'iec_2021', 'iec_2021_path', 'kzn_2016', 'np', 'open', 'pd', 'plt', 'quit', 'row', 'sheet', 'table1', 'table2', 'values']

In [57]:
print("\nExcel/CSV files currently available:")

import os

for root, dirs, files in os.walk(".", topdown=True):
    for file in files:
        if file.lower().endswith((".xlsx", ".xls", ".csv")):
            print(os.path.join(root, file))

Excel/CSV files currently available:

In [58]:
print("BASE_DIR:", BASE_DIR)
print("RAW_DIR:", RAW_DIR)
print("PROCESSED_DIR:", PROCESSED_DIR)

print("\n--- RAW DATA ---")
if os.path.exists(RAW_DIR):
    for root, dirs, files in os.walk(RAW_DIR):
        for f in files:
            print(os.path.join(root, f))
else:
    print("RAW_DIR does not exist")

print("\n--- PROCESSED DATA ---")
if os.path.exists(PROCESSED_DIR):
    for root, dirs, files in os.walk(PROCESSED_DIR):
        for f in files:
            print(os.path.join(root, f))
else:
    print("PROCESSED_DIR does not exist")

BASE_DIR: C:\Users\Admin\PycharmProjects\SPU-TEAM-DIRISA
RAW_DIR: C:\Users\Admin\PycharmProjects\SPU-TEAM-DIRISA\data\raw
PROCESSED_DIR: C:\Users\Admin\PycharmProjects\SPU-TEAM-DIRISA\data\processed

--- RAW DATA ---
C:\Users\Admin\PycharmProjects\SPU-TEAM-DIRISA\data\raw\.gitkeep
C:\Users\Admin\PycharmProjects\SPU-TEAM-DIRISA\data\raw\IEC_2016_Municipal_Results.csv
C:\Users\Admin\PycharmProjects\SPU-TEAM-DIRISA\data\raw\IEC_2021_Municipal_Results.xls
C:\Users\Admin\PycharmProjects\SPU-TEAM-DIRISA\data\raw\IEC_2021_Municipal_Results.xlsx
C:\Users\Admin\PycharmProjects\SPU-TEAM-DIRISA\data\raw\iec_kzn_ethekwini_ward_registration_2026.csv
C:\Users\Admin\PycharmProjects\SPU-TEAM-DIRISA\data\raw\StatsSA_Ward_Product_2022.xlsx

--- PROCESSED DATA ---
C:\Users\Admin\PycharmProjects\SPU-TEAM-DIRISA\data\processed\.gitkeep

In [59]:
iec_2021_actual_path = os.path.join(
    RAW_DIR,
    "IEC_2021_Municipal_Results.xlsx"
)

print("File:", iec_2021_actual_path)

xls = pd.ExcelFile(iec_2021_actual_path)

print("\nSheets:")
print(xls.sheet_names)

File: C:\Users\Admin\PycharmProjects\SPU-TEAM-DIRISA\data\raw\IEC_2021_Municipal_Results.xlsx

Sheets:
['Table 1', 'Table 2']

In [60]:
for sheet in xls.sheet_names:
    temp = pd.read_excel(
        iec_2021_actual_path,
        sheet_name=sheet,
        header=None
    )

    print("\n" + "=" * 70)
    print("SHEET:", sheet)
    print("SHAPE:", temp.shape)
    print("=" * 70)

    print(temp.head(10).to_string(index=False, header=False))

======================================================================
SHEET: Table 1
SHAPE: (73, 4)
======================================================================
                                                                                                                            November 2025 NaN NaN NaN
                                                                                         Ward Level Small Area Population Estimates, 2022 NaN NaN NaN
                                                                                                                           Technical Note NaN NaN NaN
                                                                                                                                      NaN NaN NaN NaN
                                                                                                                                      NaN NaN NaN NaN
                                                                                                                                      NaN NaN NaN NaN
                                                                                                                                 Contents NaN NaN NaN
1. Introduction                                                                                                                         1 NaN NaN NaN
         1.1 Purpose of technical note                                                                                                  1 NaN NaN NaN
                       2. Ward product development processes                                                                            1 NaN NaN NaN

======================================================================
SHEET: Table 2
SHAPE: (35, 5)
======================================================================
The  right-hand  side  portion  of  Figure  2  above,  also  demonstrates that  no  convergence  is achieved by the first raking pass in the remaining 167 wards where the small area estimates of population size are higher from ward to ward compared to the corresponding Census 2022 figures. Here the SAEs in these wards overstate the population size found in Census 2022. This  extends  to  municipal  level,  and  further  to  provincial  and  national  levels  compared  to Census 2022. For reasons of compression, the overestimates are summed up by province, showing an overall margin of error of 0,69% nationally, ranging from a low of 0,29% to a high of 1,50% between the provinces. Table 2 below, gives a summary of the incidence of this error margin,  computed as the  percentage ratio between  the “extra”  persons added  by the first raking pass and the number of persons found in Census 2022.           NaN                                         NaN          NaN                 NaN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Table 2: Overestimation of population size from first raking pass, by province           NaN                                         NaN          NaN                 NaN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   NaN           NaN                                         NaN          NaN                 NaN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Provinces No. of\nwards “Extra” persons added\nby first raking pass Census\n2022 Margin of error,\n%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         KwaZulu-Natal            40                                      67 970   12 423 907                0,55
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Eastern Cape            25                                      54 781    7 230 204                0,76
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Free State            20                                      44 419    2 964 412                1,50
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Northern Cape            19                                      15 299    1 355 945                1,13
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Mpumalanga            17                                      48 528    5 143 324                0,94
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Limpopo            16                                      47 398    6 572 721                0,72

In [61]:
iec_2021_actual_path = os.path.join(
    RAW_DIR,
    "IEC_2021_Municipal_Results.xlsx"
)

iec_2021 = pd.read_excel(
    iec_2021_actual_path,
    sheet_name=0,
    header=None
)

print("Shape:", iec_2021.shape)
print(iec_2021.head(15).to_string(index=False, header=False))

Shape: (73, 4)
                                                                                                                            November 2025 NaN NaN NaN
                                                                                         Ward Level Small Area Population Estimates, 2022 NaN NaN NaN
                                                                                                                           Technical Note NaN NaN NaN
                                                                                                                                      NaN NaN NaN NaN
                                                                                                                                      NaN NaN NaN NaN
                                                                                                                                      NaN NaN NaN NaN
                                                                                                                                 Contents NaN NaN NaN
1. Introduction                                                                                                                         1 NaN NaN NaN
         1.1 Purpose of technical note                                                                                                  1 NaN NaN NaN
                       2. Ward product development processes                                                                            1 NaN NaN NaN
                     2.1. Assessment of data below local municipality                                                                   1 NaN NaN NaN
                     2.1.2 Ward layer data assessment                                                                                   1 NaN NaN NaN
                                2.1.3 Alignment of Census 2022 data to 2020 wards                                                       1 NaN NaN NaN
                       2.1.4 Ward layer indicator assessment                                                                            2 NaN NaN NaN
                        2.2 Small area estimation methodology at ward level                                                             2 NaN NaN NaN

In [62]:
iec_2016_actual_path = os.path.join(
    RAW_DIR,
    "IEC_2016_Municipal_Results.csv"
)

iec_2016 = pd.read_csv(
    iec_2016_actual_path,
    header=None
)

print("Shape:", iec_2016.shape)
print(iec_2016.head(15).to_string(index=False, header=False))

Shape: (40707, 11)
     Province    Municipality          Ward VotingDistrict         VotingStationName RegisteredVoters BallotType SpoiltVotes                          PartyName TotalValidVotes        DateGenerated
KwaZulu-Natal ETH - eThekwini Ward 59500001       43400179 NOMFIHLELA PRIMARY SCHOOL             1607         PR          72            ACADEMIC CONGRESS UNION               0 8/11/2016 3:58:48 PM
KwaZulu-Natal ETH - eThekwini Ward 59500001       43400179 NOMFIHLELA PRIMARY SCHOOL             1607         PR          72 AFRICAN CHRISTIAN DEMOCRATIC PARTY               0 8/11/2016 3:58:48 PM
KwaZulu-Natal ETH - eThekwini Ward 59500001       43400179 NOMFIHLELA PRIMARY SCHOOL             1607         PR          72       AFRICAN INDEPENDENT CONGRESS              19 8/11/2016 3:58:48 PM
KwaZulu-Natal ETH - eThekwini Ward 59500001       43400179 NOMFIHLELA PRIMARY SCHOOL             1607         PR          72        AFRICAN MANTUNGWA COMMUNITY               0 8/11/2016 3:58:48 PM
KwaZulu-Natal ETH - eThekwini Ward 59500001       43400179 NOMFIHLELA PRIMARY SCHOOL             1607         PR          72          AFRICAN NATIONAL CONGRESS            1157 8/11/2016 3:58:48 PM
KwaZulu-Natal ETH - eThekwini Ward 59500001       43400179 NOMFIHLELA PRIMARY SCHOOL             1607         PR          72        AFRICAN PEOPLE'S CONVENTION               3 8/11/2016 3:58:48 PM
KwaZulu-Natal ETH - eThekwini Ward 59500001       43400179 NOMFIHLELA PRIMARY SCHOOL             1607         PR          72                         AL JAMA-AH               0 8/11/2016 3:58:48 PM
KwaZulu-Natal ETH - eThekwini Ward 59500001       43400179 NOMFIHLELA PRIMARY SCHOOL             1607         PR          72         ALLIED MOVEMENT FOR CHANGE               0 8/11/2016 3:58:48 PM
KwaZulu-Natal ETH - eThekwini Ward 59500001       43400179 NOMFIHLELA PRIMARY SCHOOL             1607         PR          72      AZANIAN PEOPLE'S ORGANISATION               0 8/11/2016 3:58:48 PM
KwaZulu-Natal ETH - eThekwini Ward 59500001       43400179 NOMFIHLELA PRIMARY SCHOOL             1607         PR          72            CONGRESS  OF THE PEOPLE               0 8/11/2016 3:58:48 PM
KwaZulu-Natal ETH - eThekwini Ward 59500001       43400179 NOMFIHLELA PRIMARY SCHOOL             1607         PR          72                DEMOCRATIC ALLIANCE               3 8/11/2016 3:58:48 PM
KwaZulu-Natal ETH - eThekwini Ward 59500001       43400179 NOMFIHLELA PRIMARY SCHOOL             1607         PR          72        DEMOCRATIC LIBERAL CONGRESS               0 8/11/2016 3:58:48 PM
KwaZulu-Natal ETH - eThekwini Ward 59500001       43400179 NOMFIHLELA PRIMARY SCHOOL             1607         PR          72          ECONOMIC FREEDOM FIGHTERS               9 8/11/2016 3:58:48 PM
KwaZulu-Natal ETH - eThekwini Ward 59500001       43400179 NOMFIHLELA PRIMARY SCHOOL             1607         PR          72         INDEPENDENT PEOPLE'S PARTY               1 8/11/2016 3:58:48 PM

In [63]:
import pandas as pd
import os

iec_2021_actual_path = os.path.join(
    RAW_DIR,
    "IEC_2021_Municipal_Results.xlsx"
)

xls = pd.ExcelFile(iec_2021_actual_path)

print("Available sheets:")
print(xls.sheet_names)

for sheet in xls.sheet_names:
    temp = pd.read_excel(
        iec_2021_actual_path,
        sheet_name=sheet,
        header=None
    )

    print("\n" + "=" * 80)
    print("SHEET:", sheet)
    print("ROWS:", temp.shape[0], "| COLUMNS:", temp.shape[1])
    print("=" * 80)

    print(temp.head(12).to_string(index=False, header=False))

Available sheets:
['Table 1', 'Table 2']

================================================================================
SHEET: Table 1
ROWS: 73 | COLUMNS: 4
================================================================================
                                                                                                                            November 2025 NaN NaN NaN
                                                                                         Ward Level Small Area Population Estimates, 2022 NaN NaN NaN
                                                                                                                           Technical Note NaN NaN NaN
                                                                                                                                      NaN NaN NaN NaN
                                                                                                                                      NaN NaN NaN NaN
                                                                                                                                      NaN NaN NaN NaN
                                                                                                                                 Contents NaN NaN NaN
1. Introduction                                                                                                                         1 NaN NaN NaN
         1.1 Purpose of technical note                                                                                                  1 NaN NaN NaN
                       2. Ward product development processes                                                                            1 NaN NaN NaN
                     2.1. Assessment of data below local municipality                                                                   1 NaN NaN NaN
                     2.1.2 Ward layer data assessment                                                                                   1 NaN NaN NaN

================================================================================
SHEET: Table 2
ROWS: 35 | COLUMNS: 5
================================================================================
The  right-hand  side  portion  of  Figure  2  above,  also  demonstrates that  no  convergence  is achieved by the first raking pass in the remaining 167 wards where the small area estimates of population size are higher from ward to ward compared to the corresponding Census 2022 figures. Here the SAEs in these wards overstate the population size found in Census 2022. This  extends  to  municipal  level,  and  further  to  provincial  and  national  levels  compared  to Census 2022. For reasons of compression, the overestimates are summed up by province, showing an overall margin of error of 0,69% nationally, ranging from a low of 0,29% to a high of 1,50% between the provinces. Table 2 below, gives a summary of the incidence of this error margin,  computed as the  percentage ratio between  the “extra”  persons added  by the first raking pass and the number of persons found in Census 2022.           NaN                                         NaN          NaN                 NaN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Table 2: Overestimation of population size from first raking pass, by province           NaN                                         NaN          NaN                 NaN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   NaN           NaN                                         NaN          NaN                 NaN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Provinces No. of\nwards “Extra” persons added\nby first raking pass Census\n2022 Margin of error,\n%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         KwaZulu-Natal            40                                      67 970   12 423 907                0,55
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Eastern Cape            25                                      54 781    7 230 204                0,76
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Free State            20                                      44 419    2 964 412                1,50
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Northern Cape            19                                      15 299    1 355 945                1,13
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Mpumalanga            17                                      48 528    5 143 324                0,94
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Limpopo            16                                      47 398    6 572 721                0,72
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            North West            15                                      57 208    3 804 547                1,50
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Western Cape             8                                      48 990    7 433 020                0,66

In [64]:
iec_2016_actual_path = os.path.join(
    RAW_DIR,
    "IEC_2016_Municipal_Results.csv"
)

iec_2016_raw = pd.read_csv(
    iec_2016_actual_path,
    header=None
)

print("\n" + "=" * 80)
print("2016 IEC DATA")
print("ROWS:", iec_2016_raw.shape[0], "| COLUMNS:", iec_2016_raw.shape[1])
print("=" * 80)

print(iec_2016_raw.head(15).to_string(index=False, header=False))

================================================================================
2016 IEC DATA
ROWS: 40707 | COLUMNS: 11
================================================================================
     Province    Municipality          Ward VotingDistrict         VotingStationName RegisteredVoters BallotType SpoiltVotes                          PartyName TotalValidVotes        DateGenerated
KwaZulu-Natal ETH - eThekwini Ward 59500001       43400179 NOMFIHLELA PRIMARY SCHOOL             1607         PR          72            ACADEMIC CONGRESS UNION               0 8/11/2016 3:58:48 PM
KwaZulu-Natal ETH - eThekwini Ward 59500001       43400179 NOMFIHLELA PRIMARY SCHOOL             1607         PR          72 AFRICAN CHRISTIAN DEMOCRATIC PARTY               0 8/11/2016 3:58:48 PM
KwaZulu-Natal ETH - eThekwini Ward 59500001       43400179 NOMFIHLELA PRIMARY SCHOOL             1607         PR          72       AFRICAN INDEPENDENT CONGRESS              19 8/11/2016 3:58:48 PM
KwaZulu-Natal ETH - eThekwini Ward 59500001       43400179 NOMFIHLELA PRIMARY SCHOOL             1607         PR          72        AFRICAN MANTUNGWA COMMUNITY               0 8/11/2016 3:58:48 PM
KwaZulu-Natal ETH - eThekwini Ward 59500001       43400179 NOMFIHLELA PRIMARY SCHOOL             1607         PR          72          AFRICAN NATIONAL CONGRESS            1157 8/11/2016 3:58:48 PM
KwaZulu-Natal ETH - eThekwini Ward 59500001       43400179 NOMFIHLELA PRIMARY SCHOOL             1607         PR          72        AFRICAN PEOPLE'S CONVENTION               3 8/11/2016 3:58:48 PM
KwaZulu-Natal ETH - eThekwini Ward 59500001       43400179 NOMFIHLELA PRIMARY SCHOOL             1607         PR          72                         AL JAMA-AH               0 8/11/2016 3:58:48 PM
KwaZulu-Natal ETH - eThekwini Ward 59500001       43400179 NOMFIHLELA PRIMARY SCHOOL             1607         PR          72         ALLIED MOVEMENT FOR CHANGE               0 8/11/2016 3:58:48 PM
KwaZulu-Natal ETH - eThekwini Ward 59500001       43400179 NOMFIHLELA PRIMARY SCHOOL             1607         PR          72      AZANIAN PEOPLE'S ORGANISATION               0 8/11/2016 3:58:48 PM
KwaZulu-Natal ETH - eThekwini Ward 59500001       43400179 NOMFIHLELA PRIMARY SCHOOL             1607         PR          72            CONGRESS  OF THE PEOPLE               0 8/11/2016 3:58:48 PM
KwaZulu-Natal ETH - eThekwini Ward 59500001       43400179 NOMFIHLELA PRIMARY SCHOOL             1607         PR          72                DEMOCRATIC ALLIANCE               3 8/11/2016 3:58:48 PM
KwaZulu-Natal ETH - eThekwini Ward 59500001       43400179 NOMFIHLELA PRIMARY SCHOOL             1607         PR          72        DEMOCRATIC LIBERAL CONGRESS               0 8/11/2016 3:58:48 PM
KwaZulu-Natal ETH - eThekwini Ward 59500001       43400179 NOMFIHLELA PRIMARY SCHOOL             1607         PR          72          ECONOMIC FREEDOM FIGHTERS               9 8/11/2016 3:58:48 PM
KwaZulu-Natal ETH - eThekwini Ward 59500001       43400179 NOMFIHLELA PRIMARY SCHOOL             1607         PR          72         INDEPENDENT PEOPLE'S PARTY               1 8/11/2016 3:58:48 PM

In [65]:
print(iec_2021.columns.tolist())

[0, 1, 2, 3]

In [66]:
print(iec_2021.head(10))

                                                   0    1    2    3
0                                      November 2025  NaN  NaN  NaN
1   Ward Level Small Area Population Estimates, 2022  NaN  NaN  NaN
2                                     Technical Note  NaN  NaN  NaN
3                                                NaN  NaN  NaN  NaN
4                                                NaN  NaN  NaN  NaN
5                                                NaN  NaN  NaN  NaN
6                                           Contents  NaN  NaN  NaN
7  1. Introduction                               ...  NaN  NaN  NaN
8  1.1 Purpose of technical note                 ...  NaN  NaN  NaN
9  2. Ward product development processes         ...  NaN  NaN  NaN

In [67]:
print(iec_2016_raw.columns.tolist())
print(iec_2016_raw.head(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
              0                1              2               3   \
0       Province     Municipality           Ward  VotingDistrict
1  KwaZulu-Natal  ETH - eThekwini  Ward 59500001        43400179
2  KwaZulu-Natal  ETH - eThekwini  Ward 59500001        43400179
3  KwaZulu-Natal  ETH - eThekwini  Ward 59500001        43400179
4  KwaZulu-Natal  ETH - eThekwini  Ward 59500001        43400179
5  KwaZulu-Natal  ETH - eThekwini  Ward 59500001        43400179
6  KwaZulu-Natal  ETH - eThekwini  Ward 59500001        43400179
7  KwaZulu-Natal  ETH - eThekwini  Ward 59500001        43400179
8  KwaZulu-Natal  ETH - eThekwini  Ward 59500001        43400179
9  KwaZulu-Natal  ETH - eThekwini  Ward 59500001        43400179

                          4                 5           6            7   \
0          VotingStationName  RegisteredVoters  BallotType  SpoiltVotes
1  NOMFIHLELA PRIMARY SCHOOL              1607          PR           72
2  NOMFIHLELA PRIMARY SCHOOL              1607          PR           72
3  NOMFIHLELA PRIMARY SCHOOL              1607          PR           72
4  NOMFIHLELA PRIMARY SCHOOL              1607          PR           72
5  NOMFIHLELA PRIMARY SCHOOL              1607          PR           72
6  NOMFIHLELA PRIMARY SCHOOL              1607          PR           72
7  NOMFIHLELA PRIMARY SCHOOL              1607          PR           72
8  NOMFIHLELA PRIMARY SCHOOL              1607          PR           72
9  NOMFIHLELA PRIMARY SCHOOL              1607          PR           72

                                   8                9                     10
0                           PartyName  TotalValidVotes         DateGenerated
1             ACADEMIC CONGRESS UNION                0  8/11/2016 3:58:48 PM
2  AFRICAN CHRISTIAN DEMOCRATIC PARTY                0  8/11/2016 3:58:48 PM
3        AFRICAN INDEPENDENT CONGRESS               19  8/11/2016 3:58:48 PM
4         AFRICAN MANTUNGWA COMMUNITY                0  8/11/2016 3:58:48 PM
5           AFRICAN NATIONAL CONGRESS             1157  8/11/2016 3:58:48 PM
6         AFRICAN PEOPLE'S CONVENTION                3  8/11/2016 3:58:48 PM
7                          AL JAMA-AH                0  8/11/2016 3:58:48 PM
8          ALLIED MOVEMENT FOR CHANGE                0  8/11/2016 3:58:48 PM
9       AZANIAN PEOPLE'S ORGANISATION                0  8/11/2016 3:58:48 PM

In [68]:
print("2021 columns:")
for i, col in enumerate(iec_2021.columns):
    print(i, repr(col))

print("\n2016 columns:")
for i, col in enumerate(iec_2016_raw.columns):
    print(i, repr(col))

2021 columns:
0 0
1 1
2 2
3 3

2016 columns:
0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
10 10

In [69]:
print("\n2021 data sample:")
display(iec_2021.head())

print("\n2016 data sample:")
display(iec_2016_raw.head())

2021 data sample:

                                                  0    1    2    3
0                                     November 2025  NaN  NaN  NaN
1  Ward Level Small Area Population Estimates, 2022  NaN  NaN  NaN
2                                    Technical Note  NaN  NaN  NaN
3                                               NaN  NaN  NaN  NaN
4                                               NaN  NaN  NaN  NaN

2016 data sample:

,0,1,2,3,4,5,6,7,8,9,10
0,Province,Municipality,Ward,VotingDistrict,VotingStationName,RegisteredVoters,BallotType,SpoiltVotes,PartyName,TotalValidVotes,DateGenerated
1,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,ACADEMIC CONGRESS UNION,0,8/11/2016 3:58:48 PM
2,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,AFRICAN CHRISTIAN DEMOCRATIC PARTY,0,8/11/2016 3:58:48 PM
3,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,AFRICAN INDEPENDENT CONGRESS,19,8/11/2016 3:58:48 PM
4,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,AFRICAN MANTUNGWA COMMUNITY,0,8/11/2016 3:58:48 PM

In [70]:
print("2021:", iec_2021.shape)
print("2016:", iec_2016_raw.shape)

2021: (73, 4)
2016: (40707, 11)

In [71]:
print("2016:")
print(iec_2016_raw.columns.tolist())

print("\n2021:")
print(iec_2021.columns.tolist())

2016:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

2021:
[0, 1, 2, 3]

In [72]:

print("\n2021:")
print(iec_2021.head().to_string())

2016:
              0                1              2               3                          4                 5           6            7                                   8                9                     10
0       Province     Municipality           Ward  VotingDistrict          VotingStationName  RegisteredVoters  BallotType  SpoiltVotes                           PartyName  TotalValidVotes         DateGenerated
1  KwaZulu-Natal  ETH - eThekwini  Ward 59500001        43400179  NOMFIHLELA PRIMARY SCHOOL              1607          PR           72             ACADEMIC CONGRESS UNION                0  8/11/2016 3:58:48 PM
2  KwaZulu-Natal  ETH - eThekwini  Ward 59500001        43400179  NOMFIHLELA PRIMARY SCHOOL              1607          PR           72  AFRICAN CHRISTIAN DEMOCRATIC PARTY                0  8/11/2016 3:58:48 PM
3  KwaZulu-Natal  ETH - eThekwini  Ward 59500001        43400179  NOMFIHLELA PRIMARY SCHOOL              1607          PR           72        AFRICAN INDEPENDENT CONGRESS               19  8/11/2016 3:58:48 PM
4  KwaZulu-Natal  ETH - eThekwini  Ward 59500001        43400179  NOMFIHLELA PRIMARY SCHOOL              1607          PR           72         AFRICAN MANTUNGWA COMMUNITY                0  8/11/2016 3:58:48 PM

2021:
                                                  0    1    2    3
0                                     November 2025  NaN  NaN  NaN
1  Ward Level Small Area Population Estimates, 2022  NaN  NaN  NaN
2                                    Technical Note  NaN  NaN  NaN
3                                               NaN  NaN  NaN  NaN
4                                               NaN  NaN  NaN  NaN

In [74]:
from pathlib import Path
import pandas as pd

BASE_DIR = Path(r"C:\Users\Admin\PycharmProjects\SPU-TEAM-DIRISA")

RAW_DIR = BASE_DIR / "data" / "raw"
INTERIM_DIR = BASE_DIR / "data" / "interim"

print("RAW:", RAW_DIR)
print("INTERIM:", INTERIM_DIR)

print("\nRaw folder:")
for file in RAW_DIR.iterdir():
    print(file.name)

RAW: C:\Users\Admin\PycharmProjects\SPU-TEAM-DIRISA\data\raw
INTERIM: C:\Users\Admin\PycharmProjects\SPU-TEAM-DIRISA\data\interim

Raw folder:
.gitkeep
IEC_2016_Municipal_Results.csv
IEC_2021_Municipal_Results.xls
IEC_2021_Municipal_Results.xlsx
iec_kzn_ethekwini_ward_registration_2026.csv
StatsSA_Ward_Product_2022.xlsx

In [75]:
INTERIM_DIR.mkdir(parents=True, exist_ok=True)

print("Interim folder created:", INTERIM_DIR)

Interim folder created: C:\Users\Admin\PycharmProjects\SPU-TEAM-DIRISA\data\interim

In [76]:
CLEANING_LOG = INTERIM_DIR / "cleaning_log.csv"

if not CLEANING_LOG.exists():
    log_df = pd.DataFrame(columns=[
        "file",
        "check",
        "issue_found",
        "action_taken",
        "limitation"
    ])
    log_df.to_csv(CLEANING_LOG, index=False)

print("Cleaning log:", CLEANING_LOG)

Cleaning log: C:\Users\Admin\PycharmProjects\SPU-TEAM-DIRISA\data\interim\cleaning_log.csv

In [77]:
iec_2016_path = RAW_DIR / "IEC_2016_Municipal_Results.csv"

iec_2016 = pd.read_csv(iec_2016_path)

print("Rows:", len(iec_2016))
print("Columns:", len(iec_2016.columns))

print("\nColumns:")
print(iec_2016.columns.tolist())

Rows: 40706
Columns: 11

Columns:
['Province', 'Municipality', 'Ward', 'VotingDistrict', 'VotingStationName', 'RegisteredVoters', 'BallotType', 'SpoiltVotes', 'PartyName', 'TotalValidVotes', 'DateGenerated']

In [78]:
missing_2016 = iec_2016.isna().sum()

print("Missing values:")
print(missing_2016)

Missing values:
Province             0
Municipality         0
Ward                 0
VotingDistrict       0
VotingStationName    0
RegisteredVoters     0
BallotType           0
SpoiltVotes          0
PartyName            0
TotalValidVotes      0
DateGenerated        0
dtype: int64

In [79]:
text_columns = iec_2016.select_dtypes(include="object").columns

for column in text_columns:
    print("\n" + "=" * 50)
    print(column)
    print("=" * 50)
    print(iec_2016[column].dropna().astype(str).unique()[:30])

==================================================
Province
==================================================
<StringArray>
['KwaZulu-Natal']
Length: 1, dtype: str

==================================================
Municipality
==================================================
<StringArray>
['ETH - eThekwini']
Length: 1, dtype: str

==================================================
Ward
==================================================
<StringArray>
['Ward 59500001', 'Ward 59500002', 'Ward 59500003', 'Ward 59500004',
 'Ward 59500005', 'Ward 59500006', 'Ward 59500007', 'Ward 59500008',
 'Ward 59500009', 'Ward 59500010', 'Ward 59500011', 'Ward 59500012',
 'Ward 59500013', 'Ward 59500014', 'Ward 59500015', 'Ward 59500016',
 'Ward 59500017', 'Ward 59500018', 'Ward 59500019', 'Ward 59500020',
 'Ward 59500021', 'Ward 59500022', 'Ward 59500023', 'Ward 59500024',
 'Ward 59500025', 'Ward 59500026', 'Ward 59500027', 'Ward 59500028',
 'Ward 59500029', 'Ward 59500030']
Length: 30, dtype: str

==================================================
VotingStationName
==================================================
<StringArray>
[                'NOMFIHLELA PRIMARY SCHOOL',
                    'OTHWEBA PRIMARY SCHOOL',
        'CATO RIDGE LIBRARY ACTIVITIES ROOM',
                      'NGIDI PRIMARY SCHOOL',
                      'MVINI PRIMARY SCHOOL',
                      'XIMBA COMMUNITY HALL',
                    'MABHILA PRIMARY SCHOOL',
                    'NTUKUSO PRIMARY SCHOOL',
                 'INGCINDEZI PRIMARY SCHOOL',
                 'INSIMANGWE PRIMARY SCHOOL',
                 'INDUNAKAZI PRIMARY SCHOOL',
                 'EMKHATHINI PRIMARY SCHOOL',
                    'SIYAJABULA HIGH SCHOOL',
                   'QINISELANI TRIBAL COURT',
                  'UMPHUMELA PRIMARY SCHOOL',
                          'KHAMANGWA SCHOOL',
                  'BONGUMUSA PRIMARY SCHOOL',
            'MAPHEPHETHE TRIDITONAL COUNCIL',
                     'UPHISO PRIMARY SCHOOL',
                           'NKANGALA CRECHE',
 'LETHOKUHLE COMBINED PRIMARY SCHOOL SCHOOL',
               'KWANONGQANGA PRIMARY SCHOOL',
           'AMAQADI COMBINED PRIMARY SCHOOL',
                 'MATHABETHU PRIMARY SCHOOL',
                 'INGCUKWINI PRIMARY SCHOOL',
              'MBANANA ZENEX PRIMARY SCHOOL',
             'KHULANI JUNIOR PRIMARY SCHOOL',
                       'SILINDELE LP SCHOOL',
                       'NOGUJWA HIGH SCHOOL',
                 'INGOMEZULU PRIMARY SCHOOL']
Length: 30, dtype: str

==================================================
BallotType
==================================================
<StringArray>
['PR', 'Ward']
Length: 2, dtype: str

==================================================
PartyName
==================================================
<StringArray>
[                 'ACADEMIC CONGRESS UNION',
       'AFRICAN CHRISTIAN DEMOCRATIC PARTY',
             'AFRICAN INDEPENDENT CONGRESS',
              'AFRICAN MANTUNGWA COMMUNITY',
                'AFRICAN NATIONAL CONGRESS',
              'AFRICAN PEOPLE'S CONVENTION',
                               'AL JAMA-AH',
               'ALLIED MOVEMENT FOR CHANGE',
            'AZANIAN PEOPLE'S ORGANISATION',
                  'CONGRESS  OF THE PEOPLE',
                      'DEMOCRATIC ALLIANCE',
              'DEMOCRATIC LIBERAL CONGRESS',
                'ECONOMIC FREEDOM FIGHTERS',
               'INDEPENDENT PEOPLE'S PARTY',
 'INDEPENDENT RATEPAYERS ASSOCIATION OF SA',
                    'INKATHA FREEDOM PARTY',
               'MINORITIES OF SOUTH AFRICA',
                           'MINORITY FRONT',
        'PAN AFRICANIST CONGRESS OF AZANIA',
          'PEOPLE'S REVOLUTIONARY MOVEMENT',
            'SOUTH AFRICAN POLITICAL PARTY',
                   'THE PROMISE OF FREEDOM',
                           'TRULY ALLIANCE',
               'UNITED DEMOCRATIC MOVEMENT',
                     'UNITED PEOPLES PARTY',
                   'UNITED RESIDENTS FRONT',
                       'VRYHEIDSFRONT PLUS',
                              'INDEPENDENT']
Length: 28, dtype: str

==================================================
DateGenerated
==================================================
<StringArray>
['8/11/2016 3:58:48 PM']
Length: 1, dtype: str

C:\Users\Admin\AppData\Local\Temp\ipykernel_35388\393022041.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = iec_2016.select_dtypes(include="object").columns

In [80]:
print(iec_2016.dtypes)

Province               str
Municipality           str
Ward                   str
VotingDistrict       int64
VotingStationName      str
RegisteredVoters     int64
BallotType             str
SpoiltVotes          int64
PartyName              str
TotalValidVotes      int64
DateGenerated          str
dtype: object

In [81]:
numeric_columns = [
    "RegisteredVoters",
    "SpoiltVotes",
    "TotalValidVotes"
]

for column in numeric_columns:
    if column in iec_2016.columns:
        print(
            column,
            "→",
            iec_2016[column].dtype
        )

RegisteredVoters → int64
SpoiltVotes → int64
TotalValidVotes → int64

In [82]:
for column in numeric_columns:
    if column in iec_2016.columns:
        try:
            total = pd.to_numeric(
                iec_2016[column],
                errors="raise"
            ).sum()

            print(column, "✓ numeric | Total:", total)

        except Exception as e:
            print(column, "✗ problem:", e)

RegisteredVoters ✓ numeric | Total: 90295784
SpoiltVotes ✓ numeric | Total: 1217817
TotalValidVotes ✓ numeric | Total: 2225605

In [83]:
print("Duplicate rows:", iec_2016.duplicated().sum())

Duplicate rows: 0

In [84]:
duplicates = iec_2016[iec_2016.duplicated(keep=False)]

print(duplicates)

Empty DataFrame
Columns: [Province, Municipality, Ward, VotingDistrict, VotingStationName, RegisteredVoters, BallotType, SpoiltVotes, PartyName, TotalValidVotes, DateGenerated]
Index: []

In [85]:
print(iec_2016.head(10))
print("\nLast 10 rows:")
print(iec_2016.tail(10))

        Province     Municipality           Ward  VotingDistrict  \
0  KwaZulu-Natal  ETH - eThekwini  Ward 59500001        43400179
1  KwaZulu-Natal  ETH - eThekwini  Ward 59500001        43400179
2  KwaZulu-Natal  ETH - eThekwini  Ward 59500001        43400179
3  KwaZulu-Natal  ETH - eThekwini  Ward 59500001        43400179
4  KwaZulu-Natal  ETH - eThekwini  Ward 59500001        43400179
5  KwaZulu-Natal  ETH - eThekwini  Ward 59500001        43400179
6  KwaZulu-Natal  ETH - eThekwini  Ward 59500001        43400179
7  KwaZulu-Natal  ETH - eThekwini  Ward 59500001        43400179
8  KwaZulu-Natal  ETH - eThekwini  Ward 59500001        43400179
9  KwaZulu-Natal  ETH - eThekwini  Ward 59500001        43400179

           VotingStationName  RegisteredVoters BallotType  SpoiltVotes  \
0  NOMFIHLELA PRIMARY SCHOOL              1607         PR           72
1  NOMFIHLELA PRIMARY SCHOOL              1607         PR           72
2  NOMFIHLELA PRIMARY SCHOOL              1607         PR           72
3  NOMFIHLELA PRIMARY SCHOOL              1607         PR           72
4  NOMFIHLELA PRIMARY SCHOOL              1607         PR           72
5  NOMFIHLELA PRIMARY SCHOOL              1607         PR           72
6  NOMFIHLELA PRIMARY SCHOOL              1607         PR           72
7  NOMFIHLELA PRIMARY SCHOOL              1607         PR           72
8  NOMFIHLELA PRIMARY SCHOOL              1607         PR           72
9  NOMFIHLELA PRIMARY SCHOOL              1607         PR           72

                            PartyName  TotalValidVotes         DateGenerated
0             ACADEMIC CONGRESS UNION                0  8/11/2016 3:58:48 PM
1  AFRICAN CHRISTIAN DEMOCRATIC PARTY                0  8/11/2016 3:58:48 PM
2        AFRICAN INDEPENDENT CONGRESS               19  8/11/2016 3:58:48 PM
3         AFRICAN MANTUNGWA COMMUNITY                0  8/11/2016 3:58:48 PM
4           AFRICAN NATIONAL CONGRESS             1157  8/11/2016 3:58:48 PM
5         AFRICAN PEOPLE'S CONVENTION                3  8/11/2016 3:58:48 PM
6                          AL JAMA-AH                0  8/11/2016 3:58:48 PM
7          ALLIED MOVEMENT FOR CHANGE                0  8/11/2016 3:58:48 PM
8       AZANIAN PEOPLE'S ORGANISATION                0  8/11/2016 3:58:48 PM
9             CONGRESS  OF THE PEOPLE                0  8/11/2016 3:58:48 PM

Last 10 rows:
            Province     Municipality           Ward  VotingDistrict  \
40696  KwaZulu-Natal  ETH - eThekwini  Ward 59500110        43362288
40697  KwaZulu-Natal  ETH - eThekwini  Ward 59500110        43362288
40698  KwaZulu-Natal  ETH - eThekwini  Ward 59500110        43362288
40699  KwaZulu-Natal  ETH - eThekwini  Ward 59500110        43362288
40700  KwaZulu-Natal  ETH - eThekwini  Ward 59500110        43362288
40701  KwaZulu-Natal  ETH - eThekwini  Ward 59500110        43362288
40702  KwaZulu-Natal  ETH - eThekwini  Ward 59500110        43362288
40703  KwaZulu-Natal  ETH - eThekwini  Ward 59500110        43362288
40704  KwaZulu-Natal  ETH - eThekwini  Ward 59500110        43362288
40705  KwaZulu-Natal  ETH - eThekwini  Ward 59500110        43362288

             VotingStationName  RegisteredVoters BallotType  SpoiltVotes  \
40696  MT ROYAL PRIMARY SCHOOL              2466       Ward           31
40697  MT ROYAL PRIMARY SCHOOL              2466       Ward           31
40698  MT ROYAL PRIMARY SCHOOL              2466       Ward           31
40699  MT ROYAL PRIMARY SCHOOL              2466       Ward           31
40700  MT ROYAL PRIMARY SCHOOL              2466       Ward           31
40701  MT ROYAL PRIMARY SCHOOL              2466       Ward           31
40702  MT ROYAL PRIMARY SCHOOL              2466       Ward           31
40703  MT ROYAL PRIMARY SCHOOL              2466       Ward           31
40704  MT ROYAL PRIMARY SCHOOL              2466       Ward           31
40705  MT ROYAL PRIMARY SCHOOL              2466       Ward           31

                                      PartyName  TotalValidVotes  \
40696                 ECONOMIC FREEDOM FIGHTERS               22
40697                               INDEPENDENT              460
40698  INDEPENDENT RATEPAYERS ASSOCIATION OF SA                0
40699                     INKATHA FREEDOM PARTY               19
40700                MINORITIES OF SOUTH AFRICA                1
40701                            MINORITY FRONT                0
40702         PAN AFRICANIST CONGRESS OF AZANIA                0
40703                            TRULY ALLIANCE                1
40704                      UNITED PEOPLES PARTY                1
40705                        VRYHEIDSFRONT PLUS                0

              DateGenerated
40696  8/11/2016 3:58:48 PM
40697  8/11/2016 3:58:48 PM
40698  8/11/2016 3:58:48 PM
40699  8/11/2016 3:58:48 PM
40700  8/11/2016 3:58:48 PM
40701  8/11/2016 3:58:48 PM
40702  8/11/2016 3:58:48 PM
40703  8/11/2016 3:58:48 PM
40704  8/11/2016 3:58:48 PM
40705  8/11/2016 3:58:48 PM

In [86]:
print(iec_2016["BallotType"].value_counts())

BallotType
PR      23382
Ward    17324
Name: count, dtype: int64

In [87]:
print(
    iec_2016.groupby("BallotType")[
        ["RegisteredVoters", "SpoiltVotes", "TotalValidVotes"]
    ].sum()
)

            RegisteredVoters  SpoiltVotes  TotalValidVotes
BallotType
PR                  51832548       809406          1104552
Ward                38463236       408411          1121053

In [88]:
print(
    iec_2016.groupby("BallotType")["Ward"].nunique()
)

BallotType
PR      110
Ward    110
Name: Ward, dtype: int64

In [89]:
# Step 10: Check for impossible or suspicious numeric values

print("RegisteredVoters < 0:")
print((iec_2016["RegisteredVoters"] < 0).sum())

print("\nSpoiltVotes < 0:")
print((iec_2016["SpoiltVotes"] < 0).sum())

print("\nTotalValidVotes < 0:")
print((iec_2016["TotalValidVotes"] < 0).sum())

print("\nRegisteredVoters = 0:")
print((iec_2016["RegisteredVoters"] == 0).sum())

print("\nTotalValidVotes > RegisteredVoters:")
print((iec_2016["TotalValidVotes"] > iec_2016["RegisteredVoters"]).sum())

RegisteredVoters < 0:
0

SpoiltVotes < 0:
0

TotalValidVotes < 0:
0

RegisteredVoters = 0:
0

TotalValidVotes > RegisteredVoters:
2

In [90]:
# Step 11: Inspect rows where valid votes exceed registered voters

suspicious_2016 = iec_2016[
    iec_2016["TotalValidVotes"] > iec_2016["RegisteredVoters"]
]

print(suspicious_2016.to_string(index=False))

     Province    Municipality          Ward  VotingDistrict        VotingStationName  RegisteredVoters BallotType  SpoiltVotes           PartyName  TotalValidVotes        DateGenerated
KwaZulu-Natal ETH - eThekwini Ward 59500069        43371592 OCEANVIEW PRIMARY SCHOOL              1619         PR            0 DEMOCRATIC ALLIANCE             1726 8/11/2016 3:58:48 PM
KwaZulu-Natal ETH - eThekwini Ward 59500069        43371592 OCEANVIEW PRIMARY SCHOOL              1619       Ward            0 DEMOCRATIC ALLIANCE             1726 8/11/2016 3:58:48 PM

In [91]:
# Compare the suspicious rows by ballot type

print("\nBallot types:")
print(suspicious_2016["BallotType"].value_counts())

print("\nDifference:")
suspicious_2016 = suspicious_2016.copy()
suspicious_2016["Difference"] = (
    suspicious_2016["TotalValidVotes"]
    - suspicious_2016["RegisteredVoters"]
)

print(
    suspicious_2016[
        [
            "Municipality",
            "Ward",
            "VotingDistrict",
            "VotingStationName",
            "BallotType",
            "RegisteredVoters",
            "TotalValidVotes",
            "SpoiltVotes",
            "Difference"
        ]
    ].to_string(index=False)
)

Ballot types:
BallotType
PR      1
Ward    1
Name: count, dtype: int64

Difference:
   Municipality          Ward  VotingDistrict        VotingStationName BallotType  RegisteredVoters  TotalValidVotes  SpoiltVotes  Difference
ETH - eThekwini Ward 59500069        43371592 OCEANVIEW PRIMARY SCHOOL         PR              1619             1726            0         107
ETH - eThekwini Ward 59500069        43371592 OCEANVIEW PRIMARY SCHOOL       Ward              1619             1726            0         107

In [92]:
# Step 12: Record the identified data-quality issue

new_log = pd.DataFrame([{
    "file": "IEC_2016_Municipal_Results.csv",
    "check": "Numeric validity",
    "issue_found": "2 rows have TotalValidVotes greater than RegisteredVoters; both refer to the same voting district/station and appear once for PR and once for Ward.",
    "action_taken": "Rows retained unchanged; flagged for investigation during data validation/model preparation.",
    "limitation": "IEC source data contains a voting-station record where valid votes exceed registered voters."
}])

cleaning_log = pd.concat([cleaning_log, new_log], ignore_index=True)

cleaning_log.to_csv(
    INTERIM_DIR / "cleaning_log.csv",
    index=False
)

print("Cleaning log updated.")
print(cleaning_log.tail(3).to_string(index=False))

NameError: name 'cleaning_log' is not defined

In [93]:
from pathlib import Path
import pandas as pd

BASE_DIR = Path(r"C:\Users\Admin\PycharmProjects\SPU-TEAM-DIRISA")
INTERIM_DIR = BASE_DIR / "data" / "interim"

log_file = INTERIM_DIR / "cleaning_log.csv"

if log_file.exists():
    cleaning_log = pd.read_csv(log_file)
    print("Existing cleaning log loaded.")
else:
    cleaning_log = pd.DataFrame(columns=[
        "file",
        "check",
        "issue_found",
        "action_taken",
        "limitation"
    ])
    print("New cleaning log created.")

print(cleaning_log)

Existing cleaning log loaded.
Empty DataFrame
Columns: [file, check, issue_found, action_taken, limitation]
Index: []

In [94]:
new_log = pd.DataFrame([{
    "file": "IEC_2016_Municipal_Results.csv",
    "check": "Numeric validity",
    "issue_found": "2 rows have TotalValidVotes greater than RegisteredVoters; both refer to the same voting district/station and appear once for PR and once for Ward.",
    "action_taken": "Rows retained unchanged; flagged for investigation during data validation/model preparation.",
    "limitation": "IEC source data contains a voting-station record where valid votes exceed registered voters."
}])

cleaning_log = pd.concat([cleaning_log, new_log], ignore_index=True)

cleaning_log.to_csv(
    INTERIM_DIR / "cleaning_log.csv",
    index=False
)

print("Cleaning log updated successfully.")
print(cleaning_log.tail(3).to_string(index=False))

Cleaning log updated successfully.
                          file            check                                                                                                                                         issue_found                                                                                 action_taken                                                                                   limitation
IEC_2016_Municipal_Results.csv Numeric validity 2 rows have TotalValidVotes greater than RegisteredVoters; both refer to the same voting district/station and appear once for PR and once for Ward. Rows retained unchanged; flagged for investigation during data validation/model preparation. IEC source data contains a voting-station record where valid votes exceed registered voters.

In [95]:
# Step 13: Check text columns for blank or whitespace-only values

text_columns = iec_2016.select_dtypes(
    include=["object", "string"]
).columns

for col in text_columns:
    blank_count = iec_2016[col].astype("string").str.strip().eq("").sum()
    print(f"{col}: {blank_count} blank/whitespace values")

Province: 0 blank/whitespace values
Municipality: 0 blank/whitespace values
Ward: 0 blank/whitespace values
VotingStationName: 0 blank/whitespace values
BallotType: 0 blank/whitespace values
PartyName: 0 blank/whitespace values
DateGenerated: 0 blank/whitespace values

In [96]:
# Step 14: Save cleaned 2016 file to interim

INTERIM_DIR.mkdir(parents=True, exist_ok=True)

interim_2016 = INTERIM_DIR / "IEC_2016_Municipal_Results.csv"

iec_2016.to_csv(interim_2016, index=False)

print("Saved successfully:")
print(interim_2016)
print(f"\nRows: {len(iec_2016):,}")
print(f"Columns: {len(iec_2016.columns)}")

Saved successfully:
C:\Users\Admin\PycharmProjects\SPU-TEAM-DIRISA\data\interim\IEC_2016_Municipal_Results.csv

Rows: 40,706
Columns: 11

In [97]:
# Step 15: Verify the saved interim file

check_2016 = pd.read_csv(interim_2016)

print("File exists:", interim_2016.exists())
print("Rows:", len(check_2016))
print("Columns:", len(check_2016.columns))
print("\nColumns:")
print(check_2016.columns.tolist())

print("\nFirst 3 rows:")
print(check_2016.head(3).to_string(index=False))

File exists: True
Rows: 40706
Columns: 11

Columns:
['Province', 'Municipality', 'Ward', 'VotingDistrict', 'VotingStationName', 'RegisteredVoters', 'BallotType', 'SpoiltVotes', 'PartyName', 'TotalValidVotes', 'DateGenerated']

First 3 rows:
     Province    Municipality          Ward  VotingDistrict         VotingStationName  RegisteredVoters BallotType  SpoiltVotes                          PartyName  TotalValidVotes        DateGenerated
KwaZulu-Natal ETH - eThekwini Ward 59500001        43400179 NOMFIHLELA PRIMARY SCHOOL              1607         PR           72            ACADEMIC CONGRESS UNION                0 8/11/2016 3:58:48 PM
KwaZulu-Natal ETH - eThekwini Ward 59500001        43400179 NOMFIHLELA PRIMARY SCHOOL              1607         PR           72 AFRICAN CHRISTIAN DEMOCRATIC PARTY                0 8/11/2016 3:58:48 PM
KwaZulu-Natal ETH - eThekwini Ward 59500001        43400179 NOMFIHLELA PRIMARY SCHOOL              1607         PR           72       AFRICAN INDEPENDENT CONGRESS               19 8/11/2016 3:58:48 PM

In [98]:
# Step 16: Load the 2021 IEC Excel workbook

IEC_2021_FILE = RAW_DIR / "IEC_2021_Municipal_Results.xlsx"

print("File exists:", IEC_2021_FILE.exists())
print("File:", IEC_2021_FILE)

excel_2021 = pd.ExcelFile(IEC_2021_FILE)

print("\nSheets found:")
print(excel_2021.sheet_names)

File exists: True
File: C:\Users\Admin\PycharmProjects\SPU-TEAM-DIRISA\data\raw\IEC_2021_Municipal_Results.xlsx

Sheets found:
['Table 1', 'Table 2']

In [99]:
# Step 17: Inspect the structure of both 2021 sheets

for sheet in excel_2021.sheet_names:
    print("\n" + "=" * 60)
    print("SHEET:", sheet)
    print("=" * 60)

    df = pd.read_excel(IEC_2021_FILE, sheet_name=sheet)

    print("Rows:", len(df))
    print("Columns:", len(df.columns))
    print("\nColumn names:")
    print(df.columns.tolist())

    print("\nFirst 5 rows:")
    print(df.head().to_string(index=False))

============================================================
SHEET: Table 1
============================================================
Rows: 72
Columns: 4

Column names:
['November 2025', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']

First 5 rows:
                                   November 2025 Unnamed: 1 Unnamed: 2 Unnamed: 3
Ward Level Small Area Population Estimates, 2022        NaN        NaN        NaN
                                  Technical Note        NaN        NaN        NaN
                                             NaN        NaN        NaN        NaN
                                             NaN        NaN        NaN        NaN
                                             NaN        NaN        NaN        NaN

============================================================
SHEET: Table 2
============================================================
Rows: 34
Columns: 5

Column names:
['The  right-hand  side  portion  of  Figure  2  above,  also  demonstrates that  no  convergence  is achieved by the first raking pass in the remaining 167 wards where the small area estimates of population size are higher from ward to ward compared to the corresponding Census 2022 figures. Here the SAEs in these wards overstate the population size found in Census 2022. This  extends  to  municipal  level,  and  further  to  provincial  and  national  levels  compared  to Census 2022. For reasons of compression, the overestimates are summed up by province, showing an overall margin of error of 0,69% nationally, ranging from a low of 0,29% to a high of 1,50% between the provinces. Table 2 below, gives a summary of the incidence of this error margin,  computed as the  percentage ratio between  the “extra”  persons added  by the first raking pass and the number of persons found in Census 2022.', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']

First 5 rows:
The  right-hand  side  portion  of  Figure  2  above,  also  demonstrates that  no  convergence  is achieved by the first raking pass in the remaining 167 wards where the small area estimates of population size are higher from ward to ward compared to the corresponding Census 2022 figures. Here the SAEs in these wards overstate the population size found in Census 2022. This  extends  to  municipal  level,  and  further  to  provincial  and  national  levels  compared  to Census 2022. For reasons of compression, the overestimates are summed up by province, showing an overall margin of error of 0,69% nationally, ranging from a low of 0,29% to a high of 1,50% between the provinces. Table 2 below, gives a summary of the incidence of this error margin,  computed as the  percentage ratio between  the “extra”  persons added  by the first raking pass and the number of persons found in Census 2022.    Unnamed: 1                                  Unnamed: 2   Unnamed: 3          Unnamed: 4
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Table 2: Overestimation of population size from first raking pass, by province           NaN                                         NaN          NaN                 NaN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   NaN           NaN                                         NaN          NaN                 NaN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Provinces No. of\nwards “Extra” persons added\nby first raking pass Census\n2022 Margin of error,\n%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         KwaZulu-Natal            40                                      67 970   12 423 907                0,55
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Eastern Cape            25                                      54 781    7 230 204                0,76

In [100]:
# Step 18: Inspect Table 1

table1_2021 = pd.read_excel(
    IEC_2021_FILE,
    sheet_name="Table 1",
    header=None
)

print("Rows:", len(table1_2021))
print("Columns:", len(table1_2021.columns))

print("\nFirst 20 rows:")
print(table1_2021.head(20).to_string(index=False, header=False))

Rows: 73
Columns: 4

First 20 rows:
                                                                                                                                                                                                                                                                                                                                                                                                                          November 2025 NaN NaN NaN
                                                                                                                                                                                                                                                                                                                                                                                       Ward Level Small Area Population Estimates, 2022 NaN NaN NaN
                                                                                                                                                                                                                                                                                                                                                                                                                         Technical Note NaN NaN NaN
                                                                                                                                                                                                                                                                                                                                                                                                                                    NaN NaN NaN NaN
                                                                                                                                                                                                                                                                                                                                                                                                                                    NaN NaN NaN NaN
                                                                                                                                                                                                                                                                                                                                                                                                                                    NaN NaN NaN NaN
                                                                                                                                                                                                                                                                                                                                                                                                                               Contents NaN NaN NaN
                                                                                                                                                                                                                                                                                              1. Introduction                                                                                                                         1 NaN NaN NaN
                                                                                                                                                                                                                                                                                                       1.1 Purpose of technical note                                                                                                  1 NaN NaN NaN
                                                                                                                                                                                                                                                                                                                     2. Ward product development processes                                                                            1 NaN NaN NaN
                                                                                                                                                                                                                                                                                                                   2.1. Assessment of data below local municipality                                                                   1 NaN NaN NaN
                                                                                                                                                                                                                                                                                                                   2.1.2 Ward layer data assessment                                                                                   1 NaN NaN NaN
                                                                                                                                                                                                                                                                                                                              2.1.3 Alignment of Census 2022 data to 2020 wards                                                       1 NaN NaN NaN
                                                                                                                                                                                                                                                                                                                     2.1.4 Ward layer indicator assessment                                                                            2 NaN NaN NaN
                                                                                                                                                                                                                                                                                                                      2.2 Small area estimation methodology at ward level                                                             2 NaN NaN NaN
                                                                                                                                                                                                                                                                                                3. Main findings                                                                                                                      4 NaN NaN NaN
                                                                                                                                                                                                                                                                                               4. Conclusion                                                                                                                          8 NaN NaN NaN
                                                                                                                                                                                                                                                                                                            5. How to access the ward data                                                                                            9 NaN NaN NaN
                                                                                                                                                                                                                                                                                               References                                                                                                                            10 NaN NaN NaN
1. Introduction\nThis technical note outlines  processes and methods  used to derive  Small  Area  Estimates (SAEs) of the population structure at ward level, utilising intercensal Census 2011 and Census 2022 data. Small Area Estimates are estimates for area-level domains produced from mutually consistent data sources where the final series of the estimates is derived by pooling together\ninformation from these sources. NaN NaN NaN

In [101]:
# Step 19: List all files currently in data/raw

print("Files currently in data/raw:\n")

for file in sorted(RAW_DIR.iterdir()):
    if file.is_file():
        print(file.name)

Files currently in data/raw:

.gitkeep
IEC_2016_Municipal_Results.csv
IEC_2021_Municipal_Results.xls
IEC_2021_Municipal_Results.xlsx
iec_kzn_ethekwini_ward_registration_2026.csv
StatsSA_Ward_Product_2022.xlsx

In [102]:
import pandas as pd
from pathlib import Path

raw_file = Path(
    r"C:\Users\Admin\PycharmProjects\SPU-TEAM-DIRISA\notebooks\KZN_Voter_Prediction_2021-2022 Cleaned\IEC_2016_Municipal_Results.csv"
)

df = pd.read_csv(raw_file)

print("File loaded successfully!")
print("Shape:", df.shape)

df.head()

File loaded successfully!
Shape: (40706, 11)

,Province,Municipality,Ward,VotingDistrict,VotingStationName,RegisteredVoters,BallotType,SpoiltVotes,PartyName,TotalValidVotes,DateGenerated
0,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,ACADEMIC CONGRESS UNION,0,8/11/2016 3:58:48 PM
1,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,AFRICAN CHRISTIAN DEMOCRATIC PARTY,0,8/11/2016 3:58:48 PM
2,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,AFRICAN INDEPENDENT CONGRESS,19,8/11/2016 3:58:48 PM
3,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,AFRICAN MANTUNGWA COMMUNITY,0,8/11/2016 3:58:48 PM
4,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,AFRICAN NATIONAL CONGRESS,1157,8/11/2016 3:58:48 PM

In [103]:
print("Columns:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isna().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

Columns:
['Province', 'Municipality', 'Ward', 'VotingDistrict', 'VotingStationName', 'RegisteredVoters', 'BallotType', 'SpoiltVotes', 'PartyName', 'TotalValidVotes', 'DateGenerated']

Data types:
Province               str
Municipality           str
Ward                   str
VotingDistrict       int64
VotingStationName      str
RegisteredVoters     int64
BallotType             str
SpoiltVotes          int64
PartyName              str
TotalValidVotes      int64
DateGenerated          str
dtype: object

Missing values:
Province             0
Municipality         0
Ward                 0
VotingDistrict       0
VotingStationName    0
RegisteredVoters     0
BallotType           0
SpoiltVotes          0
PartyName            0
TotalValidVotes      0
DateGenerated        0
dtype: int64

Duplicate rows:
0

In [104]:
print("\nFirst 5 rows:")
display(df.head())

print("\nLast 5 rows:")
display(df.tail())

First 5 rows:

,Province,Municipality,Ward,VotingDistrict,VotingStationName,RegisteredVoters,BallotType,SpoiltVotes,PartyName,TotalValidVotes,DateGenerated
0,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,ACADEMIC CONGRESS UNION,0,8/11/2016 3:58:48 PM
1,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,AFRICAN CHRISTIAN DEMOCRATIC PARTY,0,8/11/2016 3:58:48 PM
2,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,AFRICAN INDEPENDENT CONGRESS,19,8/11/2016 3:58:48 PM
3,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,AFRICAN MANTUNGWA COMMUNITY,0,8/11/2016 3:58:48 PM
4,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,AFRICAN NATIONAL CONGRESS,1157,8/11/2016 3:58:48 PM

Last 5 rows:

,Province,Municipality,Ward,VotingDistrict,VotingStationName,RegisteredVoters,BallotType,SpoiltVotes,PartyName,TotalValidVotes,DateGenerated
40701,KwaZulu-Natal,ETH - eThekwini,Ward 59500110,43362288,MT ROYAL PRIMARY SCHOOL,2466,Ward,31,MINORITY FRONT,0,8/11/2016 3:58:48 PM
40702,KwaZulu-Natal,ETH - eThekwini,Ward 59500110,43362288,MT ROYAL PRIMARY SCHOOL,2466,Ward,31,PAN AFRICANIST CONGRESS OF AZANIA,0,8/11/2016 3:58:48 PM
40703,KwaZulu-Natal,ETH - eThekwini,Ward 59500110,43362288,MT ROYAL PRIMARY SCHOOL,2466,Ward,31,TRULY ALLIANCE,1,8/11/2016 3:58:48 PM
40704,KwaZulu-Natal,ETH - eThekwini,Ward 59500110,43362288,MT ROYAL PRIMARY SCHOOL,2466,Ward,31,UNITED PEOPLES PARTY,1,8/11/2016 3:58:48 PM
40705,KwaZulu-Natal,ETH - eThekwini,Ward 59500110,43362288,MT ROYAL PRIMARY SCHOOL,2466,Ward,31,VRYHEIDSFRONT PLUS,0,8/11/2016 3:58:48 PM

In [105]:
print(df.columns.tolist())
print(df.dtypes)
print(df.isna().sum())
print("Duplicates:", df.duplicated().sum())

['Province', 'Municipality', 'Ward', 'VotingDistrict', 'VotingStationName', 'RegisteredVoters', 'BallotType', 'SpoiltVotes', 'PartyName', 'TotalValidVotes', 'DateGenerated']
Province               str
Municipality           str
Ward                   str
VotingDistrict       int64
VotingStationName      str
RegisteredVoters     int64
BallotType             str
SpoiltVotes          int64
PartyName              str
TotalValidVotes      int64
DateGenerated          str
dtype: object
Province             0
Municipality         0
Ward                 0
VotingDistrict       0
VotingStationName    0
RegisteredVoters     0
BallotType           0
SpoiltVotes          0
PartyName            0
TotalValidVotes      0
DateGenerated        0
dtype: int64
Duplicates: 0

In [106]:
print("COLUMNS")
print(df.columns.tolist())

print("\nDATA TYPES")
print(df.dtypes)

print("\nMISSING VALUES")
print(df.isna().sum())

print("\nDUPLICATES")
print("Duplicates:", df.duplicated().sum())

COLUMNS
['Province', 'Municipality', 'Ward', 'VotingDistrict', 'VotingStationName', 'RegisteredVoters', 'BallotType', 'SpoiltVotes', 'PartyName', 'TotalValidVotes', 'DateGenerated']

DATA TYPES
Province               str
Municipality           str
Ward                   str
VotingDistrict       int64
VotingStationName      str
RegisteredVoters     int64
BallotType             str
SpoiltVotes          int64
PartyName              str
TotalValidVotes      int64
DateGenerated          str
dtype: object

MISSING VALUES
Province             0
Municipality         0
Ward                 0
VotingDistrict       0
VotingStationName    0
RegisteredVoters     0
BallotType           0
SpoiltVotes          0
PartyName            0
TotalValidVotes      0
DateGenerated        0
dtype: int64

DUPLICATES
Duplicates: 0

In [107]:
print(df["Ward"].head(20).tolist())

['Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001']

In [108]:
print("Ward lengths:")
print(df["Ward"].astype(str).str.len().value_counts())

Ward lengths:
Ward
13    40706
Name: count, dtype: int64

In [109]:
print("Example ward codes:")
print(df["Ward"].drop_duplicates().head(30).tolist())

Example ward codes:
['Ward 59500001', 'Ward 59500002', 'Ward 59500003', 'Ward 59500004', 'Ward 59500005', 'Ward 59500006', 'Ward 59500007', 'Ward 59500008', 'Ward 59500009', 'Ward 59500010', 'Ward 59500011', 'Ward 59500012', 'Ward 59500013', 'Ward 59500014', 'Ward 59500015', 'Ward 59500016', 'Ward 59500017', 'Ward 59500018', 'Ward 59500019', 'Ward 59500020', 'Ward 59500021', 'Ward 59500022', 'Ward 59500023', 'Ward 59500024', 'Ward 59500025', 'Ward 59500026', 'Ward 59500027', 'Ward 59500028', 'Ward 59500029', 'Ward 59500030']

In [110]:
numeric_columns = [
    "VotingDistrict",
    "RegisteredVoters",
    "SpoiltVotes",
    "TotalValidVotes"
]

for column in numeric_columns:
    print(f"\n{column}")
    print("Minimum:", df[column].min())
    print("Maximum:", df[column].max())
    print("Sum:", df[column].sum())

VotingDistrict
Minimum: 43350016
Maximum: 44070072
Sum: 1767476998181

RegisteredVoters
Minimum: 101
Maximum: 8099
Sum: 90295784

SpoiltVotes
Minimum: 0
Maximum: 993
Sum: 1217817

TotalValidVotes
Minimum: 0
Maximum: 4175
Sum: 2225605

In [111]:
for column in numeric_columns:
    negative = (df[column] < 0).sum()
    print(f"{column}: {negative} negative values")

VotingDistrict: 0 negative values
RegisteredVoters: 0 negative values
SpoiltVotes: 0 negative values
TotalValidVotes: 0 negative values

In [112]:
print("Number of municipalities:", df["Municipality"].nunique())

print("\nMunicipalities:")
for municipality in sorted(df["Municipality"].unique()):
    print(municipality)

Number of municipalities: 1

Municipalities:
ETH - eThekwini

In [114]:
df["Province"] = df["Province"].str.strip()
df["Municipality"] = df["Municipality"].str.strip()
df["VotingStationName"] = df["VotingStationName"].str.strip()
df["PartyName"] = df["PartyName"].str.strip()
df["BallotType"] = df["BallotType"].str.strip()

In [115]:
print("Number of parties:", df["PartyName"].nunique())

for party in sorted(df["PartyName"].unique()):
    print(repr(party))

Number of parties: 28
'ACADEMIC CONGRESS UNION'
'AFRICAN CHRISTIAN DEMOCRATIC PARTY'
'AFRICAN INDEPENDENT CONGRESS'
'AFRICAN MANTUNGWA COMMUNITY'
'AFRICAN NATIONAL CONGRESS'
"AFRICAN PEOPLE'S CONVENTION"
'AL JAMA-AH'
'ALLIED MOVEMENT FOR CHANGE'
"AZANIAN PEOPLE'S ORGANISATION"
'CONGRESS  OF THE PEOPLE'
'DEMOCRATIC ALLIANCE'
'DEMOCRATIC LIBERAL CONGRESS'
'ECONOMIC FREEDOM FIGHTERS'
'INDEPENDENT'
"INDEPENDENT PEOPLE'S PARTY"
'INDEPENDENT RATEPAYERS ASSOCIATION OF SA'
'INKATHA FREEDOM PARTY'
'MINORITIES OF SOUTH AFRICA'
'MINORITY FRONT'
'PAN AFRICANIST CONGRESS OF AZANIA'
"PEOPLE'S REVOLUTIONARY MOVEMENT"
'SOUTH AFRICAN POLITICAL PARTY'
'THE PROMISE OF FREEDOM'
'TRULY ALLIANCE'
'UNITED DEMOCRATIC MOVEMENT'
'UNITED PEOPLES PARTY'
'UNITED RESIDENTS FRONT'
'VRYHEIDSFRONT PLUS'

In [116]:
print(df["BallotType"].value_counts(dropna=False))

BallotType
PR      23382
Ward    17324
Name: count, dtype: int64

In [117]:
print(df["DateGenerated"].unique())

<StringArray>
['8/11/2016 3:58:48 PM']
Length: 1, dtype: str

In [118]:
df["DateGenerated"] = pd.to_datetime(
    df["DateGenerated"],
    errors="coerce"
)

In [119]:
print(df["DateGenerated"].dtype)
print(df["DateGenerated"].isna().sum())

datetime64[us]
0

In [120]:
display(df.head(10))
display(df.tail(10))

,Province,Municipality,Ward,VotingDistrict,VotingStationName,RegisteredVoters,BallotType,SpoiltVotes,PartyName,TotalValidVotes,DateGenerated
0,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,ACADEMIC CONGRESS UNION,0,2016-08-11 15:58:48
1,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,AFRICAN CHRISTIAN DEMOCRATIC PARTY,0,2016-08-11 15:58:48
2,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,AFRICAN INDEPENDENT CONGRESS,19,2016-08-11 15:58:48
3,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,AFRICAN MANTUNGWA COMMUNITY,0,2016-08-11 15:58:48
4,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,AFRICAN NATIONAL CONGRESS,1157,2016-08-11 15:58:48
5,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,AFRICAN PEOPLE'S CONVENTION,3,2016-08-11 15:58:48
6,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,AL JAMA-AH,0,2016-08-11 15:58:48
7,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,ALLIED MOVEMENT FOR CHANGE,0,2016-08-11 15:58:48
8,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,AZANIAN PEOPLE'S ORGANISATION,0,2016-08-11 15:58:48
9,KwaZulu-Natal,ETH - eThekwini,Ward 59500001,43400179,NOMFIHLELA PRIMARY SCHOOL,1607,PR,72,CONGRESS OF THE PEOPLE,0,2016-08-11 15:58:48

,Province,Municipality,Ward,VotingDistrict,VotingStationName,RegisteredVoters,BallotType,SpoiltVotes,PartyName,TotalValidVotes,DateGenerated
40696,KwaZulu-Natal,ETH - eThekwini,Ward 59500110,43362288,MT ROYAL PRIMARY SCHOOL,2466,Ward,31,ECONOMIC FREEDOM FIGHTERS,22,2016-08-11 15:58:48
40697,KwaZulu-Natal,ETH - eThekwini,Ward 59500110,43362288,MT ROYAL PRIMARY SCHOOL,2466,Ward,31,INDEPENDENT,460,2016-08-11 15:58:48
40698,KwaZulu-Natal,ETH - eThekwini,Ward 59500110,43362288,MT ROYAL PRIMARY SCHOOL,2466,Ward,31,INDEPENDENT RATEPAYERS ASSOCIATION OF SA,0,2016-08-11 15:58:48
40699,KwaZulu-Natal,ETH - eThekwini,Ward 59500110,43362288,MT ROYAL PRIMARY SCHOOL,2466,Ward,31,INKATHA FREEDOM PARTY,19,2016-08-11 15:58:48
40700,KwaZulu-Natal,ETH - eThekwini,Ward 59500110,43362288,MT ROYAL PRIMARY SCHOOL,2466,Ward,31,MINORITIES OF SOUTH AFRICA,1,2016-08-11 15:58:48
40701,KwaZulu-Natal,ETH - eThekwini,Ward 59500110,43362288,MT ROYAL PRIMARY SCHOOL,2466,Ward,31,MINORITY FRONT,0,2016-08-11 15:58:48
40702,KwaZulu-Natal,ETH - eThekwini,Ward 59500110,43362288,MT ROYAL PRIMARY SCHOOL,2466,Ward,31,PAN AFRICANIST CONGRESS OF AZANIA,0,2016-08-11 15:58:48
40703,KwaZulu-Natal,ETH - eThekwini,Ward 59500110,43362288,MT ROYAL PRIMARY SCHOOL,2466,Ward,31,TRULY ALLIANCE,1,2016-08-11 15:58:48
40704,KwaZulu-Natal,ETH - eThekwini,Ward 59500110,43362288,MT ROYAL PRIMARY SCHOOL,2466,Ward,31,UNITED PEOPLES PARTY,1,2016-08-11 15:58:48
40705,KwaZulu-Natal,ETH - eThekwini,Ward 59500110,43362288,MT ROYAL PRIMARY SCHOOL,2466,Ward,31,VRYHEIDSFRONT PLUS,0,2016-08-11 15:58:48

In [121]:
print(df["Province"].value_counts())

Province
KwaZulu-Natal    40706
Name: count, dtype: int64

In [122]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
40701    False
40702    False
40703    False
40704    False
40705    False
Length: 40706, dtype: bool

In [123]:
print(
    "Unique voting districts:",
    df["VotingDistrict"].nunique()
)

print(
    "Total rows:",
    len(df)
)

Unique voting districts: 866
Total rows: 40706

In [124]:
party_rows = df.groupby(
    ["VotingDistrict", "PartyName"]
).size()

print("Duplicate VotingDistrict + PartyName combinations:")
print(party_rows[party_rows > 1].head(20))

Duplicate VotingDistrict + PartyName combinations:
VotingDistrict  PartyName
43350016        ACADEMIC CONGRESS UNION                     2
                AFRICAN CHRISTIAN DEMOCRATIC PARTY          2
                AFRICAN INDEPENDENT CONGRESS                2
                AFRICAN NATIONAL CONGRESS                   2
                AFRICAN PEOPLE'S CONVENTION                 2
                AL JAMA-AH                                  2
                ALLIED MOVEMENT FOR CHANGE                  2
                AZANIAN PEOPLE'S ORGANISATION               2
                DEMOCRATIC ALLIANCE                         2
                DEMOCRATIC LIBERAL CONGRESS                 2
                ECONOMIC FREEDOM FIGHTERS                   2
                INDEPENDENT RATEPAYERS ASSOCIATION OF SA    2
                INKATHA FREEDOM PARTY                       2
                MINORITIES OF SOUTH AFRICA                  2
                MINORITY FRONT                              2
                PAN AFRICANIST CONGRESS OF AZANIA           2
                TRULY ALLIANCE                              2
                UNITED PEOPLES PARTY                        2
                VRYHEIDSFRONT PLUS                          2
43350027        ACADEMIC CONGRESS UNION                     2
dtype: int64

In [125]:
print("===== WARD CODES =====")
print(df["Ward"].head(20).tolist())
print(df["Ward"].astype(str).str.len().value_counts())

print("\n===== MUNICIPALITIES =====")
print(df["Municipality"].nunique())
for x in sorted(df["Municipality"].unique()):
    print(repr(x))

print("\n===== PARTIES =====")
print(df["PartyName"].nunique())
for x in sorted(df["PartyName"].unique()):
    print(repr(x))

print("\n===== BALLOT TYPES =====")
print(df["BallotType"].value_counts())

print("\n===== DATES =====")
print(df["DateGenerated"].unique())

print("\n===== NUMERIC CHECK =====")
for column in numeric_columns:
    print(
        column,
        "| min:", df[column].min(),
        "| max:", df[column].max(),
        "| negative:", (df[column] < 0).sum()
    )

print("\n===== SIZE =====")
print("Rows:", len(df))
print("Voting districts:", df["VotingDistrict"].nunique())

===== WARD CODES =====
['Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001']
Ward
13    40706
Name: count, dtype: int64

===== MUNICIPALITIES =====
1
'ETH - eThekwini'

===== PARTIES =====
28
'ACADEMIC CONGRESS UNION'
'AFRICAN CHRISTIAN DEMOCRATIC PARTY'
'AFRICAN INDEPENDENT CONGRESS'
'AFRICAN MANTUNGWA COMMUNITY'
'AFRICAN NATIONAL CONGRESS'
"AFRICAN PEOPLE'S CONVENTION"
'AL JAMA-AH'
'ALLIED MOVEMENT FOR CHANGE'
"AZANIAN PEOPLE'S ORGANISATION"
'CONGRESS  OF THE PEOPLE'
'DEMOCRATIC ALLIANCE'
'DEMOCRATIC LIBERAL CONGRESS'
'ECONOMIC FREEDOM FIGHTERS'
'INDEPENDENT'
"INDEPENDENT PEOPLE'S PARTY"
'INDEPENDENT RATEPAYERS ASSOCIATION OF SA'
'INKATHA FREEDOM PARTY'
'MINORITIES OF SOUTH AFRICA'
'MINORITY FRONT'
'PAN AFRICANIST CONGRESS OF AZANIA'
"PEOPLE'S REVOLUTIONARY MOVEMENT"
'SOUTH AFRICAN POLITICAL PARTY'
'THE PROMISE OF FREEDOM'
'TRULY ALLIANCE'
'UNITED DEMOCRATIC MOVEMENT'
'UNITED PEOPLES PARTY'
'UNITED RESIDENTS FRONT'
'VRYHEIDSFRONT PLUS'

===== BALLOT TYPES =====
BallotType
PR      23382
Ward    17324
Name: count, dtype: int64

===== DATES =====
<DatetimeArray>
['2016-08-11 15:58:48']
Length: 1, dtype: datetime64[us]

===== NUMERIC CHECK =====
VotingDistrict | min: 43350016 | max: 44070072 | negative: 0
RegisteredVoters | min: 101 | max: 8099 | negative: 0
SpoiltVotes | min: 0 | max: 993 | negative: 0
TotalValidVotes | min: 0 | max: 4175 | negative: 0

===== SIZE =====
Rows: 40706
Voting districts: 866

In [126]:
# Make a copy so we don't accidentally modify the original dataframe
clean_df = df.copy()

# --------------------------------------------------
# 1. Clean column names
# --------------------------------------------------

clean_df.columns = (
    clean_df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

print(clean_df.columns.tolist())

['province', 'municipality', 'ward', 'votingdistrict', 'votingstationname', 'registeredvoters', 'ballottype', 'spoiltvotes', 'partyname', 'totalvalidvotes', 'dategenerated']

In [127]:
clean_df = clean_df.rename(columns={
    "votingdistrict": "voting_district",
    "votingstationname": "voting_station_name",
    "registeredvoters": "registered_voters",
    "ballottype": "ballot_type",
    "spoiltvotes": "spoilt_votes",
    "partyname": "party_name",
    "totalvalidvotes": "total_valid_votes",
    "dategenerated": "date_generated"
})

print(clean_df.columns.tolist())

['province', 'municipality', 'ward', 'voting_district', 'voting_station_name', 'registered_voters', 'ballot_type', 'spoilt_votes', 'party_name', 'total_valid_votes', 'date_generated']

In [128]:
text_columns = [
    "province",
    "municipality",
    "ward",
    "voting_station_name",
    "ballot_type",
    "party_name"
]

for column in text_columns:
    clean_df[column] = (
        clean_df[column]
        .astype(str)
        .str.strip()
    )

In [129]:
print("Unique parties:", clean_df["party_name"].nunique())

for party in sorted(clean_df["party_name"].unique()):
    print(repr(party))

Unique parties: 28
'ACADEMIC CONGRESS UNION'
'AFRICAN CHRISTIAN DEMOCRATIC PARTY'
'AFRICAN INDEPENDENT CONGRESS'
'AFRICAN MANTUNGWA COMMUNITY'
'AFRICAN NATIONAL CONGRESS'
"AFRICAN PEOPLE'S CONVENTION"
'AL JAMA-AH'
'ALLIED MOVEMENT FOR CHANGE'
"AZANIAN PEOPLE'S ORGANISATION"
'CONGRESS  OF THE PEOPLE'
'DEMOCRATIC ALLIANCE'
'DEMOCRATIC LIBERAL CONGRESS'
'ECONOMIC FREEDOM FIGHTERS'
'INDEPENDENT'
"INDEPENDENT PEOPLE'S PARTY"
'INDEPENDENT RATEPAYERS ASSOCIATION OF SA'
'INKATHA FREEDOM PARTY'
'MINORITIES OF SOUTH AFRICA'
'MINORITY FRONT'
'PAN AFRICANIST CONGRESS OF AZANIA'
"PEOPLE'S REVOLUTIONARY MOVEMENT"
'SOUTH AFRICAN POLITICAL PARTY'
'THE PROMISE OF FREEDOM'
'TRULY ALLIANCE'
'UNITED DEMOCRATIC MOVEMENT'
'UNITED PEOPLES PARTY'
'UNITED RESIDENTS FRONT'
'VRYHEIDSFRONT PLUS'

In [130]:
clean_df["ward"] = clean_df["ward"].astype(str).str.strip()

In [131]:
print(clean_df["ward"].head(20).tolist())
print(clean_df["ward"].astype(str).str.len().value_counts())

['Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001', 'Ward 59500001']
ward
13    40706
Name: count, dtype: int64

In [132]:
numeric_columns = [
    "voting_district",
    "registered_voters",
    "spoilt_votes",
    "total_valid_votes"
]

for column in numeric_columns:
    clean_df[column] = pd.to_numeric(
        clean_df[column],
        errors="coerce"
    )

print(clean_df[numeric_columns].dtypes)

voting_district      int64
registered_voters    int64
spoilt_votes         int64
total_valid_votes    int64
dtype: object

In [133]:
print(clean_df[numeric_columns].sum())

voting_district      1767476998181
registered_voters         90295784
spoilt_votes               1217817
total_valid_votes          2225605
dtype: int64

In [134]:
clean_df["date_generated"] = pd.to_datetime(
    clean_df["date_generated"],
    errors="coerce"
)

print(clean_df["date_generated"].dtype)
print(clean_df["date_generated"].isna().sum())

datetime64[us]
0

In [135]:
clean_df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
40701    False
40702    False
40703    False
40704    False
40705    False
Length: 40706, dtype: bool

In [136]:
key_columns = [
    "voting_district",
    "ballot_type",
    "party_name"
]

duplicates = clean_df[
    clean_df.duplicated(
        subset=key_columns,
        keep=False
    )
]

print("Logical duplicates:", len(duplicates))

display(duplicates.head(20))

Logical duplicates: 0

Empty DataFrame
Columns: [province, municipality, ward, voting_district, voting_station_name, registered_voters, ballot_type, spoilt_votes, party_name, total_valid_votes, date_generated]
Index: []

In [137]:
print(clean_df.head())
print(clean_df.tail())

        province     municipality           ward  voting_district  \
0  KwaZulu-Natal  ETH - eThekwini  Ward 59500001         43400179
1  KwaZulu-Natal  ETH - eThekwini  Ward 59500001         43400179
2  KwaZulu-Natal  ETH - eThekwini  Ward 59500001         43400179
3  KwaZulu-Natal  ETH - eThekwini  Ward 59500001         43400179
4  KwaZulu-Natal  ETH - eThekwini  Ward 59500001         43400179

         voting_station_name  registered_voters ballot_type  spoilt_votes  \
0  NOMFIHLELA PRIMARY SCHOOL               1607          PR            72
1  NOMFIHLELA PRIMARY SCHOOL               1607          PR            72
2  NOMFIHLELA PRIMARY SCHOOL               1607          PR            72
3  NOMFIHLELA PRIMARY SCHOOL               1607          PR            72
4  NOMFIHLELA PRIMARY SCHOOL               1607          PR            72

                           party_name  total_valid_votes      date_generated
0             ACADEMIC CONGRESS UNION                  0 2016-08-11 15:58:48
1  AFRICAN CHRISTIAN DEMOCRATIC PARTY                  0 2016-08-11 15:58:48
2        AFRICAN INDEPENDENT CONGRESS                 19 2016-08-11 15:58:48
3         AFRICAN MANTUNGWA COMMUNITY                  0 2016-08-11 15:58:48
4           AFRICAN NATIONAL CONGRESS               1157 2016-08-11 15:58:48
            province     municipality           ward  voting_district  \
40701  KwaZulu-Natal  ETH - eThekwini  Ward 59500110         43362288
40702  KwaZulu-Natal  ETH - eThekwini  Ward 59500110         43362288
40703  KwaZulu-Natal  ETH - eThekwini  Ward 59500110         43362288
40704  KwaZulu-Natal  ETH - eThekwini  Ward 59500110         43362288
40705  KwaZulu-Natal  ETH - eThekwini  Ward 59500110         43362288

           voting_station_name  registered_voters ballot_type  spoilt_votes  \
40701  MT ROYAL PRIMARY SCHOOL               2466        Ward            31
40702  MT ROYAL PRIMARY SCHOOL               2466        Ward            31
40703  MT ROYAL PRIMARY SCHOOL               2466        Ward            31
40704  MT ROYAL PRIMARY SCHOOL               2466        Ward            31
40705  MT ROYAL PRIMARY SCHOOL               2466        Ward            31

                              party_name  total_valid_votes  \
40701                     MINORITY FRONT                  0
40702  PAN AFRICANIST CONGRESS OF AZANIA                  0
40703                     TRULY ALLIANCE                  1
40704               UNITED PEOPLES PARTY                  1
40705                 VRYHEIDSFRONT PLUS                  0

           date_generated
40701 2016-08-11 15:58:48
40702 2016-08-11 15:58:48
40703 2016-08-11 15:58:48
40704 2016-08-11 15:58:48
40705 2016-08-11 15:58:48

In [138]:
for column in ["province", "municipality", "ballot_type"]:
    print(f"\n{column}:")
    print(clean_df[column].value_counts().head(20))

province:
province
KwaZulu-Natal    40706
Name: count, dtype: int64

municipality:
municipality
ETH - eThekwini    40706
Name: count, dtype: int64

ballot_type:
ballot_type
PR      23382
Ward    17324
Name: count, dtype: int64

In [139]:
print("========== FINAL CLEANING CHECK ==========")

print("\nShape:")
print(clean_df.shape)

print("\nMissing values:")
print(clean_df.isna().sum())

print("\nExact duplicates:")
print(clean_df.duplicated().sum())

print("\nLogical duplicates:")
print(
    clean_df.duplicated(
        subset=["voting_district", "ballot_type", "party_name"]
    ).sum()
)

print("\nData types:")
print(clean_df.dtypes)

========== FINAL CLEANING CHECK ==========

Shape:
(40706, 11)

Missing values:
province               0
municipality           0
ward                   0
voting_district        0
voting_station_name    0
registered_voters      0
ballot_type            0
spoilt_votes           0
party_name             0
total_valid_votes      0
date_generated         0
dtype: int64

Exact duplicates:
0

Logical duplicates:
0

Data types:
province                          str
municipality                      str
ward                              str
voting_district                 int64
voting_station_name               str
registered_voters               int64
ballot_type                       str
spoilt_votes                    int64
party_name                        str
total_valid_votes               int64
date_generated         datetime64[us]
dtype: object

In [140]:
from pathlib import Path

interim_folder = Path(
    "../data/interim/KZN_Voter_Turnout_Predictor_2016-2022"
)

interim_folder.mkdir(
    parents=True,
    exist_ok=True
)

In [141]:
interim_file = (
    interim_folder /
    "IEC_2016_Municipal_Results.csv"
)

clean_df.to_csv(
    interim_file,
    index=False
)

print("Saved cleaned file to:")
print(interim_file.resolve())

Saved cleaned file to:
C:\Users\Admin\PycharmProjects\SPU-TEAM-DIRISA\data\interim\KZN_Voter_Turnout_Predictor_2016-2022\IEC_2016_Municipal_Results.csv

In [142]:
notes_file = (
    interim_folder /
    "IEC_2016_Municipal_Results_cleaning_notes.txt"
)

notes = """IEC 2016 Municipal Results - Cleaning Notes

1. Missing values:
- No missing values were found in the supplied dataset.

2. Inconsistent formats:
- Column names standardized to lowercase snake_case.
- Leading/trailing whitespace removed from text fields.
- Party names retained as supplied because no confirmed spelling inconsistencies were identified.

3. Data types:
- Voting district, registered voters, spoilt votes and total valid votes confirmed/converted to numeric.
- Ward retained as text to prevent possible loss of leading zeros.
- DateGenerated converted to datetime.

4. Duplicates and junk rows:
- No exact duplicate rows were found.
- Logical duplicates were checked using VotingDistrict + BallotType + PartyName.
- PR and Ward ballot types were retained because they represent different ballot types.
- No confirmed junk rows were removed.

5. Known limitation:
- Ward boundaries changed between local government elections. A ward code from 2016 should not automatically be assumed to represent the same geographic area in another election year.
"""

notes_file.write_text(notes, encoding="utf-8")

print("Cleaning notes saved to:")
print(notes_file.resolve())

Cleaning notes saved to:
C:\Users\Admin\PycharmProjects\SPU-TEAM-DIRISA\data\interim\KZN_Voter_Turnout_Predictor_2016-2022\IEC_2016_Municipal_Results_cleaning_notes.txt