# Data Cleaning: KZN Socioeconomic and Political Distrust 2011–2023

This notebook cleans and validates the KwaZulu-Natal socioeconomic and political distrust datasets.

The raw files are kept unchanged in `data/raw/`. The cleaned versions are saved separately in `data/interim/`.

The cleaning process checks for:
- File structure
- Missing values
- Blank values
- Duplicate records
- Inconsistent formats
- Data types
- Year consistency
- Province and location values
- Invalid or unexpected values
- Preservation of records after cleaning

In [1]:
import pandas as pd
from pathlib import Path

In [2]:
# Notebook location:
# SPU-TEAM-DIRISA/notebooks/Data Collection/

project_root = Path("../..")

raw_folder = (
    project_root
    / "data"
    / "raw"
    / "KZN-Socioeconomic-Political-Distrust-2011-2023"
)

interim_folder = (
    project_root
    / "data"
    / "interim"
    / "KZN-Socioeconomic-Political-Distrust-2011-2023"
)

interim_folder.mkdir(parents=True, exist_ok=True)

print("Raw folder:", raw_folder)
print("Raw folder exists:", raw_folder.exists())
print("Interim folder:", interim_folder)

Raw folder: ..\..\data\raw\KZN-Socioeconomic-Political-Distrust-2011-2023
Raw folder exists: True
Interim folder: ..\..\data\interim\KZN-Socioeconomic-Political-Distrust-2011-2023

In [3]:
raw_files = sorted(
    [file for file in raw_folder.iterdir() if file.is_file()]
)

print("Number of files:", len(raw_files))

for file in raw_files:
    print(file.name)

Number of files: 2
KZN_IEC_HSRC_Youth_Distrust_2023_long.csv
KZN_StatsSA_Socioeconomic_Indicators_2011_2023.csv

In [4]:
# Load the two datasets

dataframes = {}

for file in raw_files:

    if file.suffix.lower() == ".csv":
        df = pd.read_csv(file)
    
    elif file.suffix.lower() in [".xlsx", ".xls"]:
        df = pd.read_excel(file)
    
    else:
        print("Unsupported file type:", file.name)
        continue

    dataframes[file.name] = df

    print("\nFile:", file.name)
    print("Rows:", len(df))
    print("Columns:", len(df.columns))

File: KZN_IEC_HSRC_Youth_Distrust_2023_long.csv
Rows: 5
Columns: 6

File: KZN_StatsSA_Socioeconomic_Indicators_2011_2023.csv
Rows: 30
Columns: 7

In [5]:
for file_name, df in dataframes.items():

    print("\n" + "=" * 80)
    print("FILE:", file_name)
    print("=" * 80)

    print("\nColumns:")
    for number, column in enumerate(df.columns, start=1):
        print(f"{number}. {column}")

    print("\nFirst 5 rows:")
    display(df.head())

================================================================================
FILE: KZN_IEC_HSRC_Youth_Distrust_2023_long.csv
================================================================================

Columns:
1. geography
2. year
3. indicator
4. value
5. unit
6. source

First 5 rows:

,geography,year,indicator,value,unit,source
0,KwaZulu-Natal,2023,Dissatisfied with democracy,85.0,%,"IEC/HSRC Online Youth Survey 2023 (n=5,086, ag..."
1,KwaZulu-Natal,2023,Distrust of national government,83.0,%,"IEC/HSRC Online Youth Survey 2023 (n=5,086, ag..."
2,KwaZulu-Natal,2023,Distrust of provincial government,80.0,%,"IEC/HSRC Online Youth Survey 2023 (n=5,086, ag..."
3,KwaZulu-Natal,2023,Distrust of political parties,77.0,%,"IEC/HSRC Online Youth Survey 2023 (n=5,086, ag..."
4,KwaZulu-Natal,2023,Distrust of the IEC,55.0,%,"IEC/HSRC Online Youth Survey 2023 (n=5,086, ag..."

================================================================================
FILE: KZN_StatsSA_Socioeconomic_Indicators_2011_2023.csv
================================================================================

Columns:
1. geography_level
2. geography_name
3. indicator
4. year
5. value
6. unit
7. source

First 5 rows:

,geography_level,geography_name,indicator,year,value,unit,source
0,Province,KwaZulu-Natal,"Poverty headcount (P0, %)",2011,56.9,%,StatsSA Poverty Trends (LBPL) by Province
1,Province,KwaZulu-Natal,"Poverty headcount (P0, %)",2015,59.6,%,StatsSA Poverty Trends (LBPL) by Province
2,Province,KwaZulu-Natal,"Poverty headcount (P0, %)",2023,49.6,%,StatsSA Poverty Trends (LBPL) by Province
3,Province,KwaZulu-Natal,"Poverty gap (P1, %)",2011,25.9,%,StatsSA Poverty Trends (LBPL) by Province
4,Province,KwaZulu-Natal,"Poverty gap (P1, %)",2015,27.1,%,StatsSA Poverty Trends (LBPL) by Province

In [6]:
# Check the structure of each dataset

for file_name, df in dataframes.items():

    print("\n" + "=" * 80)
    print("FILE:", file_name)
    print("=" * 80)

    print("Number of rows:", len(df))
    print("Number of columns:", len(df.columns))
    print("Column names and data types:")

    display(
        pd.DataFrame({
            "column": df.columns,
            "data_type": df.dtypes.astype(str).values
        })
    )

================================================================================
FILE: KZN_IEC_HSRC_Youth_Distrust_2023_long.csv
================================================================================
Number of rows: 5
Number of columns: 6
Column names and data types:

      column data_type
0  geography       str
1       year     int64
2  indicator       str
3      value   float64
4       unit       str
5     source       str

================================================================================
FILE: KZN_StatsSA_Socioeconomic_Indicators_2011_2023.csv
================================================================================
Number of rows: 30
Number of columns: 7
Column names and data types:

            column data_type
0  geography_level       str
1   geography_name       str
2        indicator       str
3             year     int64
4            value   float64
5             unit       str
6           source       str

In [7]:
# Check for missing values

for file_name, df in dataframes.items():

    print("\n" + "=" * 80)
    print("FILE:", file_name)
    print("=" * 80)

    missing = df.isnull().sum()

    display(missing.to_frame("missing_values"))

    print("Total missing values:", missing.sum())

================================================================================
FILE: KZN_IEC_HSRC_Youth_Distrust_2023_long.csv
================================================================================

           missing_values
geography               0
year                    0
indicator               0
value                   0
unit                    0
source                  0

Total missing values: 0

================================================================================
FILE: KZN_StatsSA_Socioeconomic_Indicators_2011_2023.csv
================================================================================

                 missing_values
geography_level               0
geography_name                0
indicator                     0
year                          0
value                         0
unit                          0
source                        0

Total missing values: 0

In [8]:
# Check for blank or empty values

for file_name, df in dataframes.items():

    print("\n" + "=" * 80)
    print("FILE:", file_name)
    print("=" * 80)

    blank_counts = {}

    for column in df.columns:

        if df[column].dtype == "object":
            blank_counts[column] = (
                df[column]
                .astype(str)
                .str.strip()
                .eq("")
                .sum()
            )
        else:
            blank_counts[column] = 0

    blank_counts = pd.Series(blank_counts)

    display(blank_counts.to_frame("blank_values"))

    print("Total blank values:", blank_counts.sum())

================================================================================
FILE: KZN_IEC_HSRC_Youth_Distrust_2023_long.csv
================================================================================

           blank_values
geography             0
year                  0
indicator             0
value                 0
unit                  0
source                0

Total blank values: 0

================================================================================
FILE: KZN_StatsSA_Socioeconomic_Indicators_2011_2023.csv
================================================================================

                 blank_values
geography_level             0
geography_name              0
indicator                   0
year                        0
value                       0
unit                        0
source                      0

Total blank values: 0

In [10]:
# Check for duplicate complete records

for file_name, df in dataframes.items():

    duplicate_count = df.duplicated().sum()

    print(
        file_name,
        "| Duplicate complete records:",
        duplicate_count
    )

KZN_IEC_HSRC_Youth_Distrust_2023_long.csv | Duplicate complete records: 0
KZN_StatsSA_Socioeconomic_Indicators_2011_2023.csv | Duplicate complete records: 0

In [11]:
# Check for unnecessary spaces in text values

for file_name, df in dataframes.items():

    print("\n" + "=" * 80)
    print("FILE:", file_name)
    print("=" * 80)

    for column in df.select_dtypes(include="object").columns:

        spaces = (
            df[column]
            .astype(str)
            .ne(df[column].astype(str).str.strip())
            .sum()
        )

        print(
            f"{column} | Values with leading/trailing spaces: {spaces}"
        )

================================================================================
FILE: KZN_IEC_HSRC_Youth_Distrust_2023_long.csv
================================================================================
geography | Values with leading/trailing spaces: 0
indicator | Values with leading/trailing spaces: 0
unit | Values with leading/trailing spaces: 0
source | Values with leading/trailing spaces: 0

================================================================================
FILE: KZN_StatsSA_Socioeconomic_Indicators_2011_2023.csv
================================================================================
geography_level | Values with leading/trailing spaces: 0
geography_name | Values with leading/trailing spaces: 0
indicator | Values with leading/trailing spaces: 0
unit | Values with leading/trailing spaces: 0
source | Values with leading/trailing spaces: 0

C:\Users\Admin\AppData\Local\Temp\ipykernel_35552\451504164.py:9: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for column in df.select_dtypes(include="object").columns:
C:\Users\Admin\AppData\Local\Temp\ipykernel_35552\451504164.py:9: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for column in df.select_dtypes(include="object").columns:

In [13]:
# Check unique values in text columns

for file_name, df in dataframes.items():

    print("\n" + "=" * 80)
    print("FILE:", file_name)
    print("=" * 80)

    for column in df.select_dtypes(include="str").columns:

        unique_values = df[column].dropna().unique()

        print(f"\n{column}")
        print("Number of unique values:", len(unique_values))

        for value in sorted(unique_values.astype(str)):
            print(" -", value)

================================================================================
FILE: KZN_IEC_HSRC_Youth_Distrust_2023_long.csv
================================================================================

geography
Number of unique values: 1
 - KwaZulu-Natal

indicator
Number of unique values: 5
 - Dissatisfied with democracy
 - Distrust of national government
 - Distrust of political parties
 - Distrust of provincial government
 - Distrust of the IEC

unit
Number of unique values: 1
 - %

source
Number of unique values: 1
 - IEC/HSRC Online Youth Survey 2023 (n=5,086, ages 18-35)

================================================================================
FILE: KZN_StatsSA_Socioeconomic_Indicators_2011_2023.csv
================================================================================

geography_level
Number of unique values: 2
 - Metro
 - Province

geography_name
Number of unique values: 2
 - KwaZulu-Natal
 - eThekwini Metropolitan

indicator
Number of unique values: 6
 - Food poverty headcount (FPL, %)
 - Gini coefficient (income per capita)
 - Poverty gap (P1, %)
 - Poverty headcount (P0, %)
 - Poverty share (%)
 - Severity of poverty (P2, %)

unit
Number of unique values: 2
 - %
 - index (0-1)

source
Number of unique values: 4
 - StatsSA Food Poverty Headcount by Province (FPL)
 - StatsSA Income Inequality (Gini)
 - StatsSA Poverty Trends (LBPL) by Province
 - StatsSA Poverty Trends by Metro Municipality

In [14]:
# Inspect numerical columns

for file_name, df in dataframes.items():

    print("\n" + "=" * 80)
    print("FILE:", file_name)
    print("=" * 80)

    numeric_columns = df.select_dtypes(include="number").columns

    if len(numeric_columns) == 0:
        print("No numeric columns detected.")
    else:
        display(df[numeric_columns].describe().T)

================================================================================
FILE: KZN_IEC_HSRC_Youth_Distrust_2023_long.csv
================================================================================

       count    mean        std     min     25%     50%     75%     max
year     5.0  2023.0   0.000000  2023.0  2023.0  2023.0  2023.0  2023.0
value    5.0    76.0  12.124356    55.0    77.0    80.0    83.0    85.0

================================================================================
FILE: KZN_StatsSA_Socioeconomic_Indicators_2011_2023.csv
================================================================================

,count,mean,std,min,25%,50%,75%,max
year,30.0,2016.333333,5.074163,2011.000,2011.00,2015.0,2023.00,2023.0
value,30.0,23.904033,15.278820,0.604,14.85,24.2,28.65,59.6

In [15]:
# Check columns that appear to contain year information

for file_name, df in dataframes.items():

    print("\n" + "=" * 80)
    print("FILE:", file_name)
    print("=" * 80)

    year_columns = [
        column
        for column in df.columns
        if "year" in column.lower()
    ]

    if year_columns:
        for column in year_columns:
            print(f"\n{column}")
            print(
                df[column]
                .dropna()
                .unique()
            )
    else:
        print("No column containing 'year' found.")

================================================================================
FILE: KZN_IEC_HSRC_Youth_Distrust_2023_long.csv
================================================================================

year
[2023]

================================================================================
FILE: KZN_StatsSA_Socioeconomic_Indicators_2011_2023.csv
================================================================================

year
[2011 2015 2023]

In [16]:
# Check province and location-related columns

for file_name, df in dataframes.items():

    print("\n" + "=" * 80)
    print("FILE:", file_name)
    print("=" * 80)

    location_columns = [
        column
        for column in df.columns
        if any(
            word in column.lower()
            for word in [
                "province",
                "municipality",
                "district",
                "location",
                "region",
                "area"
            ]
        )
    ]

    if location_columns:

        for column in location_columns:

            print(f"\n{column}")
            print(
                df[column]
                .dropna()
                .astype(str)
                .unique()
            )

    else:
        print("No obvious location-related columns found.")

================================================================================
FILE: KZN_IEC_HSRC_Youth_Distrust_2023_long.csv
================================================================================
No obvious location-related columns found.

================================================================================
FILE: KZN_StatsSA_Socioeconomic_Indicators_2011_2023.csv
================================================================================
No obvious location-related columns found.

In [17]:
# Check geography and location values directly

for file_name, df in dataframes.items():

    print("\n" + "=" * 80)
    print("FILE:", file_name)
    print("=" * 80)

    location_columns = [
        column
        for column in df.columns
        if any(
            word in column.lower()
            for word in [
                "geography",
                "province",
                "municipality",
                "district",
                "location",
                "region",
                "area"
            ]
        )
    ]

    if location_columns:

        for column in location_columns:

            print(f"\n{column}")
            print("Number of unique values:", df[column].nunique())

            values = df[column].dropna().astype(str).unique()

            for value in sorted(values):
                print(" -", value)

    else:
        print("No geography or location-related columns found.")

================================================================================
FILE: KZN_IEC_HSRC_Youth_Distrust_2023_long.csv
================================================================================

geography
Number of unique values: 1
 - KwaZulu-Natal

================================================================================
FILE: KZN_StatsSA_Socioeconomic_Indicators_2011_2023.csv
================================================================================

geography_level
Number of unique values: 2
 - Metro
 - Province

geography_name
Number of unique values: 2
 - KwaZulu-Natal
 - eThekwini Metropolitan

In [18]:
# Look for common indicators of possible junk or formatting problems

possible_problem_values = [
    "",
    " ",
    "N/A",
    "NA",
    "n/a",
    "na",
    "null",
    "NULL",
    "-",
    "--"
]

for file_name, df in dataframes.items():

    print("\n" + "=" * 80)
    print("FILE:", file_name)
    print("=" * 80)

    for column in df.select_dtypes(include="object").columns:

        found = (
            df[column]
            .astype(str)
            .str.strip()
            .isin(possible_problem_values)
            .sum()
        )

        if found > 0:
            print(
                f"{column} | Possible placeholder/junk values: {found}"
            )

================================================================================
FILE: KZN_IEC_HSRC_Youth_Distrust_2023_long.csv
================================================================================

================================================================================
FILE: KZN_StatsSA_Socioeconomic_Indicators_2011_2023.csv
================================================================================

C:\Users\Admin\AppData\Local\Temp\ipykernel_35552\2679837211.py:22: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for column in df.select_dtypes(include="object").columns:
C:\Users\Admin\AppData\Local\Temp\ipykernel_35552\2679837211.py:22: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for column in df.select_dtypes(include="object").columns:

In [19]:
# Check for completely empty rows

for file_name, df in dataframes.items():

    empty_rows = df.isnull().all(axis=1).sum()

    print(
        file_name,
        "| Completely empty rows:",
        empty_rows
    )

KZN_IEC_HSRC_Youth_Distrust_2023_long.csv | Completely empty rows: 0
KZN_StatsSA_Socioeconomic_Indicators_2011_2023.csv | Completely empty rows: 0

In [20]:
# Check for completely empty columns

for file_name, df in dataframes.items():

    empty_columns = df.isnull().all(axis=0)

    print("\n" + "=" * 80)
    print("FILE:", file_name)
    print("=" * 80)

    print(
        "Completely empty columns:",
        empty_columns.sum()
    )

    if empty_columns.any():
        print(
            list(df.columns[empty_columns])
        )

================================================================================
FILE: KZN_IEC_HSRC_Youth_Distrust_2023_long.csv
================================================================================
Completely empty columns: 0

================================================================================
FILE: KZN_StatsSA_Socioeconomic_Indicators_2011_2023.csv
================================================================================
Completely empty columns: 0

In [21]:
# Check text columns for values that appear to be numbers

for file_name, df in dataframes.items():

    print("\n" + "=" * 80)
    print("FILE:", file_name)
    print("=" * 80)

    for column in df.select_dtypes(include="object").columns:

        cleaned_values = (
            df[column]
            .dropna()
            .astype(str)
            .str.strip()
            .str.replace(",", "", regex=False)
        )

        if len(cleaned_values) > 0:

            numeric_conversion = pd.to_numeric(
                cleaned_values,
                errors="coerce"
            )

            numeric_like = numeric_conversion.notna().sum()

            if numeric_like > 0:
                print(
                    f"{column} | Numeric-looking text values: "
                    f"{numeric_like} of {len(cleaned_values)}"
                )

================================================================================
FILE: KZN_IEC_HSRC_Youth_Distrust_2023_long.csv
================================================================================

================================================================================
FILE: KZN_StatsSA_Socioeconomic_Indicators_2011_2023.csv
================================================================================

C:\Users\Admin\AppData\Local\Temp\ipykernel_35552\2410157101.py:9: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for column in df.select_dtypes(include="object").columns:
C:\Users\Admin\AppData\Local\Temp\ipykernel_35552\2410157101.py:9: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for column in df.select_dtypes(include="object").columns:

In [22]:
# Check text columns for values that appear to be numbers

for file_name, df in dataframes.items():

    print("\n" + "=" * 80)
    print("FILE:", file_name)
    print("=" * 80)

    for column in df.select_dtypes(include="object").columns:

        cleaned_values = (
            df[column]
            .dropna()
            .astype(str)
            .str.strip()
            .str.replace(",", "", regex=False)
        )

        if len(cleaned_values) > 0:

            numeric_conversion = pd.to_numeric(
                cleaned_values,
                errors="coerce"
            )

            numeric_like = numeric_conversion.notna().sum()

            if numeric_like > 0:
                print(
                    f"{column} | Numeric-looking text values: "
                    f"{numeric_like} of {len(cleaned_values)}"
                )

================================================================================
FILE: KZN_IEC_HSRC_Youth_Distrust_2023_long.csv
================================================================================

================================================================================
FILE: KZN_StatsSA_Socioeconomic_Indicators_2011_2023.csv
================================================================================

C:\Users\Admin\AppData\Local\Temp\ipykernel_35552\2410157101.py:9: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for column in df.select_dtypes(include="object").columns:
C:\Users\Admin\AppData\Local\Temp\ipykernel_35552\2410157101.py:9: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for column in df.select_dtypes(include="object").columns:

In [23]:
# Create copies for cleaning

cleaned_dataframes = {}

for file_name, df in dataframes.items():

    cleaned_df = df.copy()

    # Remove leading/trailing spaces from text columns
    for column in cleaned_df.select_dtypes(include="object").columns:
        cleaned_df[column] = cleaned_df[column].str.strip()

    cleaned_dataframes[file_name] = cleaned_df

print(
    "Cleaned copies created for:",
    len(cleaned_dataframes),
    "files"
)

Cleaned copies created for: 2 files

C:\Users\Admin\AppData\Local\Temp\ipykernel_35552\2070564372.py:10: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for column in cleaned_df.select_dtypes(include="object").columns:
C:\Users\Admin\AppData\Local\Temp\ipykernel_35552\2070564372.py:10: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for column in cleaned_df.select_dtypes(include="object").columns:

In [24]:
# Save cleaned files to the interim folder

for file_name, cleaned_df in cleaned_dataframes.items():

    output_file = interim_folder / file_name

    if output_file.suffix.lower() == ".csv":
        cleaned_df.to_csv(
            output_file,
            index=False,
            encoding="utf-8"
        )

    elif output_file.suffix.lower() in [".xlsx", ".xls"]:
        cleaned_df.to_excel(
            output_file,
            index=False
        )

    print("Saved:", output_file)

Saved: ..\..\data\interim\KZN-Socioeconomic-Political-Distrust-2011-2023\KZN_IEC_HSRC_Youth_Distrust_2023_long.csv
Saved: ..\..\data\interim\KZN-Socioeconomic-Political-Distrust-2011-2023\KZN_StatsSA_Socioeconomic_Indicators_2011_2023.csv

In [25]:
# Reload the cleaned files

validated_dataframes = {}

for file_name, cleaned_df in cleaned_dataframes.items():

    cleaned_file = interim_folder / file_name

    if cleaned_file.suffix.lower() == ".csv":
        validated_df = pd.read_csv(cleaned_file)

    elif cleaned_file.suffix.lower() in [".xlsx", ".xls"]:
        validated_df = pd.read_excel(cleaned_file)

    validated_dataframes[file_name] = validated_df

    print(
        file_name,
        "| Rows:", len(validated_df),
        "| Columns:", len(validated_df.columns)
    )

KZN_IEC_HSRC_Youth_Distrust_2023_long.csv | Rows: 5 | Columns: 6
KZN_StatsSA_Socioeconomic_Indicators_2011_2023.csv | Rows: 30 | Columns: 7

In [26]:
# Final validation

print("=" * 60)
print("FINAL CLEANING VALIDATION")
print("=" * 60)

for file_name in dataframes:

    original = dataframes[file_name]
    cleaned = validated_dataframes[file_name]

    print("\nFILE:", file_name)

    print("Original rows:", len(original))
    print("Cleaned rows:", len(cleaned))

    print(
        "Rows preserved:",
        len(original) == len(cleaned)
    )

    print(
        "Original columns:",
        len(original.columns)
    )

    print(
        "Cleaned columns:",
        len(cleaned.columns)
    )

    print(
        "Columns preserved:",
        list(original.columns) == list(cleaned.columns)
    )

    print(
        "Missing values after cleaning:",
        cleaned.isnull().sum().sum()
    )

    print(
        "Duplicate records after cleaning:",
        cleaned.duplicated().sum()
    )

============================================================
FINAL CLEANING VALIDATION
============================================================

FILE: KZN_IEC_HSRC_Youth_Distrust_2023_long.csv
Original rows: 5
Cleaned rows: 5
Rows preserved: True
Original columns: 6
Cleaned columns: 6
Columns preserved: True
Missing values after cleaning: 0
Duplicate records after cleaning: 0

FILE: KZN_StatsSA_Socioeconomic_Indicators_2011_2023.csv
Original rows: 30
Cleaned rows: 30
Rows preserved: True
Original columns: 7
Cleaned columns: 7
Columns preserved: True
Missing values after cleaning: 0
Duplicate records after cleaning: 0

In [27]:
# Confirm that every cleaned file exists

print("Expected files:", len(raw_files))

saved_files = sorted(
    [file for file in interim_folder.iterdir() if file.is_file()]
)

print("Saved files:", len(saved_files))

for file in saved_files:
    print(file.name)

Expected files: 2
Saved files: 2
KZN_IEC_HSRC_Youth_Distrust_2023_long.csv
KZN_StatsSA_Socioeconomic_Indicators_2011_2023.csv