# Data Cleaning: Voter Registration KZN

This notebook cleans and validates the KwaZulu-Natal voter registration dataset.

The raw files are kept unchanged in `data/raw/`. The cleaned files are saved separately in `data/interim/`.

The cleaning process checks for:
- Missing values
- Incorrect data types and number formatting
- Duplicate ward records
- Duplicate complete records
- Invalid ward codes
- Invalid voting district counts
- Invalid registered voter counts
- Preservation of records after cleaning
- Consistency between the raw and cleaned files

In [1]:
import pandas as pd
from pathlib import Path

In [2]:
# Notebook location:
# SPU-TEAM-DIRISA/notebooks/Data Collection/

project_root = Path("../..")

raw_folder = (
    project_root
    / "data"
    / "raw"
    / "Voter Registration_KZN"
)

interim_folder = (
    project_root
    / "data"
    / "interim"
    / "Voter Registration_KZN_cleaned"
)

interim_folder.mkdir(parents=True, exist_ok=True)

print("Raw folder:", raw_folder)
print("Raw folder exists:", raw_folder.exists())
print("Interim folder:", interim_folder)

Raw folder: ..\..\data\raw\Voter Registration_KZN
Raw folder exists: True
Interim folder: ..\..\data\interim\Voter Registration_KZN_cleaned

In [3]:
raw_files = sorted(raw_folder.glob("*.csv"))

print("Number of raw CSV files:", len(raw_files))

for file in raw_files:
    print(file.name)

Number of raw CSV files: 44
iec_kzn_ethekwini_ward_registration_2026.csv
iec_kzn_kzn212___umdoni_ward_registration_2026.csv
iec_kzn_kzn213___umzumbe_ward_registration_2026.csv
iec_kzn_kzn214___umuziwabantu_ward_registration_2026.csv
iec_kzn_kzn216___ray_nkonyeni_ward_registration_2026.csv
iec_kzn_kzn221___umshwathi_ward_registration_2026.csv
iec_kzn_kzn222___umngeni_ward_registration_2026.csv
iec_kzn_kzn223___mpofana_ward_registration_2026.csv
iec_kzn_kzn224___impendle_ward_registration_2026.csv
iec_kzn_kzn225___msunduzi_ward_registration_2026.csv
iec_kzn_kzn226___mkhambathini_ward_registration_2026.csv
iec_kzn_kzn227___richmond_ward_registration_2026.csv
iec_kzn_kzn235___okhahlamba_ward_registration_2026.csv
iec_kzn_kzn237___inkosi_langalibalele_ward_registration_2026.csv
iec_kzn_kzn238___alfred_duma_ward_registration_2026.csv
iec_kzn_kzn241___endumeni_ward_registration_2026.csv
iec_kzn_kzn242___nqutu_ward_registration_2026.csv
iec_kzn_kzn244___umsinga_ward_registration_2026.csv
iec_kzn_kzn245___umvoti_ward_registration_2026.csv
iec_kzn_kzn252___newcastle_ward_registration_2026.csv
iec_kzn_kzn253___emadlangeni_ward_registration_2026.csv
iec_kzn_kzn254___dannhauser_ward_registration_2026.csv
iec_kzn_kzn261___edumbe_ward_registration_2026.csv
iec_kzn_kzn262___uphongolo_ward_registration_2026.csv
iec_kzn_kzn263___abaqulusi_ward_registration_2026.csv
iec_kzn_kzn265___nongoma_ward_registration_2026.csv
iec_kzn_kzn266___ulundi_ward_registration_2026.csv
iec_kzn_kzn271___umhlabuyalingana_ward_registration_2026.csv
iec_kzn_kzn272___jozini_ward_registration_2026.csv
iec_kzn_kzn275___inkosi_umtubatuba_ward_registration_2026.csv
iec_kzn_kzn276___big_five_hlabisa_ward_registration_2026.csv
iec_kzn_kzn281___umfolozi_ward_registration_2026.csv
iec_kzn_kzn282___umhlathuze_ward_registration_2026.csv
iec_kzn_kzn284___umlalazi_ward_registration_2026.csv
iec_kzn_kzn285___mthonjaneni_ward_registration_2026.csv
iec_kzn_kzn286___nkandla_ward_registration_2026.csv
iec_kzn_kzn291___mandeni_ward_registration_2026.csv
iec_kzn_kzn292___kwadukuza_ward_registration_2026.csv
iec_kzn_kzn293___ndwedwe_ward_registration_2026.csv
iec_kzn_kzn294___maphumulo_ward_registration_2026.csv
iec_kzn_kzn433___greater_kokstad_ward_registration_2026.csv
iec_kzn_kzn434___johannes_phumani_pungula_ward_registration_2026.csv
iec_kzn_kzn435___umzimkhulu_ward_registration_2026.csv
iec_kzn_kzn436___dr._nkosazana_dlamini_zuma_ward_registration_2026.csv

In [4]:
file_structure = []

for file in raw_files:
    df = pd.read_csv(file)

    file_structure.append({
        "file": file.name,
        "rows": len(df),
        "columns": len(df.columns),
        "column_names": list(df.columns)
    })

structure_df = pd.DataFrame(file_structure)

structure_df

,file,rows,columns,column_names
0,iec_kzn_ethekwini_ward_registration_2026.csv,112,3,"[ward, voting_districts, registered_voters]"
1,iec_kzn_kzn212___umdoni_ward_registration_2026...,19,3,"[ward, voting_districts, registered_voters]"
2,iec_kzn_kzn213___umzumbe_ward_registration_202...,20,3,"[ward, voting_districts, registered_voters]"
3,iec_kzn_kzn214___umuziwabantu_ward_registratio...,11,3,"[ward, voting_districts, registered_voters]"
4,iec_kzn_kzn216___ray_nkonyeni_ward_registratio...,36,3,"[ward, voting_districts, registered_voters]"
5,iec_kzn_kzn221___umshwathi_ward_registration_2...,14,3,"[ward, voting_districts, registered_voters]"
6,iec_kzn_kzn222___umngeni_ward_registration_202...,13,3,"[ward, voting_districts, registered_voters]"
7,iec_kzn_kzn223___mpofana_ward_registration_202...,6,3,"[ward, voting_districts, registered_voters]"
8,iec_kzn_kzn224___impendle_ward_registration_20...,6,3,"[ward, voting_districts, registered_voters]"
9,iec_kzn_kzn225___msunduzi_ward_registration_20...,41,3,"[ward, voting_districts, registered_voters]"
10,iec_kzn_kzn226___mkhambathini_ward_registratio...,10,3,"[ward, voting_districts, registered_voters]"
11,iec_kzn_kzn227___richmond_ward_registration_20...,9,3,"[ward, voting_districts, registered_voters]"
12,iec_kzn_kzn235___okhahlamba_ward_registration_...,15,3,"[ward, voting_districts, registered_voters]"
13,iec_kzn_kzn237___inkosi_langalibalele_ward_reg...,24,3,"[ward, voting_districts, registered_voters]"
14,iec_kzn_kzn238___alfred_duma_ward_registration...,37,3,"[ward, voting_districts, registered_voters]"
15,iec_kzn_kzn241___endumeni_ward_registration_20...,8,3,"[ward, voting_districts, registered_voters]"
16,iec_kzn_kzn242___nqutu_ward_registration_2026.csv,20,3,"[ward, voting_districts, registered_voters]"
17,iec_kzn_kzn244___umsinga_ward_registration_202...,21,3,"[ward, voting_districts, registered_voters]"
18,iec_kzn_kzn245___umvoti_ward_registration_2026...,14,3,"[ward, voting_districts, registered_voters]"
19,iec_kzn_kzn252___newcastle_ward_registration_2...,36,3,"[ward, voting_districts, registered_voters]"
20,iec_kzn_kzn253___emadlangeni_ward_registration...,6,3,"[ward, voting_districts, registered_voters]"
21,iec_kzn_kzn254___dannhauser_ward_registration_...,13,3,"[ward, voting_districts, registered_voters]"
22,iec_kzn_kzn261___edumbe_ward_registration_2026...,10,3,"[ward, voting_districts, registered_voters]"
23,iec_kzn_kzn262___uphongolo_ward_registration_2...,15,3,"[ward, voting_districts, registered_voters]"
24,iec_kzn_kzn263___abaqulusi_ward_registration_2...,24,3,"[ward, voting_districts, registered_voters]"
25,iec_kzn_kzn265___nongoma_ward_registration_202...,23,3,"[ward, voting_districts, registered_voters]"
26,iec_kzn_kzn266___ulundi_ward_registration_2026...,25,3,"[ward, voting_districts, registered_voters]"
27,iec_kzn_kzn271___umhlabuyalingana_ward_registr...,20,3,"[ward, voting_districts, registered_voters]"
28,iec_kzn_kzn272___jozini_ward_registration_2026...,25,3,"[ward, voting_districts, registered_voters]"
29,iec_kzn_kzn275___inkosi_umtubatuba_ward_regist...,23,3,"[ward, voting_districts, registered_voters]"
30,iec_kzn_kzn276___big_five_hlabisa_ward_registr...,14,3,"[ward, voting_districts, registered_voters]"
31,iec_kzn_kzn281___umfolozi_ward_registration_20...,18,3,"[ward, voting_districts, registered_voters]"
32,iec_kzn_kzn282___umhlathuze_ward_registration_...,36,3,"[ward, voting_districts, registered_voters]"
33,iec_kzn_kzn284___umlalazi_ward_registration_20...,28,3,"[ward, voting_districts, registered_voters]"
34,iec_kzn_kzn285___mthonjaneni_ward_registration...,13,3,"[ward, voting_districts, registered_voters]"
35,iec_kzn_kzn286___nkandla_ward_registration_202...,14,3,"[ward, voting_districts, registered_voters]"
36,iec_kzn_kzn291___mandeni_ward_registration_202...,18,3,"[ward, voting_districts, registered_voters]"
37,iec_kzn_kzn292___kwadukuza_ward_registration_2...,30,3,"[ward, voting_districts, registered_voters]"
38,iec_kzn_kzn293___ndwedwe_ward_registration_202...,19,3,"[ward, voting_districts, registered_voters]"
39,iec_kzn_kzn294___maphumulo_ward_registration_2...,13,3,"[ward, voting_districts, registered_voters]"
40,iec_kzn_kzn433___greater_kokstad_ward_registra...,11,3,"[ward, voting_districts, registered_voters]"
41,iec_kzn_kzn434___johannes_phumani_pungula_ward...,14,3,"[ward, voting_districts, registered_voters]"
42,iec_kzn_kzn435___umzimkhulu_ward_registration_...,22,3,"[ward, voting_districts, registered_voters]"
43,iec_kzn_kzn436___dr._nkosazana_dlamini_zuma_wa...,15,3,"[ward, voting_districts, registered_voters]"

In [5]:
expected_columns = [
    "ward",
    "voting_districts",
    "registered_voters"
]

for file in raw_files:
    df = pd.read_csv(file)

    if list(df.columns) != expected_columns:
        print("Different structure:", file.name)

print("Structure check complete.")

Structure check complete.

In [6]:
first_file = raw_files[0]

first_data = pd.read_csv(first_file)

print("File:", first_file.name)
print("Rows:", len(first_data))
print("Columns:", list(first_data.columns))

display(first_data.head())

File: iec_kzn_ethekwini_ward_registration_2026.csv
Rows: 112
Columns: ['ward', 'voting_districts', 'registered_voters']

       ward  voting_districts registered_voters
0  59500001                14            19,964
1  59500002                21            21,172
2  59500003                13            17,103
3  59500004                 9            20,987
4  59500005                 5            14,950

In [7]:
missing_results = []

for file in raw_files:
    df = pd.read_csv(file)

    for column in df.columns:
        missing = df[column].isnull().sum()

        missing_results.append({
            "file": file.name,
            "column": column,
            "missing_values": missing
        })

missing_df = pd.DataFrame(missing_results)

display(missing_df)

print(
    "Total missing values:",
    missing_df["missing_values"].sum()
)

,file,column,missing_values
0,iec_kzn_ethekwini_ward_registration_2026.csv,ward,0
1,iec_kzn_ethekwini_ward_registration_2026.csv,voting_districts,0
2,iec_kzn_ethekwini_ward_registration_2026.csv,registered_voters,0
3,iec_kzn_kzn212___umdoni_ward_registration_2026...,ward,0
4,iec_kzn_kzn212___umdoni_ward_registration_2026...,voting_districts,0
...,...,...,...
127,iec_kzn_kzn435___umzimkhulu_ward_registration_...,voting_districts,0
128,iec_kzn_kzn435___umzimkhulu_ward_registration_...,registered_voters,0
129,iec_kzn_kzn436___dr._nkosazana_dlamini_zuma_wa...,ward,0
130,iec_kzn_kzn436___dr._nkosazana_dlamini_zuma_wa...,voting_districts,0
131,iec_kzn_kzn436___dr._nkosazana_dlamini_zuma_wa...,registered_voters,0

Total missing values: 0

In [8]:
blank_results = []

for file in raw_files:
    df = pd.read_csv(file)

    for column in df.columns:
        blanks = (
            df[column]
            .astype(str)
            .str.strip()
            .eq("")
            .sum()
        )

        blank_results.append({
            "file": file.name,
            "column": column,
            "blank_values": blanks
        })

blank_df = pd.DataFrame(blank_results)

display(blank_df)

print(
    "Total blank values:",
    blank_df["blank_values"].sum()
)

,file,column,blank_values
0,iec_kzn_ethekwini_ward_registration_2026.csv,ward,0
1,iec_kzn_ethekwini_ward_registration_2026.csv,voting_districts,0
2,iec_kzn_ethekwini_ward_registration_2026.csv,registered_voters,0
3,iec_kzn_kzn212___umdoni_ward_registration_2026...,ward,0
4,iec_kzn_kzn212___umdoni_ward_registration_2026...,voting_districts,0
...,...,...,...
127,iec_kzn_kzn435___umzimkhulu_ward_registration_...,voting_districts,0
128,iec_kzn_kzn435___umzimkhulu_ward_registration_...,registered_voters,0
129,iec_kzn_kzn436___dr._nkosazana_dlamini_zuma_wa...,ward,0
130,iec_kzn_kzn436___dr._nkosazana_dlamini_zuma_wa...,voting_districts,0
131,iec_kzn_kzn436___dr._nkosazana_dlamini_zuma_wa...,registered_voters,0

Total blank values: 0

In [9]:
ward_results = []

for file in raw_files:
    df = pd.read_csv(file)

    invalid_wards = (
        ~df["ward"]
        .astype(str)
        .str.strip()
        .str.match(r"^\d+$")
    ).sum()

    ward_results.append({
        "file": file.name,
        "invalid_ward_codes": invalid_wards
    })

ward_df = pd.DataFrame(ward_results)

display(ward_df)

print(
    "Total invalid ward codes:",
    ward_df["invalid_ward_codes"].sum()
)

                                                 file  invalid_ward_codes
0        iec_kzn_ethekwini_ward_registration_2026.csv                   0
1   iec_kzn_kzn212___umdoni_ward_registration_2026...                   0
2   iec_kzn_kzn213___umzumbe_ward_registration_202...                   0
3   iec_kzn_kzn214___umuziwabantu_ward_registratio...                   0
4   iec_kzn_kzn216___ray_nkonyeni_ward_registratio...                   0
5   iec_kzn_kzn221___umshwathi_ward_registration_2...                   0
6   iec_kzn_kzn222___umngeni_ward_registration_202...                   0
7   iec_kzn_kzn223___mpofana_ward_registration_202...                   0
8   iec_kzn_kzn224___impendle_ward_registration_20...                   0
9   iec_kzn_kzn225___msunduzi_ward_registration_20...                   0
10  iec_kzn_kzn226___mkhambathini_ward_registratio...                   0
11  iec_kzn_kzn227___richmond_ward_registration_20...                   0
12  iec_kzn_kzn235___okhahlamba_ward_registration_...                   0
13  iec_kzn_kzn237___inkosi_langalibalele_ward_reg...                   0
14  iec_kzn_kzn238___alfred_duma_ward_registration...                   0
15  iec_kzn_kzn241___endumeni_ward_registration_20...                   0
16  iec_kzn_kzn242___nqutu_ward_registration_2026.csv                   0
17  iec_kzn_kzn244___umsinga_ward_registration_202...                   0
18  iec_kzn_kzn245___umvoti_ward_registration_2026...                   0
19  iec_kzn_kzn252___newcastle_ward_registration_2...                   0
20  iec_kzn_kzn253___emadlangeni_ward_registration...                   0
21  iec_kzn_kzn254___dannhauser_ward_registration_...                   0
22  iec_kzn_kzn261___edumbe_ward_registration_2026...                   0
23  iec_kzn_kzn262___uphongolo_ward_registration_2...                   0
24  iec_kzn_kzn263___abaqulusi_ward_registration_2...                   0
25  iec_kzn_kzn265___nongoma_ward_registration_202...                   0
26  iec_kzn_kzn266___ulundi_ward_registration_2026...                   0
27  iec_kzn_kzn271___umhlabuyalingana_ward_registr...                   0
28  iec_kzn_kzn272___jozini_ward_registration_2026...                   0
29  iec_kzn_kzn275___inkosi_umtubatuba_ward_regist...                   0
30  iec_kzn_kzn276___big_five_hlabisa_ward_registr...                   0
31  iec_kzn_kzn281___umfolozi_ward_registration_20...                   0
32  iec_kzn_kzn282___umhlathuze_ward_registration_...                   0
33  iec_kzn_kzn284___umlalazi_ward_registration_20...                   0
34  iec_kzn_kzn285___mthonjaneni_ward_registration...                   0
35  iec_kzn_kzn286___nkandla_ward_registration_202...                   0
36  iec_kzn_kzn291___mandeni_ward_registration_202...                   0
37  iec_kzn_kzn292___kwadukuza_ward_registration_2...                   0
38  iec_kzn_kzn293___ndwedwe_ward_registration_202...                   0
39  iec_kzn_kzn294___maphumulo_ward_registration_2...                   0
40  iec_kzn_kzn433___greater_kokstad_ward_registra...                   0
41  iec_kzn_kzn434___johannes_phumani_pungula_ward...                   0
42  iec_kzn_kzn435___umzimkhulu_ward_registration_...                   0
43  iec_kzn_kzn436___dr._nkosazana_dlamini_zuma_wa...                   0

Total invalid ward codes: 0

In [10]:
district_results = []

for file in raw_files:
    df = pd.read_csv(file)

    invalid_districts = (
        pd.to_numeric(
            df["voting_districts"],
            errors="coerce"
        )
        .le(0)
    ).sum()

    district_results.append({
        "file": file.name,
        "invalid_voting_districts": invalid_districts
    })

district_df = pd.DataFrame(district_results)

display(district_df)

print(
    "Total invalid voting district values:",
    district_df["invalid_voting_districts"].sum()
)

,file,invalid_voting_districts
0,iec_kzn_ethekwini_ward_registration_2026.csv,0
1,iec_kzn_kzn212___umdoni_ward_registration_2026...,0
2,iec_kzn_kzn213___umzumbe_ward_registration_202...,0
3,iec_kzn_kzn214___umuziwabantu_ward_registratio...,0
4,iec_kzn_kzn216___ray_nkonyeni_ward_registratio...,0
5,iec_kzn_kzn221___umshwathi_ward_registration_2...,0
6,iec_kzn_kzn222___umngeni_ward_registration_202...,0
7,iec_kzn_kzn223___mpofana_ward_registration_202...,0
8,iec_kzn_kzn224___impendle_ward_registration_20...,0
9,iec_kzn_kzn225___msunduzi_ward_registration_20...,0
10,iec_kzn_kzn226___mkhambathini_ward_registratio...,0
11,iec_kzn_kzn227___richmond_ward_registration_20...,0
12,iec_kzn_kzn235___okhahlamba_ward_registration_...,0
13,iec_kzn_kzn237___inkosi_langalibalele_ward_reg...,0
14,iec_kzn_kzn238___alfred_duma_ward_registration...,0
15,iec_kzn_kzn241___endumeni_ward_registration_20...,0
16,iec_kzn_kzn242___nqutu_ward_registration_2026.csv,0
17,iec_kzn_kzn244___umsinga_ward_registration_202...,0
18,iec_kzn_kzn245___umvoti_ward_registration_2026...,0
19,iec_kzn_kzn252___newcastle_ward_registration_2...,0
20,iec_kzn_kzn253___emadlangeni_ward_registration...,0
21,iec_kzn_kzn254___dannhauser_ward_registration_...,0
22,iec_kzn_kzn261___edumbe_ward_registration_2026...,0
23,iec_kzn_kzn262___uphongolo_ward_registration_2...,0
24,iec_kzn_kzn263___abaqulusi_ward_registration_2...,0
25,iec_kzn_kzn265___nongoma_ward_registration_202...,0
26,iec_kzn_kzn266___ulundi_ward_registration_2026...,0
27,iec_kzn_kzn271___umhlabuyalingana_ward_registr...,0
28,iec_kzn_kzn272___jozini_ward_registration_2026...,0
29,iec_kzn_kzn275___inkosi_umtubatuba_ward_regist...,0
30,iec_kzn_kzn276___big_five_hlabisa_ward_registr...,0
31,iec_kzn_kzn281___umfolozi_ward_registration_20...,0
32,iec_kzn_kzn282___umhlathuze_ward_registration_...,0
33,iec_kzn_kzn284___umlalazi_ward_registration_20...,0
34,iec_kzn_kzn285___mthonjaneni_ward_registration...,0
35,iec_kzn_kzn286___nkandla_ward_registration_202...,0
36,iec_kzn_kzn291___mandeni_ward_registration_202...,0
37,iec_kzn_kzn292___kwadukuza_ward_registration_2...,0
38,iec_kzn_kzn293___ndwedwe_ward_registration_202...,0
39,iec_kzn_kzn294___maphumulo_ward_registration_2...,0
40,iec_kzn_kzn433___greater_kokstad_ward_registra...,0
41,iec_kzn_kzn434___johannes_phumani_pungula_ward...,0
42,iec_kzn_kzn435___umzimkhulu_ward_registration_...,0
43,iec_kzn_kzn436___dr._nkosazana_dlamini_zuma_wa...,0

Total invalid voting district values: 0

In [11]:
duplicate_ward_results = []

for file in raw_files:
    df = pd.read_csv(file)

    duplicates = df["ward"].duplicated().sum()

    duplicate_ward_results.append({
        "file": file.name,
        "duplicate_wards": duplicates
    })

duplicate_ward_df = pd.DataFrame(duplicate_ward_results)

display(duplicate_ward_df)

print(
    "Total duplicate ward records:",
    duplicate_ward_df["duplicate_wards"].sum()
)

                                                 file  duplicate_wards
0        iec_kzn_ethekwini_ward_registration_2026.csv                0
1   iec_kzn_kzn212___umdoni_ward_registration_2026...                0
2   iec_kzn_kzn213___umzumbe_ward_registration_202...                0
3   iec_kzn_kzn214___umuziwabantu_ward_registratio...                0
4   iec_kzn_kzn216___ray_nkonyeni_ward_registratio...                0
5   iec_kzn_kzn221___umshwathi_ward_registration_2...                0
6   iec_kzn_kzn222___umngeni_ward_registration_202...                0
7   iec_kzn_kzn223___mpofana_ward_registration_202...                0
8   iec_kzn_kzn224___impendle_ward_registration_20...                0
9   iec_kzn_kzn225___msunduzi_ward_registration_20...                0
10  iec_kzn_kzn226___mkhambathini_ward_registratio...                0
11  iec_kzn_kzn227___richmond_ward_registration_20...                0
12  iec_kzn_kzn235___okhahlamba_ward_registration_...                0
13  iec_kzn_kzn237___inkosi_langalibalele_ward_reg...                0
14  iec_kzn_kzn238___alfred_duma_ward_registration...                0
15  iec_kzn_kzn241___endumeni_ward_registration_20...                0
16  iec_kzn_kzn242___nqutu_ward_registration_2026.csv                0
17  iec_kzn_kzn244___umsinga_ward_registration_202...                0
18  iec_kzn_kzn245___umvoti_ward_registration_2026...                0
19  iec_kzn_kzn252___newcastle_ward_registration_2...                0
20  iec_kzn_kzn253___emadlangeni_ward_registration...                0
21  iec_kzn_kzn254___dannhauser_ward_registration_...                0
22  iec_kzn_kzn261___edumbe_ward_registration_2026...                0
23  iec_kzn_kzn262___uphongolo_ward_registration_2...                0
24  iec_kzn_kzn263___abaqulusi_ward_registration_2...                0
25  iec_kzn_kzn265___nongoma_ward_registration_202...                0
26  iec_kzn_kzn266___ulundi_ward_registration_2026...                0
27  iec_kzn_kzn271___umhlabuyalingana_ward_registr...                0
28  iec_kzn_kzn272___jozini_ward_registration_2026...                0
29  iec_kzn_kzn275___inkosi_umtubatuba_ward_regist...                0
30  iec_kzn_kzn276___big_five_hlabisa_ward_registr...                0
31  iec_kzn_kzn281___umfolozi_ward_registration_20...                0
32  iec_kzn_kzn282___umhlathuze_ward_registration_...                0
33  iec_kzn_kzn284___umlalazi_ward_registration_20...                0
34  iec_kzn_kzn285___mthonjaneni_ward_registration...                0
35  iec_kzn_kzn286___nkandla_ward_registration_202...                0
36  iec_kzn_kzn291___mandeni_ward_registration_202...                0
37  iec_kzn_kzn292___kwadukuza_ward_registration_2...                0
38  iec_kzn_kzn293___ndwedwe_ward_registration_202...                0
39  iec_kzn_kzn294___maphumulo_ward_registration_2...                0
40  iec_kzn_kzn433___greater_kokstad_ward_registra...                0
41  iec_kzn_kzn434___johannes_phumani_pungula_ward...                0
42  iec_kzn_kzn435___umzimkhulu_ward_registration_...                0
43  iec_kzn_kzn436___dr._nkosazana_dlamini_zuma_wa...                0

Total duplicate ward records: 0

In [28]:
# Check the data format and data types in all files

format_check = []

for file in raw_files:
    df = pd.read_csv(file)

    for column in df.columns:
        format_check.append({
            "file": file.name,
            "column": column,
            "data_type": str(df[column].dtype),
            "example_value": df[column].iloc[0]
        })

format_df = pd.DataFrame(format_check)

display(format_df)

,file,column,data_type,example_value
0,iec_kzn_ethekwini_ward_registration_2026.csv,ward,int64,59500001
1,iec_kzn_ethekwini_ward_registration_2026.csv,voting_districts,int64,14
2,iec_kzn_ethekwini_ward_registration_2026.csv,registered_voters,str,"19,964"
3,iec_kzn_kzn212___umdoni_ward_registration_2026...,ward,int64,52102001
4,iec_kzn_kzn212___umdoni_ward_registration_2026...,voting_districts,int64,10
...,...,...,...,...
127,iec_kzn_kzn435___umzimkhulu_ward_registration_...,voting_districts,int64,7
128,iec_kzn_kzn435___umzimkhulu_ward_registration_...,registered_voters,str,"4,635"
129,iec_kzn_kzn436___dr._nkosazana_dlamini_zuma_wa...,ward,int64,54306001
130,iec_kzn_kzn436___dr._nkosazana_dlamini_zuma_wa...,voting_districts,int64,8
131,iec_kzn_kzn436___dr._nkosazana_dlamini_zuma_wa...,registered_voters,str,"3,779"

In [29]:
# Count registered voter values containing commas


# Inspect values in columns that are expected to contain numbers

for file in raw_files[:3]:
    df = pd.read_csv(file)

    print("\nFile:", file.name)

    print("Voting districts examples:")
    print(df["voting_districts"].head().to_list())

    print("Registered voters examples:")
    print(df["registered_voters"].head().to_list())

File: iec_kzn_ethekwini_ward_registration_2026.csv
Voting districts examples:
[14, 21, 13, 9, 5]
Registered voters examples:
['19,964', '21,172', '17,103', '20,987', '14,950']

File: iec_kzn_kzn212___umdoni_ward_registration_2026.csv
Voting districts examples:
[10, 10, 6, 8, 5]
Registered voters examples:
['3,992', '4,556', '5,082', '4,008', '4,713']

File: iec_kzn_kzn213___umzumbe_ward_registration_2026.csv
Voting districts examples:
[7, 6, 7, 7, 3]
Registered voters examples:
['4,168', '4,671', '4,505', '4,574', '3,563']

In [30]:
# Fix the registered_voters format

cleaning_summary = []

for file in raw_files:

    df = pd.read_csv(file)

    # Remove commas and convert registered_voters to a numeric type
    df["registered_voters"] = (
        df["registered_voters"]
        .astype(str)
        .str.strip()
        .str.replace(",", "", regex=False)
        .astype("int64")
    )

    # Convert voting_districts to integer
    df["voting_districts"] = (
        pd.to_numeric(
            df["voting_districts"],
            errors="raise"
        ).astype(int)
    )

    # Keep ward as a string identifier
    df["ward"] = (
        df["ward"]
        .astype(str)
        .str.strip()
    )

    output_file = interim_folder / file.name

    df.to_csv(
        output_file,
        index=False,
        encoding="utf-8"
    )

    cleaning_summary.append({
        "file": file.name,
        "rows": len(df)
    })

print(f"Cleaning complete. {len(cleaning_summary)} files processed.")

Cleaning complete. 44 files processed.

In [31]:
# Check the data types after cleaning

cleaned_format_check = []

for file in cleaned_files if "cleaned_files" in globals() else sorted(interim_folder.glob("*.csv")):

    df = pd.read_csv(file)

    for column in df.columns:
        cleaned_format_check.append({
            "file": file.name,
            "column": column,
            "data_type": str(df[column].dtype),
            "example_value": df[column].iloc[0]
        })

cleaned_format_df = pd.DataFrame(cleaned_format_check)

display(cleaned_format_df)

,file,column,data_type,example_value
0,iec_kzn_ethekwini_ward_registration_2026.csv,ward,int64,59500001
1,iec_kzn_ethekwini_ward_registration_2026.csv,voting_districts,int64,14
2,iec_kzn_ethekwini_ward_registration_2026.csv,registered_voters,int64,19964
3,iec_kzn_kzn212___umdoni_ward_registration_2026...,ward,int64,52102001
4,iec_kzn_kzn212___umdoni_ward_registration_2026...,voting_districts,int64,10
...,...,...,...,...
127,iec_kzn_kzn435___umzimkhulu_ward_registration_...,voting_districts,int64,7
128,iec_kzn_kzn435___umzimkhulu_ward_registration_...,registered_voters,int64,4635
129,iec_kzn_kzn436___dr._nkosazana_dlamini_zuma_wa...,ward,int64,54306001
130,iec_kzn_kzn436___dr._nkosazana_dlamini_zuma_wa...,voting_districts,int64,8
131,iec_kzn_kzn436___dr._nkosazana_dlamini_zuma_wa...,registered_voters,int64,3779

In [12]:
duplicate_record_results = []

for file in raw_files:
    df = pd.read_csv(file)

    duplicates = df.duplicated().sum()

    duplicate_record_results.append({
        "file": file.name,
        "duplicate_complete_records": duplicates
    })

duplicate_record_df = pd.DataFrame(duplicate_record_results)

display(duplicate_record_df)

print(
    "Total duplicate complete records:",
    duplicate_record_df["duplicate_complete_records"].sum()
)

,file,duplicate_complete_records
0,iec_kzn_ethekwini_ward_registration_2026.csv,0
1,iec_kzn_kzn212___umdoni_ward_registration_2026...,0
2,iec_kzn_kzn213___umzumbe_ward_registration_202...,0
3,iec_kzn_kzn214___umuziwabantu_ward_registratio...,0
4,iec_kzn_kzn216___ray_nkonyeni_ward_registratio...,0
5,iec_kzn_kzn221___umshwathi_ward_registration_2...,0
6,iec_kzn_kzn222___umngeni_ward_registration_202...,0
7,iec_kzn_kzn223___mpofana_ward_registration_202...,0
8,iec_kzn_kzn224___impendle_ward_registration_20...,0
9,iec_kzn_kzn225___msunduzi_ward_registration_20...,0
10,iec_kzn_kzn226___mkhambathini_ward_registratio...,0
11,iec_kzn_kzn227___richmond_ward_registration_20...,0
12,iec_kzn_kzn235___okhahlamba_ward_registration_...,0
13,iec_kzn_kzn237___inkosi_langalibalele_ward_reg...,0
14,iec_kzn_kzn238___alfred_duma_ward_registration...,0
15,iec_kzn_kzn241___endumeni_ward_registration_20...,0
16,iec_kzn_kzn242___nqutu_ward_registration_2026.csv,0
17,iec_kzn_kzn244___umsinga_ward_registration_202...,0
18,iec_kzn_kzn245___umvoti_ward_registration_2026...,0
19,iec_kzn_kzn252___newcastle_ward_registration_2...,0
20,iec_kzn_kzn253___emadlangeni_ward_registration...,0
21,iec_kzn_kzn254___dannhauser_ward_registration_...,0
22,iec_kzn_kzn261___edumbe_ward_registration_2026...,0
23,iec_kzn_kzn262___uphongolo_ward_registration_2...,0
24,iec_kzn_kzn263___abaqulusi_ward_registration_2...,0
25,iec_kzn_kzn265___nongoma_ward_registration_202...,0
26,iec_kzn_kzn266___ulundi_ward_registration_2026...,0
27,iec_kzn_kzn271___umhlabuyalingana_ward_registr...,0
28,iec_kzn_kzn272___jozini_ward_registration_2026...,0
29,iec_kzn_kzn275___inkosi_umtubatuba_ward_regist...,0
30,iec_kzn_kzn276___big_five_hlabisa_ward_registr...,0
31,iec_kzn_kzn281___umfolozi_ward_registration_20...,0
32,iec_kzn_kzn282___umhlathuze_ward_registration_...,0
33,iec_kzn_kzn284___umlalazi_ward_registration_20...,0
34,iec_kzn_kzn285___mthonjaneni_ward_registration...,0
35,iec_kzn_kzn286___nkandla_ward_registration_202...,0
36,iec_kzn_kzn291___mandeni_ward_registration_202...,0
37,iec_kzn_kzn292___kwadukuza_ward_registration_2...,0
38,iec_kzn_kzn293___ndwedwe_ward_registration_202...,0
39,iec_kzn_kzn294___maphumulo_ward_registration_2...,0
40,iec_kzn_kzn433___greater_kokstad_ward_registra...,0
41,iec_kzn_kzn434___johannes_phumani_pungula_ward...,0
42,iec_kzn_kzn435___umzimkhulu_ward_registration_...,0
43,iec_kzn_kzn436___dr._nkosazana_dlamini_zuma_wa...,0

Total duplicate complete records: 0

In [13]:
row_counts = []

for file in raw_files:
    df = pd.read_csv(file)

    row_counts.append({
        "file": file.name,
        "rows": len(df)
    })

row_counts_df = pd.DataFrame(row_counts)

display(row_counts_df)

print(
    "Total ward records across all files:",
    row_counts_df["rows"].sum()
)

                                                 file  rows
0        iec_kzn_ethekwini_ward_registration_2026.csv   112
1   iec_kzn_kzn212___umdoni_ward_registration_2026...    19
2   iec_kzn_kzn213___umzumbe_ward_registration_202...    20
3   iec_kzn_kzn214___umuziwabantu_ward_registratio...    11
4   iec_kzn_kzn216___ray_nkonyeni_ward_registratio...    36
5   iec_kzn_kzn221___umshwathi_ward_registration_2...    14
6   iec_kzn_kzn222___umngeni_ward_registration_202...    13
7   iec_kzn_kzn223___mpofana_ward_registration_202...     6
8   iec_kzn_kzn224___impendle_ward_registration_20...     6
9   iec_kzn_kzn225___msunduzi_ward_registration_20...    41
10  iec_kzn_kzn226___mkhambathini_ward_registratio...    10
11  iec_kzn_kzn227___richmond_ward_registration_20...     9
12  iec_kzn_kzn235___okhahlamba_ward_registration_...    15
13  iec_kzn_kzn237___inkosi_langalibalele_ward_reg...    24
14  iec_kzn_kzn238___alfred_duma_ward_registration...    37
15  iec_kzn_kzn241___endumeni_ward_registration_20...     8
16  iec_kzn_kzn242___nqutu_ward_registration_2026.csv    20
17  iec_kzn_kzn244___umsinga_ward_registration_202...    21
18  iec_kzn_kzn245___umvoti_ward_registration_2026...    14
19  iec_kzn_kzn252___newcastle_ward_registration_2...    36
20  iec_kzn_kzn253___emadlangeni_ward_registration...     6
21  iec_kzn_kzn254___dannhauser_ward_registration_...    13
22  iec_kzn_kzn261___edumbe_ward_registration_2026...    10
23  iec_kzn_kzn262___uphongolo_ward_registration_2...    15
24  iec_kzn_kzn263___abaqulusi_ward_registration_2...    24
25  iec_kzn_kzn265___nongoma_ward_registration_202...    23
26  iec_kzn_kzn266___ulundi_ward_registration_2026...    25
27  iec_kzn_kzn271___umhlabuyalingana_ward_registr...    20
28  iec_kzn_kzn272___jozini_ward_registration_2026...    25
29  iec_kzn_kzn275___inkosi_umtubatuba_ward_regist...    23
30  iec_kzn_kzn276___big_five_hlabisa_ward_registr...    14
31  iec_kzn_kzn281___umfolozi_ward_registration_20...    18
32  iec_kzn_kzn282___umhlathuze_ward_registration_...    36
33  iec_kzn_kzn284___umlalazi_ward_registration_20...    28
34  iec_kzn_kzn285___mthonjaneni_ward_registration...    13
35  iec_kzn_kzn286___nkandla_ward_registration_202...    14
36  iec_kzn_kzn291___mandeni_ward_registration_202...    18
37  iec_kzn_kzn292___kwadukuza_ward_registration_2...    30
38  iec_kzn_kzn293___ndwedwe_ward_registration_202...    19
39  iec_kzn_kzn294___maphumulo_ward_registration_2...    13
40  iec_kzn_kzn433___greater_kokstad_ward_registra...    11
41  iec_kzn_kzn434___johannes_phumani_pungula_ward...    14
42  iec_kzn_kzn435___umzimkhulu_ward_registration_...    22
43  iec_kzn_kzn436___dr._nkosazana_dlamini_zuma_wa...    15

Total ward records across all files: 921

In [14]:
cleaning_summary = []

for file in raw_files:

    df = pd.read_csv(file)

    cleaned_df = pd.DataFrame({
        "ward": df["ward"].astype(str).str.strip(),
        "voting_districts": (
            pd.to_numeric(
                df["voting_districts"],
                errors="raise"
            ).astype(int)
        ),
        "registered_voters": (
            df["registered_voters"]
            .astype(str)
            .str.strip()
            .str.replace(",", "", regex=False)
            .astype("int64")
        )
    })

    output_file = interim_folder / file.name

    cleaned_df.to_csv(
        output_file,
        index=False,
        encoding="utf-8"
    )

    cleaning_summary.append({
        "file": file.name,
        "original_rows": len(df),
        "cleaned_rows": len(cleaned_df)
    })

cleaning_summary_df = pd.DataFrame(cleaning_summary)

print(
    f"Cleaning complete. {len(cleaning_summary_df)} files processed."
)

display(cleaning_summary_df)

Cleaning complete. 44 files processed.

,file,original_rows,cleaned_rows
0,iec_kzn_ethekwini_ward_registration_2026.csv,112,112
1,iec_kzn_kzn212___umdoni_ward_registration_2026...,19,19
2,iec_kzn_kzn213___umzumbe_ward_registration_202...,20,20
3,iec_kzn_kzn214___umuziwabantu_ward_registratio...,11,11
4,iec_kzn_kzn216___ray_nkonyeni_ward_registratio...,36,36
5,iec_kzn_kzn221___umshwathi_ward_registration_2...,14,14
6,iec_kzn_kzn222___umngeni_ward_registration_202...,13,13
7,iec_kzn_kzn223___mpofana_ward_registration_202...,6,6
8,iec_kzn_kzn224___impendle_ward_registration_20...,6,6
9,iec_kzn_kzn225___msunduzi_ward_registration_20...,41,41
10,iec_kzn_kzn226___mkhambathini_ward_registratio...,10,10
11,iec_kzn_kzn227___richmond_ward_registration_20...,9,9
12,iec_kzn_kzn235___okhahlamba_ward_registration_...,15,15
13,iec_kzn_kzn237___inkosi_langalibalele_ward_reg...,24,24
14,iec_kzn_kzn238___alfred_duma_ward_registration...,37,37
15,iec_kzn_kzn241___endumeni_ward_registration_20...,8,8
16,iec_kzn_kzn242___nqutu_ward_registration_2026.csv,20,20
17,iec_kzn_kzn244___umsinga_ward_registration_202...,21,21
18,iec_kzn_kzn245___umvoti_ward_registration_2026...,14,14
19,iec_kzn_kzn252___newcastle_ward_registration_2...,36,36
20,iec_kzn_kzn253___emadlangeni_ward_registration...,6,6
21,iec_kzn_kzn254___dannhauser_ward_registration_...,13,13
22,iec_kzn_kzn261___edumbe_ward_registration_2026...,10,10
23,iec_kzn_kzn262___uphongolo_ward_registration_2...,15,15
24,iec_kzn_kzn263___abaqulusi_ward_registration_2...,24,24
25,iec_kzn_kzn265___nongoma_ward_registration_202...,23,23
26,iec_kzn_kzn266___ulundi_ward_registration_2026...,25,25
27,iec_kzn_kzn271___umhlabuyalingana_ward_registr...,20,20
28,iec_kzn_kzn272___jozini_ward_registration_2026...,25,25
29,iec_kzn_kzn275___inkosi_umtubatuba_ward_regist...,23,23
30,iec_kzn_kzn276___big_five_hlabisa_ward_registr...,14,14
31,iec_kzn_kzn281___umfolozi_ward_registration_20...,18,18
32,iec_kzn_kzn282___umhlathuze_ward_registration_...,36,36
33,iec_kzn_kzn284___umlalazi_ward_registration_20...,28,28
34,iec_kzn_kzn285___mthonjaneni_ward_registration...,13,13
35,iec_kzn_kzn286___nkandla_ward_registration_202...,14,14
36,iec_kzn_kzn291___mandeni_ward_registration_202...,18,18
37,iec_kzn_kzn292___kwadukuza_ward_registration_2...,30,30
38,iec_kzn_kzn293___ndwedwe_ward_registration_202...,19,19
39,iec_kzn_kzn294___maphumulo_ward_registration_2...,13,13
40,iec_kzn_kzn433___greater_kokstad_ward_registra...,11,11
41,iec_kzn_kzn434___johannes_phumani_pungula_ward...,14,14
42,iec_kzn_kzn435___umzimkhulu_ward_registration_...,22,22
43,iec_kzn_kzn436___dr._nkosazana_dlamini_zuma_wa...,15,15

In [15]:
cleaned_files = sorted(interim_folder.glob("*.csv"))

print("Number of cleaned files:", len(cleaned_files))

missing_cleaned_files = [
    file.name
    for file in raw_files
    if not (interim_folder / file.name).exists()
]

print("Missing cleaned files:", len(missing_cleaned_files))

if missing_cleaned_files:
    print(missing_cleaned_files)

Number of cleaned files: 44
Missing cleaned files: 0

In [16]:
for file in cleaned_files[:3]:

    df = pd.read_csv(file)

    print("\nFile:", file.name)
    print(df.dtypes)

File: iec_kzn_ethekwini_ward_registration_2026.csv
ward                 int64
voting_districts     int64
registered_voters    int64
dtype: object

File: iec_kzn_kzn212___umdoni_ward_registration_2026.csv
ward                 int64
voting_districts     int64
registered_voters    int64
dtype: object

File: iec_kzn_kzn213___umzumbe_ward_registration_2026.csv
ward                 int64
voting_districts     int64
registered_voters    int64
dtype: object

In [17]:
comma_results = []

for file in cleaned_files:

    df = pd.read_csv(file)

    commas = (
        df["registered_voters"]
        .astype(str)
        .str.contains(",", regex=False)
        .sum()
    )

    comma_results.append({
        "file": file.name,
        "registered_voters_with_commas": commas
    })

comma_df = pd.DataFrame(comma_results)

display(comma_df)

print(
    "Total registered voter values still containing commas:",
    comma_df["registered_voters_with_commas"].sum()
)

,file,registered_voters_with_commas
0,iec_kzn_ethekwini_ward_registration_2026.csv,0
1,iec_kzn_kzn212___umdoni_ward_registration_2026...,0
2,iec_kzn_kzn213___umzumbe_ward_registration_202...,0
3,iec_kzn_kzn214___umuziwabantu_ward_registratio...,0
4,iec_kzn_kzn216___ray_nkonyeni_ward_registratio...,0
5,iec_kzn_kzn221___umshwathi_ward_registration_2...,0
6,iec_kzn_kzn222___umngeni_ward_registration_202...,0
7,iec_kzn_kzn223___mpofana_ward_registration_202...,0
8,iec_kzn_kzn224___impendle_ward_registration_20...,0
9,iec_kzn_kzn225___msunduzi_ward_registration_20...,0
10,iec_kzn_kzn226___mkhambathini_ward_registratio...,0
11,iec_kzn_kzn227___richmond_ward_registration_20...,0
12,iec_kzn_kzn235___okhahlamba_ward_registration_...,0
13,iec_kzn_kzn237___inkosi_langalibalele_ward_reg...,0
14,iec_kzn_kzn238___alfred_duma_ward_registration...,0
15,iec_kzn_kzn241___endumeni_ward_registration_20...,0
16,iec_kzn_kzn242___nqutu_ward_registration_2026.csv,0
17,iec_kzn_kzn244___umsinga_ward_registration_202...,0
18,iec_kzn_kzn245___umvoti_ward_registration_2026...,0
19,iec_kzn_kzn252___newcastle_ward_registration_2...,0
20,iec_kzn_kzn253___emadlangeni_ward_registration...,0
21,iec_kzn_kzn254___dannhauser_ward_registration_...,0
22,iec_kzn_kzn261___edumbe_ward_registration_2026...,0
23,iec_kzn_kzn262___uphongolo_ward_registration_2...,0
24,iec_kzn_kzn263___abaqulusi_ward_registration_2...,0
25,iec_kzn_kzn265___nongoma_ward_registration_202...,0
26,iec_kzn_kzn266___ulundi_ward_registration_2026...,0
27,iec_kzn_kzn271___umhlabuyalingana_ward_registr...,0
28,iec_kzn_kzn272___jozini_ward_registration_2026...,0
29,iec_kzn_kzn275___inkosi_umtubatuba_ward_regist...,0
30,iec_kzn_kzn276___big_five_hlabisa_ward_registr...,0
31,iec_kzn_kzn281___umfolozi_ward_registration_20...,0
32,iec_kzn_kzn282___umhlathuze_ward_registration_...,0
33,iec_kzn_kzn284___umlalazi_ward_registration_20...,0
34,iec_kzn_kzn285___mthonjaneni_ward_registration...,0
35,iec_kzn_kzn286___nkandla_ward_registration_202...,0
36,iec_kzn_kzn291___mandeni_ward_registration_202...,0
37,iec_kzn_kzn292___kwadukuza_ward_registration_2...,0
38,iec_kzn_kzn293___ndwedwe_ward_registration_202...,0
39,iec_kzn_kzn294___maphumulo_ward_registration_2...,0
40,iec_kzn_kzn433___greater_kokstad_ward_registra...,0
41,iec_kzn_kzn434___johannes_phumani_pungula_ward...,0
42,iec_kzn_kzn435___umzimkhulu_ward_registration_...,0
43,iec_kzn_kzn436___dr._nkosazana_dlamini_zuma_wa...,0

Total registered voter values still containing commas: 0

In [32]:
cleaned_missing = []

for file in cleaned_files:

    df = pd.read_csv(file)

    cleaned_missing.append({
        "file": file.name,
        "missing_values": df.isnull().sum().sum()
    })

cleaned_missing_df = pd.DataFrame(cleaned_missing)

display(cleaned_missing_df)

print(
    "Total missing values after cleaning:",
    cleaned_missing_df["missing_values"].sum()
)

                                                 file  missing_values
0        iec_kzn_ethekwini_ward_registration_2026.csv               0
1   iec_kzn_kzn212___umdoni_ward_registration_2026...               0
2   iec_kzn_kzn213___umzumbe_ward_registration_202...               0
3   iec_kzn_kzn214___umuziwabantu_ward_registratio...               0
4   iec_kzn_kzn216___ray_nkonyeni_ward_registratio...               0
5   iec_kzn_kzn221___umshwathi_ward_registration_2...               0
6   iec_kzn_kzn222___umngeni_ward_registration_202...               0
7   iec_kzn_kzn223___mpofana_ward_registration_202...               0
8   iec_kzn_kzn224___impendle_ward_registration_20...               0
9   iec_kzn_kzn225___msunduzi_ward_registration_20...               0
10  iec_kzn_kzn226___mkhambathini_ward_registratio...               0
11  iec_kzn_kzn227___richmond_ward_registration_20...               0
12  iec_kzn_kzn235___okhahlamba_ward_registration_...               0
13  iec_kzn_kzn237___inkosi_langalibalele_ward_reg...               0
14  iec_kzn_kzn238___alfred_duma_ward_registration...               0
15  iec_kzn_kzn241___endumeni_ward_registration_20...               0
16  iec_kzn_kzn242___nqutu_ward_registration_2026.csv               0
17  iec_kzn_kzn244___umsinga_ward_registration_202...               0
18  iec_kzn_kzn245___umvoti_ward_registration_2026...               0
19  iec_kzn_kzn252___newcastle_ward_registration_2...               0
20  iec_kzn_kzn253___emadlangeni_ward_registration...               0
21  iec_kzn_kzn254___dannhauser_ward_registration_...               0
22  iec_kzn_kzn261___edumbe_ward_registration_2026...               0
23  iec_kzn_kzn262___uphongolo_ward_registration_2...               0
24  iec_kzn_kzn263___abaqulusi_ward_registration_2...               0
25  iec_kzn_kzn265___nongoma_ward_registration_202...               0
26  iec_kzn_kzn266___ulundi_ward_registration_2026...               0
27  iec_kzn_kzn271___umhlabuyalingana_ward_registr...               0
28  iec_kzn_kzn272___jozini_ward_registration_2026...               0
29  iec_kzn_kzn275___inkosi_umtubatuba_ward_regist...               0
30  iec_kzn_kzn276___big_five_hlabisa_ward_registr...               0
31  iec_kzn_kzn281___umfolozi_ward_registration_20...               0
32  iec_kzn_kzn282___umhlathuze_ward_registration_...               0
33  iec_kzn_kzn284___umlalazi_ward_registration_20...               0
34  iec_kzn_kzn285___mthonjaneni_ward_registration...               0
35  iec_kzn_kzn286___nkandla_ward_registration_202...               0
36  iec_kzn_kzn291___mandeni_ward_registration_202...               0
37  iec_kzn_kzn292___kwadukuza_ward_registration_2...               0
38  iec_kzn_kzn293___ndwedwe_ward_registration_202...               0
39  iec_kzn_kzn294___maphumulo_ward_registration_2...               0
40  iec_kzn_kzn433___greater_kokstad_ward_registra...               0
41  iec_kzn_kzn434___johannes_phumani_pungula_ward...               0
42  iec_kzn_kzn435___umzimkhulu_ward_registration_...               0
43  iec_kzn_kzn436___dr._nkosazana_dlamini_zuma_wa...               0

Total missing values after cleaning: 0

In [33]:
cleaned_duplicates = []

for file in cleaned_files:

    df = pd.read_csv(file)

    cleaned_duplicates.append({
        "file": file.name,
        "duplicate_wards": df["ward"].duplicated().sum()
    })

cleaned_duplicates_df = pd.DataFrame(cleaned_duplicates)

display(cleaned_duplicates_df)

print(
    "Total duplicate wards after cleaning:",
    cleaned_duplicates_df["duplicate_wards"].sum()
)

                                                 file  duplicate_wards
0        iec_kzn_ethekwini_ward_registration_2026.csv                0
1   iec_kzn_kzn212___umdoni_ward_registration_2026...                0
2   iec_kzn_kzn213___umzumbe_ward_registration_202...                0
3   iec_kzn_kzn214___umuziwabantu_ward_registratio...                0
4   iec_kzn_kzn216___ray_nkonyeni_ward_registratio...                0
5   iec_kzn_kzn221___umshwathi_ward_registration_2...                0
6   iec_kzn_kzn222___umngeni_ward_registration_202...                0
7   iec_kzn_kzn223___mpofana_ward_registration_202...                0
8   iec_kzn_kzn224___impendle_ward_registration_20...                0
9   iec_kzn_kzn225___msunduzi_ward_registration_20...                0
10  iec_kzn_kzn226___mkhambathini_ward_registratio...                0
11  iec_kzn_kzn227___richmond_ward_registration_20...                0
12  iec_kzn_kzn235___okhahlamba_ward_registration_...                0
13  iec_kzn_kzn237___inkosi_langalibalele_ward_reg...                0
14  iec_kzn_kzn238___alfred_duma_ward_registration...                0
15  iec_kzn_kzn241___endumeni_ward_registration_20...                0
16  iec_kzn_kzn242___nqutu_ward_registration_2026.csv                0
17  iec_kzn_kzn244___umsinga_ward_registration_202...                0
18  iec_kzn_kzn245___umvoti_ward_registration_2026...                0
19  iec_kzn_kzn252___newcastle_ward_registration_2...                0
20  iec_kzn_kzn253___emadlangeni_ward_registration...                0
21  iec_kzn_kzn254___dannhauser_ward_registration_...                0
22  iec_kzn_kzn261___edumbe_ward_registration_2026...                0
23  iec_kzn_kzn262___uphongolo_ward_registration_2...                0
24  iec_kzn_kzn263___abaqulusi_ward_registration_2...                0
25  iec_kzn_kzn265___nongoma_ward_registration_202...                0
26  iec_kzn_kzn266___ulundi_ward_registration_2026...                0
27  iec_kzn_kzn271___umhlabuyalingana_ward_registr...                0
28  iec_kzn_kzn272___jozini_ward_registration_2026...                0
29  iec_kzn_kzn275___inkosi_umtubatuba_ward_regist...                0
30  iec_kzn_kzn276___big_five_hlabisa_ward_registr...                0
31  iec_kzn_kzn281___umfolozi_ward_registration_20...                0
32  iec_kzn_kzn282___umhlathuze_ward_registration_...                0
33  iec_kzn_kzn284___umlalazi_ward_registration_20...                0
34  iec_kzn_kzn285___mthonjaneni_ward_registration...                0
35  iec_kzn_kzn286___nkandla_ward_registration_202...                0
36  iec_kzn_kzn291___mandeni_ward_registration_202...                0
37  iec_kzn_kzn292___kwadukuza_ward_registration_2...                0
38  iec_kzn_kzn293___ndwedwe_ward_registration_202...                0
39  iec_kzn_kzn294___maphumulo_ward_registration_2...                0
40  iec_kzn_kzn433___greater_kokstad_ward_registra...                0
41  iec_kzn_kzn434___johannes_phumani_pungula_ward...                0
42  iec_kzn_kzn435___umzimkhulu_ward_registration_...                0
43  iec_kzn_kzn436___dr._nkosazana_dlamini_zuma_wa...                0

Total duplicate wards after cleaning: 0

In [20]:
range_results = []

for file in cleaned_files:

    df = pd.read_csv(file)

    invalid_registered = (df["registered_voters"] < 0).sum()
    invalid_districts = (df["voting_districts"] <= 0).sum()

    range_results.append({
        "file": file.name,
        "negative_registered_voters": invalid_registered,
        "invalid_voting_districts": invalid_districts
    })

range_df = pd.DataFrame(range_results)

display(range_df)

print(
    "Negative registered voter values:",
    range_df["negative_registered_voters"].sum()
)

print(
    "Invalid voting district values:",
    range_df["invalid_voting_districts"].sum()
)

,file,negative_registered_voters,invalid_voting_districts
0,iec_kzn_ethekwini_ward_registration_2026.csv,0,0
1,iec_kzn_kzn212___umdoni_ward_registration_2026...,0,0
2,iec_kzn_kzn213___umzumbe_ward_registration_202...,0,0
3,iec_kzn_kzn214___umuziwabantu_ward_registratio...,0,0
4,iec_kzn_kzn216___ray_nkonyeni_ward_registratio...,0,0
5,iec_kzn_kzn221___umshwathi_ward_registration_2...,0,0
6,iec_kzn_kzn222___umngeni_ward_registration_202...,0,0
7,iec_kzn_kzn223___mpofana_ward_registration_202...,0,0
8,iec_kzn_kzn224___impendle_ward_registration_20...,0,0
9,iec_kzn_kzn225___msunduzi_ward_registration_20...,0,0
10,iec_kzn_kzn226___mkhambathini_ward_registratio...,0,0
11,iec_kzn_kzn227___richmond_ward_registration_20...,0,0
12,iec_kzn_kzn235___okhahlamba_ward_registration_...,0,0
13,iec_kzn_kzn237___inkosi_langalibalele_ward_reg...,0,0
14,iec_kzn_kzn238___alfred_duma_ward_registration...,0,0
15,iec_kzn_kzn241___endumeni_ward_registration_20...,0,0
16,iec_kzn_kzn242___nqutu_ward_registration_2026.csv,0,0
17,iec_kzn_kzn244___umsinga_ward_registration_202...,0,0
18,iec_kzn_kzn245___umvoti_ward_registration_2026...,0,0
19,iec_kzn_kzn252___newcastle_ward_registration_2...,0,0
20,iec_kzn_kzn253___emadlangeni_ward_registration...,0,0
21,iec_kzn_kzn254___dannhauser_ward_registration_...,0,0
22,iec_kzn_kzn261___edumbe_ward_registration_2026...,0,0
23,iec_kzn_kzn262___uphongolo_ward_registration_2...,0,0
24,iec_kzn_kzn263___abaqulusi_ward_registration_2...,0,0
25,iec_kzn_kzn265___nongoma_ward_registration_202...,0,0
26,iec_kzn_kzn266___ulundi_ward_registration_2026...,0,0
27,iec_kzn_kzn271___umhlabuyalingana_ward_registr...,0,0
28,iec_kzn_kzn272___jozini_ward_registration_2026...,0,0
29,iec_kzn_kzn275___inkosi_umtubatuba_ward_regist...,0,0
30,iec_kzn_kzn276___big_five_hlabisa_ward_registr...,0,0
31,iec_kzn_kzn281___umfolozi_ward_registration_20...,0,0
32,iec_kzn_kzn282___umhlathuze_ward_registration_...,0,0
33,iec_kzn_kzn284___umlalazi_ward_registration_20...,0,0
34,iec_kzn_kzn285___mthonjaneni_ward_registration...,0,0
35,iec_kzn_kzn286___nkandla_ward_registration_202...,0,0
36,iec_kzn_kzn291___mandeni_ward_registration_202...,0,0
37,iec_kzn_kzn292___kwadukuza_ward_registration_2...,0,0
38,iec_kzn_kzn293___ndwedwe_ward_registration_202...,0,0
39,iec_kzn_kzn294___maphumulo_ward_registration_2...,0,0
40,iec_kzn_kzn433___greater_kokstad_ward_registra...,0,0
41,iec_kzn_kzn434___johannes_phumani_pungula_ward...,0,0
42,iec_kzn_kzn435___umzimkhulu_ward_registration_...,0,0
43,iec_kzn_kzn436___dr._nkosazana_dlamini_zuma_wa...,0,0

Negative registered voter values: 0
Invalid voting district values: 0

In [21]:
row_check = []

for raw_file in raw_files:

    cleaned_file = interim_folder / raw_file.name

    raw_df = pd.read_csv(raw_file)
    cleaned_df = pd.read_csv(cleaned_file)

    row_check.append({
        "file": raw_file.name,
        "raw_rows": len(raw_df),
        "cleaned_rows": len(cleaned_df),
        "rows_preserved": len(raw_df) == len(cleaned_df)
    })

row_check_df = pd.DataFrame(row_check)

display(row_check_df)

print(
    "Files where row counts were not preserved:",
    (~row_check_df["rows_preserved"]).sum()
)

,file,raw_rows,cleaned_rows,rows_preserved
0,iec_kzn_ethekwini_ward_registration_2026.csv,112,112,True
1,iec_kzn_kzn212___umdoni_ward_registration_2026...,19,19,True
2,iec_kzn_kzn213___umzumbe_ward_registration_202...,20,20,True
3,iec_kzn_kzn214___umuziwabantu_ward_registratio...,11,11,True
4,iec_kzn_kzn216___ray_nkonyeni_ward_registratio...,36,36,True
5,iec_kzn_kzn221___umshwathi_ward_registration_2...,14,14,True
6,iec_kzn_kzn222___umngeni_ward_registration_202...,13,13,True
7,iec_kzn_kzn223___mpofana_ward_registration_202...,6,6,True
8,iec_kzn_kzn224___impendle_ward_registration_20...,6,6,True
9,iec_kzn_kzn225___msunduzi_ward_registration_20...,41,41,True
10,iec_kzn_kzn226___mkhambathini_ward_registratio...,10,10,True
11,iec_kzn_kzn227___richmond_ward_registration_20...,9,9,True
12,iec_kzn_kzn235___okhahlamba_ward_registration_...,15,15,True
13,iec_kzn_kzn237___inkosi_langalibalele_ward_reg...,24,24,True
14,iec_kzn_kzn238___alfred_duma_ward_registration...,37,37,True
15,iec_kzn_kzn241___endumeni_ward_registration_20...,8,8,True
16,iec_kzn_kzn242___nqutu_ward_registration_2026.csv,20,20,True
17,iec_kzn_kzn244___umsinga_ward_registration_202...,21,21,True
18,iec_kzn_kzn245___umvoti_ward_registration_2026...,14,14,True
19,iec_kzn_kzn252___newcastle_ward_registration_2...,36,36,True
20,iec_kzn_kzn253___emadlangeni_ward_registration...,6,6,True
21,iec_kzn_kzn254___dannhauser_ward_registration_...,13,13,True
22,iec_kzn_kzn261___edumbe_ward_registration_2026...,10,10,True
23,iec_kzn_kzn262___uphongolo_ward_registration_2...,15,15,True
24,iec_kzn_kzn263___abaqulusi_ward_registration_2...,24,24,True
25,iec_kzn_kzn265___nongoma_ward_registration_202...,23,23,True
26,iec_kzn_kzn266___ulundi_ward_registration_2026...,25,25,True
27,iec_kzn_kzn271___umhlabuyalingana_ward_registr...,20,20,True
28,iec_kzn_kzn272___jozini_ward_registration_2026...,25,25,True
29,iec_kzn_kzn275___inkosi_umtubatuba_ward_regist...,23,23,True
30,iec_kzn_kzn276___big_five_hlabisa_ward_registr...,14,14,True
31,iec_kzn_kzn281___umfolozi_ward_registration_20...,18,18,True
32,iec_kzn_kzn282___umhlathuze_ward_registration_...,36,36,True
33,iec_kzn_kzn284___umlalazi_ward_registration_20...,28,28,True
34,iec_kzn_kzn285___mthonjaneni_ward_registration...,13,13,True
35,iec_kzn_kzn286___nkandla_ward_registration_202...,14,14,True
36,iec_kzn_kzn291___mandeni_ward_registration_202...,18,18,True
37,iec_kzn_kzn292___kwadukuza_ward_registration_2...,30,30,True
38,iec_kzn_kzn293___ndwedwe_ward_registration_202...,19,19,True
39,iec_kzn_kzn294___maphumulo_ward_registration_2...,13,13,True
40,iec_kzn_kzn433___greater_kokstad_ward_registra...,11,11,True
41,iec_kzn_kzn434___johannes_phumani_pungula_ward...,14,14,True
42,iec_kzn_kzn435___umzimkhulu_ward_registration_...,22,22,True
43,iec_kzn_kzn436___dr._nkosazana_dlamini_zuma_wa...,15,15,True

Files where row counts were not preserved: 0

In [22]:
value_check = []

for raw_file in raw_files:

    cleaned_file = interim_folder / raw_file.name

    raw_df = pd.read_csv(raw_file)
    cleaned_df = pd.read_csv(cleaned_file)

    raw_values = (
        raw_df["registered_voters"]
        .astype(str)
        .str.strip()
        .str.replace(",", "", regex=False)
    )

    cleaned_values = (
        cleaned_df["registered_voters"]
        .astype(str)
        .str.strip()
    )

    mismatches = (
        raw_values != cleaned_values
    ).sum()

    value_check.append({
        "file": raw_file.name,
        "registered_voter_value_mismatches": mismatches
    })

value_check_df = pd.DataFrame(value_check)

display(value_check_df)

print(
    "Total registered voter value mismatches:",
    value_check_df["registered_voter_value_mismatches"].sum()
)

,file,registered_voter_value_mismatches
0,iec_kzn_ethekwini_ward_registration_2026.csv,0
1,iec_kzn_kzn212___umdoni_ward_registration_2026...,0
2,iec_kzn_kzn213___umzumbe_ward_registration_202...,0
3,iec_kzn_kzn214___umuziwabantu_ward_registratio...,0
4,iec_kzn_kzn216___ray_nkonyeni_ward_registratio...,0
5,iec_kzn_kzn221___umshwathi_ward_registration_2...,0
6,iec_kzn_kzn222___umngeni_ward_registration_202...,0
7,iec_kzn_kzn223___mpofana_ward_registration_202...,0
8,iec_kzn_kzn224___impendle_ward_registration_20...,0
9,iec_kzn_kzn225___msunduzi_ward_registration_20...,0
10,iec_kzn_kzn226___mkhambathini_ward_registratio...,0
11,iec_kzn_kzn227___richmond_ward_registration_20...,0
12,iec_kzn_kzn235___okhahlamba_ward_registration_...,0
13,iec_kzn_kzn237___inkosi_langalibalele_ward_reg...,0
14,iec_kzn_kzn238___alfred_duma_ward_registration...,0
15,iec_kzn_kzn241___endumeni_ward_registration_20...,0
16,iec_kzn_kzn242___nqutu_ward_registration_2026.csv,0
17,iec_kzn_kzn244___umsinga_ward_registration_202...,0
18,iec_kzn_kzn245___umvoti_ward_registration_2026...,0
19,iec_kzn_kzn252___newcastle_ward_registration_2...,0
20,iec_kzn_kzn253___emadlangeni_ward_registration...,0
21,iec_kzn_kzn254___dannhauser_ward_registration_...,0
22,iec_kzn_kzn261___edumbe_ward_registration_2026...,0
23,iec_kzn_kzn262___uphongolo_ward_registration_2...,0
24,iec_kzn_kzn263___abaqulusi_ward_registration_2...,0
25,iec_kzn_kzn265___nongoma_ward_registration_202...,0
26,iec_kzn_kzn266___ulundi_ward_registration_2026...,0
27,iec_kzn_kzn271___umhlabuyalingana_ward_registr...,0
28,iec_kzn_kzn272___jozini_ward_registration_2026...,0
29,iec_kzn_kzn275___inkosi_umtubatuba_ward_regist...,0
30,iec_kzn_kzn276___big_five_hlabisa_ward_registr...,0
31,iec_kzn_kzn281___umfolozi_ward_registration_20...,0
32,iec_kzn_kzn282___umhlathuze_ward_registration_...,0
33,iec_kzn_kzn284___umlalazi_ward_registration_20...,0
34,iec_kzn_kzn285___mthonjaneni_ward_registration...,0
35,iec_kzn_kzn286___nkandla_ward_registration_202...,0
36,iec_kzn_kzn291___mandeni_ward_registration_202...,0
37,iec_kzn_kzn292___kwadukuza_ward_registration_2...,0
38,iec_kzn_kzn293___ndwedwe_ward_registration_202...,0
39,iec_kzn_kzn294___maphumulo_ward_registration_2...,0
40,iec_kzn_kzn433___greater_kokstad_ward_registra...,0
41,iec_kzn_kzn434___johannes_phumani_pungula_ward...,0
42,iec_kzn_kzn435___umzimkhulu_ward_registration_...,0
43,iec_kzn_kzn436___dr._nkosazana_dlamini_zuma_wa...,0

Total registered voter value mismatches: 0

In [23]:
all_cleaned_data = []

for file in cleaned_files:

    df = pd.read_csv(file)

    df["source_file"] = file.name

    all_cleaned_data.append(df)

combined_check = pd.concat(
    all_cleaned_data,
    ignore_index=True
)

print("Total ward records:", len(combined_check))
print(
    "Minimum registered voters in a ward:",
    combined_check["registered_voters"].min()
)
print(
    "Maximum registered voters in a ward:",
    combined_check["registered_voters"].max()
)
print(
    "Wards with zero registered voters:",
    (combined_check["registered_voters"] == 0).sum()
)

Total ward records: 921
Minimum registered voters in a ward: 2632
Maximum registered voters in a ward: 24254
Wards with zero registered voters: 0

In [24]:
duplicate_wards_across_files = (
    combined_check["ward"]
    .duplicated()
    .sum()
)

print(
    "Duplicate ward codes across all 44 files:",
    duplicate_wards_across_files
)

Duplicate ward codes across all 44 files: 0

In [25]:
print("=" * 60)
print("FINAL CLEANING VALIDATION")
print("=" * 60)

print("Raw files:", len(raw_files))
print("Cleaned files:", len(cleaned_files))
print("Total ward records:", len(combined_check))

print(
    "Total missing values:",
    cleaned_missing_df["missing_values"].sum()
)

print(
    "Duplicate wards within files:",
    cleaned_duplicates_df["duplicate_wards"].sum()
)

print(
    "Duplicate ward codes across files:",
    duplicate_wards_across_files
)

print(
    "Registered voter values with commas:",
    comma_df["registered_voters_with_commas"].sum()
)

print(
    "Registered voter value mismatches:",
    value_check_df["registered_voter_value_mismatches"].sum()
)

print(
    "Files with lost/added rows:",
    (~row_check_df["rows_preserved"]).sum()
)

print(
    "Cleaned folder exists:",
    interim_folder.exists()
)

print(
    "All cleaned files exist:",
    len(cleaned_files) == len(raw_files)
)

============================================================
FINAL CLEANING VALIDATION
============================================================
Raw files: 44
Cleaned files: 44
Total ward records: 921
Total missing values: 0
Duplicate wards within files: 0
Duplicate ward codes across files: 0
Registered voter values with commas: 0
Registered voter value mismatches: 0
Files with lost/added rows: 0
Cleaned folder exists: True
All cleaned files exist: True