In [1]:
from pathlib import Path
import pandas as pd
import requests

PROJECT_ROOT = Path.cwd().parent

RAW_DIR = PROJECT_ROOT / "data" / "raw"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

IPSOS_RAW_DIR = RAW_DIR / "ipsos"
IPSOS_PROCESSED_DIR = PROCESSED_DIR / "ipsos"

IPSOS_RAW_DIR.mkdir(parents=True, exist_ok=True)
IPSOS_PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

print("Raw folder:", IPSOS_RAW_DIR)
print("Processed folder:", IPSOS_PROCESSED_DIR)

Raw folder: c:\Users\Admin\Desktop\Dirisa_1\SPU-TEAM-DIRISA\data\raw\ipsos
Processed folder: c:\Users\Admin\Desktop\Dirisa_1\SPU-TEAM-DIRISA\data\processed\ipsos

In [2]:
IPSOS_URL = "https://www.ipsos.com/en-za/nearly-half-south-africans-feel-politically-homeless-ahead-local-elections"

response = requests.get(IPSOS_URL, timeout=30)

print("Status code:", response.status_code)
print("Page size:", len(response.text))

Status code: 200
Page size: 52975

In [3]:
raw_article_file = IPSOS_RAW_DIR / "ipsos_2026_politically_homeless_article.html"

with open(raw_article_file, "w", encoding="utf-8") as file:
    file.write(response.text)

print("Saved:", raw_article_file)
print("File exists:", raw_article_file.exists())
print("File size:", raw_article_file.stat().st_size, "bytes")

Saved: c:\Users\Admin\Desktop\Dirisa_1\SPU-TEAM-DIRISA\data\raw\ipsos\ipsos_2026_politically_homeless_article.html
File exists: True
File size: 53655 bytes

In [4]:
IPSOS_CHARTS_URL = "https://www.ipsos.com/sites/default/files/ct/news/documents/2026-03/Ipsos%20Khayabus%20Pulse%20of%20the%20People%20-%20Local%20Government%20Elections%20Charts.pdf"

charts_response = requests.get(
    IPSOS_CHARTS_URL,
    timeout=30
)

print("Status code:", charts_response.status_code)
print("Content type:", charts_response.headers.get("Content-Type"))
print("File size:", len(charts_response.content), "bytes")

Status code: 404
Content type: text/html; charset=UTF-8
File size: 37382 bytes

In [5]:
IPSOS_CHARTS_URL = (
    "https://www.ipsos.com/sites/default/files/ct/news/documents/2026-03/"
    "Nearly%20half%20of%20South%20Africans%20feel%20politically%20homeless%20ahead%20of%20local%20elections_Ipsos_Press%20Release_26%20March%202026%20-%20Charts.pdf"
)

charts_response = requests.get(
    IPSOS_CHARTS_URL,
    timeout=30
)

print("Status code:", charts_response.status_code)
print("Content type:", charts_response.headers.get("Content-Type"))
print("File size:", len(charts_response.content), "bytes")

Status code: 200
Content type: application/pdf
File size: 362630 bytes

In [6]:
raw_charts_file = (
    IPSOS_RAW_DIR
    / "ipsos_2026_local_government_elections_charts.pdf"
)

with open(raw_charts_file, "wb") as file:
    file.write(charts_response.content)

print("Saved:", raw_charts_file)
print("File exists:", raw_charts_file.exists())
print("File size:", raw_charts_file.stat().st_size, "bytes")

Saved: c:\Users\Admin\Desktop\Dirisa_1\SPU-TEAM-DIRISA\data\raw\ipsos\ipsos_2026_local_government_elections_charts.pdf
File exists: True
File size: 362630 bytes

In [8]:
%pip install PyPDF2

Defaulting to user installation because normal site-packages is not writeable
Collecting PyPDF2
  Downloading pypdf2-3.0.1-py3-none-any.whl.metadata (6.8 kB)
Downloading pypdf2-3.0.1-py3-none-any.whl (232 kB)
Installing collected packages: PyPDF2
Successfully installed PyPDF2-3.0.1
Note: you may need to restart the kernel to use updated packages.

In [10]:
import PyPDF2

pdf_file = open(raw_charts_file, "rb")

pdf_reader = PyPDF2.PdfReader(pdf_file)

print("Number of pages:", len(pdf_reader.pages))

Number of pages: 7

In [13]:
import PyPDF2

with open(raw_charts_file, "rb") as file:
    pdf_reader = PyPDF2.PdfReader(file)
    
    print("Number of pages:", len(pdf_reader.pages))
    
    for page_number in range(len(pdf_reader.pages)):
        page = pdf_reader.pages[page_number]
        text = page.extract_text()
        
        print("=" * 80)
        print(f"PAGE {page_number + 1}")
        print("=" * 80)
        
        if text:
            print(text[:5000])
        else:
            print("No text could be extracted from this page.")
        
        print()

Number of pages: 7
================================================================================
PAGE 1
================================================================================
© 2024 Ipsos. All rights reserved.
Contains Ipsos' Confidential and
Proprietary information and may not
be disclosed or reproduced without
the prior written consent of Ipsos.
NEARLY HALF OF
SOUTH AFRICANS
FEEL POLITICALLY
HOMELESS AHEAD
OF LOCAL
ELECTIONS
Ipsos in South Africa
26 March 2026
© 2026 Ipsos. All rights reserved.
Contains Ipsos' Confidential and
Proprietary information and may not
be disclosed or reproduced without
the prior written consent of Ipsos.


================================================================================
PAGE 2
================================================================================
Source: Ipsos Khayabus |  © Ipsos 2026
Nearly half of South Africans feel politically homeless ahead of local elections   (26 March 2026)Despite the
upcoming
elections,
interest in
politics
remains
notably
subdued
Q:How interested are
you in politics and
elections ? 27%
34%38%1%Very interested
Somewhat interested
Not interested
Don’t know

================================================================================
PAGE 3
================================================================================
Source: Ipsos Khayabus |  © Ipsos 2026
Nearly half of South Africans feel politically homeless ahead of local elections   (26 March 2026)About two -
thirds of eligible
voters indicate
that they have
the desire and
intention to
vote in the
Local
Government
Elections
Q:How important is
casting your vote in the
2026 Local Government
Elections to you
personally?35%
31%15%17%2%Extremely important
Quite important
So-so
Not at all important
Don’t know

================================================================================
PAGE 4
================================================================================
Source: Ipsos Khayabus |  © Ipsos 2026
Nearly half of South Africans feel politically homeless ahead of local elections   (26 March 2026)Trust in
South
Africa's
electoral
institutions
remains
divided.
Q:How likely are you to
trust the IEC
(Independent Electoral
Commission)?11%
28%
18%17%23%3%Extremely likely
Very likely
Neither likely nor
unlikely
Not very likely
Not at all likely
Don’t know

================================================================================
PAGE 5
================================================================================
Source: Ipsos Khayabus |  © Ipsos 2026
Nearly half of South Africans feel politically homeless ahead of local elections   (26 March 2026)The results were analysed across different voter groups
33%
22%
11%
10%
3%
2%
2%
1%
4%
12%35%
22%
11%
11%
3%
3%
3%
1%
3%
8%38%
22%
13%
13%
3%
4%
2%
1%
4%
*38%
22%
12%
14%
3%
4%
3%
2%
2%
*35%
25%
13%
14%
4%
4%
2%
1%
2%
*
ANC DA EFF MKP PA ActionSA IFP FF+ Other
partyWill not
voteNational Vote: All
Eligible to Vote 18+
Registered Voters
National vote
Local govt. Vote: All
Eligible to Vote 18+
Registered Voters Local
Govt. Vote
Registered Voters Local
Govt. Vote Metropolitan
areas onlyAll eligible voters (18+), registered voters only, and registered voters in metropolitan areas, looking at both
national and local government voting intentions and party choices.

================================================================================
PAGE 6
================================================================================
6 © Ipsos 2025
Survey Methodology in detail
Khayabus :
This press release is based on the
views of 3,600 randomly selected
respondents. Interviews were
conducted by trained Ipsos
interviewers in the homes and
home languages of respondents.
Interviews were conducted
between December 2025 and
January 2026 –with a 2 -week break
over the festive period.
A scientific process of multi -stage
stratified random selection distributed interviews in all areas of
the county, including deep rural
areas. This methodology ensured
that the results are representative
of the views of the universe (adult
South Africans) and that findings
can be weighted and projected to
the universe.
Trained quantitative fieldworkers
were responsible for the
interviewing and CAPI (Computer -
Assisted Personal Interviewing) was
used.
All results were collated and analysed in an aggregate format to
protect the identity and
confidentiality of respondents.
All sample surveys are subject to a
margin of error, determined by
sample size, sampling methodology
and response rate. The sample
error for this sample at a 95%
confidence level is a maximum of
plus or minus 1.9%.
6

================================================================================
PAGE 7
================================================================================
© 2024 Ipsos. All rights reserved.
Contains Ipsos' Confidential and
Proprietary information and may not
be disclosed or reproduced without
the prior written consent of Ipsos.
© 2026 Ipsos. All rights reserved.
Contains Ipsos' Confidential and
Proprietary information and may not
be disclosed or reproduced without
the prior written consent of Ipsos.southafrica@ipsos.com
011 709 7800
3021 Winnie Mandela Drive, Bryanston, Johannesburg, 2191
Golf Park 4, Raapenberg Road, Pinelands, Cape Town, 7405
CONTACT US
CONNECT WITH US
@ipsos -south -africa
@IpsosSouthAfrica
@ipsos_sa @ipsossouthafricawww.ipsos.com/en -za
@ipsos -south -africaTHANK YOU

In [14]:
for page_number, page in enumerate(pdf_reader.pages, start=1):
    text = page.extract_text()
    
    print("=" * 80)
    print(f"PAGE {page_number}")
    print("=" * 80)
    
    if text:
        print(text[:5000])
    else:
        print("No text could be extracted from this page.")
    
    print()

================================================================================
PAGE 1
================================================================================
© 2024 Ipsos. All rights reserved.
Contains Ipsos' Confidential and
Proprietary information and may not
be disclosed or reproduced without
the prior written consent of Ipsos.
NEARLY HALF OF
SOUTH AFRICANS
FEEL POLITICALLY
HOMELESS AHEAD
OF LOCAL
ELECTIONS
Ipsos in South Africa
26 March 2026
© 2026 Ipsos. All rights reserved.
Contains Ipsos' Confidential and
Proprietary information and may not
be disclosed or reproduced without
the prior written consent of Ipsos.


================================================================================
PAGE 2
================================================================================
Source: Ipsos Khayabus |  © Ipsos 2026
Nearly half of South Africans feel politically homeless ahead of local elections   (26 March 2026)Despite the
upcoming
elections,
interest in
politics
remains
notably
subdued
Q:How interested are
you in politics and
elections ? 27%
34%38%1%Very interested
Somewhat interested
Not interested
Don’t know

================================================================================
PAGE 3
================================================================================
Source: Ipsos Khayabus |  © Ipsos 2026
Nearly half of South Africans feel politically homeless ahead of local elections   (26 March 2026)About two -
thirds of eligible
voters indicate
that they have
the desire and
intention to
vote in the
Local
Government
Elections
Q:How important is
casting your vote in the
2026 Local Government
Elections to you
personally?35%
31%15%17%2%Extremely important
Quite important
So-so
Not at all important
Don’t know

================================================================================
PAGE 4
================================================================================
Source: Ipsos Khayabus |  © Ipsos 2026
Nearly half of South Africans feel politically homeless ahead of local elections   (26 March 2026)Trust in
South
Africa's
electoral
institutions
remains
divided.
Q:How likely are you to
trust the IEC
(Independent Electoral
Commission)?11%
28%
18%17%23%3%Extremely likely
Very likely
Neither likely nor
unlikely
Not very likely
Not at all likely
Don’t know

================================================================================
PAGE 5
================================================================================
Source: Ipsos Khayabus |  © Ipsos 2026
Nearly half of South Africans feel politically homeless ahead of local elections   (26 March 2026)The results were analysed across different voter groups
33%
22%
11%
10%
3%
2%
2%
1%
4%
12%35%
22%
11%
11%
3%
3%
3%
1%
3%
8%38%
22%
13%
13%
3%
4%
2%
1%
4%
*38%
22%
12%
14%
3%
4%
3%
2%
2%
*35%
25%
13%
14%
4%
4%
2%
1%
2%
*
ANC DA EFF MKP PA ActionSA IFP FF+ Other
partyWill not
voteNational Vote: All
Eligible to Vote 18+
Registered Voters
National vote
Local govt. Vote: All
Eligible to Vote 18+
Registered Voters Local
Govt. Vote
Registered Voters Local
Govt. Vote Metropolitan
areas onlyAll eligible voters (18+), registered voters only, and registered voters in metropolitan areas, looking at both
national and local government voting intentions and party choices.

================================================================================
PAGE 6
================================================================================
6 © Ipsos 2025
Survey Methodology in detail
Khayabus :
This press release is based on the
views of 3,600 randomly selected
respondents. Interviews were
conducted by trained Ipsos
interviewers in the homes and
home languages of respondents.
Interviews were conducted
between December 2025 and
January 2026 –with a 2 -week break
over the festive period.
A scientific process of multi -stage
stratified random selection distributed interviews in all areas of
the county, including deep rural
areas. This methodology ensured
that the results are representative
of the views of the universe (adult
South Africans) and that findings
can be weighted and projected to
the universe.
Trained quantitative fieldworkers
were responsible for the
interviewing and CAPI (Computer -
Assisted Personal Interviewing) was
used.
All results were collated and analysed in an aggregate format to
protect the identity and
confidentiality of respondents.
All sample surveys are subject to a
margin of error, determined by
sample size, sampling methodology
and response rate. The sample
error for this sample at a 95%
confidence level is a maximum of
plus or minus 1.9%.
6

================================================================================
PAGE 7
================================================================================
© 2024 Ipsos. All rights reserved.
Contains Ipsos' Confidential and
Proprietary information and may not
be disclosed or reproduced without
the prior written consent of Ipsos.
© 2026 Ipsos. All rights reserved.
Contains Ipsos' Confidential and
Proprietary information and may not
be disclosed or reproduced without
the prior written consent of Ipsos.southafrica@ipsos.com
011 709 7800
3021 Winnie Mandela Drive, Bryanston, Johannesburg, 2191
Golf Park 4, Raapenberg Road, Pinelands, Cape Town, 7405
CONTACT US
CONNECT WITH US
@ipsos -south -africa
@IpsosSouthAfrica
@ipsos_sa @ipsossouthafricawww.ipsos.com/en -za
@ipsos -south -africaTHANK YOU

In [15]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(response.text, "html.parser")

article_text = soup.get_text(
    separator="\n",
    strip=True
)

print("Article text length:", len(article_text))

print("\n--- KZN / PROVINCE ---")
for keyword in ["KwaZulu-Natal", "KZN", "Gauteng", "Northern Cape", "North West", "Limpopo"]:
    if keyword.lower() in article_text.lower():
        print(f"Found: {keyword}")

print("\n--- AGE ---")
for keyword in ["18-24", "25-34", "18–24", "25–34", "young"]:
    if keyword.lower() in article_text.lower():
        print(f"Found: {keyword}")

print("\n--- TRUST ---")
for keyword in ["trust", "IEC", "electoral"]:
    print(f"{keyword}: {article_text.lower().count(keyword.lower())} occurrence(s)")

Article text length: 10949

--- KZN / PROVINCE ---
Found: KwaZulu-Natal
Found: Gauteng
Found: Northern Cape
Found: Limpopo

--- AGE ---
Found: 18-24
Found: 25-34
Found: young

--- TRUST ---
trust: 10 occurrence(s)
IEC: 9 occurrence(s)
electoral: 4 occurrence(s)

In [16]:
keywords = [
    "KwaZulu-Natal",
    "KZN",
    "18-24",
    "25-34",
    "trust",
    "registered",
    "vote",
    "politics"
]

for keyword in keywords:
    print("\n" + "=" * 80)
    print(f"SEARCHING FOR: {keyword}")
    print("=" * 80)

    text_lower = article_text.lower()
    keyword_lower = keyword.lower()

    start = 0
    found = False

    while True:
        position = text_lower.find(keyword_lower, start)

        if position == -1:
            break

        found = True

        # Show surrounding text
        section_start = max(0, position - 350)
        section_end = min(len(article_text), position + 700)

        print(article_text[section_start:section_end])
        print("-" * 80)

        start = position + len(keyword_lower)

    if not found:
        print("No matches found.")

================================================================================
SEARCHING FOR: KwaZulu-Natal
================================================================================
ions are split, with similar proportions expressing trust and distrust:
The data reveals information about where knowledge and trust-building of the role of the IEC are needed most:
Young voters are most sceptical:
40% of 18-24-year-olds and 42% of 25-34-year-olds are more unlikely to trust the IEC.
Provincial divides exist:
Distrust is highest in KwaZulu-Natal (58%), Northern Cape (52%), NorthWest (42%), and Limpopo (42%).
Geographic priorities emerge:
Given population sizes, KwaZulu-Natal and Gauteng, along with metropolitan areas and rural villages, should be focal points for trust-building efforts.
"These findings point to clear priorities for voter education," says Harris. "Young people and certain provinces need targeted engagement if we want to see improved turnout and build confidence in the electoral process."
Support for political parties
To ensure authentic responses, the party support questions were asked using a confidential digital "ballot paper" approach: the electronic device is passed directly to respondents, who mark
--------------------------------------------------------------------------------
-building of the role of the IEC are needed most:
Young voters are most sceptical:
40% of 18-24-year-olds and 42% of 25-34-year-olds are more unlikely to trust the IEC.
Provincial divides exist:
Distrust is highest in KwaZulu-Natal (58%), Northern Cape (52%), NorthWest (42%), and Limpopo (42%).
Geographic priorities emerge:
Given population sizes, KwaZulu-Natal and Gauteng, along with metropolitan areas and rural villages, should be focal points for trust-building efforts.
"These findings point to clear priorities for voter education," says Harris. "Young people and certain provinces need targeted engagement if we want to see improved turnout and build confidence in the electoral process."
Support for political parties
To ensure authentic responses, the party support questions were asked using a confidential digital "ballot paper" approach: the electronic device is passed directly to respondents, who mark their own party choices on a graphic replicating a real ballot paper. This method is designed to resemble an actual election and re
--------------------------------------------------------------------------------

================================================================================
SEARCHING FOR: KZN
================================================================================
No matches found.

================================================================================
SEARCHING FOR: 18-24
================================================================================
ant” to them
The stumbling blocks
Trust in South Africa's electoral institutions remains divided. When asked about the IEC, opinions are split, with similar proportions expressing trust and distrust:
The data reveals information about where knowledge and trust-building of the role of the IEC are needed most:
Young voters are most sceptical:
40% of 18-24-year-olds and 42% of 25-34-year-olds are more unlikely to trust the IEC.
Provincial divides exist:
Distrust is highest in KwaZulu-Natal (58%), Northern Cape (52%), NorthWest (42%), and Limpopo (42%).
Geographic priorities emerge:
Given population sizes, KwaZulu-Natal and Gauteng, along with metropolitan areas and rural villages, should be focal points for trust-building efforts.
"These findings point to clear priorities for voter education," says Harris. "Young people and certain provinces need targeted engagement if we want to see improved turnout and build confidence in the electoral process."
Support for political parties
To ensure authentic responses, the party support questions we
--------------------------------------------------------------------------------

================================================================================
SEARCHING FOR: 25-34
================================================================================
blocks
Trust in South Africa's electoral institutions remains divided. When asked about the IEC, opinions are split, with similar proportions expressing trust and distrust:
The data reveals information about where knowledge and trust-building of the role of the IEC are needed most:
Young voters are most sceptical:
40% of 18-24-year-olds and 42% of 25-34-year-olds are more unlikely to trust the IEC.
Provincial divides exist:
Distrust is highest in KwaZulu-Natal (58%), Northern Cape (52%), NorthWest (42%), and Limpopo (42%).
Geographic priorities emerge:
Given population sizes, KwaZulu-Natal and Gauteng, along with metropolitan areas and rural villages, should be focal points for trust-building efforts.
"These findings point to clear priorities for voter education," says Harris. "Young people and certain provinces need targeted engagement if we want to see improved turnout and build confidence in the electoral process."
Support for political parties
To ensure authentic responses, the party support questions were asked using a confidenti
--------------------------------------------------------------------------------

================================================================================
SEARCHING FOR: trust
================================================================================

Ipsos around the world
Privacy & Data Protection
Search
Submit
Ipsos
Insights Hub
Nearly half of South Africans feel politically homeless ahead of local elections
Politics
South Africa
Government
+2
Election
Polling
Nearly half of South Africans feel politically homeless ahead of local elections
Ipsos study reveals voter alienation, low municipal trust, and a mixed appetite for polls as 2026/7 elections approach – regardless of a choice of more than 500 parties
26.03.26
Share
As South Africa gears up for local government elections (required by law to take place between 2 November 2026 and 31 January 2027), new Ipsos research reveals a nation grappling with political disconnection: nearly half (47%) of South Africans say no political party represents their views, this despite more than 500 parties being registered with the
IEC
. Yet democratic hope persists. Six in ten eligible voters (61%) say they are looking forward to voting, even as only 38% believe their local governments/municipalities are doing their jobs well.
"South Africans
--------------------------------------------------------------------------------
work was completed between December 2025 and January 2026.
Key findings include:
Political alienation:
47% of South Africans say no political party represents their views
Municipal dissatisfaction:
Only 38% believe their local government is doing its job well
Limited interest:
38% of eligible voters have no interest in politics and elections
Youth trust deficit:
40% of 18-34-year-olds do not trust the IEC
Desire to vote:
64% say they want to vote in the upcoming local elections
Coalition appetite:
63% believe political parties should work together at local government level
Although the exact election date remains unknown, political campaigning is already in full swing. The IEC is planning special “registration weekends”, but potential voters should note they can register to vote at any time, either online or at their nearest IEC office, and this process is ongoing. Under the Electoral Act, the voters' roll closes as soon as an election date is announced.
The political mood in the country
Given the sheer number of choices available to
--------------------------------------------------------------------------------
January 2026.
Key findings include:
Political alienation:
47% of South Africans say no political party represents their views
Municipal dissatisfaction:
Only 38% believe their local government is doing its job well
Limited interest:
38% of eligible voters have no interest in politics and elections
Youth trust deficit:
40% of 18-34-year-olds do not trust the IEC
Desire to vote:
64% say they want to vote in the upcoming local elections
Coalition appetite:
63% believe political parties should work together at local government level
Although the exact election date remains unknown, political campaigning is already in full swing. The IEC is planning special “registration weekends”, but potential voters should note they can register to vote at any time, either online or at their nearest IEC office, and this process is ongoing. Under the Electoral Act, the voters' roll closes as soon as an election date is announced.
The political mood in the country
Given the sheer number of choices available to voters, it may seem paradoxical that 47% of S
--------------------------------------------------------------------------------
igible voters indicate that they have the desire and intention to vote in the Local Government Elections:
64% say they want to vote (21% "definitely want to" and 43% "want to")
67% say they are likely to vote (27% "very likely" and 40% "likely")
66% say voting in the local government elections is “personally important” to them
The stumbling blocks
Trust in South Africa's electoral institutions remains divided. When asked about the IEC, opinions are split, with similar proportions expressing trust and distrust:
The data reveals information about where knowledge and trust-building of the role of the IEC are needed most:
Young voters are most sceptical:
40% of 18-24-year-olds and 42% of 25-34-year-olds are more unlikely to trust the IEC.
Provincial divides exist:
Distrust is highest in KwaZulu-Natal (58%), Northern Cape (52%), NorthWest (42%), and Limpopo (42%).
Geographic priorities emerge:
Given population sizes, KwaZulu-Natal and Gauteng, along with metropolitan areas and rural villages, should be focal points for trust-building effor
--------------------------------------------------------------------------------
ly want to" and 43% "want to")
67% say they are likely to vote (27% "very likely" and 40% "likely")
66% say voting in the local government elections is “personally important” to them
The stumbling blocks
Trust in South Africa's electoral institutions remains divided. When asked about the IEC, opinions are split, with similar proportions expressing trust and distrust:
The data reveals information about where knowledge and trust-building of the role of the IEC are needed most:
Young voters are most sceptical:
40% of 18-24-year-olds and 42% of 25-34-year-olds are more unlikely to trust the IEC.
Provincial divides exist:
Distrust is highest in KwaZulu-Natal (58%), Northern Cape (52%), NorthWest (42%), and Limpopo (42%).
Geographic priorities emerge:
Given population sizes, KwaZulu-Natal and Gauteng, along with metropolitan areas and rural villages, should be focal points for trust-building efforts.
"These findings point to clear priorities for voter education," says Harris. "Young people and certain provinces need targeted engagement if w
--------------------------------------------------------------------------------
nd 43% "want to")
67% say they are likely to vote (27% "very likely" and 40% "likely")
66% say voting in the local government elections is “personally important” to them
The stumbling blocks
Trust in South Africa's electoral institutions remains divided. When asked about the IEC, opinions are split, with similar proportions expressing trust and distrust:
The data reveals information about where knowledge and trust-building of the role of the IEC are needed most:
Young voters are most sceptical:
40% of 18-24-year-olds and 42% of 25-34-year-olds are more unlikely to trust the IEC.
Provincial divides exist:
Distrust is highest in KwaZulu-Natal (58%), Northern Cape (52%), NorthWest (42%), and Limpopo (42%).
Geographic priorities emerge:
Given population sizes, KwaZulu-Natal and Gauteng, along with metropolitan areas and rural villages, should be focal points for trust-building efforts.
"These findings point to clear priorities for voter education," says Harris. "Young people and certain provinces need targeted engagement if we want to see
--------------------------------------------------------------------------------
ikely" and 40% "likely")
66% say voting in the local government elections is “personally important” to them
The stumbling blocks
Trust in South Africa's electoral institutions remains divided. When asked about the IEC, opinions are split, with similar proportions expressing trust and distrust:
The data reveals information about where knowledge and trust-building of the role of the IEC are needed most:
Young voters are most sceptical:
40% of 18-24-year-olds and 42% of 25-34-year-olds are more unlikely to trust the IEC.
Provincial divides exist:
Distrust is highest in KwaZulu-Natal (58%), Northern Cape (52%), NorthWest (42%), and Limpopo (42%).
Geographic priorities emerge:
Given population sizes, KwaZulu-Natal and Gauteng, along with metropolitan areas and rural villages, should be focal points for trust-building efforts.
"These findings point to clear priorities for voter education," says Harris. "Young people and certain provinces need targeted engagement if we want to see improved turnout and build confidence in the electoral proces
--------------------------------------------------------------------------------
ral institutions remains divided. When asked about the IEC, opinions are split, with similar proportions expressing trust and distrust:
The data reveals information about where knowledge and trust-building of the role of the IEC are needed most:
Young voters are most sceptical:
40% of 18-24-year-olds and 42% of 25-34-year-olds are more unlikely to trust the IEC.
Provincial divides exist:
Distrust is highest in KwaZulu-Natal (58%), Northern Cape (52%), NorthWest (42%), and Limpopo (42%).
Geographic priorities emerge:
Given population sizes, KwaZulu-Natal and Gauteng, along with metropolitan areas and rural villages, should be focal points for trust-building efforts.
"These findings point to clear priorities for voter education," says Harris. "Young people and certain provinces need targeted engagement if we want to see improved turnout and build confidence in the electoral process."
Support for political parties
To ensure authentic responses, the party support questions were asked using a confidential digital "ballot paper" approach: t
--------------------------------------------------------------------------------
 about the IEC, opinions are split, with similar proportions expressing trust and distrust:
The data reveals information about where knowledge and trust-building of the role of the IEC are needed most:
Young voters are most sceptical:
40% of 18-24-year-olds and 42% of 25-34-year-olds are more unlikely to trust the IEC.
Provincial divides exist:
Distrust is highest in KwaZulu-Natal (58%), Northern Cape (52%), NorthWest (42%), and Limpopo (42%).
Geographic priorities emerge:
Given population sizes, KwaZulu-Natal and Gauteng, along with metropolitan areas and rural villages, should be focal points for trust-building efforts.
"These findings point to clear priorities for voter education," says Harris. "Young people and certain provinces need targeted engagement if we want to see improved turnout and build confidence in the electoral process."
Support for political parties
To ensure authentic responses, the party support questions were asked using a confidential digital "ballot paper" approach: the electronic device is passed directly to r
--------------------------------------------------------------------------------
s and 42% of 25-34-year-olds are more unlikely to trust the IEC.
Provincial divides exist:
Distrust is highest in KwaZulu-Natal (58%), Northern Cape (52%), NorthWest (42%), and Limpopo (42%).
Geographic priorities emerge:
Given population sizes, KwaZulu-Natal and Gauteng, along with metropolitan areas and rural villages, should be focal points for trust-building efforts.
"These findings point to clear priorities for voter education," says Harris. "Young people and certain provinces need targeted engagement if we want to see improved turnout and build confidence in the electoral process."
Support for political parties
To ensure authentic responses, the party support questions were asked using a confidential digital "ballot paper" approach: the electronic device is passed directly to respondents, who mark their own party choices on a graphic replicating a real ballot paper. This method is designed to resemble an actual election and reassure respondents that their choices remain confidential.
The results were analysed across different vo
--------------------------------------------------------------------------------

================================================================================
SEARCHING FOR: registered
================================================================================
s
26.03.26
Share
As South Africa gears up for local government elections (required by law to take place between 2 November 2026 and 31 January 2027), new Ipsos research reveals a nation grappling with political disconnection: nearly half (47%) of South Africans say no political party represents their views, this despite more than 500 parties being registered with the
IEC
. Yet democratic hope persists. Six in ten eligible voters (61%) say they are looking forward to voting, even as only 38% believe their local governments/municipalities are doing their jobs well.
"South Africans are caught between disillusionment and determination," says Mari Harris, Political Analyst at Ipsos in South Africa. "Nearly half feel no party represents them, yet the majority still want to exercise their democratic right. This tension will define the upcoming local government elections."
These are findings from the Ipsos Khayabus "Pulse of the People" study, conducted twice yearly through face-to-face in-home interviews with 3,600 randomly selected South Af
--------------------------------------------------------------------------------
sult that service delivery invariably suffers."
Despite the upcoming elections, interest in politics remains notably subdued:
Only six in ten (61%) South Africans eligible to vote say that they have any interest in politics and elections, while 38% are not interested at all. Despite this, nearly three-quarters (73%) of eligible voters say they are registered to vote. However, registration does not guarantee turnout.
The trend of voter alienation and disengagement has grown stronger over recent election cycles, a pattern clearly visible in IEC-calculated turnout rates, particularly since the 2016 Local Government Elections. It's important to note that these turnout figures are based on the proportion of registered voters who participate, not the total eligible voting population.
"When you look at the proportion of eligible voters who actually participate in elections, the numbers are sobering," says Harris. "Voter education and inspiration to register to vote cannot be the IEC's responsibility alone. Concerned citizens, community and c
--------------------------------------------------------------------------------
o vote. However, registration does not guarantee turnout.
The trend of voter alienation and disengagement has grown stronger over recent election cycles, a pattern clearly visible in IEC-calculated turnout rates, particularly since the 2016 Local Government Elections. It's important to note that these turnout figures are based on the proportion of registered voters who participate, not the total eligible voting population.

In [17]:
paragraphs = soup.find_all("p")

print("Number of paragraphs:", len(paragraphs))

for i, paragraph in enumerate(paragraphs):
    text = paragraph.get_text(" ", strip=True)
    
    # Show paragraphs containing information relevant to our project
    relevant_words = [
        "vote",
        "voter",
        "election",
        "politic",
        "IEC",
        "trust",
        "interest",
        "registered",
        "local government",
        "KwaZulu-Natal",
        "KZN",
        "young",
        "18-24",
        "25-34",
        "%"
    ]
    
    if any(word.lower() in text.lower() for word in relevant_words):
        print(f"\n--- Paragraph {i + 1} ---")
        print(text)

Number of paragraphs: 24

--- Paragraph 1 ---
As South Africa gears up for local government elections (required by law to take place between 2 November 2026 and 31 January 2027), new Ipsos research reveals a nation grappling with political disconnection: nearly half (47%) of South Africans say no political party represents their views, this despite more than 500 parties being registered with the IEC . Yet democratic hope persists. Six in ten eligible voters (61%) say they are looking forward to voting, even as only 38% believe their local governments/municipalities are doing their jobs well.

--- Paragraph 2 ---
"South Africans are caught between disillusionment and determination," says Mari Harris, Political Analyst at Ipsos in South Africa. "Nearly half feel no party represents them, yet the majority still want to exercise their democratic right. This tension will define the upcoming local government elections."

--- Paragraph 4 ---
Although the exact election date remains unknown, political campaigning is already in full swing. The IEC is planning special “registration weekends”, but potential voters should note they can register to vote at any time, either online or at their nearest IEC office, and this process is ongoing. Under the Electoral Act, the voters' roll closes as soon as an election date is announced.

--- Paragraph 5 ---
Given the sheer number of choices available to voters, it may seem paradoxical that 47% of South Africans say no party represents their views.

--- Paragraph 6 ---
"Too many parties with conflicting messages, focused at winning the support of voters, can create confusion rather than clarity," says Harris. "It's telling that almost half (47%) of South Africans agree that parties with less than 1% national support should be excluded from Parliament 1 . While that question referred to national politics, the same dynamic plays out at local government level, where small parties can become 'kingmakers' without necessarily contributing to stable governance in the municipality, with the result that service delivery invariably suffers."

--- Paragraph 7 ---
Despite the upcoming elections, interest in politics remains notably subdued:

--- Paragraph 8 ---
Only six in ten (61%) South Africans eligible to vote say that they have any interest in politics and elections, while 38% are not interested at all. Despite this, nearly three-quarters (73%) of eligible voters say they are registered to vote. However, registration does not guarantee turnout.

--- Paragraph 9 ---
The trend of voter alienation and disengagement has grown stronger over recent election cycles, a pattern clearly visible in IEC-calculated turnout rates, particularly since the 2016 Local Government Elections. It's important to note that these turnout figures are based on the proportion of registered voters who participate, not the total eligible voting population.

--- Paragraph 10 ---
"When you look at the proportion of eligible voters who actually participate in elections, the numbers are sobering," says Harris. "Voter education and inspiration to register to vote cannot be the IEC's responsibility alone. Concerned citizens, community and civic organisations, and political parties all have a civic duty to encourage participation."

--- Paragraph 11 ---
The current situation is that roughly two-thirds of eligible voters indicate that they have the desire and intention to vote in the Local Government Elections:

--- Paragraph 12 ---
Trust in South Africa's electoral institutions remains divided. When asked about the IEC, opinions are split, with similar proportions expressing trust and distrust:

--- Paragraph 13 ---
The data reveals information about where knowledge and trust-building of the role of the IEC are needed most:

--- Paragraph 14 ---
"These findings point to clear priorities for voter education," says Harris. "Young people and certain provinces need targeted engagement if we want to see improved turnout and build confidence in the electoral process."

--- Paragraph 15 ---
To ensure authentic responses, the party support questions were asked using a confidential digital "ballot paper" approach: the electronic device is passed directly to respondents, who mark their own party choices on a graphic replicating a real ballot paper. This method is designed to resemble an actual election and reassure respondents that their choices remain confidential.

--- Paragraph 16 ---
The results were analysed across different voter groups: all eligible voters (18+), registered voters only, and registered voters in metropolitan areas, looking at both national and local government voting intentions and party choices.

--- Paragraph 17 ---
The ANC remains the party most supported by registered voters for local government elections at 38%, followed by the DA at 22%. MKP (14%) and the EFF (12%) are closely matched, followed at some distance by ActionSA at 4% and the IFP and PA each at 3% each. The FF+ registers 2%, and it is the last party receiving more than 1% of the vote.

--- Paragraph 18 ---
"The picture for local government shows a competitive landscape," says Harris. "While the ANC maintains its lead, the combined opposition vote suggests many municipalities could see coalition negotiations after the elections."

--- Paragraph 19 ---
Despite mixed views on the current Government of National Unity, the concept of coalition governance is gaining acceptance. While 43% of South Africans agree that the GNU is working well and represents a better form of government than ANC majority rule, 27% disagree. However, support for cooperation is notably stronger at local level: 63% believe political parties should work together in municipalities, with only 22% opposed.

--- Paragraph 20 ---
"Regardless of how South Africans feel about the GNU nationally, the appetite for cooperation at local government level is clear," says Harris. "South Africa is a complex country, and many citizens recognise that parties need to work together to deliver services effectively. The upcoming elections may well produce more coalition-led municipalities, and voters seem to be ready for that."

--- Paragraph 21 ---
1 Currently 28% disagree with this sentiment, while 25% neither disagree nor agree or had no opinion.

--- Paragraph 23 ---
Khayabus: This press release is based on the views of 3,600 randomly selected respondents. Interviews were conducted by trained Ipsos interviewers in the homes and home languages of respondents. Interviews were conducted between December 2025 and January 2026 – with a 2-week break over the festive period. A scientific process of multi-stage stratified random selection distributed interviews in all areas of the county, including deep rural areas. This methodology ensured that the results are representative of the views of the universe (adult South Africans) and that findings can be weighted and projected to the universe. Trained quantitative fieldworkers were responsible for the interviewing and CAPI (Computer-Assisted Personal Interviewing) was used. All results were collated and analysed in an aggregate format to protect the identity and confidentiality of respondents. All sample surveys are subject to a margin of error, determined by sample size, sampling methodology and response rate. The sample error for this sample at a 95% confidence level is a maximum of plus or minus 1.9%.

In [19]:
paragraphs = soup.find_all("p")

print("Number of paragraphs:", len(paragraphs))

for i, paragraph in enumerate(paragraphs):
    text = paragraph.get_text(" ", strip=True)
    
    # Show paragraphs containing information relevant to our project
    relevant_words = [
        "vote",
        "voter",
        "election",
        "politic",
        "IEC",
        "trust",
        "interest",
        "registered",
        "local government",
        "KwaZulu-Natal",
        "KZN",
        "young",
        "18-24",
        "25-34",
        "%"
    ]
    
    if any(word.lower() in text.lower() for word in relevant_words):
        print(f"\n--- Paragraph {i + 1} ---")
        print(text)

Number of paragraphs: 24

--- Paragraph 1 ---
As South Africa gears up for local government elections (required by law to take place between 2 November 2026 and 31 January 2027), new Ipsos research reveals a nation grappling with political disconnection: nearly half (47%) of South Africans say no political party represents their views, this despite more than 500 parties being registered with the IEC . Yet democratic hope persists. Six in ten eligible voters (61%) say they are looking forward to voting, even as only 38% believe their local governments/municipalities are doing their jobs well.

--- Paragraph 2 ---
"South Africans are caught between disillusionment and determination," says Mari Harris, Political Analyst at Ipsos in South Africa. "Nearly half feel no party represents them, yet the majority still want to exercise their democratic right. This tension will define the upcoming local government elections."

--- Paragraph 4 ---
Although the exact election date remains unknown, political campaigning is already in full swing. The IEC is planning special “registration weekends”, but potential voters should note they can register to vote at any time, either online or at their nearest IEC office, and this process is ongoing. Under the Electoral Act, the voters' roll closes as soon as an election date is announced.

--- Paragraph 5 ---
Given the sheer number of choices available to voters, it may seem paradoxical that 47% of South Africans say no party represents their views.

--- Paragraph 6 ---
"Too many parties with conflicting messages, focused at winning the support of voters, can create confusion rather than clarity," says Harris. "It's telling that almost half (47%) of South Africans agree that parties with less than 1% national support should be excluded from Parliament 1 . While that question referred to national politics, the same dynamic plays out at local government level, where small parties can become 'kingmakers' without necessarily contributing to stable governance in the municipality, with the result that service delivery invariably suffers."

--- Paragraph 7 ---
Despite the upcoming elections, interest in politics remains notably subdued:

--- Paragraph 8 ---
Only six in ten (61%) South Africans eligible to vote say that they have any interest in politics and elections, while 38% are not interested at all. Despite this, nearly three-quarters (73%) of eligible voters say they are registered to vote. However, registration does not guarantee turnout.

--- Paragraph 9 ---
The trend of voter alienation and disengagement has grown stronger over recent election cycles, a pattern clearly visible in IEC-calculated turnout rates, particularly since the 2016 Local Government Elections. It's important to note that these turnout figures are based on the proportion of registered voters who participate, not the total eligible voting population.

--- Paragraph 10 ---
"When you look at the proportion of eligible voters who actually participate in elections, the numbers are sobering," says Harris. "Voter education and inspiration to register to vote cannot be the IEC's responsibility alone. Concerned citizens, community and civic organisations, and political parties all have a civic duty to encourage participation."

--- Paragraph 11 ---
The current situation is that roughly two-thirds of eligible voters indicate that they have the desire and intention to vote in the Local Government Elections:

--- Paragraph 12 ---
Trust in South Africa's electoral institutions remains divided. When asked about the IEC, opinions are split, with similar proportions expressing trust and distrust:

--- Paragraph 13 ---
The data reveals information about where knowledge and trust-building of the role of the IEC are needed most:

--- Paragraph 14 ---
"These findings point to clear priorities for voter education," says Harris. "Young people and certain provinces need targeted engagement if we want to see improved turnout and build confidence in the electoral process."

--- Paragraph 15 ---
To ensure authentic responses, the party support questions were asked using a confidential digital "ballot paper" approach: the electronic device is passed directly to respondents, who mark their own party choices on a graphic replicating a real ballot paper. This method is designed to resemble an actual election and reassure respondents that their choices remain confidential.

--- Paragraph 16 ---
The results were analysed across different voter groups: all eligible voters (18+), registered voters only, and registered voters in metropolitan areas, looking at both national and local government voting intentions and party choices.

--- Paragraph 17 ---
The ANC remains the party most supported by registered voters for local government elections at 38%, followed by the DA at 22%. MKP (14%) and the EFF (12%) are closely matched, followed at some distance by ActionSA at 4% and the IFP and PA each at 3% each. The FF+ registers 2%, and it is the last party receiving more than 1% of the vote.

--- Paragraph 18 ---
"The picture for local government shows a competitive landscape," says Harris. "While the ANC maintains its lead, the combined opposition vote suggests many municipalities could see coalition negotiations after the elections."

--- Paragraph 19 ---
Despite mixed views on the current Government of National Unity, the concept of coalition governance is gaining acceptance. While 43% of South Africans agree that the GNU is working well and represents a better form of government than ANC majority rule, 27% disagree. However, support for cooperation is notably stronger at local level: 63% believe political parties should work together in municipalities, with only 22% opposed.

--- Paragraph 20 ---
"Regardless of how South Africans feel about the GNU nationally, the appetite for cooperation at local government level is clear," says Harris. "South Africa is a complex country, and many citizens recognise that parties need to work together to deliver services effectively. The upcoming elections may well produce more coalition-led municipalities, and voters seem to be ready for that."

--- Paragraph 21 ---
1 Currently 28% disagree with this sentiment, while 25% neither disagree nor agree or had no opinion.

--- Paragraph 23 ---
Khayabus: This press release is based on the views of 3,600 randomly selected respondents. Interviews were conducted by trained Ipsos interviewers in the homes and home languages of respondents. Interviews were conducted between December 2025 and January 2026 – with a 2-week break over the festive period. A scientific process of multi-stage stratified random selection distributed interviews in all areas of the county, including deep rural areas. This methodology ensured that the results are representative of the views of the universe (adult South Africans) and that findings can be weighted and projected to the universe. Trained quantitative fieldworkers were responsible for the interviewing and CAPI (Computer-Assisted Personal Interviewing) was used. All results were collated and analysed in an aggregate format to protect the identity and confidentiality of respondents. All sample surveys are subject to a margin of error, determined by sample size, sampling methodology and response rate. The sample error for this sample at a 95% confidence level is a maximum of plus or minus 1.9%.

In [20]:
for i in range(9, 22):
    text = paragraphs[i].get_text(" ", strip=True)
    
    print(f"\n--- Paragraph {i + 1} ---")
    print(text)

--- Paragraph 10 ---
"When you look at the proportion of eligible voters who actually participate in elections, the numbers are sobering," says Harris. "Voter education and inspiration to register to vote cannot be the IEC's responsibility alone. Concerned citizens, community and civic organisations, and political parties all have a civic duty to encourage participation."

--- Paragraph 11 ---
The current situation is that roughly two-thirds of eligible voters indicate that they have the desire and intention to vote in the Local Government Elections:

--- Paragraph 12 ---
Trust in South Africa's electoral institutions remains divided. When asked about the IEC, opinions are split, with similar proportions expressing trust and distrust:

--- Paragraph 13 ---
The data reveals information about where knowledge and trust-building of the role of the IEC are needed most:

--- Paragraph 14 ---
"These findings point to clear priorities for voter education," says Harris. "Young people and certain provinces need targeted engagement if we want to see improved turnout and build confidence in the electoral process."

--- Paragraph 15 ---
To ensure authentic responses, the party support questions were asked using a confidential digital "ballot paper" approach: the electronic device is passed directly to respondents, who mark their own party choices on a graphic replicating a real ballot paper. This method is designed to resemble an actual election and reassure respondents that their choices remain confidential.

--- Paragraph 16 ---
The results were analysed across different voter groups: all eligible voters (18+), registered voters only, and registered voters in metropolitan areas, looking at both national and local government voting intentions and party choices.

--- Paragraph 17 ---
The ANC remains the party most supported by registered voters for local government elections at 38%, followed by the DA at 22%. MKP (14%) and the EFF (12%) are closely matched, followed at some distance by ActionSA at 4% and the IFP and PA each at 3% each. The FF+ registers 2%, and it is the last party receiving more than 1% of the vote.

--- Paragraph 18 ---
"The picture for local government shows a competitive landscape," says Harris. "While the ANC maintains its lead, the combined opposition vote suggests many municipalities could see coalition negotiations after the elections."

--- Paragraph 19 ---
Despite mixed views on the current Government of National Unity, the concept of coalition governance is gaining acceptance. While 43% of South Africans agree that the GNU is working well and represents a better form of government than ANC majority rule, 27% disagree. However, support for cooperation is notably stronger at local level: 63% believe political parties should work together in municipalities, with only 22% opposed.

--- Paragraph 20 ---
"Regardless of how South Africans feel about the GNU nationally, the appetite for cooperation at local government level is clear," says Harris. "South Africa is a complex country, and many citizens recognise that parties need to work together to deliver services effectively. The upcoming elections may well produce more coalition-led municipalities, and voters seem to be ready for that."

--- Paragraph 21 ---
1 Currently 28% disagree with this sentiment, while 25% neither disagree nor agree or had no opinion.

--- Paragraph 22 ---

In [21]:
for i in range(17, 21):
    text = paragraphs[i].get_text(" ", strip=True)
    
    print(f"\n--- Paragraph {i + 1} ---")
    print(text)

--- Paragraph 18 ---
"The picture for local government shows a competitive landscape," says Harris. "While the ANC maintains its lead, the combined opposition vote suggests many municipalities could see coalition negotiations after the elections."

--- Paragraph 19 ---
Despite mixed views on the current Government of National Unity, the concept of coalition governance is gaining acceptance. While 43% of South Africans agree that the GNU is working well and represents a better form of government than ANC majority rule, 27% disagree. However, support for cooperation is notably stronger at local level: 63% believe political parties should work together in municipalities, with only 22% opposed.

--- Paragraph 20 ---
"Regardless of how South Africans feel about the GNU nationally, the appetite for cooperation at local government level is clear," says Harris. "South Africa is a complex country, and many citizens recognise that parties need to work together to deliver services effectively. The upcoming elections may well produce more coalition-led municipalities, and voters seem to be ready for that."

--- Paragraph 21 ---
1 Currently 28% disagree with this sentiment, while 25% neither disagree nor agree or had no opinion.

In [22]:
ipsos_data = pd.DataFrame([
    {
        "indicator": "Interest in politics and elections",
        "group": "Eligible voters",
        "geography": "South Africa",
        "value": 61,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "December 2025-January 2026"
    },
    {
        "indicator": "Not interested in politics and elections",
        "group": "Eligible voters",
        "geography": "South Africa",
        "value": 38,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "December 2025-January 2026"
    },
    {
        "indicator": "Registered to vote",
        "group": "Eligible voters",
        "geography": "South Africa",
        "value": 73,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "December 2025-January 2026"
    },
    {
        "indicator": "Want to vote in upcoming local elections",
        "group": "Eligible voters",
        "geography": "South Africa",
        "value": 64,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "December 2025-January 2026"
    },
    {
        "indicator": "Likely to vote in upcoming local elections",
        "group": "Eligible voters",
        "geography": "South Africa",
        "value": 67,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "December 2025-January 2026"
    },
    {
        "indicator": "Voting personally important",
        "group": "Eligible voters",
        "geography": "South Africa",
        "value": 66,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "December 2025-January 2026"
    },
    {
        "indicator": "Distrust of IEC",
        "group": "Eligible voters",
        "geography": "KwaZulu-Natal",
        "value": 58,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "December 2025-January 2026"
    },
    {
        "indicator": "Unlikely to trust IEC",
        "group": "Age 18-24",
        "geography": "South Africa",
        "value": 40,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "December 2025-January 2026"
    },
    {
        "indicator": "Unlikely to trust IEC",
        "group": "Age 25-34",
        "geography": "South Africa",
        "value": 42,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "December 2025-January 2026"
    },
    {
        "indicator": "Local government doing its job well",
        "group": "Eligible voters",
        "geography": "South Africa",
        "value": 38,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "December 2025-January 2026"
    }
])

print("Rows:", ipsos_data.shape[0])
print("Columns:", ipsos_data.shape[1])
display(ipsos_data)

Rows: 10
Columns: 7

,indicator,group,geography,value,unit,source,survey_period
0,Interest in politics and elections,Eligible voters,South Africa,61,percent,Ipsos,December 2025-January 2026
1,Not interested in politics and elections,Eligible voters,South Africa,38,percent,Ipsos,December 2025-January 2026
2,Registered to vote,Eligible voters,South Africa,73,percent,Ipsos,December 2025-January 2026
3,Want to vote in upcoming local elections,Eligible voters,South Africa,64,percent,Ipsos,December 2025-January 2026
4,Likely to vote in upcoming local elections,Eligible voters,South Africa,67,percent,Ipsos,December 2025-January 2026
5,Voting personally important,Eligible voters,South Africa,66,percent,Ipsos,December 2025-January 2026
6,Distrust of IEC,Eligible voters,KwaZulu-Natal,58,percent,Ipsos,December 2025-January 2026
7,Unlikely to trust IEC,Age 18-24,South Africa,40,percent,Ipsos,December 2025-January 2026
8,Unlikely to trust IEC,Age 25-34,South Africa,42,percent,Ipsos,December 2025-January 2026
9,Local government doing its job well,Eligible voters,South Africa,38,percent,Ipsos,December 2025-January 2026

In [23]:
# Keep only the indicators that are specifically useful for our KZN-focused project.
# We will add more KZN observations from other Ipsos studies afterward.

ipsos_kzn_data = pd.DataFrame([
    {
        "year": 2026,
        "indicator": "Distrust of IEC",
        "group": "Eligible voters",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": 58,
        "unit": "percent",
        "source": "Ipsos Khayabus Pulse of the People",
        "survey_period": "December 2025-January 2026"
    }
])

print("Rows:", ipsos_kzn_data.shape[0])
print("Columns:", ipsos_kzn_data.shape[1])
display(ipsos_kzn_data)

Rows: 1
Columns: 9

,year,indicator,group,geography,geography_level,value,unit,source,survey_period
0,2026,Distrust of IEC,Eligible voters,KwaZulu-Natal,Province,58,percent,Ipsos Khayabus Pulse of the People,December 2025-January 2026

In [24]:
september_2026_kzn = pd.DataFrame([
    {
        "year": 2026,
        "indicator": "Indicated they would not vote in upcoming Local Government Elections",
        "group": "Registered voters",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": None,
        "value_min": 25,
        "value_max": 30,
        "unit": "percent",
        "source": "Ipsos Khayabus Pulse of the People",
        "survey_period": "June-July 2026",
        "notes": "Ipsos reports that between one-quarter and three in ten registered voters in KwaZulu-Natal indicated that they did not intend to vote."
    },
    {
        "year": 2026,
        "indicator": "Indicated they would not vote in upcoming Local Government Elections",
        "group": "Registered voters",
        "geography": "eThekwini",
        "geography_level": "Metropolitan municipality",
        "value": None,
        "value_min": 20,
        "value_max": 25,
        "unit": "percent",
        "source": "Ipsos Khayabus Pulse of the People",
        "survey_period": "June-July 2026",
        "notes": "Ipsos reports that roughly one-fifth to one-quarter of registered voters in eThekwini indicated that they did not intend to vote."
    }
])

print("Rows:", september_2026_kzn.shape[0])
print("Columns:", september_2026_kzn.shape[1])
display(september_2026_kzn)

Rows: 2
Columns: 12

,year,indicator,group,geography,geography_level,value,value_min,value_max,unit,source,survey_period,notes
0,2026,Indicated they would not vote in upcoming Loca...,Registered voters,KwaZulu-Natal,Province,None,25,30,percent,Ipsos Khayabus Pulse of the People,June-July 2026,Ipsos reports that between one-quarter and thr...
1,2026,Indicated they would not vote in upcoming Loca...,Registered voters,eThekwini,Metropolitan municipality,None,20,25,percent,Ipsos Khayabus Pulse of the People,June-July 2026,Ipsos reports that roughly one-fifth to one-qu...

In [25]:
ipsos_2025_kzn = pd.DataFrame([
    {
        "year": 2025,
        "indicator": "Positive municipal performance rating",
        "group": "Residents",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": 30,
        "value_min": None,
        "value_max": None,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "2025",
        "notes": "KZN provincial result from Ipsos research on municipal performance."
    }
])

print("Rows:", ipsos_2025_kzn.shape[0])
print("Columns:", ipsos_2025_kzn.shape[1])
display(ipsos_2025_kzn)

Rows: 1
Columns: 12

,year,indicator,group,geography,geography_level,value,value_min,value_max,unit,source,survey_period,notes
0,2025,Positive municipal performance rating,Residents,KwaZulu-Natal,Province,30,None,None,percent,Ipsos,2025,KZN provincial result from Ipsos research on m...

In [26]:
ipsos_2021_kzn = pd.DataFrame([
    {
        "year": 2021,
        "indicator": "Safety and security as local-government priority",
        "group": "Voters",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": 55,
        "value_min": None,
        "value_max": None,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "2021",
        "notes": "KZN respondents identifying safety and security as an important local-government issue."
    },
    {
        "year": 2021,
        "indicator": "Affordable services as local-government priority",
        "group": "Voters",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": 31,
        "value_min": None,
        "value_max": None,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "2021",
        "notes": "KZN respondents identifying affordable services as an important local-government issue."
    },
    {
        "year": 2021,
        "indicator": "Refuse removal and clean streets as local-government priority",
        "group": "Voters",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": 14,
        "value_min": None,
        "value_max": None,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "2021",
        "notes": "KZN respondents identifying refuse removal and clean streets as an important local-government issue."
    }
])

print("Rows:", ipsos_2021_kzn.shape[0])
print("Columns:", ipsos_2021_kzn.shape[1])
display(ipsos_2021_kzn)

Rows: 3
Columns: 12

,year,indicator,group,geography,geography_level,value,value_min,value_max,unit,source,survey_period,notes
0,2021,Safety and security as local-government priority,Voters,KwaZulu-Natal,Province,55,None,None,percent,Ipsos,2021,KZN respondents identifying safety and securit...
1,2021,Affordable services as local-government priority,Voters,KwaZulu-Natal,Province,31,None,None,percent,Ipsos,2021,KZN respondents identifying affordable service...
2,2021,Refuse removal and clean streets as local-gove...,Voters,KwaZulu-Natal,Province,14,None,None,percent,Ipsos,2021,KZN respondents identifying refuse removal and...

In [27]:
ipsos_2020_kzn = pd.DataFrame([
    {
        "year": 2020,
        "indicator": "No political party represents their views",
        "group": "Eligible voters",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": 36,
        "value_min": None,
        "value_max": None,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "2020",
        "notes": "Percentage of eligible KZN voters agreeing or strongly agreeing that no political party represents their views."
    }
])

print("Rows:", ipsos_2020_kzn.shape[0])
print("Columns:", ipsos_2020_kzn.shape[1])
display(ipsos_2020_kzn)

Rows: 1
Columns: 12

,year,indicator,group,geography,geography_level,value,value_min,value_max,unit,source,survey_period,notes
0,2020,No political party represents their views,Eligible voters,KwaZulu-Natal,Province,36,None,None,percent,Ipsos,2020,Percentage of eligible KZN voters agreeing or ...

In [28]:
kzn_keywords = [
    "KwaZulu-Natal",
    "KZN",
    "eThekwini",
    "municipality",
    "province",
    "provincial"
]

print("KZN-related passages found:\n")

for i, paragraph in enumerate(paragraphs):
    text = paragraph.get_text(" ", strip=True)
    
    if any(keyword.lower() in text.lower() for keyword in kzn_keywords):
        print(f"\n--- Paragraph {i + 1} ---")
        print(text)

KZN-related passages found:


--- Paragraph 6 ---
"Too many parties with conflicting messages, focused at winning the support of voters, can create confusion rather than clarity," says Harris. "It's telling that almost half (47%) of South Africans agree that parties with less than 1% national support should be excluded from Parliament 1 . While that question referred to national politics, the same dynamic plays out at local government level, where small parties can become 'kingmakers' without necessarily contributing to stable governance in the municipality, with the result that service delivery invariably suffers."

--- Paragraph 14 ---
"These findings point to clear priorities for voter education," says Harris. "Young people and certain provinces need targeted engagement if we want to see improved turnout and build confidence in the electoral process."

In [29]:
ipsos_kzn_combined = pd.concat(
    [
        ipsos_kzn_data,
        september_2026_kzn,
        ipsos_2025_kzn,
        ipsos_2021_kzn,
        ipsos_2020_kzn
    ],
    ignore_index=True
)

print("Rows:", ipsos_kzn_combined.shape[0])
print("Columns:", ipsos_kzn_combined.shape[1])

display(ipsos_kzn_combined)

Rows: 8
Columns: 12

,year,indicator,group,geography,geography_level,value,unit,source,survey_period,value_min,value_max,notes
0,2026,Distrust of IEC,Eligible voters,KwaZulu-Natal,Province,58,percent,Ipsos Khayabus Pulse of the People,December 2025-January 2026,NaN,NaN,NaN
1,2026,Indicated they would not vote in upcoming Loca...,Registered voters,KwaZulu-Natal,Province,None,percent,Ipsos Khayabus Pulse of the People,June-July 2026,25,30,Ipsos reports that between one-quarter and thr...
2,2026,Indicated they would not vote in upcoming Loca...,Registered voters,eThekwini,Metropolitan municipality,None,percent,Ipsos Khayabus Pulse of the People,June-July 2026,20,25,Ipsos reports that roughly one-fifth to one-qu...
3,2025,Positive municipal performance rating,Residents,KwaZulu-Natal,Province,30,percent,Ipsos,2025,None,None,KZN provincial result from Ipsos research on m...
4,2021,Safety and security as local-government priority,Voters,KwaZulu-Natal,Province,55,percent,Ipsos,2021,None,None,KZN respondents identifying safety and securit...
5,2021,Affordable services as local-government priority,Voters,KwaZulu-Natal,Province,31,percent,Ipsos,2021,None,None,KZN respondents identifying affordable service...
6,2021,Refuse removal and clean streets as local-gove...,Voters,KwaZulu-Natal,Province,14,percent,Ipsos,2021,None,None,KZN respondents identifying refuse removal and...
7,2020,No political party represents their views,Eligible voters,KwaZulu-Natal,Province,36,percent,Ipsos,2020,None,None,Percentage of eligible KZN voters agreeing or ...

In [30]:
additional_kzn = pd.DataFrame([
    {
        "year": 2019,
        "indicator": "Elections are free and fair",
        "indicator_type": "Electoral trust",
        "group": "Registered voters",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": 54,
        "value_min": None,
        "value_max": None,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "22 March-17 April 2019",
        "notes": "Percentage agreeing that elections in South Africa are free and fair."
    },
    {
        "year": 2020,
        "indicator": "No political party represents their views",
        "indicator_type": "Political representation",
        "group": "Eligible voters",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": 36,
        "value_min": None,
        "value_max": None,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "20 September-8 November 2019",
        "notes": "Ipsos publication released in February 2020; fieldwork was conducted in September-November 2019."
    },
    {
        "year": 2021,
        "indicator": "Medium voter turnout scenario",
        "indicator_type": "Voter participation",
        "group": "Registered voters",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": 57,
        "value_min": None,
        "value_max": None,
        "unit": "percent",
        "source": "Ipsos/eNCA",
        "survey_period": "9-14 October 2021",
        "notes": "Ipsos projected a 57% medium voter turnout scenario for KZN; this is a survey-based scenario, not actual turnout."
    },
    {
        "year": 2023,
        "indicator": "ANC party support",
        "indicator_type": "Party support",
        "group": "Registered voters",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": 22,
        "value_min": None,
        "value_max": None,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "1 June-20 July 2023",
        "notes": "Reported KZN party-choice result."
    },
    {
        "year": 2023,
        "indicator": "DA party support",
        "indicator_type": "Party support",
        "group": "Registered voters",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": 13,
        "value_min": None,
        "value_max": None,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "1 June-20 July 2023",
        "notes": "Reported KZN party-choice result."
    },
    {
        "year": 2023,
        "indicator": "EFF party support",
        "indicator_type": "Party support",
        "group": "Registered voters",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": 13,
        "value_min": None,
        "value_max": None,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "1 June-20 July 2023",
        "notes": "Reported KZN party-choice result."
    },
    {
        "year": 2023,
        "indicator": "IFP party support",
        "indicator_type": "Party support",
        "group": "Registered voters",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": 17,
        "value_min": None,
        "value_max": None,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "1 June-20 July 2023",
        "notes": "Reported KZN party-choice result."
    },
    {
        "year": 2023,
        "indicator": "ActionSA party support",
        "indicator_type": "Party support",
        "group": "Registered voters",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": 1,
        "value_min": None,
        "value_max": None,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "1 June-20 July 2023",
        "notes": "Reported KZN party-choice result."
    },
    {
        "year": 2023,
        "indicator": "ACDP party support",
        "indicator_type": "Party support",
        "group": "Registered voters",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": None,
        "value_min": None,
        "value_max": 1,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "1 June-20 July 2023",
        "notes": "Ipsos marked this result with an asterisk, meaning support measured at less than one percent."
    },
    {
        "year": 2023,
        "indicator": "FF+ party support",
        "indicator_type": "Party support",
        "group": "Registered voters",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": None,
        "value_min": None,
        "value_max": 1,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "1 June-20 July 2023",
        "notes": "Ipsos marked this result with an asterisk, meaning support measured at less than one percent."
    },
    {
        "year": 2023,
        "indicator": "Other parties party support",
        "indicator_type": "Party support",
        "group": "Registered voters",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": 7,
        "value_min": None,
        "value_max": None,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "1 June-20 July 2023",
        "notes": "Reported KZN party-choice result."
    },
    {
        "year": 2023,
        "indicator": "Will not vote",
        "indicator_type": "Voter participation",
        "group": "Registered voters",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": 8,
        "value_min": None,
        "value_max": None,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "1 June-20 July 2023",
        "notes": "Registered voters indicating they would not vote."
    },
    {
        "year": 2023,
        "indicator": "Refuse to answer",
        "indicator_type": "Electoral uncertainty",
        "group": "Registered voters",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": 12,
        "value_min": None,
        "value_max": None,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "1 June-20 July 2023",
        "notes": "Registered voters refusing to state their party choice."
    },
    {
        "year": 2023,
        "indicator": "Don't know",
        "indicator_type": "Electoral uncertainty",
        "group": "Registered voters",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": 7,
        "value_min": None,
        "value_max": None,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "1 June-20 July 2023",
        "notes": "Registered voters who did not know which party they would support."
    },
    {
        "year": 2024,
        "indicator": "Undecided about party or candidate",
        "indicator_type": "Electoral uncertainty",
        "group": "Electorate",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": None,
        "value_min": None,
        "value_max": 20,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "9 March-15 April 2024",
        "notes": "Ipsos reported that almost one-fifth of the KZN electorate had not yet decided which party or candidate to vote for."
    },
    {
        "year": 2025,
        "indicator": "Municipality rated very well",
        "indicator_type": "Municipal performance",
        "group": "Residents",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": 7,
        "value_min": None,
        "value_max": None,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "2025",
        "notes": "KZN respondents rating their municipality's performance very well."
    }
])

print("Rows:", additional_kzn.shape[0])
print("Columns:", additional_kzn.shape[1])
display(additional_kzn)

Rows: 16
Columns: 13

,year,indicator,indicator_type,group,geography,geography_level,value,value_min,value_max,unit,source,survey_period,notes
0,2019,Elections are free and fair,Electoral trust,Registered voters,KwaZulu-Natal,Province,54.0,None,NaN,percent,Ipsos,22 March-17 April 2019,Percentage agreeing that elections in South Af...
1,2020,No political party represents their views,Political representation,Eligible voters,KwaZulu-Natal,Province,36.0,None,NaN,percent,Ipsos,20 September-8 November 2019,Ipsos publication released in February 2020; f...
2,2021,Medium voter turnout scenario,Voter participation,Registered voters,KwaZulu-Natal,Province,57.0,None,NaN,percent,Ipsos/eNCA,9-14 October 2021,Ipsos projected a 57% medium voter turnout sce...
3,2023,ANC party support,Party support,Registered voters,KwaZulu-Natal,Province,22.0,None,NaN,percent,Ipsos,1 June-20 July 2023,Reported KZN party-choice result.
4,2023,DA party support,Party support,Registered voters,KwaZulu-Natal,Province,13.0,None,NaN,percent,Ipsos,1 June-20 July 2023,Reported KZN party-choice result.
5,2023,EFF party support,Party support,Registered voters,KwaZulu-Natal,Province,13.0,None,NaN,percent,Ipsos,1 June-20 July 2023,Reported KZN party-choice result.
6,2023,IFP party support,Party support,Registered voters,KwaZulu-Natal,Province,17.0,None,NaN,percent,Ipsos,1 June-20 July 2023,Reported KZN party-choice result.
7,2023,ActionSA party support,Party support,Registered voters,KwaZulu-Natal,Province,1.0,None,NaN,percent,Ipsos,1 June-20 July 2023,Reported KZN party-choice result.
8,2023,ACDP party support,Party support,Registered voters,KwaZulu-Natal,Province,NaN,None,1.0,percent,Ipsos,1 June-20 July 2023,"Ipsos marked this result with an asterisk, mea..."
9,2023,FF+ party support,Party support,Registered voters,KwaZulu-Natal,Province,NaN,None,1.0,percent,Ipsos,1 June-20 July 2023,"Ipsos marked this result with an asterisk, mea..."
10,2023,Other parties party support,Party support,Registered voters,KwaZulu-Natal,Province,7.0,None,NaN,percent,Ipsos,1 June-20 July 2023,Reported KZN party-choice result.
11,2023,Will not vote,Voter participation,Registered voters,KwaZulu-Natal,Province,8.0,None,NaN,percent,Ipsos,1 June-20 July 2023,Registered voters indicating they would not vote.
12,2023,Refuse to answer,Electoral uncertainty,Registered voters,KwaZulu-Natal,Province,12.0,None,NaN,percent,Ipsos,1 June-20 July 2023,Registered voters refusing to state their part...
13,2023,Don't know,Electoral uncertainty,Registered voters,KwaZulu-Natal,Province,7.0,None,NaN,percent,Ipsos,1 June-20 July 2023,Registered voters who did not know which party...
14,2024,Undecided about party or candidate,Electoral uncertainty,Electorate,KwaZulu-Natal,Province,NaN,None,20.0,percent,Ipsos,9 March-15 April 2024,Ipsos reported that almost one-fifth of the KZ...
15,2025,Municipality rated very well,Municipal performance,Residents,KwaZulu-Natal,Province,7.0,None,NaN,percent,Ipsos,2025,KZN respondents rating their municipality's pe...

In [31]:
ipsos_2026_extra = pd.DataFrame([
    {
        "year": 2026,
        "indicator": "MK party support",
        "indicator_type": "Party support",
        "group": "Registered voters who selected a party",
        "geography": "eThekwini",
        "geography_level": "Metropolitan municipality",
        "value": 55,
        "value_min": None,
        "value_max": None,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "June-July 2026",
        "notes": "Ipsos reports MK support at 55% in eThekwini. The metro-level results have a maximum margin of error of ±6.86 percentage points."
    }
])

print("Rows:", ipsos_2026_extra.shape[0])
print("Columns:", ipsos_2026_extra.shape[1])
display(ipsos_2026_extra)

Rows: 1
Columns: 13

,year,indicator,indicator_type,group,geography,geography_level,value,value_min,value_max,unit,source,survey_period,notes
0,2026,MK party support,Party support,Registered voters who selected a party,eThekwini,Metropolitan municipality,55,None,None,percent,Ipsos,June-July 2026,Ipsos reports MK support at 55% in eThekwini. ...

In [32]:
kzn_ipsos_combined = pd.concat(
    [
        ipsos_kzn_data,
        september_2026_kzn,
        ipsos_2025_kzn,
        ipsos_2021_kzn,
        ipsos_2020_kzn,
        additional_kzn,
        ipsos_2026_extra
    ],
    ignore_index=True
)

print("Rows:", kzn_ipsos_combined.shape[0])
print("Columns:", kzn_ipsos_combined.shape[1])

display(kzn_ipsos_combined)

Rows: 25
Columns: 13

,year,indicator,group,geography,geography_level,value,unit,source,survey_period,value_min,value_max,notes,indicator_type
0,2026,Distrust of IEC,Eligible voters,KwaZulu-Natal,Province,58,percent,Ipsos Khayabus Pulse of the People,December 2025-January 2026,NaN,NaN,NaN,NaN
1,2026,Indicated they would not vote in upcoming Loca...,Registered voters,KwaZulu-Natal,Province,None,percent,Ipsos Khayabus Pulse of the People,June-July 2026,25,30,Ipsos reports that between one-quarter and thr...,NaN
2,2026,Indicated they would not vote in upcoming Loca...,Registered voters,eThekwini,Metropolitan municipality,None,percent,Ipsos Khayabus Pulse of the People,June-July 2026,20,25,Ipsos reports that roughly one-fifth to one-qu...,NaN
3,2025,Positive municipal performance rating,Residents,KwaZulu-Natal,Province,30,percent,Ipsos,2025,None,None,KZN provincial result from Ipsos research on m...,NaN
4,2021,Safety and security as local-government priority,Voters,KwaZulu-Natal,Province,55,percent,Ipsos,2021,None,None,KZN respondents identifying safety and securit...,NaN
5,2021,Affordable services as local-government priority,Voters,KwaZulu-Natal,Province,31,percent,Ipsos,2021,None,None,KZN respondents identifying affordable service...,NaN
6,2021,Refuse removal and clean streets as local-gove...,Voters,KwaZulu-Natal,Province,14,percent,Ipsos,2021,None,None,KZN respondents identifying refuse removal and...,NaN
7,2020,No political party represents their views,Eligible voters,KwaZulu-Natal,Province,36,percent,Ipsos,2020,None,None,Percentage of eligible KZN voters agreeing or ...,NaN
8,2019,Elections are free and fair,Registered voters,KwaZulu-Natal,Province,54.0,percent,Ipsos,22 March-17 April 2019,None,NaN,Percentage agreeing that elections in South Af...,Electoral trust
9,2020,No political party represents their views,Eligible voters,KwaZulu-Natal,Province,36.0,percent,Ipsos,20 September-8 November 2019,None,NaN,Ipsos publication released in February 2020; f...,Political representation
10,2021,Medium voter turnout scenario,Registered voters,KwaZulu-Natal,Province,57.0,percent,Ipsos/eNCA,9-14 October 2021,None,NaN,Ipsos projected a 57% medium voter turnout sce...,Voter participation
11,2023,ANC party support,Registered voters,KwaZulu-Natal,Province,22.0,percent,Ipsos,1 June-20 July 2023,None,NaN,Reported KZN party-choice result.,Party support
12,2023,DA party support,Registered voters,KwaZulu-Natal,Province,13.0,percent,Ipsos,1 June-20 July 2023,None,NaN,Reported KZN party-choice result.,Party support
13,2023,EFF party support,Registered voters,KwaZulu-Natal,Province,13.0,percent,Ipsos,1 June-20 July 2023,None,NaN,Reported KZN party-choice result.,Party support
14,2023,IFP party support,Registered voters,KwaZulu-Natal,Province,17.0,percent,Ipsos,1 June-20 July 2023,None,NaN,Reported KZN party-choice result.,Party support
15,2023,ActionSA party support,Registered voters,KwaZulu-Natal,Province,1.0,percent,Ipsos,1 June-20 July 2023,None,NaN,Reported KZN party-choice result.,Party support
16,2023,ACDP party support,Registered voters,KwaZulu-Natal,Province,NaN,percent,Ipsos,1 June-20 July 2023,None,1.0,"Ipsos marked this result with an asterisk, mea...",Party support
17,2023,FF+ party support,Registered voters,KwaZulu-Natal,Province,NaN,percent,Ipsos,1 June-20 July 2023,None,1.0,"Ipsos marked this result with an asterisk, mea...",Party support
18,2023,Other parties party support,Registered voters,KwaZulu-Natal,Province,7.0,percent,Ipsos,1 June-20 July 2023,None,NaN,Reported KZN party-choice result.,Party support
19,2023,Will not vote,Registered voters,KwaZulu-Natal,Province,8.0,percent,Ipsos,1 June-20 July 2023,None,NaN,Registered voters indicating they would not vote.,Voter participation
20,2023,Refuse to answer,Registered voters,KwaZulu-Natal,Province,12.0,percent,Ipsos,1 June-20 July 2023,None,NaN,Registered voters refusing to state their part...,Electoral uncertainty
21,2023,Don't know,Registered voters,KwaZulu-Natal,Province,7.0,percent,Ipsos,1 June-20 July 2023,None,NaN,Registered voters who did not know which party...,Electoral uncertainty
22,2024,Undecided about party or candidate,Electorate,KwaZulu-Natal,Province,NaN,percent,Ipsos,9 March-15 April 2024,None,20.0,Ipsos reported that almost one-fifth of the KZ...,Electoral uncertainty
23,2025,Municipality rated very well,Residents,KwaZulu-Natal,Province,7.0,percent,Ipsos,2025,None,NaN,KZN respondents rating their municipality's pe...,Municipal performance
24,2026,MK party support,Registered voters who selected a party,eThekwini,Metropolitan municipality,55,percent,Ipsos,June-July 2026,None,None,Ipsos reports MK support at 55% in eThekwini. ...,Party support

In [33]:
additional_kzn_early = pd.DataFrame([
    # 2018 — KZN provincial ballot
    {
        "year": 2018,
        "indicator": "ANC provincial ballot support",
        "indicator_type": "Party support",
        "group": "Voters",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": 62,
        "value_min": None,
        "value_max": None,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "20 April-7 June 2018",
        "notes": "Ipsos provincial ballot result for KwaZulu-Natal."
    },
    {
        "year": 2018,
        "indicator": "DA provincial ballot support",
        "indicator_type": "Party support",
        "group": "Voters",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": 7,
        "value_min": None,
        "value_max": None,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "20 April-7 June 2018",
        "notes": "Ipsos provincial ballot result for KwaZulu-Natal."
    },
    {
        "year": 2018,
        "indicator": "EFF provincial ballot support",
        "indicator_type": "Party support",
        "group": "Voters",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": 3,
        "value_min": None,
        "value_max": None,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "20 April-7 June 2018",
        "notes": "Ipsos provincial ballot result for KwaZulu-Natal."
    },
    {
        "year": 2018,
        "indicator": "IFP provincial ballot support",
        "indicator_type": "Party support",
        "group": "Voters",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": 3,
        "value_min": None,
        "value_max": None,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "20 April-7 June 2018",
        "notes": "Ipsos provincial ballot result for KwaZulu-Natal."
    },
    {
        "year": 2018,
        "indicator": "Would not vote",
        "indicator_type": "Voter participation",
        "group": "Voters",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": 2,
        "value_min": None,
        "value_max": None,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "20 April-7 June 2018",
        "notes": "Respondents indicating they would not vote."
    },
    {
        "year": 2018,
        "indicator": "None of the current parties",
        "indicator_type": "Political representation",
        "group": "Voters",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": 1,
        "value_min": None,
        "value_max": None,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "20 April-7 June 2018",
        "notes": "Respondents indicating none of the current parties."
    },
    {
        "year": 2018,
        "indicator": "Refused to answer",
        "indicator_type": "Electoral uncertainty",
        "group": "Voters",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": 16,
        "value_min": None,
        "value_max": None,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "20 April-7 June 2018",
        "notes": "Respondents refusing to state their provincial party choice."
    },
    {
        "year": 2018,
        "indicator": "Not registered to vote",
        "indicator_type": "Voter registration",
        "group": "Voters",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": 2,
        "value_min": None,
        "value_max": None,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "20 April-7 June 2018",
        "notes": "Respondents indicating they were not registered to vote."
    },
    {
        "year": 2018,
        "indicator": "Don't know",
        "indicator_type": "Electoral uncertainty",
        "group": "Voters",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": 3,
        "value_min": None,
        "value_max": None,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "20 April-7 June 2018",
        "notes": "Respondents who did not know their provincial party choice."
    },

    # 2019 — provincial government and premier
    {
        "year": 2019,
        "indicator": "Provincial government doing its job well",
        "indicator_type": "Provincial government performance",
        "group": "Registered voters",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": 46,
        "value_min": None,
        "value_max": None,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "2019",
        "notes": "Registered KZN voters rating the provincial government as doing its job very or fairly well."
    },
    {
        "year": 2019,
        "indicator": "Premier doing their job well",
        "indicator_type": "Provincial government performance",
        "group": "Registered voters",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": 41,
        "value_min": None,
        "value_max": None,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "2019",
        "notes": "Registered KZN voters rating the premier as doing their job very or fairly well."
    },

    # 2021 — intention to vote
    {
        "year": 2021,
        "indicator": "Definitely want to vote/want to vote",
        "indicator_type": "Voter participation",
        "group": "Registered voters",
        "geography": "KwaZulu-Natal",
        "geography_level": "Province",
        "value": 71,
        "value_min": None,
        "value_max": None,
        "unit": "percent",
        "source": "Ipsos",
        "survey_period": "2021",
        "notes": "Registered KZN voters saying they definitely want to vote or want to vote."
    }
])

print("Rows:", additional_kzn_early.shape[0])
print("Columns:", additional_kzn_early.shape[1])

display(additional_kzn_early)

Rows: 12
Columns: 13

,year,indicator,indicator_type,group,geography,geography_level,value,value_min,value_max,unit,source,survey_period,notes
0,2018,ANC provincial ballot support,Party support,Voters,KwaZulu-Natal,Province,62,None,None,percent,Ipsos,20 April-7 June 2018,Ipsos provincial ballot result for KwaZulu-Natal.
1,2018,DA provincial ballot support,Party support,Voters,KwaZulu-Natal,Province,7,None,None,percent,Ipsos,20 April-7 June 2018,Ipsos provincial ballot result for KwaZulu-Natal.
2,2018,EFF provincial ballot support,Party support,Voters,KwaZulu-Natal,Province,3,None,None,percent,Ipsos,20 April-7 June 2018,Ipsos provincial ballot result for KwaZulu-Natal.
3,2018,IFP provincial ballot support,Party support,Voters,KwaZulu-Natal,Province,3,None,None,percent,Ipsos,20 April-7 June 2018,Ipsos provincial ballot result for KwaZulu-Natal.
4,2018,Would not vote,Voter participation,Voters,KwaZulu-Natal,Province,2,None,None,percent,Ipsos,20 April-7 June 2018,Respondents indicating they would not vote.
5,2018,None of the current parties,Political representation,Voters,KwaZulu-Natal,Province,1,None,None,percent,Ipsos,20 April-7 June 2018,Respondents indicating none of the current par...
6,2018,Refused to answer,Electoral uncertainty,Voters,KwaZulu-Natal,Province,16,None,None,percent,Ipsos,20 April-7 June 2018,Respondents refusing to state their provincial...
7,2018,Not registered to vote,Voter registration,Voters,KwaZulu-Natal,Province,2,None,None,percent,Ipsos,20 April-7 June 2018,Respondents indicating they were not registere...
8,2018,Don't know,Electoral uncertainty,Voters,KwaZulu-Natal,Province,3,None,None,percent,Ipsos,20 April-7 June 2018,Respondents who did not know their provincial ...
9,2019,Provincial government doing its job well,Provincial government performance,Registered voters,KwaZulu-Natal,Province,46,None,None,percent,Ipsos,2019,Registered KZN voters rating the provincial go...
10,2019,Premier doing their job well,Provincial government performance,Registered voters,KwaZulu-Natal,Province,41,None,None,percent,Ipsos,2019,Registered KZN voters rating the premier as do...
11,2021,Definitely want to vote/want to vote,Voter participation,Registered voters,KwaZulu-Natal,Province,71,None,None,percent,Ipsos,2021,Registered KZN voters saying they definitely w...

In [34]:
kzn_ipsos_all = pd.concat(
    [
        ipsos_kzn_data,
        september_2026_kzn,
        ipsos_2025_kzn,
        ipsos_2021_kzn,
        ipsos_2020_kzn,
        additional_kzn,
        ipsos_2026_extra,
        additional_kzn_early
    ],
    ignore_index=True
)

print("Total rows:", kzn_ipsos_all.shape[0])
print("Total columns:", kzn_ipsos_all.shape[1])

display(kzn_ipsos_all)

Total rows: 37
Total columns: 13

,year,indicator,group,geography,geography_level,value,unit,source,survey_period,value_min,value_max,notes,indicator_type
0,2026,Distrust of IEC,Eligible voters,KwaZulu-Natal,Province,58,percent,Ipsos Khayabus Pulse of the People,December 2025-January 2026,NaN,NaN,NaN,NaN
1,2026,Indicated they would not vote in upcoming Loca...,Registered voters,KwaZulu-Natal,Province,None,percent,Ipsos Khayabus Pulse of the People,June-July 2026,25,30,Ipsos reports that between one-quarter and thr...,NaN
2,2026,Indicated they would not vote in upcoming Loca...,Registered voters,eThekwini,Metropolitan municipality,None,percent,Ipsos Khayabus Pulse of the People,June-July 2026,20,25,Ipsos reports that roughly one-fifth to one-qu...,NaN
3,2025,Positive municipal performance rating,Residents,KwaZulu-Natal,Province,30,percent,Ipsos,2025,None,None,KZN provincial result from Ipsos research on m...,NaN
4,2021,Safety and security as local-government priority,Voters,KwaZulu-Natal,Province,55,percent,Ipsos,2021,None,None,KZN respondents identifying safety and securit...,NaN
5,2021,Affordable services as local-government priority,Voters,KwaZulu-Natal,Province,31,percent,Ipsos,2021,None,None,KZN respondents identifying affordable service...,NaN
6,2021,Refuse removal and clean streets as local-gove...,Voters,KwaZulu-Natal,Province,14,percent,Ipsos,2021,None,None,KZN respondents identifying refuse removal and...,NaN
7,2020,No political party represents their views,Eligible voters,KwaZulu-Natal,Province,36,percent,Ipsos,2020,None,None,Percentage of eligible KZN voters agreeing or ...,NaN
8,2019,Elections are free and fair,Registered voters,KwaZulu-Natal,Province,54.0,percent,Ipsos,22 March-17 April 2019,None,NaN,Percentage agreeing that elections in South Af...,Electoral trust
9,2020,No political party represents their views,Eligible voters,KwaZulu-Natal,Province,36.0,percent,Ipsos,20 September-8 November 2019,None,NaN,Ipsos publication released in February 2020; f...,Political representation
10,2021,Medium voter turnout scenario,Registered voters,KwaZulu-Natal,Province,57.0,percent,Ipsos/eNCA,9-14 October 2021,None,NaN,Ipsos projected a 57% medium voter turnout sce...,Voter participation
11,2023,ANC party support,Registered voters,KwaZulu-Natal,Province,22.0,percent,Ipsos,1 June-20 July 2023,None,NaN,Reported KZN party-choice result.,Party support
12,2023,DA party support,Registered voters,KwaZulu-Natal,Province,13.0,percent,Ipsos,1 June-20 July 2023,None,NaN,Reported KZN party-choice result.,Party support
13,2023,EFF party support,Registered voters,KwaZulu-Natal,Province,13.0,percent,Ipsos,1 June-20 July 2023,None,NaN,Reported KZN party-choice result.,Party support
14,2023,IFP party support,Registered voters,KwaZulu-Natal,Province,17.0,percent,Ipsos,1 June-20 July 2023,None,NaN,Reported KZN party-choice result.,Party support
15,2023,ActionSA party support,Registered voters,KwaZulu-Natal,Province,1.0,percent,Ipsos,1 June-20 July 2023,None,NaN,Reported KZN party-choice result.,Party support
16,2023,ACDP party support,Registered voters,KwaZulu-Natal,Province,NaN,percent,Ipsos,1 June-20 July 2023,None,1.0,"Ipsos marked this result with an asterisk, mea...",Party support
17,2023,FF+ party support,Registered voters,KwaZulu-Natal,Province,NaN,percent,Ipsos,1 June-20 July 2023,None,1.0,"Ipsos marked this result with an asterisk, mea...",Party support
18,2023,Other parties party support,Registered voters,KwaZulu-Natal,Province,7.0,percent,Ipsos,1 June-20 July 2023,None,NaN,Reported KZN party-choice result.,Party support
19,2023,Will not vote,Registered voters,KwaZulu-Natal,Province,8.0,percent,Ipsos,1 June-20 July 2023,None,NaN,Registered voters indicating they would not vote.,Voter participation
20,2023,Refuse to answer,Registered voters,KwaZulu-Natal,Province,12.0,percent,Ipsos,1 June-20 July 2023,None,NaN,Registered voters refusing to state their part...,Electoral uncertainty
21,2023,Don't know,Registered voters,KwaZulu-Natal,Province,7.0,percent,Ipsos,1 June-20 July 2023,None,NaN,Registered voters who did not know which party...,Electoral uncertainty
22,2024,Undecided about party or candidate,Electorate,KwaZulu-Natal,Province,NaN,percent,Ipsos,9 March-15 April 2024,None,20.0,Ipsos reported that almost one-fifth of the KZ...,Electoral uncertainty
23,2025,Municipality rated very well,Residents,KwaZulu-Natal,Province,7.0,percent,Ipsos,2025,None,NaN,KZN respondents rating their municipality's pe...,Municipal performance
24,2026,MK party support,Registered voters who selected a party,eThekwini,Metropolitan municipality,55,percent,Ipsos,June-July 2026,None,None,Ipsos reports MK support at 55% in eThekwini. ...,Party support
25,2018,ANC provincial ballot support,Voters,KwaZulu-Natal,Province,62,percent,Ipsos,20 April-7 June 2018,None,None,Ipsos provincial ballot result for KwaZulu-Natal.,Party support
26,2018,DA provincial ballot support,Voters,KwaZulu-Natal,Province,7,percent,Ipsos,20 April-7 June 2018,None,None,Ipsos provincial ballot result for KwaZulu-Natal.,Party support
27,2018,EFF provincial ballot support,Voters,KwaZulu-Natal,Province,3,percent,Ipsos,20 April-7 June 2018,None,None,Ipsos provincial ballot result for KwaZulu-Natal.,Party support
28,2018,IFP provincial ballot support,Voters,KwaZulu-Natal,Province,3,percent,Ipsos,20 April-7 June 2018,None,None,Ipsos provincial ballot result for KwaZulu-Natal.,Party support
29,2018,Would not vote,Voters,KwaZulu-Natal,Province,2,percent,Ipsos,20 April-7 June 2018,None,None,Respondents indicating they would not vote.,Voter participation
30,2018,None of the current parties,Voters,KwaZulu-Natal,Province,1,percent,Ipsos,20 April-7 June 2018,None,None,Respondents indicating none of the current par...,Political representation
31,2018,Refused to answer,Voters,KwaZulu-Natal,Province,16,percent,Ipsos,20 April-7 June 2018,None,None,Respondents refusing to state their provincial...,Electoral uncertainty
32,2018,Not registered to vote,Voters,KwaZulu-Natal,Province,2,percent,Ipsos,20 April-7 June 2018,None,None,Respondents indicating they were not registere...,Voter registration
33,2018,Don't know,Voters,KwaZulu-Natal,Province,3,percent,Ipsos,20 April-7 June 2018,None,None,Respondents who did not know their provincial ...,Electoral uncertainty
34,2019,Provincial government doing its job well,Registered voters,KwaZulu-Natal,Province,46,percent,Ipsos,2019,None,None,Registered KZN voters rating the provincial go...,Provincial government performance
35,2019,Premier doing their job well,Registered voters,KwaZulu-Natal,Province,41,percent,Ipsos,2019,None,None,Registered KZN voters rating the premier as do...,Provincial government performance
36,2021,Definitely want to vote/want to vote,Registered voters,KwaZulu-Natal,Province,71,percent,Ipsos,2021,None,None,Registered KZN voters saying they definitely w...,Voter participation

In [35]:
duplicate_mask = kzn_ipsos_all.duplicated(keep=False)

print("Number of duplicate rows:", duplicate_mask.sum())

if duplicate_mask.sum() > 0:
    display(
        kzn_ipsos_all.loc[duplicate_mask]
        .sort_values(["year", "indicator"])
    )
else:
    print("No exact duplicate rows found.")

Number of duplicate rows: 0
No exact duplicate rows found.

In [36]:
logical_duplicates = kzn_ipsos_all[
    kzn_ipsos_all.duplicated(
        subset=[
            "year",
            "indicator",
            "geography",
            "geography_level",
            "value",
            "value_min",
            "value_max"
        ],
        keep=False
    )
].sort_values(
    [
        "year",
        "indicator",
        "geography"
    ]
)

print("Potential logical duplicates:", len(logical_duplicates))

display(logical_duplicates)

Potential logical duplicates: 2

,year,indicator,group,geography,geography_level,value,unit,source,survey_period,value_min,value_max,notes,indicator_type
7,2020,No political party represents their views,Eligible voters,KwaZulu-Natal,Province,36,percent,Ipsos,2020,None,None,Percentage of eligible KZN voters agreeing or ...,NaN
9,2020,No political party represents their views,Eligible voters,KwaZulu-Natal,Province,36.0,percent,Ipsos,20 September-8 November 2019,None,NaN,Ipsos publication released in February 2020; f...,Political representation

In [37]:
kzn_ipsos_all = kzn_ipsos_all.drop(index=7).reset_index(drop=True)

print("Rows after removing duplicate:", kzn_ipsos_all.shape[0])

display(
    kzn_ipsos_all[
        kzn_ipsos_all["indicator"] == "No political party represents their views"
    ]
)

Rows after removing duplicate: 36

,year,indicator,group,geography,geography_level,value,unit,source,survey_period,value_min,value_max,notes,indicator_type
8,2020,No political party represents their views,Eligible voters,KwaZulu-Natal,Province,36.0,percent,Ipsos,20 September-8 November 2019,None,NaN,Ipsos publication released in February 2020; f...,Political representation

In [38]:
print("Rows:", len(kzn_ipsos_all))
print("Columns:", len(kzn_ipsos_all.columns))

print("\n--- Missing values ---")
display(kzn_ipsos_all.isna().sum())

print("\n--- Years covered ---")
print(sorted(kzn_ipsos_all["year"].dropna().unique()))

print("\n--- Geographies ---")
print(kzn_ipsos_all["geography"].value_counts())

print("\n--- Geography levels ---")
print(kzn_ipsos_all["geography_level"].value_counts())

print("\n--- Indicator types ---")
print(kzn_ipsos_all["indicator_type"].value_counts(dropna=False))

print("\n--- Units ---")
print(kzn_ipsos_all["unit"].value_counts(dropna=False))

print("\n--- Duplicate rows ---")
print(kzn_ipsos_all.duplicated().sum())

Rows: 36
Columns: 13

--- Missing values ---

year                0
indicator           0
group               0
geography           0
geography_level     0
value               5
unit                0
source              0
survey_period       0
value_min          34
value_max          31
notes               1
indicator_type      7
dtype: int64

--- Years covered ---
[np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2023), np.int64(2024), np.int64(2025), np.int64(2026)]

--- Geographies ---
geography
KwaZulu-Natal    34
eThekwini         2
Name: count, dtype: int64

--- Geography levels ---
geography_level
Province                     34
Metropolitan municipality     2
Name: count, dtype: int64

--- Indicator types ---
indicator_type
Party support                        13
NaN                                   7
Electoral uncertainty                 5
Voter participation                   4
Political representation              2
Provincial government performance     2
Electoral trust                       1
Municipal performance                 1
Voter registration                    1
Name: count, dtype: int64

--- Units ---
unit
percent    36
Name: count, dtype: int64

--- Duplicate rows ---
0

In [39]:
missing_indicator_type = kzn_ipsos_all[
    kzn_ipsos_all["indicator_type"].isna()
]

display(
    missing_indicator_type[
        [
            "year",
            "indicator",
            "group",
            "geography",
            "value",
            "value_min",
            "value_max",
            "survey_period"
        ]
    ]
)

,year,indicator,group,geography,value,value_min,value_max,survey_period
0,2026,Distrust of IEC,Eligible voters,KwaZulu-Natal,58,NaN,NaN,December 2025-January 2026
1,2026,Indicated they would not vote in upcoming Loca...,Registered voters,KwaZulu-Natal,None,25,30,June-July 2026
2,2026,Indicated they would not vote in upcoming Loca...,Registered voters,eThekwini,None,20,25,June-July 2026
3,2025,Positive municipal performance rating,Residents,KwaZulu-Natal,30,None,None,2025
4,2021,Safety and security as local-government priority,Voters,KwaZulu-Natal,55,None,None,2021
5,2021,Affordable services as local-government priority,Voters,KwaZulu-Natal,31,None,None,2021
6,2021,Refuse removal and clean streets as local-gove...,Voters,KwaZulu-Natal,14,None,None,2021

In [40]:
kzn_ipsos_all.loc[
    kzn_ipsos_all["indicator"] == "Distrust of IEC",
    "indicator_type"
] = "Electoral trust"

kzn_ipsos_all.loc[
    kzn_ipsos_all["indicator"] == "Indicated they would not vote in upcoming Local Government Elections",
    "indicator_type"
] = "Voter participation"

kzn_ipsos_all.loc[
    kzn_ipsos_all["indicator"] == "Positive municipal performance rating",
    "indicator_type"
] = "Municipal performance"

kzn_ipsos_all.loc[
    kzn_ipsos_all["indicator"].isin([
        "Safety and security as local-government priority",
        "Affordable services as local-government priority",
        "Refuse removal and clean streets as local-government priority"
    ]),
    "indicator_type"
] = "Local-government priorities"

print(
    "Missing indicator types:",
    kzn_ipsos_all["indicator_type"].isna().sum()
)

display(
    kzn_ipsos_all[
        [
            "year",
            "indicator",
            "indicator_type"
        ]
    ]
)

Missing indicator types: 0

,year,indicator,indicator_type
0,2026,Distrust of IEC,Electoral trust
1,2026,Indicated they would not vote in upcoming Loca...,Voter participation
2,2026,Indicated they would not vote in upcoming Loca...,Voter participation
3,2025,Positive municipal performance rating,Municipal performance
4,2021,Safety and security as local-government priority,Local-government priorities
5,2021,Affordable services as local-government priority,Local-government priorities
6,2021,Refuse removal and clean streets as local-gove...,Local-government priorities
7,2019,Elections are free and fair,Electoral trust
8,2020,No political party represents their views,Political representation
9,2021,Medium voter turnout scenario,Voter participation
10,2023,ANC party support,Party support
11,2023,DA party support,Party support
12,2023,EFF party support,Party support
13,2023,IFP party support,Party support
14,2023,ActionSA party support,Party support
15,2023,ACDP party support,Party support
16,2023,FF+ party support,Party support
17,2023,Other parties party support,Party support
18,2023,Will not vote,Voter participation
19,2023,Refuse to answer,Electoral uncertainty
20,2023,Don't know,Electoral uncertainty
21,2024,Undecided about party or candidate,Electoral uncertainty
22,2025,Municipality rated very well,Municipal performance
23,2026,MK party support,Party support
24,2018,ANC provincial ballot support,Party support
25,2018,DA provincial ballot support,Party support
26,2018,EFF provincial ballot support,Party support
27,2018,IFP provincial ballot support,Party support
28,2018,Would not vote,Voter participation
29,2018,None of the current parties,Political representation
30,2018,Refused to answer,Electoral uncertainty
31,2018,Not registered to vote,Voter registration
32,2018,Don't know,Electoral uncertainty
33,2019,Provincial government doing its job well,Provincial government performance
34,2019,Premier doing their job well,Provincial government performance
35,2021,Definitely want to vote/want to vote,Voter participation

In [41]:
print("Rows:", len(kzn_ipsos_all))
print("Columns:", len(kzn_ipsos_all.columns))

print("\nMissing values:")
display(kzn_ipsos_all.isna().sum())

print("\nDuplicate rows:", kzn_ipsos_all.duplicated().sum())

print("\nGeographies:")
display(kzn_ipsos_all["geography"].value_counts())

print("\nYears:")
print(sorted(kzn_ipsos_all["year"].unique()))

print("\nIndicator types:")
display(kzn_ipsos_all["indicator_type"].value_counts())

print("\nKZN rows:")
print((kzn_ipsos_all["geography"] == "KwaZulu-Natal").sum())

print("\neThekwini rows:")
print((kzn_ipsos_all["geography"] == "eThekwini").sum())

Rows: 36
Columns: 13

Missing values:

year                0
indicator           0
group               0
geography           0
geography_level     0
value               5
unit                0
source              0
survey_period       0
value_min          34
value_max          31
notes               1
indicator_type      0
dtype: int64

Duplicate rows: 0

Geographies:

geography
KwaZulu-Natal    34
eThekwini         2
Name: count, dtype: int64

Years:
[np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2023), np.int64(2024), np.int64(2025), np.int64(2026)]

Indicator types:

indicator_type
Party support                        13
Voter participation                   6
Electoral uncertainty                 5
Local-government priorities           3
Electoral trust                       2
Municipal performance                 2
Political representation              2
Provincial government performance     2
Voter registration                    1
Name: count, dtype: int64

KZN rows:
34

eThekwini rows:
2

In [42]:
ipsos_output_path = (
    IPSOS_PROCESSED_DIR
    / "kzn_ipsos_electoral_and_municipal_indicators.csv"
)

kzn_ipsos_all.to_csv(
    ipsos_output_path,
    index=False,
    encoding="utf-8"
)

print("Saved to:")
print(ipsos_output_path)

Saved to:
c:\Users\Admin\Desktop\Dirisa_1\SPU-TEAM-DIRISA\data\processed\ipsos\kzn_ipsos_electoral_and_municipal_indicators.csv

In [43]:
ipsos_check = pd.read_csv(ipsos_output_path)

print("Saved file shape:", ipsos_check.shape)
print("Saved file duplicates:", ipsos_check.duplicated().sum())
print("Saved file missing indicator types:", ipsos_check["indicator_type"].isna().sum())

display(ipsos_check.head())

Saved file shape: (36, 13)
Saved file duplicates: 0
Saved file missing indicator types: 0

,year,indicator,group,geography,geography_level,value,unit,source,survey_period,value_min,value_max,notes,indicator_type
0,2026,Distrust of IEC,Eligible voters,KwaZulu-Natal,Province,58.0,percent,Ipsos Khayabus Pulse of the People,December 2025-January 2026,NaN,NaN,NaN,Electoral trust
1,2026,Indicated they would not vote in upcoming Loca...,Registered voters,KwaZulu-Natal,Province,NaN,percent,Ipsos Khayabus Pulse of the People,June-July 2026,25.0,30.0,Ipsos reports that between one-quarter and thr...,Voter participation
2,2026,Indicated they would not vote in upcoming Loca...,Registered voters,eThekwini,Metropolitan municipality,NaN,percent,Ipsos Khayabus Pulse of the People,June-July 2026,20.0,25.0,Ipsos reports that roughly one-fifth to one-qu...,Voter participation
3,2025,Positive municipal performance rating,Residents,KwaZulu-Natal,Province,30.0,percent,Ipsos,2025,NaN,NaN,KZN provincial result from Ipsos research on m...,Municipal performance
4,2021,Safety and security as local-government priority,Voters,KwaZulu-Natal,Province,55.0,percent,Ipsos,2021,NaN,NaN,KZN respondents identifying safety and securit...,Local-government priorities

In [44]:
ipsos_excel_path = (
    IPSOS_PROCESSED_DIR
    / "kzn_ipsos_electoral_and_municipal_indicators.xlsx"
)

kzn_ipsos_all.to_excel(
    ipsos_excel_path,
    index=False,
    sheet_name="Ipsos KZN Data"
)

print("Excel file saved to:")
print(ipsos_excel_path)

Excel file saved to:
c:\Users\Admin\Desktop\Dirisa_1\SPU-TEAM-DIRISA\data\processed\ipsos\kzn_ipsos_electoral_and_municipal_indicators.xlsx