## Stats SA Data Extraction Approach

Before extracting the data, the Stats SA SuperWEB platform will be inspected to understand how the available municipal and statistical data is accessed.

The extraction will focus on **KwaZulu-Natal** and will investigate the datasets available for municipalities, including Census 2022 Municipal Profiles, time-series municipal profiles, Community Survey data, health and vital statistics, social and labour statistics, and municipal boundary information.

Where possible, the extraction will obtain data that can be linked to municipalities and wards and that can support the analysis of voter participation and the characteristics of areas with different levels of participation.

The extraction process will first establish access to the Stats SA platform, identify the available datasets and variables, and then retrieve the relevant data. Raw extracted data will be preserved in `data/raw/statssa/`.

This notebook is limited to **data extraction and verification**. Cleaning, transformation, feature engineering, analysis, and modelling will be handled later in the project.

In [1]:
# We are extracting data from Statistics South Africa (Stats SA)
# for KwaZulu-Natal.
#
# The main source is the Stats SA SuperWEB platform:
# https://superweb.statssa.gov.za
#
# We will investigate available datasets including:
# - Census 2022 Municipal Profiles
# - Time Series Municipal Profiles
# - Community Survey
# - Health and Vital Statistics
# - Social Statistics
# - Labour Statistics
# - Municipal boundaries
#
# Raw extracted data will be saved to:
# data/raw/statssa/

from pathlib import Path
import pandas as pd
import requests
from bs4 import BeautifulSoup

# Project root
PROJECT_ROOT = Path.cwd().parent

# Raw data directory
RAW_DIR = PROJECT_ROOT / "data" / "raw" / "statssa"
RAW_DIR.mkdir(parents=True, exist_ok=True)

# Stats SA source
STATSSA_URL = "https://superweb.statssa.gov.za"

# Extraction scope
TARGET_PROVINCE = "KwaZulu-Natal"

# Historical period of interest
START_YEAR = 2011
CURRENT_YEAR = 2026

print("Stats SA extraction setup complete.")
print("Source:", STATSSA_URL)
print("Province:", TARGET_PROVINCE)
print("Period:", START_YEAR, "to", CURRENT_YEAR)
print("Raw directory:", RAW_DIR)

Stats SA extraction setup complete.
Source: https://superweb.statssa.gov.za
Province: KwaZulu-Natal
Period: 2011 to 2026
Raw directory: c:\Users\Admin\Desktop\Dirisa_1\SPU-TEAM-DIRISA\data\raw\statssa

In [3]:
# We first open the Stats SA SuperWEB page and keep a session active.
# The session is needed because Stats SA SuperWEB may use
# cookies and session state when accessing the available data.

statssa_session = requests.Session()

initial_response = statssa_session.get(
    STATSSA_URL,
    timeout=30
)

print("HTTP status:", initial_response.status_code)
print("Content type:", initial_response.headers.get("Content-Type"))
print("Response size:", len(initial_response.content), "bytes")

assert initial_response.status_code == 200, (
    "Stats SA SuperWEB page could not be loaded."
)

initial_soup = BeautifulSoup(
    initial_response.text,
    "html.parser"
)

print("Stats SA source loaded successfully.")
print("Session established successfully.")

HTTP status: 200
Content type: text/html
Response size: 212 bytes
Stats SA source loaded successfully.
Session established successfully.

In [4]:
# Check what the Stats SA server actually returned.
# This helps us confirm whether we reached the SuperWEB platform,
# a login page, or a redirect/information page before extraction.

print(initial_response.text)

<html>
<head>
<META NAME="robots" CONTENT="noindex,nofollow">
<script src="/_Incapsula_Resource?SWJIYLWA=5074a744e2e3d891814e9a2dace20bd4,719d34d31c8e3a6e6fffd425f7e032f3">
</script>
<body>
</body></html>

In [6]:
# ============================================
# CELL 3 — INSPECT STATS SA FORM FIELDS
# ============================================

# Stats SA SuperWEB uses session-based web requests.
# We need to identify the hidden fields and other
# session information generated by the page before
# attempting to reproduce any data requests.
#
# These values are inspected dynamically because
# they may change between sessions.

form_state = {}

for field in initial_soup.select(
    "input[type='hidden'][name]"
):
    name = field.get("name")
    value = field.get("value", "")

    form_state[name] = value

print("Hidden form fields found:", len(form_state))

print("\nHidden fields:")
for field in form_state:
    print("-", field)

Hidden form fields found: 0

Hidden fields:

In [7]:
# ============================================
# CELL 4 — IDENTIFY STATS SA DATA CONTROLS
# ============================================

# We now inspect the available form controls on the
# Stats SA SuperWEB page.
#
# The goal is to identify how the platform represents
# dataset, province, geography, or table selections
# before sending a request.
#
# We do not invent request parameters. We first inspect
# the controls returned by Stats SA.

select_fields = initial_soup.select("select[name]")

print("Select fields found:", len(select_fields))

print("\nAvailable selection controls:")

for field in select_fields:
    print(
        "Name:", field.get("name"),
        "| ID:", field.get("id")
    )

    options = field.find_all("option")

    print("Options:", len(options))

    for option in options[:10]:
        print(
            "  ",
            option.get("value", ""),
            "→",
            option.get_text(strip=True)
        )

    print()

Select fields found: 0

Available selection controls:

In [8]:
# ============================================
# CELL 4 — ACCESS STATS SA DATA CATALOGUE
# ============================================

# The browser Network activity showed that Stats SA
# retrieves its available database tables through a
# REST GET request.
#
# We reproduce that request programmatically so that
# we can inspect the datasets available through SuperWEB.

CATALOGUE_URL = (
    "https://superweb.statssa.gov.za/"
    "webapi/rest/catalogue/databaseTables/tree"
)

catalogue_response = statssa_session.get(
    CATALOGUE_URL,
    params={"nocache": "1"},
    timeout=30
)

print("HTTP status:", catalogue_response.status_code)
print("Content type:", catalogue_response.headers.get("Content-Type"))
print("Response size:", len(catalogue_response.content), "bytes")

assert catalogue_response.status_code == 200, (
    "Stats SA catalogue could not be loaded."
)

print("\nResponse preview:")
print(catalogue_response.text[:1000])

HTTP status: 200
Content type: text/html
Response size: 212 bytes

Response preview:
<html>
<head>
<META NAME="robots" CONTENT="noindex,nofollow">
<script src="/_Incapsula_Resource?SWJIYLWA=5074a744e2e3d891814e9a2dace20bd4,719d34d31c8e3a6e6fffd425f7e032f3">
</script>
<body>
</body></html>

In [9]:
# ============================================
# CELL 5 — Reproduce the Stats SA JSF request
# ============================================

# Stats SA uses JSF AJAX requests for the Data Catalogue.
# We reproduce the POST request structure observed in Chrome.

STATSSA_JSF_URL = (
    "https://superweb.statssa.gov.za"
    "/webapi/jsf/dataCatalogueExplorer.xhtml"
)

jsf_payload = {
    "j_id_44_SUBMIT": "1",
    "jakarta.faces.behavior.event": "action",
    "jakarta.faces.source": "j_id_4a",
    "jakarta.faces.partial.ajax": "true",
    "j_id_44": "j_id_44",
    "jakarta.faces.partial.execute": "j_id_4a",
    "jakarta.faces.partial.render": (
        "databasesPanelButtons "
        "tablesPanelButtons "
        "updateTablesTree "
        "infoPanel "
        "messagePanel"
    )
}

jsf_headers = {
    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
    "Faces-Request": "partial/ajax",
    "X-Requested-With": "XMLHttpRequest",
    "Referer": STATSSA_JSF_URL,
}

jsf_response = statssa_session.post(
    STATSSA_JSF_URL,
    data=jsf_payload,
    headers=jsf_headers,
    timeout=30
)

print("HTTP status:", jsf_response.status_code)
print("Content type:", jsf_response.headers.get("Content-Type"))
print("Response size:", len(jsf_response.content), "bytes")

print("\nFirst 1000 characters of response:")
print(jsf_response.text[:1000])

HTTP status: 200
Content type: text/html
Response size: 212 bytes

First 1000 characters of response:
<html>
<head>
<META NAME="robots" CONTENT="noindex,nofollow">
<script src="/_Incapsula_Resource?SWJIYLWA=5074a744e2e3d891814e9a2dace20bd4,719d34d31c8e3a6e6fffd425f7e032f3">
</script>
<body>
</body></html>

In [10]:
# ============================================
# CELL 6 — Test the Stats SA REST API
# ============================================

# Chrome successfully accessed this endpoint.
# We test whether Python can access the same API.

STATSSA_TREE_URL = (
    STATSSA_URL
    + "/webapi/rest/catalogue/databaseTables/tree"
)

tree_response = statssa_session.get(
    STATSSA_TREE_URL,
    params={"nocache": "test"},
    headers={
        "Accept": "*/*",
        "Referer": STATSSA_JSF_URL,
    },
    timeout=30
)

print("HTTP status:", tree_response.status_code)
print("Content type:", tree_response.headers.get("Content-Type"))
print("Response size:", len(tree_response.content), "bytes")

print("\nResponse:")
print(tree_response.text[:1000])

HTTP status: 200
Content type: text/html
Response size: 212 bytes

Response:
<html>
<head>
<META NAME="robots" CONTENT="noindex,nofollow">
<script src="/_Incapsula_Resource?SWJIYLWA=5074a744e2e3d891814e9a2dace20bd4,719d34d31c8e3a6e6fffd425f7e032f3">
</script>
<body>
</body></html>

In [11]:
# ============================================
# CELL 5 — Stats SA API Authentication
# ============================================

# Enter your Stats SA Open Data API key here.
# Keep this key private and DO NOT commit it to GitHub.

STATSSA_API_KEY = "65794a30655841694f694a4b563151694c434a68624763694f694a49557a49314e694a392e65794a7063334d694f694a7a644849756333526c6247786863694973496e4e3159694936496d786c614778765a323975623278766257393061476c696155426e625746706243356a623230694c434a70595851694f6a45334f5441794f5445794e7a5573496d46315a434936496e4e30636935765a47456966512e4e3076582d73776d51506b444b6461613545356d733567496d4f4b324953326443517a3658694152466f49"

# Basic verification without displaying the key
assert STATSSA_API_KEY != "PASTE_YOUR_API_KEY_HERE", (
    "65794a30655841694f694a4b563151694c434a68624763694f694a49557a49314e694a392e65794a7063334d694f694a7a644849756333526c6247786863694973496e4e3159694936496d786c614778765a323975623278766257393061476c696155426e625746706243356a623230694c434a70595851694f6a45334f5441794f5445794e7a5573496d46315a434936496e4e30636935765a47456966512e4e3076582d73776d51506b444b6461613545356d733567496d4f4b324953326443517a3658694152466f49"
)

print("Stats SA API key loaded successfully.")

Stats SA API key loaded successfully.

In [12]:
# ============================================
# CELL 6 — Test Stats SA Open Data API
# ============================================

STATSSA_API_URL = (
    "https://superweb.statssa.gov.za/webapi/api/v1"
)

api_test_response = requests.get(
    STATSSA_API_URL,
    headers={
        "APIKey": STATSSA_API_KEY,
        "Accept": "application/json"
    },
    timeout=30
)

print("HTTP status:", api_test_response.status_code)
print("Content type:", api_test_response.headers.get("Content-Type"))
print("Response size:", len(api_test_response.content), "bytes")

print("\nResponse preview:")
print(api_test_response.text[:500])

HTTP status: 200
Content type: text/html
Response size: 212 bytes

Response preview:
<html>
<head>
<META NAME="robots" CONTENT="noindex,nofollow">
<script src="/_Incapsula_Resource?SWJIYLWA=5074a744e2e3d891814e9a2dace20bd4,719d34d31c8e3a6e6fffd425f7e032f3">
</script>
<body>
</body></html>

In [14]:
# ============================================
# FIND TABLE1 TO TABLE5
# ============================================

TABLES_DIR = Path.home() / "Desktop" / "Dirisa_1"

print("Tables folder:", TABLES_DIR)

table_files = sorted(TABLES_DIR.glob("TABLE*"))

print("\nTables found:")

for file in table_files:
    print("-", file.name)

Tables folder: C:\Users\Admin\Desktop\Dirisa_1

Tables found:
- TABLE1.xlsx
- TABLE2.xlsx
- TABLE3.xlsx
- TABLE4.xlsx
- TABLE5.xlsx

In [16]:
%pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [17]:
# ============================================
# INSPECT TABLE1 TO TABLE5
# ============================================

for file in table_files:

    df = pd.read_excel(file)

    print(f"\n{'=' * 50}")
    print(file.name)
    print(f"{'=' * 50}")

    print("Rows:", len(df))
    print("Columns:")
    
    for column in df.columns:
        print(" -", column)

    print("\nFirst 3 rows:")
    display(df.head(3))

==================================================
TABLE1.xlsx
==================================================
Rows: 15
Columns:
 - Unnamed: 0
 - Unnamed: 1
 - Unnamed: 2
 - Unnamed: 3
 - Unnamed: 4
 - Unnamed: 5
 - Unnamed: 6
 - Unnamed: 7
 - Unnamed: 8
 - Unnamed: 9
 - Unnamed: 10
 - Unnamed: 11
 - Unnamed: 12
 - Unnamed: 13
 - Unnamed: 14
 - Unnamed: 15
 - Unnamed: 16
 - Unnamed: 17
 - Unnamed: 18
 - Unnamed: 19
 - Unnamed: 20
 - Unnamed: 21
 - Unnamed: 22
 - Unnamed: 23
 - Unnamed: 24
 - Unnamed: 25
 - Unnamed: 26
 - Unnamed: 27
 - Unnamed: 28
 - Unnamed: 29
 - Unnamed: 30
 - Unnamed: 31
 - Unnamed: 32
 - Unnamed: 33
 - Unnamed: 34
 - Unnamed: 35
 - Unnamed: 36
 - Unnamed: 37
 - Unnamed: 38
 - Unnamed: 39
 - Unnamed: 40
 - Unnamed: 41
 - Unnamed: 42
 - Unnamed: 43
 - Unnamed: 44
 - Unnamed: 45
 - Unnamed: 46
 - Unnamed: 47
 - Unnamed: 48
 - Unnamed: 49
 - Unnamed: 50
 - Unnamed: 51
 - Unnamed: 52
 - Unnamed: 53
 - Unnamed: 54
 - Unnamed: 55
 - Unnamed: 56
 - Unnamed: 57
 - Unnamed: 58
 - Unnamed: 59
 - Unnamed: 60
 - Unnamed: 61
 - Unnamed: 62
 - Unnamed: 63
 - Unnamed: 64
 - Unnamed: 65
 - Unnamed: 66
 - Unnamed: 67
 - Unnamed: 68
 - Unnamed: 69
 - Unnamed: 70
 - Unnamed: 71
 - Unnamed: 72
 - Unnamed: 73
 - Unnamed: 74
 - Unnamed: 75
 - Unnamed: 76
 - Unnamed: 77
 - Unnamed: 78
 - Unnamed: 79
 - Unnamed: 80
 - Unnamed: 81
 - Unnamed: 82
 - Unnamed: 83
 - Unnamed: 84
 - Unnamed: 85
 - Unnamed: 86
 - Unnamed: 87
 - Unnamed: 88
 - Unnamed: 89
 - Unnamed: 90
 - Unnamed: 91
 - Unnamed: 92
 - Unnamed: 93
 - Unnamed: 94
 - Unnamed: 95
 - Unnamed: 96
 - Unnamed: 97
 - Unnamed: 98
 - Unnamed: 99
 - Unnamed: 100
 - Unnamed: 101
 - Unnamed: 102
 - Unnamed: 103
 - Unnamed: 104
 - Unnamed: 105
 - Unnamed: 106
 - Unnamed: 107
 - Unnamed: 108
 - Unnamed: 109
 - Unnamed: 110
 - Unnamed: 111
 - Unnamed: 112
 - Unnamed: 113
 - Unnamed: 114
 - Unnamed: 115
 - Unnamed: 116
 - Unnamed: 117
 - Unnamed: 118
 - Unnamed: 119
 - Unnamed: 120
 - Unnamed: 121
 - Unnamed: 122
 - Unnamed: 123
 - Unnamed: 124
 - Unnamed: 125
 - Unnamed: 126
 - Unnamed: 127
 - Unnamed: 128
 - Unnamed: 129
 - Unnamed: 130
 - Unnamed: 131
 - Unnamed: 132
 - Unnamed: 133
 - Unnamed: 134
 - Unnamed: 135
 - Unnamed: 136
 - Unnamed: 137
 - Unnamed: 138
 - Unnamed: 139
 - Unnamed: 140
 - Unnamed: 141
 - Unnamed: 142
 - Unnamed: 143
 - Unnamed: 144
 - Unnamed: 145
 - Unnamed: 146
 - Unnamed: 147
 - Unnamed: 148
 - Unnamed: 149
 - Unnamed: 150
 - Unnamed: 151
 - Unnamed: 152
 - Unnamed: 153
 - Unnamed: 154
 - Unnamed: 155
 - Unnamed: 156
 - Unnamed: 157
 - Unnamed: 158
 - Unnamed: 159
 - Unnamed: 160
 - Unnamed: 161
 - Unnamed: 162
 - Unnamed: 163
 - Unnamed: 164
 - Unnamed: 165
 - Unnamed: 166
 - Unnamed: 167
 - Unnamed: 168
 - Unnamed: 169
 - Unnamed: 170
 - Unnamed: 171
 - Unnamed: 172
 - Unnamed: 173
 - Unnamed: 174
 - Unnamed: 175
 - Unnamed: 176
 - Unnamed: 177
 - Unnamed: 178
 - Unnamed: 179
 - Unnamed: 180
 - Unnamed: 181
 - Unnamed: 182
 - Unnamed: 183
 - Unnamed: 184
 - Unnamed: 185
 - Unnamed: 186
 - Unnamed: 187
 - Unnamed: 188
 - Unnamed: 189
 - Unnamed: 190
 - Unnamed: 191
 - Unnamed: 192
 - Unnamed: 193
 - Unnamed: 194
 - Unnamed: 195
 - Unnamed: 196
 - Unnamed: 197
 - Unnamed: 198
 - Unnamed: 199
 - Unnamed: 200
 - Unnamed: 201
 - Unnamed: 202
 - Unnamed: 203
 - Unnamed: 204
 - Unnamed: 205
 - Unnamed: 206
 - Unnamed: 207
 - Unnamed: 208
 - Unnamed: 209
 - Unnamed: 210
 - Unnamed: 211
 - Unnamed: 212
 - Unnamed: 213
 - Unnamed: 214
 - Unnamed: 215
 - Unnamed: 216
 - Unnamed: 217
 - Unnamed: 218
 - Unnamed: 219
 - Unnamed: 220
 - Unnamed: 221
 - Unnamed: 222
 - Unnamed: 223
 - Unnamed: 224
 - Unnamed: 225
 - Unnamed: 226
 - Unnamed: 227
 - Unnamed: 228
 - Unnamed: 229
 - Unnamed: 230
 - Unnamed: 231
 - Unnamed: 232
 - Unnamed: 233
 - Unnamed: 234
 - Unnamed: 235
 - Unnamed: 236
 - Unnamed: 237
 - Unnamed: 238
 - Unnamed: 239
 - Unnamed: 240
 - Unnamed: 241
 - Unnamed: 242
 - Unnamed: 243
 - Unnamed: 244
 - Unnamed: 245
 - Unnamed: 246
 - Unnamed: 247
 - Unnamed: 248
 - Unnamed: 249
 - Unnamed: 250
 - Unnamed: 251
 - Unnamed: 252
 - Unnamed: 253
 - Unnamed: 254
 - Unnamed: 255
 - Unnamed: 256
 - Unnamed: 257
 - Unnamed: 258
 - Unnamed: 259
 - Unnamed: 260
 - Unnamed: 261
 - Unnamed: 262
 - Unnamed: 263
 - Unnamed: 264
 - Unnamed: 265
 - Unnamed: 266
 - Unnamed: 267
 - Unnamed: 268
 - Unnamed: 269
 - Unnamed: 270
 - Unnamed: 271
 - Unnamed: 272
 - Unnamed: 273
 - Unnamed: 274
 - Unnamed: 275
 - Unnamed: 276
 - Unnamed: 277
 - Unnamed: 278
 - Unnamed: 279
 - Unnamed: 280
 - Unnamed: 281
 - Unnamed: 282
 - Unnamed: 283
 - Unnamed: 284
 - Unnamed: 285
 - Unnamed: 286
 - Unnamed: 287
 - Unnamed: 288
 - Unnamed: 289
 - Unnamed: 290
 - Unnamed: 291
 - Unnamed: 292
 - Unnamed: 293
 - Unnamed: 294
 - Unnamed: 295
 - Unnamed: 296
 - Unnamed: 297
 - Unnamed: 298
 - Unnamed: 299
 - Unnamed: 300
 - Unnamed: 301
 - Unnamed: 302
 - Unnamed: 303
 - Unnamed: 304
 - Unnamed: 305
 - Unnamed: 306
 - Unnamed: 307
 - Unnamed: 308
 - Unnamed: 309
 - Unnamed: 310
 - Unnamed: 311
 - Unnamed: 312
 - Unnamed: 313
 - Unnamed: 314
 - Unnamed: 315
 - Unnamed: 316
 - Unnamed: 317
 - Unnamed: 318
 - Unnamed: 319
 - Unnamed: 320
 - Unnamed: 321
 - Unnamed: 322
 - Unnamed: 323
 - Unnamed: 324
 - Unnamed: 325
 - Unnamed: 326
 - Unnamed: 327
 - Unnamed: 328
 - Unnamed: 329
 - Unnamed: 330
 - Unnamed: 331
 - Unnamed: 332
 - Unnamed: 333
 - Unnamed: 334
 - Unnamed: 335
 - Unnamed: 336
 - Unnamed: 337
 - Unnamed: 338
 - Unnamed: 339
 - Unnamed: 340
 - Unnamed: 341
 - Unnamed: 342
 - Unnamed: 343
 - Unnamed: 344
 - Unnamed: 345
 - Unnamed: 346
 - Unnamed: 347
 - Unnamed: 348
 - Unnamed: 349
 - Unnamed: 350
 - Unnamed: 351
 - Unnamed: 352
 - Unnamed: 353
 - Unnamed: 354
 - Unnamed: 355
 - Unnamed: 356
 - Unnamed: 357
 - Unnamed: 358
 - Unnamed: 359
 - Unnamed: 360
 - Unnamed: 361
 - Unnamed: 362
 - Unnamed: 363
 - Unnamed: 364
 - Unnamed: 365
 - Unnamed: 366
 - Unnamed: 367
 - Unnamed: 368
 - Unnamed: 369
 - Unnamed: 370
 - Unnamed: 371
 - Unnamed: 372
 - Unnamed: 373
 - Unnamed: 374
 - Unnamed: 375
 - Unnamed: 376
 - Unnamed: 377
 - Unnamed: 378
 - Unnamed: 379
 - Unnamed: 380
 - Unnamed: 381
 - Unnamed: 382
 - Unnamed: 383
 - Unnamed: 384
 - Unnamed: 385
 - Unnamed: 386
 - Unnamed: 387
 - Unnamed: 388
 - Unnamed: 389
 - Unnamed: 390
 - Unnamed: 391
 - Unnamed: 392
 - Unnamed: 393
 - Unnamed: 394
 - Unnamed: 395
 - Unnamed: 396
 - Unnamed: 397
 - Unnamed: 398
 - Unnamed: 399
 - Unnamed: 400
 - Unnamed: 401
 - Unnamed: 402
 - Unnamed: 403
 - Unnamed: 404
 - Unnamed: 405
 - Unnamed: 406
 - Unnamed: 407
 - Unnamed: 408
 - Unnamed: 409
 - Unnamed: 410
 - Unnamed: 411
 - Unnamed: 412
 - Unnamed: 413
 - Unnamed: 414
 - Unnamed: 415
 - Unnamed: 416
 - Unnamed: 417
 - Unnamed: 418
 - Unnamed: 419
 - Unnamed: 420
 - Unnamed: 421
 - Unnamed: 422
 - Unnamed: 423
 - Unnamed: 424
 - Unnamed: 425
 - Unnamed: 426
 - Unnamed: 427
 - Unnamed: 428
 - Unnamed: 429
 - Unnamed: 430
 - Unnamed: 431
 - Unnamed: 432
 - Unnamed: 433
 - Unnamed: 434
 - Unnamed: 435
 - Unnamed: 436
 - Unnamed: 437
 - Unnamed: 438
 - Unnamed: 439
 - Unnamed: 440
 - Unnamed: 441
 - Unnamed: 442
 - Unnamed: 443
 - Unnamed: 444
 - Unnamed: 445
 - Unnamed: 446
 - Unnamed: 447
 - Unnamed: 448
 - Unnamed: 449
 - Unnamed: 450
 - Unnamed: 451
 - Unnamed: 452
 - Unnamed: 453
 - Unnamed: 454
 - Unnamed: 455
 - Unnamed: 456
 - Unnamed: 457
 - Unnamed: 458
 - Unnamed: 459
 - Unnamed: 460
 - Unnamed: 461
 - Unnamed: 462
 - Unnamed: 463
 - Unnamed: 464
 - Unnamed: 465
 - Unnamed: 466
 - Unnamed: 467
 - Unnamed: 468
 - Unnamed: 469
 - Unnamed: 470
 - Unnamed: 471
 - Unnamed: 472
 - Unnamed: 473
 - Unnamed: 474
 - Unnamed: 475
 - Unnamed: 476
 - Unnamed: 477
 - Unnamed: 478
 - Unnamed: 479
 - Unnamed: 480
 - Unnamed: 481
 - Unnamed: 482
 - Unnamed: 483
 - Unnamed: 484
 - Unnamed: 485
 - Unnamed: 486
 - Unnamed: 487
 - Unnamed: 488
 - Unnamed: 489
 - Unnamed: 490
 - Unnamed: 491
 - Unnamed: 492
 - Unnamed: 493
 - Unnamed: 494
 - Unnamed: 495
 - Unnamed: 496
 - Unnamed: 497
 - Unnamed: 498
 - Unnamed: 499
 - Unnamed: 500
 - Unnamed: 501
 - Unnamed: 502
 - Unnamed: 503
 - Unnamed: 504
 - Unnamed: 505
 - Unnamed: 506
 - Unnamed: 507
 - Unnamed: 508
 - Unnamed: 509
 - Unnamed: 510
 - Unnamed: 511
 - Unnamed: 512
 - Unnamed: 513

First 3 rows:

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 504,Unnamed: 505,Unnamed: 506,Unnamed: 507,Unnamed: 508,Unnamed: 509,Unnamed: 510,Unnamed: 511,Unnamed: 512,Unnamed: 513
0,Descriptive 2022 (MN Phase 2),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Province, district and municipality and Questi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Counting: Population,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

==================================================
TABLE2.xlsx
==================================================
Rows: 70
Columns:
 - Unnamed: 0
 - Unnamed: 1

First 3 rows:

                            Unnamed: 0 Unnamed: 1
0        Descriptive 2022 (MN Phase 2)        NaN
1  Province, district and municipality        NaN
2                 Counting: Population        NaN

==================================================
TABLE3.xlsx
==================================================
Rows: 173
Columns:
 - Unnamed: 0
 - Unnamed: 1

First 3 rows:

                                          Unnamed: 0 Unnamed: 1
0                      Descriptive 2022 (MN Phase 2)        NaN
1  Province, district and municipality then Sex t...        NaN
2                               Counting: Population        NaN

==================================================
TABLE4.xlsx
==================================================
Rows: 14
Columns:
 - Unnamed: 0
 - Unnamed: 1
 - Unnamed: 2
 - Unnamed: 3
 - Unnamed: 4
 - Unnamed: 5
 - Unnamed: 6
 - Unnamed: 7
 - Unnamed: 8
 - Unnamed: 9
 - Unnamed: 10
 - Unnamed: 11
 - Unnamed: 12
 - Unnamed: 13
 - Unnamed: 14
 - Unnamed: 15
 - Unnamed: 16
 - Unnamed: 17
 - Unnamed: 18
 - Unnamed: 19
 - Unnamed: 20
 - Unnamed: 21
 - Unnamed: 22
 - Unnamed: 23
 - Unnamed: 24
 - Unnamed: 25
 - Unnamed: 26
 - Unnamed: 27
 - Unnamed: 28
 - Unnamed: 29
 - Unnamed: 30
 - Unnamed: 31
 - Unnamed: 32
 - Unnamed: 33
 - Unnamed: 34
 - Unnamed: 35
 - Unnamed: 36
 - Unnamed: 37
 - Unnamed: 38
 - Unnamed: 39
 - Unnamed: 40
 - Unnamed: 41
 - Unnamed: 42
 - Unnamed: 43
 - Unnamed: 44
 - Unnamed: 45
 - Unnamed: 46
 - Unnamed: 47
 - Unnamed: 48
 - Unnamed: 49
 - Unnamed: 50
 - Unnamed: 51
 - Unnamed: 52
 - Unnamed: 53
 - Unnamed: 54
 - Unnamed: 55
 - Unnamed: 56
 - Unnamed: 57
 - Unnamed: 58
 - Unnamed: 59
 - Unnamed: 60
 - Unnamed: 61
 - Unnamed: 62
 - Unnamed: 63
 - Unnamed: 64
 - Unnamed: 65
 - Unnamed: 66
 - Unnamed: 67
 - Unnamed: 68
 - Unnamed: 69
 - Unnamed: 70
 - Unnamed: 71
 - Unnamed: 72
 - Unnamed: 73
 - Unnamed: 74
 - Unnamed: 75
 - Unnamed: 76
 - Unnamed: 77
 - Unnamed: 78
 - Unnamed: 79
 - Unnamed: 80
 - Unnamed: 81
 - Unnamed: 82
 - Unnamed: 83
 - Unnamed: 84
 - Unnamed: 85
 - Unnamed: 86
 - Unnamed: 87
 - Unnamed: 88
 - Unnamed: 89
 - Unnamed: 90
 - Unnamed: 91
 - Unnamed: 92
 - Unnamed: 93
 - Unnamed: 94
 - Unnamed: 95
 - Unnamed: 96
 - Unnamed: 97

First 3 rows:

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97
0,Descriptive 2022 (MN Phase 2),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Province, district and municipality then Atten...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Counting: Population,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

==================================================
TABLE5.xlsx
==================================================
Rows: 14
Columns:
 - Unnamed: 0
 - Unnamed: 1
 - Unnamed: 2
 - Unnamed: 3
 - Unnamed: 4
 - Unnamed: 5
 - Unnamed: 6
 - Unnamed: 7
 - Unnamed: 8
 - Unnamed: 9
 - Unnamed: 10
 - Unnamed: 11
 - Unnamed: 12
 - Unnamed: 13
 - Unnamed: 14
 - Unnamed: 15
 - Unnamed: 16
 - Unnamed: 17
 - Unnamed: 18
 - Unnamed: 19
 - Unnamed: 20

First 3 rows:

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,Descriptive 2022 (MN Phase 2),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Province, district and municipality then Quest...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Counting: Population,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
# ============================================
# INSPECT TABLE5 RAW EXCEL LAYOUT
# ============================================

table5 = TABLES_DIR / "TABLE5.xlsx"

raw_table5 = pd.read_excel(
    table5,
    header=None
)

print("Rows:", len(raw_table5))
print("Columns:", len(raw_table5.columns))

display(raw_table5)

Rows: 15
Columns: 21

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Descriptive 2022 (MN Phase 2),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Province, district and municipality then Quest...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Counting: Population,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Filters:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Default Summation,Population,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,"Province, district and municipality then Quest...",KwaZulu-Natal,Household,Homeless,Transient,Institution,Urban area,Tribal or Traditional area,Farm area,Formal residential,...,Traditional residential,Farms,Parks and recreation,Collective living quarters,Industrial,Small holdings,Vacant,Commercial,Male,Female
9,NaN,12423906.662782,61367658.619297,55719,2623,601502,39366168.367817,20254463.904037,2406870.347507,34773150.614651,...,19811611.317867,1643269.858092,24476.10274,288493.911735,81909.621183,266590.178248,66941.948922,218006.301069,30078756.687159,31948745.932222
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,© Statistics South Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
# ============================================
# INSPECT RAW STATS SA TABLE STRUCTURE
# ============================================

for file in table_files:

    print(f"\n{'=' * 60}")
    print(file.name)
    print(f"{'=' * 60}")

    raw_df = pd.read_excel(
        file,
        header=None
    )

    print("Shape:", raw_df.shape)

    # Show all non-empty cells
    for row_index, row in raw_df.iterrows():

        values = [
            str(value)
            for value in row
            if pd.notna(value)
        ]

        if values:
            print(f"Row {row_index}:")
            print(values[:10], "..." if len(values) > 10 else "")

============================================================
TABLE1.xlsx
============================================================
Shape: (16, 514)
Row 1:
['Descriptive 2022 (MN Phase 2)']
Row 2:
['Province, district and municipality and Questionnaire type then Geography type then Sex']
Row 3:
['Counting: Population']
Row 5:
['Filters:']
Row 6:
['Default Summation', 'Population']
Row 8:
['Province, district and municipality', 'KwaZulu-Natal', 'Ugu', 'Umdoni Local Municipality', 'Umzumbe Local Municipality', 'UMuziwabantu Local Municipality', 'Ray Nkonyeni Local Municipality', 'Umgungundlovu', 'uMshwathi Local Municipality', 'uMngeni Local Municipality'] ...
Row 9:
['Questionnaire type then Geography type then Sex', 'Household', 'Homeless', 'Transient', 'Institution', 'Urban area', 'Tribal or Traditional area', 'Farm area', 'Male', 'Female'] ...
Row 10:
['12279374.662785625', '7768', '93', '136671', '6060765.093845516', '5819613.969936846', '543527.5990030895', '5919216.636794859', '6504690.025991391', '771411.6543514762'] ...
Row 15:
['© Statistics South Africa']

============================================================
TABLE2.xlsx
============================================================
Shape: (71, 2)
Row 1:
['Descriptive 2022 (MN Phase 2)']
Row 2:
['Province, district and municipality']
Row 3:
['Counting: Population']
Row 5:
['Filters:']
Row 6:
['Default Summation', 'Population']
Row 8:
['Province, district and municipality']
Row 9:
['KwaZulu-Natal', '12423906.662785623']
Row 10:
['Ugu', '773401.6543514762']
Row 11:
['Umdoni Local Municipality', '156442.8802611416']
Row 12:
['Umzumbe Local Municipality', '139044.8059699663']
Row 13:
['UMuziwabantu Local Municipality', '115779.52551139316']
Row 14:
['Ray Nkonyeni Local Municipality', '362134.44260897517']
Row 15:
['Umgungundlovu', '1235715.497128913']
Row 16:
['uMshwathi Local Municipality', '118477.83272986031']
Row 17:
['uMngeni Local Municipality', '105068.59563358407']
Row 18:
['Mpofana Local Municipality', '33382.36426061015']
Row 19:
['Impendle Local Municipality', '36647.72385531167']
Row 20:
['The Msunduzi Local Municipality', '817725.0794047411']
Row 21:
['Mkhambathini Local Municipality', '61660.24514030446']
Row 22:
['Richmond Local Municipality', '62753.656104501104']
Row 23:
['Uthukela', '789091.8178653348']
Row 24:
['Okhahlamba Local Municipality', '143132.47712344155']
Row 25:
['Inkosi Langalibalele Local Municipality', '230923.81823407355']
Row 26:
['Alfred Duma Local Municipality', '415035.5225078197']
Row 27:
['Umzinyathi', '649260.9800325411']
Row 28:
['Endumeni Local Municipality', '100085.33395678402']
Row 29:
['Nqutu Local Municipality', '201132.54922641235']
Row 30:
['Msinga Local Municipality', '206001.27131180197']
Row 31:
['Umvoti Local Municipality', '142041.82553754273']
Row 32:
['Amajuba', '687407.9072301094']
Row 33:
['Newcastle Local Municipality', '507710.27941126324']
Row 34:
['Emadlangeni Local Municipality', '36947.635941151464']
Row 35:
['Dannhauser Local Municipality', '142749.99187769476']
Row 36:
['Zululand', '942794.2047341743']
Row 37:
['eDumbe Local Municipality', '96735.251963954']
Row 38:
['UPhongolo Local Municipality', '151540.592491773']
Row 39:
['Abaqulusi Local Municipality', '247262.85741333273']
Row 40:
['Nongoma Local Municipality', '225278.4029577534']
Row 41:
['Ulundi Local Municipality', '221977.09990736123']
Row 42:
['Umkhanyakude', '738436.5511074458']
Row 43:
['Umhlabuyalingana Local Municipality', '191659.71423636732']
Row 44:
['Jozini Local Municipality', '199152.94824647388']
Row 45:
['Mtubatuba Local Municipality', '215869.21386156185']
Row 46:
['Big Five Hlabisa Local Municipality', '131754.67476304286']
Row 47:
['King Cetshwayo', '1021343.5473776507']
Row 48:
['Mfolozi Local Municipality', '159667.95534802426']
Row 49:
['uMhlathuze Local Municipality', '412074.9678163402']
Row 50:
['uMlalazi Local Municipality', '241416.08102747172']
Row 51:
['Mthonjaneni Local Municipality', '99288.7499040245']
Row 52:
['Nkandla Local Municipality', '108895.79328179012']
Row 53:
['iLembe', '782660.810158073']
Row 54:
['Mandeni Local Municipality', '180939.49087498474']
Row 55:
['KwaDukuza Local Municipality', '324911.653516167']
Row 56:
['Ndwedwe Local Municipality', '165826.30055840104']
Row 57:
['Maphumulo Local Municipality', '110983.36520852026']
Row 58:
['Harry Gwala', '563893.0973213334']
Row 59:
['Greater Kokstad Local Municipality', '81676.11889501508']
Row 60:
['Ubuhlebezwe Local Municipality', '133031.88088912296']
Row 61:
['Umzimkhulu Local Municipality', '220619.69942617483']
Row 62:
['Dr Nkosazana Dlamini Zuma Local Municipality', '128565.39811102043']
Row 63:
['eThekwini', '4239900.595478572']
Row 64:
['Ethekwini Metropolitan Municipality', '4239900.595478572']
Row 65:
['Total', '12423906.662785623']
Row 70:
['© Statistics South Africa']

============================================================
TABLE3.xlsx
============================================================
Shape: (174, 2)
Row 1:
['Descriptive 2022 (MN Phase 2)']
Row 2:
['Province, district and municipality then Sex then Age in completed years then Population group then Language most often spoken']
Row 3:
['Counting: Population']
Row 5:
['Filters:']
Row 6:
['Default Summation', 'Population']
Row 8:
['Province, district and municipality then Sex then Age in completed years then Population group then Language most often spoken']
Row 9:
['KwaZulu-Natal', '12423906.662782008']
Row 10:
['Male', '30078756.68715917']
Row 11:
['Female', '31948745.932222202']
Row 12:
['0', '1250353.0477566998']
Row 13:
['1', '1168240.7098342404']
Row 14:
['2', '1188298.519725562']
Row 15:
['3', '1130328.801133854']
Row 16:
['4', '1096293.544273597']
Row 17:
['5', '954477.8158382007']
Row 18:
['6', '1011729.9181077147']
Row 19:
['7', '1048430.4954019606']
Row 20:
['8', '1038061.8678377874']
Row 21:
['9', '1056403.960507052']
Row 22:
['10', '1055068.457665082']
Row 23:
['11', '1094814.8671509093']
Row 24:
['12', '1076374.1380515625']
Row 25:
['13', '1105321.124375608']
Row 26:
['14', '1072545.808294187']
Row 27:
['15', '1081806.7521004202']
Row 28:
['16', '1071637.4746376863']
Row 29:
['17', '1012704.5819278515']
Row 30:
['18', '924581.9361747585']
Row 31:
['19', '884578.6450539028']
Row 32:
['20', '1011053.8720050836']
Row 33:
['21', '1108187.811439477']
Row 34:
['22', '1071721.7514606449']
Row 35:
['23', '1046759.992262469']
Row 36:
['24', '1072014.9485557876']
Row 37:
['25', '1148424.247052114']
Row 38:
['26', '1136839.9239893607']
Row 39:
['27', '1166568.4135864838']
Row 40:
['28', '1119027.2803796697']
Row 41:
['29', '1162379.4367141034']
Row 42:
['30', '1116319.6495038825']
Row 43:
['31', '1188644.0243981257']
Row 44:
['32', '1136049.2140213395']
Row 45:
['33', '1092202.5693637016']
Row 46:
['34', '1059607.7635442668']
Row 47:
['35', '1087150.6542802271']
Row 48:
['36', '1116115.798005921']
Row 49:
['37', '1013254.1268394778']
Row 50:
['38', '985651.0993329806']
Row 51:
['39', '1020430.9534832736']
Row 52:
['40', '869827.3012684205']
Row 53:
['41', '915951.0753247882']
Row 54:
['42', '862835.272796487']
Row 55:
['43', '773994.5810113424']
Row 56:
['44', '762612.2443527612']
Row 57:
['45', '674839.8431609498']
Row 58:
['46', '693512.0272348332']
Row 59:
['47', '660506.6147818052']
Row 60:
['48', '611119.517081962']
Row 61:
['49', '653532.7432173077']
Row 62:
['50', '541704.233774958']
Row 63:
['51', '609837.051723792']
Row 64:
['52', '570241.6141584215']
Row 65:
['53', '564956.1357245826']
Row 66:
['54', '482399.8481527956']
Row 67:
['55', '487908.8266968451']
Row 68:
['56', '519401.6315074663']
Row 69:
['57', '495841.2589424853']
Row 70:
['58', '499476.1631176444']
Row 71:
['59', '493824.37993875594']
Row 72:
['60', '418434.23081899824']
Row 73:
['61', '464394.8079334493']
Row 74:
['62', '413990.47587110917']
Row 75:
['63', '424262.00762092625']
Row 76:
['64', '374585.5405778911']
Row 77:
['65', '357817.36389965215']
Row 78:
['66', '329316.6613640407']
Row 79:
['67', '312775.51926583966']
Row 80:
['68', '293990.2016532795']
Row 81:
['69', '305771.3895760297']
Row 82:
['70', '216840.96990516665']
Row 83:
['71', '247353.56951391714']
Row 84:
['72', '211995.56745580756']
Row 85:
['73', '193955.47164128817']
Row 86:
['74', '175860.65532042892']
Row 87:
['75', '154518.72986150888']
Row 88:
['76', '144378.89855819967']
Row 89:
['77', '122130.80579016994']
Row 90:
['78', '111837.23724463']
Row 91:
['79', '119167.6743545197']
Row 92:
['80', '87280.4727571206']
Row 93:
['81', '107020.9498748994']
Row 94:
['82', '79940.9218090606']
Row 95:
['83', '66487.21640759068']
Row 96:
['84', '54084.80989495051']
Row 97:
['85', '51266.5676116504']
Row 98:
['86', '41882.51298336028']
Row 99:
['87', '35638.12131190021']
Row 100:
['88', '30139.537930640163']
Row 101:
['89', '28378.165589180142']
Row 102:
['90', '18967.979100440025']
Row 103:
['91', '26005.46738770011']
Row 104:
['92', '17560.433412509978']
Row 105:
['93', '12043.999692810012']
Row 106:
['94', '8928.51205565']
Row 107:
['95', '6863.610443849997']
Row 108:
['96', '5598.085806150004']
Row 109:
['97', '4475.855592379997']
Row 110:
['98', '3023.2039067699993']
Row 111:
['99', '9334.46605617']
Row 112:
['100', '2012.87095444']
Row 113:
['101', '3053.7929948099973']
Row 114:
['102', '1529.09938422']
Row 115:
['103', '1409.8219754299992']
Row 116:
['104', '587.4269523500001']
Row 117:
['105', '416.3989903700002']
Row 118:
['106', '297.09246033']
Row 119:
['107', '507.01250353000006']
Row 120:
['108', '224.98885828000004']
Row 121:
['109', '230.58103138']
Row 122:
['110', '123.22187198999998']
Row 123:
['111', '212.68526568000007']
Row 124:
['112', '112.66083465']
Row 125:
['113', '89.4185187']
Row 126:
['114', '72.1248282']
Row 127:
['115', '66.80582670000001']
Row 128:
['116', '50.17795712']
Row 129:
['117', '48.7927508']
Row 130:
['118', '35.066935799999996']
Row 131:
['119', '47.676912099999996']
Row 132:
['120', '26.040634499999996']
Row 133:
['121', '89.60858410000002']
Row 134:
['122', '23.4395779']
Row 135:
['123', '20.78951268']
Row 136:
['124', '18.0021146']
Row 137:
['125', '22.329130799999998']
Row 138:
['126', '19.05679446']
Row 139:
['127', '20.3487991']
Row 140:
['128', '2.8551609']
Row 141:
['129', '45.698344920000004']
Row 142:
['130', '10.7050445']
Row 143:
['Unspecified', '2999']
Row 144:
['Black African', '50486855.96347812']
Row 145:
['Coloured', '5052348.525046748']
Row 146:
['Indian or Asian', '1697505.861473724']
Row 147:
['White', '4504251.530739763']
Row 148:
['Other', '247352.73866097874']
Row 149:
['Unspecified', '39188']
Row 150:
['Afrikaans', '6365488.405515495']
Row 151:
['English', '5228300.544795035']
Row 152:
['Isindebele', '1044376.7929603198']
Row 153:
['IsiXhosa', '9786927.720113318']
Row 154:
['IsiZulu', '14613202.455735149']
Row 155:
['Sepedi', '5972255.272087867']
Row 156:
['Sesotho', '4678964.246650568']
Row 157:
['Setswana', '4972786.701879141']
Row 158:
['Sign language', '9307.758971719988']
Row 159:
['Siswati', '1692719.4003870934']
Row 160:
['Tshivenda', '1480564.9534887602']
Row 161:
['Xitsonga', '2784279.19356695']
Row 162:
['Khoi,Nama and San languages', '5916.920972349997']
Row 163:
['Shona', '716966.5524298036']
Row 164:
['Chichewa/Chewa/Nyanja/Chinyanja', '161162.11719687685']
Row 165:
['Portuguese', '95160.86665483234']
Row 166:
['Other', '268067.743669248']
Row 167:
['Not applicable', '1892088.047756694']
Row 168:
['Unspecified', '258966.92456068797']
Row 173:
['© Statistics South Africa']

============================================================
TABLE4.xlsx
============================================================
Shape: (15, 98)
Row 1:
['Descriptive 2022 (MN Phase 2)']
Row 2:
['Province, district and municipality then Attendance at an ECD institution then Attendance \xa0and educational institution then Highest level of education']
Row 3:
['Counting: Population']
Row 5:
['Filters:']
Row 6:
['Default Summation', 'Population']
Row 8:
['Province, district and municipality then Attendance at an ECD institution then Attendance \xa0and educational institution then Highest level of education', 'Umdoni Local Municipality', 'Umzumbe Local Municipality', 'UMuziwabantu Local Municipality', 'Ray Nkonyeni Local Municipality', 'Okhahlamba Local Municipality', 'Inkosi Langalibalele Local Municipality', 'Alfred Duma Local Municipality', 'Endumeni Local Municipality', 'Nqutu Local Municipality'] ...
Row 9:
['156442.8802611416', '139044.8059699663', '115779.52551139316', '362134.44260897517', '143132.47712344155', '230923.81823407355', '415035.5225078197', '100085.33395678402', '201132.54922641235', '206001.27131180197'] ...
Row 14:
['© Statistics South Africa']

============================================================
TABLE5.xlsx
============================================================
Shape: (15, 21)
Row 1:
['Descriptive 2022 (MN Phase 2)']
Row 2:
['Province, district and municipality then Questionnaire type then Geography type then Enumeration area type then Sex']
Row 3:
['Counting: Population']
Row 5:
['Filters:']
Row 6:
['Default Summation', 'Population']
Row 8:
['Province, district and municipality then Questionnaire type then Geography type then Enumeration area type then Sex', 'KwaZulu-Natal', 'Household', 'Homeless', 'Transient', 'Institution', 'Urban area', 'Tribal or Traditional area', 'Farm area', 'Formal residential'] ...
Row 9:
['12423906.662782008', '61367658.61929744', '55719', '2623', '601502', '39366168.36781715', '20254463.90403709', '2406870.3475069227', '34773150.61465113', '4853052.764870647'] ...
Row 14:
['© Statistics South Africa']

In [20]:
# ============================================
# SUMMARISE STATS SA TABLE STRUCTURE
# ============================================

for file in table_files:

    raw_df = pd.read_excel(
        file,
        header=None
    )

    print(f"\n{'=' * 60}")
    print(file.name)
    print(f"{'=' * 60}")

    print("Shape:", raw_df.shape)

    # Show the important metadata rows
    for row_number in [1, 2, 3, 6]:
        if row_number < len(raw_df):
            values = raw_df.iloc[row_number].dropna().tolist()

            print(f"\nRow {row_number}:")
            print(values[:10])

    # Show first 10 geography headings
    if len(raw_df) > 8:
        geography = raw_df.iloc[8].dropna().tolist()

        print("\nGeography/classification row:")
        print(geography[:15])

    # Show first 10 values from the data row
    if len(raw_df) > 10:
        data_values = raw_df.iloc[10].dropna().tolist()

        print("\nFirst data row:")
        print(data_values[:15])

============================================================
TABLE1.xlsx
============================================================
Shape: (16, 514)

Row 1:
['Descriptive 2022 (MN Phase 2)']

Row 2:
['Province, district and municipality and Questionnaire type then Geography type then Sex']

Row 3:
['Counting: Population']

Row 6:
['Default Summation', 'Population']

Geography/classification row:
['Province, district and municipality', 'KwaZulu-Natal', 'Ugu', 'Umdoni Local Municipality', 'Umzumbe Local Municipality', 'UMuziwabantu Local Municipality', 'Ray Nkonyeni Local Municipality', 'Umgungundlovu', 'uMshwathi Local Municipality', 'uMngeni Local Municipality', 'Mpofana Local Municipality', 'Impendle Local Municipality', 'The Msunduzi Local Municipality', 'Mkhambathini Local Municipality', 'Richmond Local Municipality']

First data row:
[12279374.662785625, 7768, 93, 136671, 6060765.093845516, 5819613.969936846, 543527.5990030895, 5919216.636794859, 6504690.025991391, 771411.6543514762, 413, 9, 1568, 150558.91354772617, 598807.7361573568]

============================================================
TABLE2.xlsx
============================================================
Shape: (71, 2)

Row 1:
['Descriptive 2022 (MN Phase 2)']

Row 2:
['Province, district and municipality']

Row 3:
['Counting: Population']

Row 6:
['Default Summation', 'Population']

Geography/classification row:
['Province, district and municipality']

First data row:
['Ugu', 773401.6543514762]

============================================================
TABLE3.xlsx
============================================================
Shape: (174, 2)

Row 1:
['Descriptive 2022 (MN Phase 2)']

Row 2:
['Province, district and municipality then Sex then Age in completed years then Population group then Language most often spoken']

Row 3:
['Counting: Population']

Row 6:
['Default Summation', 'Population']

Geography/classification row:
['Province, district and municipality then Sex then Age in completed years then Population group then Language most often spoken']

First data row:
['Male', 30078756.68715917]

============================================================
TABLE4.xlsx
============================================================
Shape: (15, 98)

Row 1:
['Descriptive 2022 (MN Phase 2)']

Row 2:
['Province, district and municipality then Attendance at an ECD institution then Attendance \xa0and educational institution then Highest level of education']

Row 3:
['Counting: Population']

Row 6:
['Default Summation', 'Population']

Geography/classification row:
['Province, district and municipality then Attendance at an ECD institution then Attendance \xa0and educational institution then Highest level of education', 'Umdoni Local Municipality', 'Umzumbe Local Municipality', 'UMuziwabantu Local Municipality', 'Ray Nkonyeni Local Municipality', 'Okhahlamba Local Municipality', 'Inkosi Langalibalele Local Municipality', 'Alfred Duma Local Municipality', 'Endumeni Local Municipality', 'Nqutu Local Municipality', 'Msinga Local Municipality', 'Umvoti Local Municipality', 'Zululand', 'eDumbe Local Municipality', 'UPhongolo Local Municipality']

First data row:
[]

============================================================
TABLE5.xlsx
============================================================
Shape: (15, 21)

Row 1:
['Descriptive 2022 (MN Phase 2)']

Row 2:
['Province, district and municipality then Questionnaire type then Geography type then Enumeration area type then Sex']

Row 3:
['Counting: Population']

Row 6:
['Default Summation', 'Population']

Geography/classification row:
['Province, district and municipality then Questionnaire type then Geography type then Enumeration area type then Sex', 'KwaZulu-Natal', 'Household', 'Homeless', 'Transient', 'Institution', 'Urban area', 'Tribal or Traditional area', 'Farm area', 'Formal residential', 'Informal residential', 'Traditional residential', 'Farms', 'Parks and recreation', 'Collective living quarters']

First data row:
[]

In [21]:
# ============================================
# IDENTIFY MUNICIPALITY COLUMNS IN TABLE1
# ============================================

table1 = pd.read_excel(
    TABLES_DIR / "TABLE1.xlsx",
    header=None
)

geography_row = table1.iloc[8]
value_row = table1.iloc[10]

print("TABLE1 shape:", table1.shape)

print("\nFirst 30 geography entries:")
for i, value in enumerate(geography_row.iloc[:30]):
    print(i, "->", value)

print("\nFirst 30 corresponding values:")
for i, value in enumerate(value_row.iloc[:30]):
    print(i, "->", value)

TABLE1 shape: (16, 514)

First 30 geography entries:
0 -> Province, district and municipality
1 -> KwaZulu-Natal
2 -> nan
3 -> nan
4 -> nan
5 -> nan
6 -> nan
7 -> nan
8 -> nan
9 -> nan
10 -> Ugu
11 -> nan
12 -> nan
13 -> nan
14 -> nan
15 -> nan
16 -> nan
17 -> nan
18 -> nan
19 -> Umdoni Local Municipality
20 -> nan
21 -> nan
22 -> nan
23 -> nan
24 -> nan
25 -> nan
26 -> nan
27 -> nan
28 -> Umzumbe Local Municipality
29 -> nan

First 30 corresponding values:
0 -> nan
1 -> 12279374.662785625
2 -> 7768
3 -> 93
4 -> 136671
5 -> 6060765.093845516
6 -> 5819613.969936846
7 -> 543527.5990030895
8 -> 5919216.636794859
9 -> 6504690.025991391
10 -> 771411.6543514762
11 -> 413
12 -> 9
13 -> 1568
14 -> 150558.91354772617
15 -> 598807.7361573568
16 -> 24035.00464634987
17 -> 366400.6989871926
18 -> 407000.95536423894
19 -> 156080.8802611416
20 -> 99
21 -> 1
22 -> 262
23 -> 39850.27142586097
24 -> 104607.2186177397
25 -> 11985.390217549902
26 -> 74391.52150339381
27 -> 82051.35875776583
28 -> 138859.8059699663
29 -> 56

In [22]:
# ============================================
# INSPECT TABLE1 COLUMN HIERARCHY
# ============================================

table1 = pd.read_excel(
    TABLES_DIR / "TABLE1.xlsx",
    header=None
)

for col in range(0, 80):

    values = []

    for row in [8, 9, 10]:
        value = table1.iloc[row, col]

        if pd.notna(value):
            values.append(str(value))

    if values:
        print(f"Column {col}:")
        for value in values:
            print("   ", value)

Column 0:
    Province, district and municipality
    Questionnaire type then Geography type then Sex
Column 1:
    KwaZulu-Natal
    Household
    12279374.662785625
Column 2:
    Homeless
    7768
Column 3:
    Transient
    93
Column 4:
    Institution
    136671
Column 5:
    Urban area
    6060765.093845516
Column 6:
    Tribal or Traditional area
    5819613.969936846
Column 7:
    Farm area
    543527.5990030895
Column 8:
    Male
    5919216.636794859
Column 9:
    Female
    6504690.025991391
Column 10:
    Ugu
    Household
    771411.6543514762
Column 11:
    Homeless
    413
Column 12:
    Transient
    9
Column 13:
    Institution
    1568
Column 14:
    Urban area
    150558.91354772617
Column 15:
    Tribal or Traditional area
    598807.7361573568
Column 16:
    Farm area
    24035.00464634987
Column 17:
    Male
    366400.6989871926
Column 18:
    Female
    407000.95536423894
Column 19:
    Umdoni Local Municipality
    Household
    156080.8802611416
Column 20:
    Homeless
    99
Column 21:
    Transient
    1
Column 22:
    Institution
    262
Column 23:
    Urban area
    39850.27142586097
Column 24:
    Tribal or Traditional area
    104607.2186177397
Column 25:
    Farm area
    11985.390217549902
Column 26:
    Male
    74391.52150339381
Column 27:
    Female
    82051.35875776583
Column 28:
    Umzumbe Local Municipality
    Household
    138859.8059699663
Column 29:
    Homeless
    56
Column 30:
    Transient
    4
Column 31:
    Institution
    125
Column 32:
    Urban area
    0
Column 33:
    Tribal or Traditional area
    139029.36387646638
Column 34:
    Farm area
    15.442093500000002
Column 35:
    Male
    65512.79220890818
Column 36:
    Female
    73532.013761062
Column 37:
    UMuziwabantu Local Municipality
    Household
    115539.52551139316
Column 38:
    Homeless
    54
Column 39:
    Transient
    3
Column 40:
    Institution
    183
Column 41:
    Urban area
    12871.211719329975
Column 42:
    Tribal or Traditional area
    100534.2224893799
Column 43:
    Farm area
    2374.09130268
Column 44:
    Male
    54516.21065913827
Column 45:
    Female
    61263.31485225239
Column 46:
    Ray Nkonyeni Local Municipality
    Household
    360931.44260897517
Column 47:
    Homeless
    204
Column 48:
    Transient
    1
Column 49:
    Institution
    998
Column 50:
    Urban area
    97837.43040253523
Column 51:
    Tribal or Traditional area
    254636.93117377078
Column 52:
    Farm area
    9660.081032619968
Column 53:
    Male
    171980.17461575233
Column 54:
    Female
    190154.2679931587
Column 55:
    Umgungundlovu
    Household
    1225895.497128913
Column 56:
    Homeless
    517
Column 57:
    Transient
    4
Column 58:
    Institution
    9299
Column 59:
    Urban area
    767569.0763174186
Column 60:
    Tribal or Traditional area
    386444.07029676525
Column 61:
    Farm area
    81702.35051469016
Column 62:
    Male
    589011.7180874618
Column 63:
    Female
    646703.7790413876
Column 64:
    uMshwathi Local Municipality
    Household
    117861.83272986031
Column 65:
    Homeless
    10
Column 66:
    Transient
    1
Column 67:
    Institution
    605
Column 68:
    Urban area
    15332.360949009893
Column 69:
    Tribal or Traditional area
    72093.56327771148
Column 70:
    Farm area
    31051.908503120212
Column 71:
    Male
    55836.57193605163
Column 72:
    Female
    62641.26079379732
Column 73:
    uMngeni Local Municipality
    Household
    104354.59563358407
Column 74:
    Homeless
    59
Column 75:
    Transient
    0
Column 76:
    Institution
    655
Column 77:
    Urban area
    86250.14332081159
Column 78:
    Tribal or Traditional area
    11491.315629379887
Column 79:
    Farm area
    7327.136683379969

In [23]:
# ============================================
# EXTRACT GEOGRAPHIC HIERARCHY FROM TABLE1
# ============================================

table1 = pd.read_excel(
    TABLES_DIR / "TABLE1.xlsx",
    header=None
)

geography_row = table1.iloc[8]

# Print every non-empty geography heading
print("Geographic headings found in TABLE1:\n")

for col, value in geography_row.items():

    if pd.notna(value):
        print(f"Column {col}: {value}")

Geographic headings found in TABLE1:

Column 0: Province, district and municipality
Column 1: KwaZulu-Natal
Column 10: Ugu
Column 19: Umdoni Local Municipality
Column 28: Umzumbe Local Municipality
Column 37: UMuziwabantu Local Municipality
Column 46: Ray Nkonyeni Local Municipality
Column 55: Umgungundlovu
Column 64: uMshwathi Local Municipality
Column 73: uMngeni Local Municipality
Column 82: Mpofana Local Municipality
Column 91: Impendle Local Municipality
Column 100: The Msunduzi Local Municipality
Column 109: Mkhambathini Local Municipality
Column 118: Richmond Local Municipality
Column 127: Uthukela
Column 136: Okhahlamba Local Municipality
Column 145: Inkosi Langalibalele Local Municipality
Column 154: Alfred Duma Local Municipality
Column 163: Umzinyathi
Column 172: Endumeni Local Municipality
Column 181: Nqutu Local Municipality
Column 190: Msinga Local Municipality
Column 199: Umvoti Local Municipality
Column 208: Amajuba
Column 217: Newcastle Local Municipality
Column 226: Emadlangeni Local Municipality
Column 235: Dannhauser Local Municipality
Column 244: Zululand
Column 253: eDumbe Local Municipality
Column 262: UPhongolo Local Municipality
Column 271: Abaqulusi Local Municipality
Column 280: Nongoma Local Municipality
Column 289: Ulundi Local Municipality
Column 298: Umkhanyakude
Column 307: Umhlabuyalingana Local Municipality
Column 316: Jozini Local Municipality
Column 325: Mtubatuba Local Municipality
Column 334: Big Five Hlabisa Local Municipality
Column 343: King Cetshwayo
Column 352: Mfolozi Local Municipality
Column 361: uMhlathuze Local Municipality
Column 370: uMlalazi Local Municipality
Column 379: Mthonjaneni Local Municipality
Column 388: Nkandla Local Municipality
Column 397: iLembe
Column 406: Mandeni Local Municipality
Column 415: KwaDukuza Local Municipality
Column 424: Ndwedwe Local Municipality
Column 433: Maphumulo Local Municipality
Column 442: Harry Gwala
Column 451: Greater Kokstad Local Municipality
Column 460: Ubuhlebezwe Local Municipality
Column 469: Umzimkhulu Local Municipality
Column 478: Dr Nkosazana Dlamini Zuma Local Municipality
Column 487: eThekwini
Column 496: Ethekwini Metropolitan Municipality
Column 505: Total

In [24]:
# ============================================
# CHECK TABLE2 TO TABLE5 STRUCTURE
# ============================================

for table_number in range(2, 6):

    file = TABLES_DIR / f"TABLE{table_number}.xlsx"

    df = pd.read_excel(
        file,
        header=None
    )

    print(f"\n{'=' * 60}")
    print(f"TABLE{table_number}")
    print(f"{'=' * 60}")

    print("Shape:", df.shape)

    # Show non-empty cells from the first 10 rows
    for row in range(min(10, len(df))):

        values = df.iloc[row].dropna().tolist()

        if values:
            print(f"\nRow {row}:")
            print(values[:12])

============================================================
TABLE2
============================================================
Shape: (71, 2)

Row 1:
['Descriptive 2022 (MN Phase 2)']

Row 2:
['Province, district and municipality']

Row 3:
['Counting: Population']

Row 5:
['Filters:']

Row 6:
['Default Summation', 'Population']

Row 8:
['Province, district and municipality']

Row 9:
['KwaZulu-Natal', 12423906.662785623]

============================================================
TABLE3
============================================================
Shape: (174, 2)

Row 1:
['Descriptive 2022 (MN Phase 2)']

Row 2:
['Province, district and municipality then Sex then Age in completed years then Population group then Language most often spoken']

Row 3:
['Counting: Population']

Row 5:
['Filters:']

Row 6:
['Default Summation', 'Population']

Row 8:
['Province, district and municipality then Sex then Age in completed years then Population group then Language most often spoken']

Row 9:
['KwaZulu-Natal', 12423906.662782008]

============================================================
TABLE4
============================================================
Shape: (15, 98)

Row 1:
['Descriptive 2022 (MN Phase 2)']

Row 2:
['Province, district and municipality then Attendance at an ECD institution then Attendance \xa0and educational institution then Highest level of education']

Row 3:
['Counting: Population']

Row 5:
['Filters:']

Row 6:
['Default Summation', 'Population']

Row 8:
['Province, district and municipality then Attendance at an ECD institution then Attendance \xa0and educational institution then Highest level of education', 'Umdoni Local Municipality', 'Umzumbe Local Municipality', 'UMuziwabantu Local Municipality', 'Ray Nkonyeni Local Municipality', 'Okhahlamba Local Municipality', 'Inkosi Langalibalele Local Municipality', 'Alfred Duma Local Municipality', 'Endumeni Local Municipality', 'Nqutu Local Municipality', 'Msinga Local Municipality', 'Umvoti Local Municipality']

Row 9:
[156442.8802611416, 139044.8059699663, 115779.52551139316, 362134.44260897517, 143132.47712344155, 230923.81823407355, 415035.5225078197, 100085.33395678402, 201132.54922641235, 206001.27131180197, 142041.82553754273, 942794.2047341896]

============================================================
TABLE5
============================================================
Shape: (15, 21)

Row 1:
['Descriptive 2022 (MN Phase 2)']

Row 2:
['Province, district and municipality then Questionnaire type then Geography type then Enumeration area type then Sex']

Row 3:
['Counting: Population']

Row 5:
['Filters:']

Row 6:
['Default Summation', 'Population']

Row 8:
['Province, district and municipality then Questionnaire type then Geography type then Enumeration area type then Sex', 'KwaZulu-Natal', 'Household', 'Homeless', 'Transient', 'Institution', 'Urban area', 'Tribal or Traditional area', 'Farm area', 'Formal residential', 'Informal residential', 'Traditional residential']

Row 9:
[12423906.662782008, 61367658.61929744, 55719, 2623, 601502, 39366168.36781715, 20254463.90403709, 2406870.3475069227, 34773150.61465113, 4853052.764870647, 19811611.317867056, 1643269.8580915704]

In [25]:
# ============================================
# VIEW TABLE2 COMPLETELY
# ============================================

table2 = pd.read_excel(
    TABLES_DIR / "TABLE2.xlsx",
    header=None
)

print("TABLE2 shape:", table2.shape)

display(table2)

TABLE2 shape: (71, 2)

                                      0    1
0                                   NaN  NaN
1         Descriptive 2022 (MN Phase 2)  NaN
2   Province, district and municipality  NaN
3                  Counting: Population  NaN
4                                   NaN  NaN
..                                  ...  ...
66                                  NaN  NaN
67                                  NaN  NaN
68                                  NaN  NaN
69                                  NaN  NaN
70            © Statistics South Africa  NaN

[71 rows x 2 columns]

In [26]:
# ============================================
# INSPECT TABLE2 EXCEL STRUCTURE
# ============================================

from openpyxl import load_workbook

table2_file = TABLES_DIR / "TABLE2.xlsx"

workbook = load_workbook(
    table2_file,
    data_only=True
)

sheet = workbook.active

print("Sheet:", sheet.title)
print("Rows:", sheet.max_row)
print("Columns:", sheet.max_column)

print("\nMerged cell ranges:")
for merged_range in sheet.merged_cells.ranges:
    print("-", merged_range)

Sheet: Data Sheet 0
Rows: 71
Columns: 2

Merged cell ranges:

C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\openpyxl\reader\drawings.py:67: UserWarning: wmf image format is not supported so the image is being dropped
  warn(msg)

In [27]:
# ============================================
# SHOW ALL NON-EMPTY CELLS IN TABLE2
# ============================================

for row in range(1, sheet.max_row + 1):

    values = []

    for col in range(1, sheet.max_column + 1):
        value = sheet.cell(row=row, column=col).value

        if value is not None:
            values.append(f"Column {col}: {value}")

    if values:
        print(f"Row {row}:")
        for value in values:
            print("   ", value)

Row 2:
    Column 1: Descriptive 2022 (MN Phase 2)
Row 3:
    Column 1: Province, district and municipality
Row 4:
    Column 1: Counting: Population
Row 6:
    Column 1: Filters:
Row 7:
    Column 1: Default Summation
    Column 2: Population
Row 9:
    Column 1: Province, district and municipality
Row 10:
    Column 1: KwaZulu-Natal
    Column 2: 12423906.662785623
Row 11:
    Column 1: Ugu
    Column 2: 773401.6543514762
Row 12:
    Column 1: Umdoni Local Municipality
    Column 2: 156442.8802611416
Row 13:
    Column 1: Umzumbe Local Municipality
    Column 2: 139044.8059699663
Row 14:
    Column 1: UMuziwabantu Local Municipality
    Column 2: 115779.52551139316
Row 15:
    Column 1: Ray Nkonyeni Local Municipality
    Column 2: 362134.44260897517
Row 16:
    Column 1: Umgungundlovu
    Column 2: 1235715.497128913
Row 17:
    Column 1: uMshwathi Local Municipality
    Column 2: 118477.83272986031
Row 18:
    Column 1: uMngeni Local Municipality
    Column 2: 105068.59563358407
Row 19:
    Column 1: Mpofana Local Municipality
    Column 2: 33382.36426061015
Row 20:
    Column 1: Impendle Local Municipality
    Column 2: 36647.72385531167
Row 21:
    Column 1: The Msunduzi Local Municipality
    Column 2: 817725.0794047411
Row 22:
    Column 1: Mkhambathini Local Municipality
    Column 2: 61660.24514030446
Row 23:
    Column 1: Richmond Local Municipality
    Column 2: 62753.656104501104
Row 24:
    Column 1: Uthukela
    Column 2: 789091.8178653348
Row 25:
    Column 1: Okhahlamba Local Municipality
    Column 2: 143132.47712344155
Row 26:
    Column 1: Inkosi Langalibalele Local Municipality
    Column 2: 230923.81823407355
Row 27:
    Column 1: Alfred Duma Local Municipality
    Column 2: 415035.5225078197
Row 28:
    Column 1: Umzinyathi
    Column 2: 649260.9800325411
Row 29:
    Column 1: Endumeni Local Municipality
    Column 2: 100085.33395678402
Row 30:
    Column 1: Nqutu Local Municipality
    Column 2: 201132.54922641235
Row 31:
    Column 1: Msinga Local Municipality
    Column 2: 206001.27131180197
Row 32:
    Column 1: Umvoti Local Municipality
    Column 2: 142041.82553754273
Row 33:
    Column 1: Amajuba
    Column 2: 687407.9072301094
Row 34:
    Column 1: Newcastle Local Municipality
    Column 2: 507710.27941126324
Row 35:
    Column 1: Emadlangeni Local Municipality
    Column 2: 36947.635941151464
Row 36:
    Column 1: Dannhauser Local Municipality
    Column 2: 142749.99187769476
Row 37:
    Column 1: Zululand
    Column 2: 942794.2047341743
Row 38:
    Column 1: eDumbe Local Municipality
    Column 2: 96735.251963954
Row 39:
    Column 1: UPhongolo Local Municipality
    Column 2: 151540.592491773
Row 40:
    Column 1: Abaqulusi Local Municipality
    Column 2: 247262.85741333273
Row 41:
    Column 1: Nongoma Local Municipality
    Column 2: 225278.4029577534
Row 42:
    Column 1: Ulundi Local Municipality
    Column 2: 221977.09990736123
Row 43:
    Column 1: Umkhanyakude
    Column 2: 738436.5511074458
Row 44:
    Column 1: Umhlabuyalingana Local Municipality
    Column 2: 191659.71423636732
Row 45:
    Column 1: Jozini Local Municipality
    Column 2: 199152.94824647388
Row 46:
    Column 1: Mtubatuba Local Municipality
    Column 2: 215869.21386156185
Row 47:
    Column 1: Big Five Hlabisa Local Municipality
    Column 2: 131754.67476304286
Row 48:
    Column 1: King Cetshwayo
    Column 2: 1021343.5473776507
Row 49:
    Column 1: Mfolozi Local Municipality
    Column 2: 159667.95534802426
Row 50:
    Column 1: uMhlathuze Local Municipality
    Column 2: 412074.9678163402
Row 51:
    Column 1: uMlalazi Local Municipality
    Column 2: 241416.08102747172
Row 52:
    Column 1: Mthonjaneni Local Municipality
    Column 2: 99288.7499040245
Row 53:
    Column 1: Nkandla Local Municipality
    Column 2: 108895.79328179012
Row 54:
    Column 1: iLembe
    Column 2: 782660.810158073
Row 55:
    Column 1: Mandeni Local Municipality
    Column 2: 180939.49087498474
Row 56:
    Column 1: KwaDukuza Local Municipality
    Column 2: 324911.653516167
Row 57:
    Column 1: Ndwedwe Local Municipality
    Column 2: 165826.30055840104
Row 58:
    Column 1: Maphumulo Local Municipality
    Column 2: 110983.36520852026
Row 59:
    Column 1: Harry Gwala
    Column 2: 563893.0973213334
Row 60:
    Column 1: Greater Kokstad Local Municipality
    Column 2: 81676.11889501508
Row 61:
    Column 1: Ubuhlebezwe Local Municipality
    Column 2: 133031.88088912296
Row 62:
    Column 1: Umzimkhulu Local Municipality
    Column 2: 220619.69942617483
Row 63:
    Column 1: Dr Nkosazana Dlamini Zuma Local Municipality
    Column 2: 128565.39811102043
Row 64:
    Column 1: eThekwini
    Column 2: 4239900.595478572
Row 65:
    Column 1: Ethekwini Metropolitan Municipality
    Column 2: 4239900.595478572
Row 66:
    Column 1: Total
    Column 2: 12423906.662785623
Row 71:
    Column 1: © Statistics South Africa

In [28]:
# ============================================
# INSPECT TABLE3
# ============================================

table3 = pd.read_excel(
    TABLES_DIR / "TABLE3.xlsx",
    header=None
)

print("TABLE3 shape:", table3.shape)

for row in range(len(table3)):

    values = table3.iloc[row].dropna().tolist()

    if values:
        print(f"\nRow {row}:")
        print(values[:15])

TABLE3 shape: (174, 2)

Row 1:
['Descriptive 2022 (MN Phase 2)']

Row 2:
['Province, district and municipality then Sex then Age in completed years then Population group then Language most often spoken']

Row 3:
['Counting: Population']

Row 5:
['Filters:']

Row 6:
['Default Summation', 'Population']

Row 8:
['Province, district and municipality then Sex then Age in completed years then Population group then Language most often spoken']

Row 9:
['KwaZulu-Natal', 12423906.662782008]

Row 10:
['Male', 30078756.68715917]

Row 11:
['Female', 31948745.932222202]

Row 12:
['0', 1250353.0477566998]

Row 13:
['1', 1168240.7098342404]

Row 14:
['2', 1188298.519725562]

Row 15:
['3', 1130328.801133854]

Row 16:
['4', 1096293.544273597]

Row 17:
['5', 954477.8158382007]

Row 18:
['6', 1011729.9181077147]

Row 19:
['7', 1048430.4954019606]

Row 20:
['8', 1038061.8678377874]

Row 21:
['9', 1056403.960507052]

Row 22:
['10', 1055068.457665082]

Row 23:
['11', 1094814.8671509093]

Row 24:
['12', 1076374.1380515625]

Row 25:
['13', 1105321.124375608]

Row 26:
['14', 1072545.808294187]

Row 27:
['15', 1081806.7521004202]

Row 28:
['16', 1071637.4746376863]

Row 29:
['17', 1012704.5819278515]

Row 30:
['18', 924581.9361747585]

Row 31:
['19', 884578.6450539028]

Row 32:
['20', 1011053.8720050836]

Row 33:
['21', 1108187.811439477]

Row 34:
['22', 1071721.7514606449]

Row 35:
['23', 1046759.992262469]

Row 36:
['24', 1072014.9485557876]

Row 37:
['25', 1148424.247052114]

Row 38:
['26', 1136839.9239893607]

Row 39:
['27', 1166568.4135864838]

Row 40:
['28', 1119027.2803796697]

Row 41:
['29', 1162379.4367141034]

Row 42:
['30', 1116319.6495038825]

Row 43:
['31', 1188644.0243981257]

Row 44:
['32', 1136049.2140213395]

Row 45:
['33', 1092202.5693637016]

Row 46:
['34', 1059607.7635442668]

Row 47:
['35', 1087150.6542802271]

Row 48:
['36', 1116115.798005921]

Row 49:
['37', 1013254.1268394778]

Row 50:
['38', 985651.0993329806]

Row 51:
['39', 1020430.9534832736]

Row 52:
['40', 869827.3012684205]

Row 53:
['41', 915951.0753247882]

Row 54:
['42', 862835.272796487]

Row 55:
['43', 773994.5810113424]

Row 56:
['44', 762612.2443527612]

Row 57:
['45', 674839.8431609498]

Row 58:
['46', 693512.0272348332]

Row 59:
['47', 660506.6147818052]

Row 60:
['48', 611119.517081962]

Row 61:
['49', 653532.7432173077]

Row 62:
['50', 541704.233774958]

Row 63:
['51', 609837.051723792]

Row 64:
['52', 570241.6141584215]

Row 65:
['53', 564956.1357245826]

Row 66:
['54', 482399.8481527956]

Row 67:
['55', 487908.8266968451]

Row 68:
['56', 519401.6315074663]

Row 69:
['57', 495841.2589424853]

Row 70:
['58', 499476.1631176444]

Row 71:
['59', 493824.37993875594]

Row 72:
['60', 418434.23081899824]

Row 73:
['61', 464394.8079334493]

Row 74:
['62', 413990.47587110917]

Row 75:
['63', 424262.00762092625]

Row 76:
['64', 374585.5405778911]

Row 77:
['65', 357817.36389965215]

Row 78:
['66', 329316.6613640407]

Row 79:
['67', 312775.51926583966]

Row 80:
['68', 293990.2016532795]

Row 81:
['69', 305771.3895760297]

Row 82:
['70', 216840.96990516665]

Row 83:
['71', 247353.56951391714]

Row 84:
['72', 211995.56745580756]

Row 85:
['73', 193955.47164128817]

Row 86:
['74', 175860.65532042892]

Row 87:
['75', 154518.72986150888]

Row 88:
['76', 144378.89855819967]

Row 89:
['77', 122130.80579016994]

Row 90:
['78', 111837.23724463]

Row 91:
['79', 119167.6743545197]

Row 92:
['80', 87280.4727571206]

Row 93:
['81', 107020.9498748994]

Row 94:
['82', 79940.9218090606]

Row 95:
['83', 66487.21640759068]

Row 96:
['84', 54084.80989495051]

Row 97:
['85', 51266.5676116504]

Row 98:
['86', 41882.51298336028]

Row 99:
['87', 35638.12131190021]

Row 100:
['88', 30139.537930640163]

Row 101:
['89', 28378.165589180142]

Row 102:
['90', 18967.979100440025]

Row 103:
['91', 26005.46738770011]

Row 104:
['92', 17560.433412509978]

Row 105:
['93', 12043.999692810012]

Row 106:
['94', 8928.51205565]

Row 107:
['95', 6863.610443849997]

Row 108:
['96', 5598.085806150004]

Row 109:
['97', 4475.855592379997]

Row 110:
['98', 3023.2039067699993]

Row 111:
['99', 9334.46605617]

Row 112:
['100', 2012.87095444]

Row 113:
['101', 3053.7929948099973]

Row 114:
['102', 1529.09938422]

Row 115:
['103', 1409.8219754299992]

Row 116:
['104', 587.4269523500001]

Row 117:
['105', 416.3989903700002]

Row 118:
['106', 297.09246033]

Row 119:
['107', 507.01250353000006]

Row 120:
['108', 224.98885828000004]

Row 121:
['109', 230.58103138]

Row 122:
['110', 123.22187198999998]

Row 123:
['111', 212.68526568000007]

Row 124:
['112', 112.66083465]

Row 125:
['113', 89.4185187]

Row 126:
['114', 72.1248282]

Row 127:
['115', 66.80582670000001]

Row 128:
['116', 50.17795712]

Row 129:
['117', 48.7927508]

Row 130:
['118', 35.066935799999996]

Row 131:
['119', 47.676912099999996]

Row 132:
['120', 26.040634499999996]

Row 133:
['121', 89.60858410000002]

Row 134:
['122', 23.4395779]

Row 135:
['123', 20.78951268]

Row 136:
['124', 18.0021146]

Row 137:
['125', 22.329130799999998]

Row 138:
['126', 19.05679446]

Row 139:
['127', 20.3487991]

Row 140:
['128', 2.8551609]

Row 141:
['129', 45.698344920000004]

Row 142:
['130', 10.7050445]

Row 143:
['Unspecified', 2999]

Row 144:
['Black African', 50486855.96347812]

Row 145:
['Coloured', 5052348.525046748]

Row 146:
['Indian or Asian', 1697505.861473724]

Row 147:
['White', 4504251.530739763]

Row 148:
['Other', 247352.73866097874]

Row 149:
['Unspecified', 39188]

Row 150:
['Afrikaans', 6365488.405515495]

Row 151:
['English', 5228300.544795035]

Row 152:
['Isindebele', 1044376.7929603198]

Row 153:
['IsiXhosa', 9786927.720113318]

Row 154:
['IsiZulu', 14613202.455735149]

Row 155:
['Sepedi', 5972255.272087867]

Row 156:
['Sesotho', 4678964.246650568]

Row 157:
['Setswana', 4972786.701879141]

Row 158:
['Sign language', 9307.758971719988]

Row 159:
['Siswati', 1692719.4003870934]

Row 160:
['Tshivenda', 1480564.9534887602]

Row 161:
['Xitsonga', 2784279.19356695]

Row 162:
['Khoi,Nama and San languages', 5916.920972349997]

Row 163:
['Shona', 716966.5524298036]

Row 164:
['Chichewa/Chewa/Nyanja/Chinyanja', 161162.11719687685]

Row 165:
['Portuguese', 95160.86665483234]

Row 166:
['Other', 268067.743669248]

Row 167:
['Not applicable', 1892088.047756694]

Row 168:
['Unspecified', 258966.92456068797]

Row 173:
['© Statistics South Africa']

In [29]:
# ============================================
# INSPECT TABLE4 AND TABLE5
# ============================================

for table_number in [4, 5]:

    file = TABLES_DIR / f"TABLE{table_number}.xlsx"

    df = pd.read_excel(
        file,
        header=None
    )

    print(f"\n{'=' * 60}")
    print(f"TABLE{table_number}")
    print(f"{'=' * 60}")

    print("Shape:", df.shape)

    for row in range(min(12, len(df))):

        values = df.iloc[row].dropna().tolist()

        if values:
            print(f"\nRow {row}:")
            print(values[:15])

============================================================
TABLE4
============================================================
Shape: (15, 98)

Row 1:
['Descriptive 2022 (MN Phase 2)']

Row 2:
['Province, district and municipality then Attendance at an ECD institution then Attendance \xa0and educational institution then Highest level of education']

Row 3:
['Counting: Population']

Row 5:
['Filters:']

Row 6:
['Default Summation', 'Population']

Row 8:
['Province, district and municipality then Attendance at an ECD institution then Attendance \xa0and educational institution then Highest level of education', 'Umdoni Local Municipality', 'Umzumbe Local Municipality', 'UMuziwabantu Local Municipality', 'Ray Nkonyeni Local Municipality', 'Okhahlamba Local Municipality', 'Inkosi Langalibalele Local Municipality', 'Alfred Duma Local Municipality', 'Endumeni Local Municipality', 'Nqutu Local Municipality', 'Msinga Local Municipality', 'Umvoti Local Municipality', 'Zululand', 'eDumbe Local Municipality', 'UPhongolo Local Municipality']

Row 9:
[156442.8802611416, 139044.8059699663, 115779.52551139316, 362134.44260897517, 143132.47712344155, 230923.81823407355, 415035.5225078197, 100085.33395678402, 201132.54922641235, 206001.27131180197, 142041.82553754273, 942794.2047341896, 96735.251963954, 151540.592491773, 247262.85741333273]

============================================================
TABLE5
============================================================
Shape: (15, 21)

Row 1:
['Descriptive 2022 (MN Phase 2)']

Row 2:
['Province, district and municipality then Questionnaire type then Geography type then Enumeration area type then Sex']

Row 3:
['Counting: Population']

Row 5:
['Filters:']

Row 6:
['Default Summation', 'Population']

Row 8:
['Province, district and municipality then Questionnaire type then Geography type then Enumeration area type then Sex', 'KwaZulu-Natal', 'Household', 'Homeless', 'Transient', 'Institution', 'Urban area', 'Tribal or Traditional area', 'Farm area', 'Formal residential', 'Informal residential', 'Traditional residential', 'Farms', 'Parks and recreation', 'Collective living quarters']

Row 9:
[12423906.662782008, 61367658.61929744, 55719, 2623, 601502, 39366168.36781715, 20254463.90403709, 2406870.3475069227, 34773150.61465113, 4853052.764870647, 19811611.317867056, 1643269.8580915704, 24476.102739520204, 288493.9117350782, 81909.62118270922]

In [30]:
# ============================================
# INSPECT TABLE4 STRUCTURE
# ============================================

table4_file = TABLES_DIR / "TABLE4.xlsx"

table4 = pd.read_excel(
    table4_file,
    header=None
)

print("TABLE4 shape:", table4.shape)

# Show every non-empty value in the first 10 rows,
# together with its column number.
for row in range(10):

    print(f"\n--- ROW {row} ---")

    for col in range(table4.shape[1]):

        value = table4.iloc[row, col]

        if pd.notna(value):
            print(f"Column {col}: {value}")

TABLE4 shape: (15, 98)

--- ROW 0 ---

--- ROW 1 ---
Column 0: Descriptive 2022 (MN Phase 2)

--- ROW 2 ---
Column 0: Province, district and municipality then Attendance at an ECD institution then Attendance  and educational institution then Highest level of education

--- ROW 3 ---
Column 0: Counting: Population

--- ROW 4 ---

--- ROW 5 ---
Column 0: Filters:

--- ROW 6 ---
Column 0: Default Summation
Column 1: Population

--- ROW 7 ---

--- ROW 8 ---
Column 0: Province, district and municipality then Attendance at an ECD institution then Attendance  and educational institution then Highest level of education
Column 1: Umdoni Local Municipality
Column 2: Umzumbe Local Municipality
Column 3: UMuziwabantu Local Municipality
Column 4: Ray Nkonyeni Local Municipality
Column 5: Okhahlamba Local Municipality
Column 6: Inkosi Langalibalele Local Municipality
Column 7: Alfred Duma Local Municipality
Column 8: Endumeni Local Municipality
Column 9: Nqutu Local Municipality
Column 10: Msinga Local Municipality
Column 11: Umvoti Local Municipality
Column 12: Zululand
Column 13: eDumbe Local Municipality
Column 14: UPhongolo Local Municipality
Column 15: Abaqulusi Local Municipality
Column 16: Nongoma Local Municipality
Column 17: Ulundi Local Municipality
Column 18: Umkhanyakude
Column 19: Umhlabuyalingana Local Municipality
Column 20: Jozini Local Municipality
Column 21: Mtubatuba Local Municipality
Column 22: Big Five Hlabisa Local Municipality
Column 23: King Cetshwayo
Column 24: Mfolozi Local Municipality
Column 25: uMhlathuze Local Municipality
Column 26: uMlalazi Local Municipality
Column 27: Mthonjaneni Local Municipality
Column 28: Nkandla Local Municipality
Column 29: iLembe
Column 30: Mandeni Local Municipality
Column 31: KwaDukuza Local Municipality
Column 32: Ndwedwe Local Municipality
Column 33: Maphumulo Local Municipality
Column 34: Harry Gwala
Column 35: Greater Kokstad Local Municipality
Column 36: Ubuhlebezwe Local Municipality
Column 37: Umzimkhulu Local Municipality
Column 38: Dr Nkosazana Dlamini Zuma Local Municipality
Column 39: eThekwini
Column 40: Ethekwini Metropolitan Municipality
Column 41: KwaZulu-Natal
Column 42: Creche/educare centre
Column 43: Pre-school/nursery school/Grade 00/Grade 000/Grade R
Column 44: Day mother/Gogo/Child minder
Column 45: Home/community play group
Column 46: Other (Specify)
Column 47: Do not know
Column 49: Not applicable
Column 50: Unspecified
Column 51: No
Column 52: Yes, Pre-school
Column 53: Yes, Primary school (Grade R to Grade 7)
Column 54: Yes, Secondary school (Grade 8 to Grade 12)
Column 55: Yes, Special school for learners with disabilities
Column 56: Yes, Technical Vocational Education and Training (TVET), formerly known as Further Education and Training
 College (FET), including Private Colleges
Column 57: Yes, Other college (including Private and Public Nursing College, Agricultural College and Police College)
Column 58: Yes, Higher educational institution (including University/University of Technology and Private Higher Education Institution)
Column 59: Yes, Community Education and Training College (including Adult Education and Training Learning Centre)
Column 60: Yes, Home-based education/home schooling
Column 61: Yes, Other
Column 62: Do not know
Column 63: Not applicable
Column 64: Unspecified
Column 65: Grade R/0
Column 66: Grade 1/ Sub A/ Class 1
Column 67: Grade 2/ Sub B/ Class 2
Column 68: Grade 3/ Standard 1/ ABET/ AET 1
Column 69: Grade 4/ Standard 2
Column 70: Grade 5/ Standard 3/ ABET/ AET
Column 71: Grade 6/ Standard 4
Column 72: Grade 7/ Standard 5/ ABET/ AET
Column 73: Grade 8/ Standard 6/ Form 1
Column 74: Grade 9/ Standard 7/ Form 2/ ABET/ AET 4/ Occupational Certificate NQF Level 2
Column 75: Grade 10/ Standard 8/ Form 3/ NCV Level 2/ Occupational Certificate NQF Level 2
Column 76: Grade 11/ Standard 9/ Form 4/ NCV Level 3/ Occupational Certificate NQF Level 3
Column 77: Grade 12/ Standard 10/ Form 5/ Matric/ NCV Level 4/ Occupational Certificate NQF Level 4
Column 78: NTC I/N1
Column 79: NTC II/N2
Column 80: NTC III/N3
Column 81: N4/NTC 4/ Occupational Certificate NQF Level 5
Column 82: N5/NTC 5/ Occupational Certificate NQF Level 5
Column 83: N6/NTC 6/ Occupational Certificate NQF Level 5
Column 84: Certificate with less than Grade 12/ Standard 10
Column 85: Diploma with less than Grade 12/ Standard 10
Column 86: Higher/ National/ Advanced Certificate with Grade 12/ Std10/ Occupational Certificate NQF Level 5
Column 87: Diploma with Grade 12/ Standard 10/ Occupational Certificate NQF Level 6
Column 88: Higher Diploma/ Occupational Certificate NQF Level 7
Column 89: Bachelors Degree/ Occupational Certificate NQF Level 8
Column 90: Honours Degree/ Postgraduate Diploma/ Occupational Certificate NQF Level 8
Column 91: Masters/ Professional Masters at NQF Level 9
Column 92: PHD (Doctoral Degrees)/ Professional Doctoral Degree at NQF Level 10
Column 93: Other
Column 94: Do not know
Column 95: Not applicable
Column 96: No schooling
Column 97: Unspecified

--- ROW 9 ---
Column 1: 156442.8802611416
Column 2: 139044.8059699663
Column 3: 115779.52551139316
Column 4: 362134.44260897517
Column 5: 143132.47712344155
Column 6: 230923.81823407355
Column 7: 415035.5225078197
Column 8: 100085.33395678402
Column 9: 201132.54922641235
Column 10: 206001.27131180197
Column 11: 142041.82553754273
Column 12: 942794.2047341896
Column 13: 96735.251963954
Column 14: 151540.592491773
Column 15: 247262.85741333273
Column 16: 225278.4029577534
Column 17: 221977.09990736123
Column 18: 738436.551107445
Column 19: 191659.71423636732
Column 20: 199152.94824647388
Column 21: 215869.21386156185
Column 22: 131754.67476304286
Column 23: 1021343.5473776794
Column 24: 159667.95534802426
Column 25: 412074.9678163402
Column 26: 241416.08102747172
Column 27: 99288.7499040245
Column 28: 108895.79328179012
Column 29: 782660.810158101
Column 30: 180939.49087498474
Column 31: 324911.653516167
Column 32: 165826.30055840104
Column 33: 110983.36520852026
Column 34: 563893.0973213947
Column 35: 81676.11889501508
Column 36: 133031.88088912296
Column 37: 220619.69942617483
Column 38: 128565.39811102043
Column 39: 4239900.595478572
Column 40: 4239900.595478572
Column 41: 12423906.662782008
Column 42: 2047864.4943416105
Column 43: 417598.1223519458
Column 44: 570022.6916401176
Column 45: 346721.6216337145
Column 46: 39953.83303064005
Column 47: 54207.35983689004
Column 48: 2264998.000137179
Column 49: 56245950.99660912
Column 50: 40185.499751799696
Column 51: 36105954.3787708
Column 52: 213804.47193543546
Column 53: 8275408.912405036
Column 54: 6577003.3189805895
Column 55: 78218.62373906997
Column 56: 524930.9981877604
Column 57: 155423.83318955186
Column 58: 959945.6452616609
Column 59: 146966.06623116805
Column 60: 27841.329449860295
Column 61: 170378.8266385867
Column 62: 581212.8456914825
Column 63: 6441395.622723652
Column 64: 1769017.746192899
Column 65: 1255717.2711753459
Column 66: 1164686.5326040406
Column 67: 1284673.242954418
Column 68: 1352426.2795213787
Column 69: 1610810.2817129563
Column 70: 1720037.5700636094
Column 71: 2060723.6051406949
Column 72: 2554905.589476374
Column 73: 2899813.904840797
Column 74: 3293602.3287361097
Column 75: 4508519.314178428
Column 76: 5273843.378138219
Column 77: 15002090.486166645
Column 78: 38664.65904212996
Column 79: 54819.007461780006
Column 80: 121226.40379590982
Column 81: 172617.7116979183
Column 82: 105628.00869006958
Column 83: 252826.76715413836
Column 84: 64639.12109573973
Column 85: 163972.76758362897
Column 86: 274919.73519657797
Column 87: 1119064.9894273698
Column 88: 481794.43236057204
Column 89: 1340664.8887192968
Column 90: 531513.8727178206
Column 91: 246925.2748521237
Column 92: 85874.40260512909
Column 93: 340784.664467149
Column 94: 1905217.3438491037
Column 95: 6756513.512218568
Column 96: 3313760.0778293996
Column 97: 674225.1939188096

In [31]:
# ============================================
# TABLE4 — SHOW MUNICIPALITY/CATEGORY HEADERS
# ============================================

table4 = pd.read_excel(
    TABLES_DIR / "TABLE4.xlsx",
    header=None
)

for row in [8, 9, 10]:

    print(f"\n{'=' * 60}")
    print(f"ROW {row}")
    print(f"{'=' * 60}")

    for col in range(table4.shape[1]):

        value = table4.iloc[row, col]

        if pd.notna(value):
            print(f"{col}: {value}")

============================================================
ROW 8
============================================================
0: Province, district and municipality then Attendance at an ECD institution then Attendance  and educational institution then Highest level of education
1: Umdoni Local Municipality
2: Umzumbe Local Municipality
3: UMuziwabantu Local Municipality
4: Ray Nkonyeni Local Municipality
5: Okhahlamba Local Municipality
6: Inkosi Langalibalele Local Municipality
7: Alfred Duma Local Municipality
8: Endumeni Local Municipality
9: Nqutu Local Municipality
10: Msinga Local Municipality
11: Umvoti Local Municipality
12: Zululand
13: eDumbe Local Municipality
14: UPhongolo Local Municipality
15: Abaqulusi Local Municipality
16: Nongoma Local Municipality
17: Ulundi Local Municipality
18: Umkhanyakude
19: Umhlabuyalingana Local Municipality
20: Jozini Local Municipality
21: Mtubatuba Local Municipality
22: Big Five Hlabisa Local Municipality
23: King Cetshwayo
24: Mfolozi Local Municipality
25: uMhlathuze Local Municipality
26: uMlalazi Local Municipality
27: Mthonjaneni Local Municipality
28: Nkandla Local Municipality
29: iLembe
30: Mandeni Local Municipality
31: KwaDukuza Local Municipality
32: Ndwedwe Local Municipality
33: Maphumulo Local Municipality
34: Harry Gwala
35: Greater Kokstad Local Municipality
36: Ubuhlebezwe Local Municipality
37: Umzimkhulu Local Municipality
38: Dr Nkosazana Dlamini Zuma Local Municipality
39: eThekwini
40: Ethekwini Metropolitan Municipality
41: KwaZulu-Natal
42: Creche/educare centre
43: Pre-school/nursery school/Grade 00/Grade 000/Grade R
44: Day mother/Gogo/Child minder
45: Home/community play group
46: Other (Specify)
47: Do not know
49: Not applicable
50: Unspecified
51: No
52: Yes, Pre-school
53: Yes, Primary school (Grade R to Grade 7)
54: Yes, Secondary school (Grade 8 to Grade 12)
55: Yes, Special school for learners with disabilities
56: Yes, Technical Vocational Education and Training (TVET), formerly known as Further Education and Training
 College (FET), including Private Colleges
57: Yes, Other college (including Private and Public Nursing College, Agricultural College and Police College)
58: Yes, Higher educational institution (including University/University of Technology and Private Higher Education Institution)
59: Yes, Community Education and Training College (including Adult Education and Training Learning Centre)
60: Yes, Home-based education/home schooling
61: Yes, Other
62: Do not know
63: Not applicable
64: Unspecified
65: Grade R/0
66: Grade 1/ Sub A/ Class 1
67: Grade 2/ Sub B/ Class 2
68: Grade 3/ Standard 1/ ABET/ AET 1
69: Grade 4/ Standard 2
70: Grade 5/ Standard 3/ ABET/ AET
71: Grade 6/ Standard 4
72: Grade 7/ Standard 5/ ABET/ AET
73: Grade 8/ Standard 6/ Form 1
74: Grade 9/ Standard 7/ Form 2/ ABET/ AET 4/ Occupational Certificate NQF Level 2
75: Grade 10/ Standard 8/ Form 3/ NCV Level 2/ Occupational Certificate NQF Level 2
76: Grade 11/ Standard 9/ Form 4/ NCV Level 3/ Occupational Certificate NQF Level 3
77: Grade 12/ Standard 10/ Form 5/ Matric/ NCV Level 4/ Occupational Certificate NQF Level 4
78: NTC I/N1
79: NTC II/N2
80: NTC III/N3
81: N4/NTC 4/ Occupational Certificate NQF Level 5
82: N5/NTC 5/ Occupational Certificate NQF Level 5
83: N6/NTC 6/ Occupational Certificate NQF Level 5
84: Certificate with less than Grade 12/ Standard 10
85: Diploma with less than Grade 12/ Standard 10
86: Higher/ National/ Advanced Certificate with Grade 12/ Std10/ Occupational Certificate NQF Level 5
87: Diploma with Grade 12/ Standard 10/ Occupational Certificate NQF Level 6
88: Higher Diploma/ Occupational Certificate NQF Level 7
89: Bachelors Degree/ Occupational Certificate NQF Level 8
90: Honours Degree/ Postgraduate Diploma/ Occupational Certificate NQF Level 8
91: Masters/ Professional Masters at NQF Level 9
92: PHD (Doctoral Degrees)/ Professional Doctoral Degree at NQF Level 10
93: Other
94: Do not know
95: Not applicable
96: No schooling
97: Unspecified

============================================================
ROW 9
============================================================
1: 156442.8802611416
2: 139044.8059699663
3: 115779.52551139316
4: 362134.44260897517
5: 143132.47712344155
6: 230923.81823407355
7: 415035.5225078197
8: 100085.33395678402
9: 201132.54922641235
10: 206001.27131180197
11: 142041.82553754273
12: 942794.2047341896
13: 96735.251963954
14: 151540.592491773
15: 247262.85741333273
16: 225278.4029577534
17: 221977.09990736123
18: 738436.551107445
19: 191659.71423636732
20: 199152.94824647388
21: 215869.21386156185
22: 131754.67476304286
23: 1021343.5473776794
24: 159667.95534802426
25: 412074.9678163402
26: 241416.08102747172
27: 99288.7499040245
28: 108895.79328179012
29: 782660.810158101
30: 180939.49087498474
31: 324911.653516167
32: 165826.30055840104
33: 110983.36520852026
34: 563893.0973213947
35: 81676.11889501508
36: 133031.88088912296
37: 220619.69942617483
38: 128565.39811102043
39: 4239900.595478572
40: 4239900.595478572
41: 12423906.662782008
42: 2047864.4943416105
43: 417598.1223519458
44: 570022.6916401176
45: 346721.6216337145
46: 39953.83303064005
47: 54207.35983689004
48: 2264998.000137179
49: 56245950.99660912
50: 40185.499751799696
51: 36105954.3787708
52: 213804.47193543546
53: 8275408.912405036
54: 6577003.3189805895
55: 78218.62373906997
56: 524930.9981877604
57: 155423.83318955186
58: 959945.6452616609
59: 146966.06623116805
60: 27841.329449860295
61: 170378.8266385867
62: 581212.8456914825
63: 6441395.622723652
64: 1769017.746192899
65: 1255717.2711753459
66: 1164686.5326040406
67: 1284673.242954418
68: 1352426.2795213787
69: 1610810.2817129563
70: 1720037.5700636094
71: 2060723.6051406949
72: 2554905.589476374
73: 2899813.904840797
74: 3293602.3287361097
75: 4508519.314178428
76: 5273843.378138219
77: 15002090.486166645
78: 38664.65904212996
79: 54819.007461780006
80: 121226.40379590982
81: 172617.7116979183
82: 105628.00869006958
83: 252826.76715413836
84: 64639.12109573973
85: 163972.76758362897
86: 274919.73519657797
87: 1119064.9894273698
88: 481794.43236057204
89: 1340664.8887192968
90: 531513.8727178206
91: 246925.2748521237
92: 85874.40260512909
93: 340784.664467149
94: 1905217.3438491037
95: 6756513.512218568
96: 3313760.0778293996
97: 674225.1939188096

============================================================
ROW 10
============================================================

In [32]:
# ============================================
# TABLE4 — INSPECT CATEGORIES AND VALUES
# ============================================

print("ROW 9")
print("=" * 60)

for col in range(table4.shape[1]):
    value = table4.iloc[9, col]

    if pd.notna(value):
        print(f"{col}: {value}")


print("\nROW 10")
print("=" * 60)

for col in range(table4.shape[1]):
    value = table4.iloc[10, col]

    if pd.notna(value):
        print(f"{col}: {value}")

ROW 9
============================================================
1: 156442.8802611416
2: 139044.8059699663
3: 115779.52551139316
4: 362134.44260897517
5: 143132.47712344155
6: 230923.81823407355
7: 415035.5225078197
8: 100085.33395678402
9: 201132.54922641235
10: 206001.27131180197
11: 142041.82553754273
12: 942794.2047341896
13: 96735.251963954
14: 151540.592491773
15: 247262.85741333273
16: 225278.4029577534
17: 221977.09990736123
18: 738436.551107445
19: 191659.71423636732
20: 199152.94824647388
21: 215869.21386156185
22: 131754.67476304286
23: 1021343.5473776794
24: 159667.95534802426
25: 412074.9678163402
26: 241416.08102747172
27: 99288.7499040245
28: 108895.79328179012
29: 782660.810158101
30: 180939.49087498474
31: 324911.653516167
32: 165826.30055840104
33: 110983.36520852026
34: 563893.0973213947
35: 81676.11889501508
36: 133031.88088912296
37: 220619.69942617483
38: 128565.39811102043
39: 4239900.595478572
40: 4239900.595478572
41: 12423906.662782008
42: 2047864.4943416105
43: 417598.1223519458
44: 570022.6916401176
45: 346721.6216337145
46: 39953.83303064005
47: 54207.35983689004
48: 2264998.000137179
49: 56245950.99660912
50: 40185.499751799696
51: 36105954.3787708
52: 213804.47193543546
53: 8275408.912405036
54: 6577003.3189805895
55: 78218.62373906997
56: 524930.9981877604
57: 155423.83318955186
58: 959945.6452616609
59: 146966.06623116805
60: 27841.329449860295
61: 170378.8266385867
62: 581212.8456914825
63: 6441395.622723652
64: 1769017.746192899
65: 1255717.2711753459
66: 1164686.5326040406
67: 1284673.242954418
68: 1352426.2795213787
69: 1610810.2817129563
70: 1720037.5700636094
71: 2060723.6051406949
72: 2554905.589476374
73: 2899813.904840797
74: 3293602.3287361097
75: 4508519.314178428
76: 5273843.378138219
77: 15002090.486166645
78: 38664.65904212996
79: 54819.007461780006
80: 121226.40379590982
81: 172617.7116979183
82: 105628.00869006958
83: 252826.76715413836
84: 64639.12109573973
85: 163972.76758362897
86: 274919.73519657797
87: 1119064.9894273698
88: 481794.43236057204
89: 1340664.8887192968
90: 531513.8727178206
91: 246925.2748521237
92: 85874.40260512909
93: 340784.664467149
94: 1905217.3438491037
95: 6756513.512218568
96: 3313760.0778293996
97: 674225.1939188096

ROW 10
============================================================

In [33]:
# ============================================
# TABLE4 — INSPECT ROW LABELS
# ============================================

print("TABLE4 ROW LABELS")
print("=" * 60)

for row in range(8, table4.shape[0]):

    value = table4.iloc[row, 0]

    if pd.notna(value):
        print(f"Row {row}: {value}")

TABLE4 ROW LABELS
============================================================
Row 8: Province, district and municipality then Attendance at an ECD institution then Attendance  and educational institution then Highest level of education
Row 14: © Statistics South Africa

In [34]:
# ============================================
# TABLE4 — INSPECT FIRST 8 COLUMNS
# ============================================

print("TABLE4 FIRST 8 COLUMNS")
print("=" * 70)

for row in range(table4.shape[0]):

    values = []

    for col in range(min(8, table4.shape[1])):
        value = table4.iloc[row, col]

        if pd.notna(value):
            values.append(f"C{col}={value}")

    if values:
        print(f"Row {row}:")
        print(" | ".join(values))

TABLE4 FIRST 8 COLUMNS
======================================================================
Row 1:
C0=Descriptive 2022 (MN Phase 2)
Row 2:
C0=Province, district and municipality then Attendance at an ECD institution then Attendance  and educational institution then Highest level of education
Row 3:
C0=Counting: Population
Row 5:
C0=Filters:
Row 6:
C0=Default Summation | C1=Population
Row 8:
C0=Province, district and municipality then Attendance at an ECD institution then Attendance  and educational institution then Highest level of education | C1=Umdoni Local Municipality | C2=Umzumbe Local Municipality | C3=UMuziwabantu Local Municipality | C4=Ray Nkonyeni Local Municipality | C5=Okhahlamba Local Municipality | C6=Inkosi Langalibalele Local Municipality | C7=Alfred Duma Local Municipality
Row 9:
C1=156442.8802611416 | C2=139044.8059699663 | C3=115779.52551139316 | C4=362134.44260897517 | C5=143132.47712344155 | C6=230923.81823407355 | C7=415035.5225078197
Row 14:
C0=© Statistics South Africa

In [35]:
# ============================================
# INSPECT TABLE3 STRUCTURE
# ============================================

table3 = pd.read_excel(
    TABLES_DIR / "TABLE3.xlsx",
    header=None
)

print("TABLE3 shape:", table3.shape)

for row in range(min(15, table3.shape[0])):

    print(f"\nROW {row}")
    print("-" * 60)

    for col in range(min(10, table3.shape[1])):

        value = table3.iloc[row, col]

        if pd.notna(value):
            print(f"C{col}: {value}")

TABLE3 shape: (174, 2)

ROW 0
------------------------------------------------------------

ROW 1
------------------------------------------------------------
C0: Descriptive 2022 (MN Phase 2)

ROW 2
------------------------------------------------------------
C0: Province, district and municipality then Sex then Age in completed years then Population group then Language most often spoken

ROW 3
------------------------------------------------------------
C0: Counting: Population

ROW 4
------------------------------------------------------------

ROW 5
------------------------------------------------------------
C0: Filters:

ROW 6
------------------------------------------------------------
C0: Default Summation
C1: Population

ROW 7
------------------------------------------------------------

ROW 8
------------------------------------------------------------
C0: Province, district and municipality then Sex then Age in completed years then Population group then Language most often spoken

ROW 9
------------------------------------------------------------
C0: KwaZulu-Natal
C1: 12423906.662782008

ROW 10
------------------------------------------------------------
C0: Male
C1: 30078756.68715917

ROW 11
------------------------------------------------------------
C0: Female
C1: 31948745.932222202

ROW 12
------------------------------------------------------------
C0: 0
C1: 1250353.0477566998

ROW 13
------------------------------------------------------------
C0: 1
C1: 1168240.7098342404

ROW 14
------------------------------------------------------------
C0: 2
C1: 1188298.519725562

In [36]:
# ============================================
# TABLE3 — SHOW ALL ROWS
# ============================================

print("TABLE3")
print("=" * 80)

for row in range(table3.shape[0]):

    col0 = table3.iloc[row, 0]
    col1 = table3.iloc[row, 1]

    print(f"Row {row}: C0={col0} | C1={col1}")

TABLE3
================================================================================
Row 0: C0=nan | C1=nan
Row 1: C0=Descriptive 2022 (MN Phase 2) | C1=nan
Row 2: C0=Province, district and municipality then Sex then Age in completed years then Population group then Language most often spoken | C1=nan
Row 3: C0=Counting: Population | C1=nan
Row 4: C0=nan | C1=nan
Row 5: C0=Filters: | C1=nan
Row 6: C0=Default Summation | C1=Population
Row 7: C0=nan | C1=nan
Row 8: C0=Province, district and municipality then Sex then Age in completed years then Population group then Language most often spoken | C1=nan
Row 9: C0=KwaZulu-Natal | C1=12423906.662782008
Row 10: C0=Male | C1=30078756.68715917
Row 11: C0=Female | C1=31948745.932222202
Row 12: C0=0 | C1=1250353.0477566998
Row 13: C0=1 | C1=1168240.7098342404
Row 14: C0=2 | C1=1188298.519725562
Row 15: C0=3 | C1=1130328.801133854
Row 16: C0=4 | C1=1096293.544273597
Row 17: C0=5 | C1=954477.8158382007
Row 18: C0=6 | C1=1011729.9181077147
Row 19: C0=7 | C1=1048430.4954019606
Row 20: C0=8 | C1=1038061.8678377874
Row 21: C0=9 | C1=1056403.960507052
Row 22: C0=10 | C1=1055068.457665082
Row 23: C0=11 | C1=1094814.8671509093
Row 24: C0=12 | C1=1076374.1380515625
Row 25: C0=13 | C1=1105321.124375608
Row 26: C0=14 | C1=1072545.808294187
Row 27: C0=15 | C1=1081806.7521004202
Row 28: C0=16 | C1=1071637.4746376863
Row 29: C0=17 | C1=1012704.5819278515
Row 30: C0=18 | C1=924581.9361747585
Row 31: C0=19 | C1=884578.6450539028
Row 32: C0=20 | C1=1011053.8720050836
Row 33: C0=21 | C1=1108187.811439477
Row 34: C0=22 | C1=1071721.7514606449
Row 35: C0=23 | C1=1046759.992262469
Row 36: C0=24 | C1=1072014.9485557876
Row 37: C0=25 | C1=1148424.247052114
Row 38: C0=26 | C1=1136839.9239893607
Row 39: C0=27 | C1=1166568.4135864838
Row 40: C0=28 | C1=1119027.2803796697
Row 41: C0=29 | C1=1162379.4367141034
Row 42: C0=30 | C1=1116319.6495038825
Row 43: C0=31 | C1=1188644.0243981257
Row 44: C0=32 | C1=1136049.2140213395
Row 45: C0=33 | C1=1092202.5693637016
Row 46: C0=34 | C1=1059607.7635442668
Row 47: C0=35 | C1=1087150.6542802271
Row 48: C0=36 | C1=1116115.798005921
Row 49: C0=37 | C1=1013254.1268394778
Row 50: C0=38 | C1=985651.0993329806
Row 51: C0=39 | C1=1020430.9534832736
Row 52: C0=40 | C1=869827.3012684205
Row 53: C0=41 | C1=915951.0753247882
Row 54: C0=42 | C1=862835.272796487
Row 55: C0=43 | C1=773994.5810113424
Row 56: C0=44 | C1=762612.2443527612
Row 57: C0=45 | C1=674839.8431609498
Row 58: C0=46 | C1=693512.0272348332
Row 59: C0=47 | C1=660506.6147818052
Row 60: C0=48 | C1=611119.517081962
Row 61: C0=49 | C1=653532.7432173077
Row 62: C0=50 | C1=541704.233774958
Row 63: C0=51 | C1=609837.051723792
Row 64: C0=52 | C1=570241.6141584215
Row 65: C0=53 | C1=564956.1357245826
Row 66: C0=54 | C1=482399.8481527956
Row 67: C0=55 | C1=487908.8266968451
Row 68: C0=56 | C1=519401.6315074663
Row 69: C0=57 | C1=495841.2589424853
Row 70: C0=58 | C1=499476.1631176444
Row 71: C0=59 | C1=493824.37993875594
Row 72: C0=60 | C1=418434.23081899824
Row 73: C0=61 | C1=464394.8079334493
Row 74: C0=62 | C1=413990.47587110917
Row 75: C0=63 | C1=424262.00762092625
Row 76: C0=64 | C1=374585.5405778911
Row 77: C0=65 | C1=357817.36389965215
Row 78: C0=66 | C1=329316.6613640407
Row 79: C0=67 | C1=312775.51926583966
Row 80: C0=68 | C1=293990.2016532795
Row 81: C0=69 | C1=305771.3895760297
Row 82: C0=70 | C1=216840.96990516665
Row 83: C0=71 | C1=247353.56951391714
Row 84: C0=72 | C1=211995.56745580756
Row 85: C0=73 | C1=193955.47164128817
Row 86: C0=74 | C1=175860.65532042892
Row 87: C0=75 | C1=154518.72986150888
Row 88: C0=76 | C1=144378.89855819967
Row 89: C0=77 | C1=122130.80579016994
Row 90: C0=78 | C1=111837.23724463
Row 91: C0=79 | C1=119167.6743545197
Row 92: C0=80 | C1=87280.4727571206
Row 93: C0=81 | C1=107020.9498748994
Row 94: C0=82 | C1=79940.9218090606
Row 95: C0=83 | C1=66487.21640759068
Row 96: C0=84 | C1=54084.80989495051
Row 97: C0=85 | C1=51266.5676116504
Row 98: C0=86 | C1=41882.51298336028
Row 99: C0=87 | C1=35638.12131190021
Row 100: C0=88 | C1=30139.537930640163
Row 101: C0=89 | C1=28378.165589180142
Row 102: C0=90 | C1=18967.979100440025
Row 103: C0=91 | C1=26005.46738770011
Row 104: C0=92 | C1=17560.433412509978
Row 105: C0=93 | C1=12043.999692810012
Row 106: C0=94 | C1=8928.51205565
Row 107: C0=95 | C1=6863.610443849997
Row 108: C0=96 | C1=5598.085806150004
Row 109: C0=97 | C1=4475.855592379997
Row 110: C0=98 | C1=3023.2039067699993
Row 111: C0=99 | C1=9334.46605617
Row 112: C0=100 | C1=2012.87095444
Row 113: C0=101 | C1=3053.7929948099973
Row 114: C0=102 | C1=1529.09938422
Row 115: C0=103 | C1=1409.8219754299992
Row 116: C0=104 | C1=587.4269523500001
Row 117: C0=105 | C1=416.3989903700002
Row 118: C0=106 | C1=297.09246033
Row 119: C0=107 | C1=507.01250353000006
Row 120: C0=108 | C1=224.98885828000004
Row 121: C0=109 | C1=230.58103138
Row 122: C0=110 | C1=123.22187198999998
Row 123: C0=111 | C1=212.68526568000007
Row 124: C0=112 | C1=112.66083465
Row 125: C0=113 | C1=89.4185187
Row 126: C0=114 | C1=72.1248282
Row 127: C0=115 | C1=66.80582670000001
Row 128: C0=116 | C1=50.17795712
Row 129: C0=117 | C1=48.7927508
Row 130: C0=118 | C1=35.066935799999996
Row 131: C0=119 | C1=47.676912099999996
Row 132: C0=120 | C1=26.040634499999996
Row 133: C0=121 | C1=89.60858410000002
Row 134: C0=122 | C1=23.4395779
Row 135: C0=123 | C1=20.78951268
Row 136: C0=124 | C1=18.0021146
Row 137: C0=125 | C1=22.329130799999998
Row 138: C0=126 | C1=19.05679446
Row 139: C0=127 | C1=20.3487991
Row 140: C0=128 | C1=2.8551609
Row 141: C0=129 | C1=45.698344920000004
Row 142: C0=130 | C1=10.7050445
Row 143: C0=Unspecified | C1=2999
Row 144: C0=Black African | C1=50486855.96347812
Row 145: C0=Coloured | C1=5052348.525046748
Row 146: C0=Indian or Asian | C1=1697505.861473724
Row 147: C0=White | C1=4504251.530739763
Row 148: C0=Other | C1=247352.73866097874
Row 149: C0=Unspecified | C1=39188
Row 150: C0=Afrikaans | C1=6365488.405515495
Row 151: C0=English | C1=5228300.544795035
Row 152: C0=Isindebele | C1=1044376.7929603198
Row 153: C0=IsiXhosa | C1=9786927.720113318
Row 154: C0=IsiZulu | C1=14613202.455735149
Row 155: C0=Sepedi | C1=5972255.272087867
Row 156: C0=Sesotho | C1=4678964.246650568
Row 157: C0=Setswana | C1=4972786.701879141
Row 158: C0=Sign language | C1=9307.758971719988
Row 159: C0=Siswati | C1=1692719.4003870934
Row 160: C0=Tshivenda | C1=1480564.9534887602
Row 161: C0=Xitsonga | C1=2784279.19356695
Row 162: C0=Khoi,Nama and San languages | C1=5916.920972349997
Row 163: C0=Shona | C1=716966.5524298036
Row 164: C0=Chichewa/Chewa/Nyanja/Chinyanja | C1=161162.11719687685
Row 165: C0=Portuguese | C1=95160.86665483234
Row 166: C0=Other | C1=268067.743669248
Row 167: C0=Not applicable | C1=1892088.047756694
Row 168: C0=Unspecified | C1=258966.92456068797
Row 169: C0=nan | C1=nan
Row 170: C0=nan | C1=nan
Row 171: C0=nan | C1=nan
Row 172: C0=nan | C1=nan
Row 173: C0=© Statistics South Africa | C1=nan

In [37]:
# ============================================
# TABLE1 — INSPECT ROW STRUCTURE
# ============================================

table1 = pd.read_excel(
    TABLES_DIR / "TABLE1.xlsx",
    header=None
)

print("TABLE1 shape:", table1.shape)

print("\nROW LABELS / FIRST 5 COLUMNS")
print("=" * 80)

for row in range(min(16, table1.shape[0])):

    values = []

    for col in range(min(5, table1.shape[1])):

        value = table1.iloc[row, col]

        if pd.notna(value):
            values.append(f"C{col}={value}")

    if values:
        print(f"Row {row}: " + " | ".join(values))

TABLE1 shape: (16, 514)

ROW LABELS / FIRST 5 COLUMNS
================================================================================
Row 1: C0=Descriptive 2022 (MN Phase 2)
Row 2: C0=Province, district and municipality and Questionnaire type then Geography type then Sex
Row 3: C0=Counting: Population
Row 5: C0=Filters:
Row 6: C0=Default Summation | C1=Population
Row 8: C0=Province, district and municipality | C1=KwaZulu-Natal
Row 9: C0=Questionnaire type then Geography type then Sex | C1=Household | C2=Homeless | C3=Transient | C4=Institution
Row 10: C1=12279374.662785625 | C2=7768 | C3=93 | C4=136671
Row 15: C0=© Statistics South Africa

In [38]:
# ============================================
# TABLE1 — LIST ALL GEOGRAPHY HEADINGS
# ============================================

print("TABLE1 GEOGRAPHY HEADINGS")
print("=" * 80)

for col in range(table1.shape[1]):

    value = table1.iloc[8, col]

    if pd.notna(value):
        print(f"Column {col}: {value}")

TABLE1 GEOGRAPHY HEADINGS
================================================================================
Column 0: Province, district and municipality
Column 1: KwaZulu-Natal
Column 10: Ugu
Column 19: Umdoni Local Municipality
Column 28: Umzumbe Local Municipality
Column 37: UMuziwabantu Local Municipality
Column 46: Ray Nkonyeni Local Municipality
Column 55: Umgungundlovu
Column 64: uMshwathi Local Municipality
Column 73: uMngeni Local Municipality
Column 82: Mpofana Local Municipality
Column 91: Impendle Local Municipality
Column 100: The Msunduzi Local Municipality
Column 109: Mkhambathini Local Municipality
Column 118: Richmond Local Municipality
Column 127: Uthukela
Column 136: Okhahlamba Local Municipality
Column 145: Inkosi Langalibalele Local Municipality
Column 154: Alfred Duma Local Municipality
Column 163: Umzinyathi
Column 172: Endumeni Local Municipality
Column 181: Nqutu Local Municipality
Column 190: Msinga Local Municipality
Column 199: Umvoti Local Municipality
Column 208: Amajuba
Column 217: Newcastle Local Municipality
Column 226: Emadlangeni Local Municipality
Column 235: Dannhauser Local Municipality
Column 244: Zululand
Column 253: eDumbe Local Municipality
Column 262: UPhongolo Local Municipality
Column 271: Abaqulusi Local Municipality
Column 280: Nongoma Local Municipality
Column 289: Ulundi Local Municipality
Column 298: Umkhanyakude
Column 307: Umhlabuyalingana Local Municipality
Column 316: Jozini Local Municipality
Column 325: Mtubatuba Local Municipality
Column 334: Big Five Hlabisa Local Municipality
Column 343: King Cetshwayo
Column 352: Mfolozi Local Municipality
Column 361: uMhlathuze Local Municipality
Column 370: uMlalazi Local Municipality
Column 379: Mthonjaneni Local Municipality
Column 388: Nkandla Local Municipality
Column 397: iLembe
Column 406: Mandeni Local Municipality
Column 415: KwaDukuza Local Municipality
Column 424: Ndwedwe Local Municipality
Column 433: Maphumulo Local Municipality
Column 442: Harry Gwala
Column 451: Greater Kokstad Local Municipality
Column 460: Ubuhlebezwe Local Municipality
Column 469: Umzimkhulu Local Municipality
Column 478: Dr Nkosazana Dlamini Zuma Local Municipality
Column 487: eThekwini
Column 496: Ethekwini Metropolitan Municipality
Column 505: Total

In [39]:
# ============================================
# TABLE1 — COMPLETE GEOGRAPHY LIST
# ============================================

geography_headings = []

for col in range(table1.shape[1]):
    
    value = table1.iloc[8, col]
    
    if pd.notna(value):
        geography_headings.append((col, str(value)))

print("Total geography headings:", len(geography_headings))
print("=" * 80)

for number, (col, name) in enumerate(geography_headings, start=1):
    print(f"{number:02d}. Column {col}: {name}")

Total geography headings: 58
================================================================================
01. Column 0: Province, district and municipality
02. Column 1: KwaZulu-Natal
03. Column 10: Ugu
04. Column 19: Umdoni Local Municipality
05. Column 28: Umzumbe Local Municipality
06. Column 37: UMuziwabantu Local Municipality
07. Column 46: Ray Nkonyeni Local Municipality
08. Column 55: Umgungundlovu
09. Column 64: uMshwathi Local Municipality
10. Column 73: uMngeni Local Municipality
11. Column 82: Mpofana Local Municipality
12. Column 91: Impendle Local Municipality
13. Column 100: The Msunduzi Local Municipality
14. Column 109: Mkhambathini Local Municipality
15. Column 118: Richmond Local Municipality
16. Column 127: Uthukela
17. Column 136: Okhahlamba Local Municipality
18. Column 145: Inkosi Langalibalele Local Municipality
19. Column 154: Alfred Duma Local Municipality
20. Column 163: Umzinyathi
21. Column 172: Endumeni Local Municipality
22. Column 181: Nqutu Local Municipality
23. Column 190: Msinga Local Municipality
24. Column 199: Umvoti Local Municipality
25. Column 208: Amajuba
26. Column 217: Newcastle Local Municipality
27. Column 226: Emadlangeni Local Municipality
28. Column 235: Dannhauser Local Municipality
29. Column 244: Zululand
30. Column 253: eDumbe Local Municipality
31. Column 262: UPhongolo Local Municipality
32. Column 271: Abaqulusi Local Municipality
33. Column 280: Nongoma Local Municipality
34. Column 289: Ulundi Local Municipality
35. Column 298: Umkhanyakude
36. Column 307: Umhlabuyalingana Local Municipality
37. Column 316: Jozini Local Municipality
38. Column 325: Mtubatuba Local Municipality
39. Column 334: Big Five Hlabisa Local Municipality
40. Column 343: King Cetshwayo
41. Column 352: Mfolozi Local Municipality
42. Column 361: uMhlathuze Local Municipality
43. Column 370: uMlalazi Local Municipality
44. Column 379: Mthonjaneni Local Municipality
45. Column 388: Nkandla Local Municipality
46. Column 397: iLembe
47. Column 406: Mandeni Local Municipality
48. Column 415: KwaDukuza Local Municipality
49. Column 424: Ndwedwe Local Municipality
50. Column 433: Maphumulo Local Municipality
51. Column 442: Harry Gwala
52. Column 451: Greater Kokstad Local Municipality
53. Column 460: Ubuhlebezwe Local Municipality
54. Column 469: Umzimkhulu Local Municipality
55. Column 478: Dr Nkosazana Dlamini Zuma Local Municipality
56. Column 487: eThekwini
57. Column 496: Ethekwini Metropolitan Municipality
58. Column 505: Total

In [40]:
# ============================================
# TABLE1 — IDENTIFY MUNICIPALITY BLOCKS
# ============================================

municipality_columns = []

for col in range(1, table1.shape[1], 9):

    geography = table1.iloc[8, col]

    if pd.notna(geography):
        geography = str(geography)

        # Municipality names in this export contain "Municipality"
        if "Municipality" in geography:
            municipality_columns.append((col, geography))

print("Municipalities found:", len(municipality_columns))
print("=" * 80)

for col, municipality in municipality_columns:
    print(f"Column {col}: {municipality}")

Municipalities found: 44
================================================================================
Column 19: Umdoni Local Municipality
Column 28: Umzumbe Local Municipality
Column 37: UMuziwabantu Local Municipality
Column 46: Ray Nkonyeni Local Municipality
Column 64: uMshwathi Local Municipality
Column 73: uMngeni Local Municipality
Column 82: Mpofana Local Municipality
Column 91: Impendle Local Municipality
Column 100: The Msunduzi Local Municipality
Column 109: Mkhambathini Local Municipality
Column 118: Richmond Local Municipality
Column 136: Okhahlamba Local Municipality
Column 145: Inkosi Langalibalele Local Municipality
Column 154: Alfred Duma Local Municipality
Column 172: Endumeni Local Municipality
Column 181: Nqutu Local Municipality
Column 190: Msinga Local Municipality
Column 199: Umvoti Local Municipality
Column 217: Newcastle Local Municipality
Column 226: Emadlangeni Local Municipality
Column 235: Dannhauser Local Municipality
Column 253: eDumbe Local Municipality
Column 262: UPhongolo Local Municipality
Column 271: Abaqulusi Local Municipality
Column 280: Nongoma Local Municipality
Column 289: Ulundi Local Municipality
Column 307: Umhlabuyalingana Local Municipality
Column 316: Jozini Local Municipality
Column 325: Mtubatuba Local Municipality
Column 334: Big Five Hlabisa Local Municipality
Column 352: Mfolozi Local Municipality
Column 361: uMhlathuze Local Municipality
Column 370: uMlalazi Local Municipality
Column 379: Mthonjaneni Local Municipality
Column 388: Nkandla Local Municipality
Column 406: Mandeni Local Municipality
Column 415: KwaDukuza Local Municipality
Column 424: Ndwedwe Local Municipality
Column 433: Maphumulo Local Municipality
Column 451: Greater Kokstad Local Municipality
Column 460: Ubuhlebezwe Local Municipality
Column 469: Umzimkhulu Local Municipality
Column 478: Dr Nkosazana Dlamini Zuma Local Municipality
Column 496: Ethekwini Metropolitan Municipality

In [41]:
# ============================================
# TABLE1 — EXTRACT MUNICIPALITY DATA
# ============================================

# The category names are stored in Row 9.
category_names = [
    str(table1.iloc[9, col])
    for col in range(1, 9)
]

print("Categories:")
for category in category_names:
    print("-", category)

# Store extracted municipality records
municipality_records = []

for start_col, municipality in municipality_columns:

    record = {
        "municipality": municipality
    }

    # Each municipality has 8 category columns
    for offset, category in enumerate(category_names, start=1):

        value = table1.iloc[10, start_col + offset]

        record[category] = value

    municipality_records.append(record)

table1_municipalities = pd.DataFrame(municipality_records)

print("\nExtracted shape:", table1_municipalities.shape)

print("\nFirst 5 municipalities:")
display(table1_municipalities.head())

Categories:
- Household
- Homeless
- Transient
- Institution
- Urban area
- Tribal or Traditional area
- Farm area
- Male

Extracted shape: (44, 9)

First 5 municipalities:

,municipality,Household,Homeless,Transient,Institution,Urban area,Tribal or Traditional area,Farm area,Male
0,Umdoni Local Municipality,99,1,262,39850.271426,104607.218618,11985.390218,74391.521503,82051.358758
1,Umzumbe Local Municipality,56,4,125,0.000000,139029.363876,15.442094,65512.792209,73532.013761
2,UMuziwabantu Local Municipality,54,3,183,12871.211719,100534.222489,2374.091303,54516.210659,61263.314852
3,Ray Nkonyeni Local Municipality,204,1,998,97837.430403,254636.931174,9660.081033,171980.174616,190154.267993
4,uMshwathi Local Municipality,10,1,605,15332.360949,72093.563278,31051.908503,55836.571936,62641.260794

In [42]:
# ============================================
# TABLE1 — VERIFY EXTRACTED COLUMNS
# ============================================

print("Extracted columns:")
print("=" * 80)

for number, column in enumerate(table1_municipalities.columns, start=1):
    print(f"{number}. {column}")

print("\nShape:", table1_municipalities.shape)

Extracted columns:
================================================================================
1. municipality
2. Household
3. Homeless
4. Transient
5. Institution
6. Urban area
7. Tribal or Traditional area
8. Farm area
9. Male

Shape: (44, 9)

In [43]:
# ============================================
# TABLE2 — EXTRACT POPULATION BY GEOGRAPHY
# ============================================

table2 = pd.read_excel(
    TABLES_DIR / "TABLE2.xlsx",
    header=None
)

# Data starts at row 10.
# Row 10 onward contains geography names and population values.
table2_population = table2.iloc[10:, [0, 1]].copy()

# Give the columns clear names
table2_population.columns = [
    "geography",
    "population"
]

# Remove empty rows
table2_population = table2_population.dropna(
    subset=["geography"]
)

# Remove the Stats SA copyright/footer
table2_population = table2_population[
    table2_population["geography"] != "© Statistics South Africa"
]

print("TABLE2 extracted shape:", table2_population.shape)

display(table2_population.head(15))

TABLE2 extracted shape: (56, 2)

                          geography      population
10                              Ugu   773401.654351
11        Umdoni Local Municipality   156442.880261
12       Umzumbe Local Municipality    139044.80597
13  UMuziwabantu Local Municipality   115779.525511
14  Ray Nkonyeni Local Municipality   362134.442609
15                    Umgungundlovu  1235715.497129
16     uMshwathi Local Municipality    118477.83273
17       uMngeni Local Municipality   105068.595634
18       Mpofana Local Municipality    33382.364261
19      Impendle Local Municipality    36647.723855
20  The Msunduzi Local Municipality   817725.079405
21  Mkhambathini Local Municipality     61660.24514
22      Richmond Local Municipality    62753.656105
23                         Uthukela   789091.817865
24    Okhahlamba Local Municipality   143132.477123

In [44]:
# ============================================
# MERGE TABLE1 + TABLE2
# ============================================

# Keep only TABLE2 rows that match municipalities
# already identified in TABLE1.
table2_municipalities = table2_population[
    table2_population["geography"].isin(
        table1_municipalities["municipality"]
    )
].copy()

# Rename geography so both tables use the same key
table2_municipalities = table2_municipalities.rename(
    columns={"geography": "municipality"}
)

# Merge the two municipality-level tables
statssa_merged = table1_municipalities.merge(
    table2_municipalities,
    on="municipality",
    how="left",
    validate="one_to_one"
)

print("Merged shape:", statssa_merged.shape)

print("\nMerged columns:")
print(list(statssa_merged.columns))

print("\nFirst 5 rows:")
display(statssa_merged.head())

Merged shape: (44, 10)

Merged columns:
['municipality', 'Household', 'Homeless', 'Transient', 'Institution', 'Urban area', 'Tribal or Traditional area', 'Farm area', 'Male', 'population']

First 5 rows:

,municipality,Household,Homeless,Transient,Institution,Urban area,Tribal or Traditional area,Farm area,Male,population
0,Umdoni Local Municipality,99,1,262,39850.271426,104607.218618,11985.390218,74391.521503,82051.358758,156442.880261
1,Umzumbe Local Municipality,56,4,125,0.000000,139029.363876,15.442094,65512.792209,73532.013761,139044.80597
2,UMuziwabantu Local Municipality,54,3,183,12871.211719,100534.222489,2374.091303,54516.210659,61263.314852,115779.525511
3,Ray Nkonyeni Local Municipality,204,1,998,97837.430403,254636.931174,9660.081033,171980.174616,190154.267993,362134.442609
4,uMshwathi Local Municipality,10,1,605,15332.360949,72093.563278,31051.908503,55836.571936,62641.260794,118477.83273

In [45]:
# ============================================
# VERIFY THE MERGED DATASET
# ============================================

print("Number of municipalities:", len(statssa_merged))

print("\nMissing population values:")
print(statssa_merged["population"].isna().sum())

print("\nDuplicate municipalities:")
print(statssa_merged["municipality"].duplicated().sum())

print("\nMerged dataset shape:")
print(statssa_merged.shape)

print("\nMissing values by column:")
print(statssa_merged.isna().sum())

Number of municipalities: 44

Missing population values:
0

Duplicate municipalities:
0

Merged dataset shape:
(44, 10)

Missing values by column:
municipality                  0
Household                     0
Homeless                      0
Transient                     0
Institution                   0
Urban area                    0
Tribal or Traditional area    0
Farm area                     0
Male                          0
population                    0
dtype: int64

In [47]:
# ============================================
# SAVE VERIFIED STATSSA MERGED DATASET
# ============================================

from pathlib import Path

# Project folders
PROJECT_ROOT = Path.cwd().parent

PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

# Stats SA processed-data folder
STATSSA_PROCESSED_DIR = PROCESSED_DIR / "statssa"
STATSSA_PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

# Output file
STATSSA_MERGED_FILE = (
    STATSSA_PROCESSED_DIR
    / "kzn_municipality_population_demographics.csv"
)

# Save verified merged dataset
statssa_merged.to_csv(
    STATSSA_MERGED_FILE,
    index=False
)

print("Saved successfully:")
print(STATSSA_MERGED_FILE)

Saved successfully:
c:\Users\Admin\Desktop\Dirisa_1\SPU-TEAM-DIRISA\data\processed\statssa\kzn_municipality_population_demographics.csv

In [48]:
# ============================================
# TABLE3 — INSPECT ALL ROWS
# ============================================

print("TABLE3 COMPLETE STRUCTURE")
print("=" * 80)

for row in range(table3.shape[0]):

    geography_or_category = table3.iloc[row, 0]
    value = table3.iloc[row, 1]

    if pd.notna(geography_or_category) or pd.notna(value):
        print(
            f"Row {row:03d} | "
            f"Category: {geography_or_category} | "
            f"Value: {value}"
        )

TABLE3 COMPLETE STRUCTURE
================================================================================
Row 001 | Category: Descriptive 2022 (MN Phase 2) | Value: nan
Row 002 | Category: Province, district and municipality then Sex then Age in completed years then Population group then Language most often spoken | Value: nan
Row 003 | Category: Counting: Population | Value: nan
Row 005 | Category: Filters: | Value: nan
Row 006 | Category: Default Summation | Value: Population
Row 008 | Category: Province, district and municipality then Sex then Age in completed years then Population group then Language most often spoken | Value: nan
Row 009 | Category: KwaZulu-Natal | Value: 12423906.662782008
Row 010 | Category: Male | Value: 30078756.68715917
Row 011 | Category: Female | Value: 31948745.932222202
Row 012 | Category: 0 | Value: 1250353.0477566998
Row 013 | Category: 1 | Value: 1168240.7098342404
Row 014 | Category: 2 | Value: 1188298.519725562
Row 015 | Category: 3 | Value: 1130328.801133854
Row 016 | Category: 4 | Value: 1096293.544273597
Row 017 | Category: 5 | Value: 954477.8158382007
Row 018 | Category: 6 | Value: 1011729.9181077147
Row 019 | Category: 7 | Value: 1048430.4954019606
Row 020 | Category: 8 | Value: 1038061.8678377874
Row 021 | Category: 9 | Value: 1056403.960507052
Row 022 | Category: 10 | Value: 1055068.457665082
Row 023 | Category: 11 | Value: 1094814.8671509093
Row 024 | Category: 12 | Value: 1076374.1380515625
Row 025 | Category: 13 | Value: 1105321.124375608
Row 026 | Category: 14 | Value: 1072545.808294187
Row 027 | Category: 15 | Value: 1081806.7521004202
Row 028 | Category: 16 | Value: 1071637.4746376863
Row 029 | Category: 17 | Value: 1012704.5819278515
Row 030 | Category: 18 | Value: 924581.9361747585
Row 031 | Category: 19 | Value: 884578.6450539028
Row 032 | Category: 20 | Value: 1011053.8720050836
Row 033 | Category: 21 | Value: 1108187.811439477
Row 034 | Category: 22 | Value: 1071721.7514606449
Row 035 | Category: 23 | Value: 1046759.992262469
Row 036 | Category: 24 | Value: 1072014.9485557876
Row 037 | Category: 25 | Value: 1148424.247052114
Row 038 | Category: 26 | Value: 1136839.9239893607
Row 039 | Category: 27 | Value: 1166568.4135864838
Row 040 | Category: 28 | Value: 1119027.2803796697
Row 041 | Category: 29 | Value: 1162379.4367141034
Row 042 | Category: 30 | Value: 1116319.6495038825
Row 043 | Category: 31 | Value: 1188644.0243981257
Row 044 | Category: 32 | Value: 1136049.2140213395
Row 045 | Category: 33 | Value: 1092202.5693637016
Row 046 | Category: 34 | Value: 1059607.7635442668
Row 047 | Category: 35 | Value: 1087150.6542802271
Row 048 | Category: 36 | Value: 1116115.798005921
Row 049 | Category: 37 | Value: 1013254.1268394778
Row 050 | Category: 38 | Value: 985651.0993329806
Row 051 | Category: 39 | Value: 1020430.9534832736
Row 052 | Category: 40 | Value: 869827.3012684205
Row 053 | Category: 41 | Value: 915951.0753247882
Row 054 | Category: 42 | Value: 862835.272796487
Row 055 | Category: 43 | Value: 773994.5810113424
Row 056 | Category: 44 | Value: 762612.2443527612
Row 057 | Category: 45 | Value: 674839.8431609498
Row 058 | Category: 46 | Value: 693512.0272348332
Row 059 | Category: 47 | Value: 660506.6147818052
Row 060 | Category: 48 | Value: 611119.517081962
Row 061 | Category: 49 | Value: 653532.7432173077
Row 062 | Category: 50 | Value: 541704.233774958
Row 063 | Category: 51 | Value: 609837.051723792
Row 064 | Category: 52 | Value: 570241.6141584215
Row 065 | Category: 53 | Value: 564956.1357245826
Row 066 | Category: 54 | Value: 482399.8481527956
Row 067 | Category: 55 | Value: 487908.8266968451
Row 068 | Category: 56 | Value: 519401.6315074663
Row 069 | Category: 57 | Value: 495841.2589424853
Row 070 | Category: 58 | Value: 499476.1631176444
Row 071 | Category: 59 | Value: 493824.37993875594
Row 072 | Category: 60 | Value: 418434.23081899824
Row 073 | Category: 61 | Value: 464394.8079334493
Row 074 | Category: 62 | Value: 413990.47587110917
Row 075 | Category: 63 | Value: 424262.00762092625
Row 076 | Category: 64 | Value: 374585.5405778911
Row 077 | Category: 65 | Value: 357817.36389965215
Row 078 | Category: 66 | Value: 329316.6613640407
Row 079 | Category: 67 | Value: 312775.51926583966
Row 080 | Category: 68 | Value: 293990.2016532795
Row 081 | Category: 69 | Value: 305771.3895760297
Row 082 | Category: 70 | Value: 216840.96990516665
Row 083 | Category: 71 | Value: 247353.56951391714
Row 084 | Category: 72 | Value: 211995.56745580756
Row 085 | Category: 73 | Value: 193955.47164128817
Row 086 | Category: 74 | Value: 175860.65532042892
Row 087 | Category: 75 | Value: 154518.72986150888
Row 088 | Category: 76 | Value: 144378.89855819967
Row 089 | Category: 77 | Value: 122130.80579016994
Row 090 | Category: 78 | Value: 111837.23724463
Row 091 | Category: 79 | Value: 119167.6743545197
Row 092 | Category: 80 | Value: 87280.4727571206
Row 093 | Category: 81 | Value: 107020.9498748994
Row 094 | Category: 82 | Value: 79940.9218090606
Row 095 | Category: 83 | Value: 66487.21640759068
Row 096 | Category: 84 | Value: 54084.80989495051
Row 097 | Category: 85 | Value: 51266.5676116504
Row 098 | Category: 86 | Value: 41882.51298336028
Row 099 | Category: 87 | Value: 35638.12131190021
Row 100 | Category: 88 | Value: 30139.537930640163
Row 101 | Category: 89 | Value: 28378.165589180142
Row 102 | Category: 90 | Value: 18967.979100440025
Row 103 | Category: 91 | Value: 26005.46738770011
Row 104 | Category: 92 | Value: 17560.433412509978
Row 105 | Category: 93 | Value: 12043.999692810012
Row 106 | Category: 94 | Value: 8928.51205565
Row 107 | Category: 95 | Value: 6863.610443849997
Row 108 | Category: 96 | Value: 5598.085806150004
Row 109 | Category: 97 | Value: 4475.855592379997
Row 110 | Category: 98 | Value: 3023.2039067699993
Row 111 | Category: 99 | Value: 9334.46605617
Row 112 | Category: 100 | Value: 2012.87095444
Row 113 | Category: 101 | Value: 3053.7929948099973
Row 114 | Category: 102 | Value: 1529.09938422
Row 115 | Category: 103 | Value: 1409.8219754299992
Row 116 | Category: 104 | Value: 587.4269523500001
Row 117 | Category: 105 | Value: 416.3989903700002
Row 118 | Category: 106 | Value: 297.09246033
Row 119 | Category: 107 | Value: 507.01250353000006
Row 120 | Category: 108 | Value: 224.98885828000004
Row 121 | Category: 109 | Value: 230.58103138
Row 122 | Category: 110 | Value: 123.22187198999998
Row 123 | Category: 111 | Value: 212.68526568000007
Row 124 | Category: 112 | Value: 112.66083465
Row 125 | Category: 113 | Value: 89.4185187
Row 126 | Category: 114 | Value: 72.1248282
Row 127 | Category: 115 | Value: 66.80582670000001
Row 128 | Category: 116 | Value: 50.17795712
Row 129 | Category: 117 | Value: 48.7927508
Row 130 | Category: 118 | Value: 35.066935799999996
Row 131 | Category: 119 | Value: 47.676912099999996
Row 132 | Category: 120 | Value: 26.040634499999996
Row 133 | Category: 121 | Value: 89.60858410000002
Row 134 | Category: 122 | Value: 23.4395779
Row 135 | Category: 123 | Value: 20.78951268
Row 136 | Category: 124 | Value: 18.0021146
Row 137 | Category: 125 | Value: 22.329130799999998
Row 138 | Category: 126 | Value: 19.05679446
Row 139 | Category: 127 | Value: 20.3487991
Row 140 | Category: 128 | Value: 2.8551609
Row 141 | Category: 129 | Value: 45.698344920000004
Row 142 | Category: 130 | Value: 10.7050445
Row 143 | Category: Unspecified | Value: 2999
Row 144 | Category: Black African | Value: 50486855.96347812
Row 145 | Category: Coloured | Value: 5052348.525046748
Row 146 | Category: Indian or Asian | Value: 1697505.861473724
Row 147 | Category: White | Value: 4504251.530739763
Row 148 | Category: Other | Value: 247352.73866097874
Row 149 | Category: Unspecified | Value: 39188
Row 150 | Category: Afrikaans | Value: 6365488.405515495
Row 151 | Category: English | Value: 5228300.544795035
Row 152 | Category: Isindebele | Value: 1044376.7929603198
Row 153 | Category: IsiXhosa | Value: 9786927.720113318
Row 154 | Category: IsiZulu | Value: 14613202.455735149
Row 155 | Category: Sepedi | Value: 5972255.272087867
Row 156 | Category: Sesotho | Value: 4678964.246650568
Row 157 | Category: Setswana | Value: 4972786.701879141
Row 158 | Category: Sign language | Value: 9307.758971719988
Row 159 | Category: Siswati | Value: 1692719.4003870934
Row 160 | Category: Tshivenda | Value: 1480564.9534887602
Row 161 | Category: Xitsonga | Value: 2784279.19356695
Row 162 | Category: Khoi,Nama and San languages | Value: 5916.920972349997
Row 163 | Category: Shona | Value: 716966.5524298036
Row 164 | Category: Chichewa/Chewa/Nyanja/Chinyanja | Value: 161162.11719687685
Row 165 | Category: Portuguese | Value: 95160.86665483234
Row 166 | Category: Other | Value: 268067.743669248
Row 167 | Category: Not applicable | Value: 1892088.047756694
Row 168 | Category: Unspecified | Value: 258966.92456068797
Row 173 | Category: © Statistics South Africa | Value: nan