In [1]:
from pathlib import Path
import pandas as pd
import requests
from bs4 import BeautifulSoup

PROJECT_ROOT = Path.cwd().parent

RAW_DIR = PROJECT_ROOT / "data" / "raw"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

AFROBAROMETER_RAW_DIR = RAW_DIR / "afrobarometer"
AFROBAROMETER_PROCESSED_DIR = PROCESSED_DIR / "afrobarometer"

AFROBAROMETER_RAW_DIR.mkdir(parents=True, exist_ok=True)
AFROBAROMETER_PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

print("Project root:", PROJECT_ROOT)
print("Raw directory:", AFROBAROMETER_RAW_DIR)
print("Processed directory:", AFROBAROMETER_PROCESSED_DIR)

Project root: c:\Users\Admin\Desktop\Dirisa_1\SPU-TEAM-DIRISA
Raw directory: c:\Users\Admin\Desktop\Dirisa_1\SPU-TEAM-DIRISA\data\raw\afrobarometer
Processed directory: c:\Users\Admin\Desktop\Dirisa_1\SPU-TEAM-DIRISA\data\processed\afrobarometer

In [2]:
AFROBAROMETER_URL = "https://www.afrobarometer.org/articles/a-long-to-do-list-for-the-victors-of-south-africas-2024-election/"

print("Source:", AFROBAROMETER_URL)

Source: https://www.afrobarometer.org/articles/a-long-to-do-list-for-the-victors-of-south-africas-2024-election/

In [3]:
response = requests.get(
    AFROBAROMETER_URL,
    timeout=30
)

print("Status code:", response.status_code)
print("Page size:", len(response.text), "characters")

Status code: 200
Page size: 96513 characters

In [4]:
soup = BeautifulSoup(response.text, "html.parser")

title = soup.title.get_text(strip=True) if soup.title else None
headings = [h.get_text(" ", strip=True) for h in soup.find_all(["h1", "h2", "h3"])]
paragraphs = [p.get_text(" ", strip=True) for p in soup.find_all("p")]

print("PAGE TITLE:")
print(title)

print("\nNUMBER OF HEADINGS:", len(headings))
print("NUMBER OF PARAGRAPHS:", len(paragraphs))

print("\nHEADINGS:")
for heading in headings:
    print("-", heading)

PAGE TITLE:
A long to-do list for the victors of South Africa’s 2024 election – Afrobarometer

NUMBER OF HEADINGS: 1
NUMBER OF PARAGRAPHS: 46

HEADINGS:
- A long to-do list for the victors of South Africa’s 2024 election

In [5]:
for i, paragraph in enumerate(paragraphs):
    print(f"[{i}] {paragraph}")

[0] Let the people have a say
[1] On 29 May, South Africans will cast their ballots for the seventh time since the end of apartheid. Irrespective of who wins the general election, the new government will face formidable challenges. In 2023, citizens experienced a record 332 days of power cuts , which caused severe disruptions in the economy as well as people’s daily lives. The unemployment rate hovered at 32% and was even higher among young people (40%). The country’s education system continues to struggle to provide quality education for all children, while water infrastructure is crumbling due to insufficient maintenance and failing to expand to meet growing demand. The country’s murder rate recently climbed to its highest levels in 20 years.
[2] After Election Day, which of South Africa’s challenges should the new government prioritise?
[3] We present a citizen perspective on this question using data from a new Afrobarometer survey, which interviewed 1,800 adult South Africans via telephone between 23 April and 11 May 2024.
[4] South Africa’s most important problems
[5] Respondents were asked to identify the three most important problems that the government should address after the election. A clear picture emerges that emphasises economic challenges, service delivery, and corruption (Figure 1). Unemployment was given by far the highest priority (cited by 71% of respondents). Many South Africans also mentioned inflation/cost of living (21%), poverty (21%), and management of the economy more broadly (20%). Other priority issues include service delivery (electricity, safety, water supply, education, and housing) and corruption.
[6] Figure 1: Most important problems | South Africa | 2024
[7]
[8]
[9]
[10] Respondents were asked: In your opinion, what are the three most important problems facing this country that the government should address after the forthcoming elections?
[11] Over the past decade, Afrobarometer has consistently found that unemployment is South Africans’ leading national priority . Indeed, the share of citizens who cited this problem in 2024 is identical to that in 2015 (Figure 2). In contrast, overall economic management (+14 percentage points) and electricity supply (+11) have risen in importance since 2015 as worsening power cuts have had significant negative repercussions for people’s quality of life and the economy at large.
[12] We see lower prioritisation of housing (-17), crime and security (-10), and education (-8) between the two points in time. This is not necessarily because the government has resolved these challenges, but perhaps because others have become more urgent.
[13] Figure 2: Most important problems | South Africa | 2015 and 2024
[14]
[15] Respondents were asked:
[16] In 2015: In your opinion, what are the most important problems facing this country that government should address?
[17] In 2024: In your opinion, what are the three most important problems facing this country that the government should address after the forthcoming elections?
[18] South Africans are not unique in their focus on unemployment as a top priority for government action. On average across 39 African countries that Afrobarometer surveyed in Round 9 between late 2021 and mid-2023, unemployment also outranked all other problems (Figure 3). In Round 9, unemployment was a top priority for 50% of South Africans, placing the country fifth after Cabo Verde (60%), Namibia (60%), Gabon (54%), and Morocco (54%). In contrast, unemployment was a priority for fewer than one in 10 respondents in Seychelles (6%) and Sudan (7%).
[19] Figure 3: Prioritisation of unemployment | 39 countries | 2021/2023
[20]
[21] (% of respondents who cite “unemployment” among their top 3 priorities)
[22] South Africans’ strong emphasis on economic challenges is unsurprising given the significant deterioration in their evaluations of economic conditions over the past decade. In 2015, about six in 10 respondents (58%) said the country was in poor economic shape, an assessment shared by a staggering 79% in the weeks before the 2024 election (Figure 4). The 7% of South Africans who say the economy is doing “fairly good” or “very good” represents a lower level of satisfaction with economic conditions than recorded in any country surveyed in 2021/2023, except Tunisia (4%) and Eswatini (6%).
[23] Figure 4 : National economic conditions | South Africa | 2015-2024
[24]
[25] Respondents were asked: In general, how would you describe the present economic condition of this country?
[26] Priorities vary with age and location
[27] Young South Africans (aged 18-35 years) are significantly more likely than seniors (over age 55) to cite unemployment as a priority issue (77% vs. 66%) (Figure 5). On the other hand, poverty, water supply, and housing are more urgent issues for older respondents. The issue of housing holds particular significance given South Africa’s apartheid past and previous survey findings that citizens prefer for the government to prioritise the provision of housing over land redistribution.
[28] Figure 5: Most important problems | by age group | South Africa | 2024
[29]
[30] Respondents were asked: In your opinion, what are the three most important problems facing this country that the government should address after the forthcoming elections?
[31] We also find differences in issue prioritisation between urban and rural residents (Figure 6). Water supply is the second-highest priority for citizens in villages (30%), while 9% of urban residents mentioned water. This mirrors differences in access : In 2022, nine out of 10 urbanites (92%) had their main water source inside their property, compared to 67% of rural households, a 25-percentage-point gap. Nevertheless, it is important to note the government’s progress in this area: A decade ago, the urban-rural gap in access to piped water was 38 percentage points.
[32] Figure 6: Most important problems | by urban-rural location | South Africa | 2024
[33]
[34] Respondents were asked: In your opinion, what are the three most important problems facing this country that the government should address after the forthcoming elections?
[35] Lastly, we can get a glimpse of whether priorities vary between those who intend to vote on 29 May and those planning to stay home. Almost nine in 10 survey respondents (86%) said they are registered to vote in the 2024 election, with 88% of this group reporting that they are “probably” or “definitely” going to vote. As Figure 7 shows, likely voters don’t differ dramatically in their policy priorities from registered South Africans who say they are unlikely to vote or from those who are not registered. We see some differences in their relative prioritisation of corruption and provision of water and electricity, though the pattern is not clear.
[36] Figure 7: Most important problems | by registration status and intention to vote | South Africa | 2024
[37]
[38] Respondents were asked: In your opinion, what are the three most important problems facing this country that the government should address after the forthcoming elections?
[39] The South African election campaign season is in full swing, and political parties have launched their manifestos, campaign posters, and media messaging about how to address the country’s economic and social challenges. Our survey indicates that party policies are influential for two-thirds of registered voters. It remains to be seen whose messages will resonate most with South African voters.
[40] This was originally published by Democracy in Africa
[41]
[42] Matthias Krönke is a researcher in the Afrobarometer Analysis Unit.
[43] Rorisang Lekalake is the director of analysis at Afrobarometer.
[44] Asafika is the communications coordinator for Southern Africa
[45] Receive the latest updates from Afrobarometer

In [6]:
for i in range(24, 42):
    print(f"[{i}] {paragraphs[i]}")

[24]
[25] Respondents were asked: In general, how would you describe the present economic condition of this country?
[26] Priorities vary with age and location
[27] Young South Africans (aged 18-35 years) are significantly more likely than seniors (over age 55) to cite unemployment as a priority issue (77% vs. 66%) (Figure 5). On the other hand, poverty, water supply, and housing are more urgent issues for older respondents. The issue of housing holds particular significance given South Africa’s apartheid past and previous survey findings that citizens prefer for the government to prioritise the provision of housing over land redistribution.
[28] Figure 5: Most important problems | by age group | South Africa | 2024
[29]
[30] Respondents were asked: In your opinion, what are the three most important problems facing this country that the government should address after the forthcoming elections?
[31] We also find differences in issue prioritisation between urban and rural residents (Figure 6). Water supply is the second-highest priority for citizens in villages (30%), while 9% of urban residents mentioned water. This mirrors differences in access : In 2022, nine out of 10 urbanites (92%) had their main water source inside their property, compared to 67% of rural households, a 25-percentage-point gap. Nevertheless, it is important to note the government’s progress in this area: A decade ago, the urban-rural gap in access to piped water was 38 percentage points.
[32] Figure 6: Most important problems | by urban-rural location | South Africa | 2024
[33]
[34] Respondents were asked: In your opinion, what are the three most important problems facing this country that the government should address after the forthcoming elections?
[35] Lastly, we can get a glimpse of whether priorities vary between those who intend to vote on 29 May and those planning to stay home. Almost nine in 10 survey respondents (86%) said they are registered to vote in the 2024 election, with 88% of this group reporting that they are “probably” or “definitely” going to vote. As Figure 7 shows, likely voters don’t differ dramatically in their policy priorities from registered South Africans who say they are unlikely to vote or from those who are not registered. We see some differences in their relative prioritisation of corruption and provision of water and electricity, though the pattern is not clear.
[36] Figure 7: Most important problems | by registration status and intention to vote | South Africa | 2024
[37]
[38] Respondents were asked: In your opinion, what are the three most important problems facing this country that the government should address after the forthcoming elections?
[39] The South African election campaign season is in full swing, and political parties have launched their manifestos, campaign posters, and media messaging about how to address the country’s economic and social challenges. Our survey indicates that party policies are influential for two-thirds of registered voters. It remains to be seen whose messages will resonate most with South African voters.
[40] This was originally published by Democracy in Africa
[41]

In [7]:
tables = soup.find_all("table")

print("Number of HTML tables:", len(tables))

images = soup.find_all("img")

print("Number of images:", len(images))

for image in images:
    alt = image.get("alt")
    if alt:
        print("-", alt)

Number of HTML tables: 0
Number of images: 8

In [8]:
for i, image in enumerate(images):
    print(f"\nIMAGE {i + 1}")
    print("Alt:", image.get("alt"))
    print("Source:", image.get("src"))

IMAGE 1
Alt:
Source: None

IMAGE 2
Alt:
Source: https://www.afrobarometer.org/wp-content/uploads/2024/05/Screenshot-2024-05-30-at-13.03.13-300x177.webp

IMAGE 3
Alt:
Source: https://www.afrobarometer.org/wp-content/uploads/2024/05/Screenshot-2024-05-30-at-13.10.41-300x199.webp

IMAGE 4
Alt:
Source: https://www.afrobarometer.org/wp-content/uploads/2024/05/Screenshot-2024-05-30-at-13.11.47-300x206.webp

IMAGE 5
Alt:
Source: https://www.afrobarometer.org/wp-content/uploads/2024/05/Screenshot-2024-05-31-at-06.32.35-300x133.webp

IMAGE 6
Alt:
Source: https://www.afrobarometer.org/wp-content/uploads/2024/05/Screenshot-2024-05-31-at-06.33.54-300x162.webp

IMAGE 7
Alt:
Source: https://www.afrobarometer.org/wp-content/uploads/2024/05/Screenshot-2024-05-31-at-06.34.46-300x157.webp

IMAGE 8
Alt:
Source: https://www.afrobarometer.org/wp-content/uploads/2024/05/Screenshot-2024-05-31-at-06.36.38-300x256.webp

In [9]:
links = soup.find_all("a")

for link in links:
    text = link.get_text(" ", strip=True)
    href = link.get("href")

    if text or href:
        print("TEXT:", text)
        print("LINK:", href)
        print()

TEXT: Skip to content
LINK: #content

TEXT:
LINK: https://www.afrobarometer.org

TEXT: Analyse online
LINK: https://www.afrobarometer.org/online-data-analysis/

TEXT: Opportunities
LINK: https://www.afrobarometer.org/careers/

TEXT: Blog
LINK: https://www.afrobarometer.org/blog/

TEXT: Contact us
LINK: https://www.afrobarometer.org/contact-us/

TEXT: Support our work
LINK: https://www.afrobarometer.org/support/

TEXT: About
LINK: https://www.afrobarometer.org/about/

TEXT: Our history
LINK: https://www.afrobarometer.org/about/history/

TEXT: What we do
LINK: https://www.afrobarometer.org/about/what-we-do/

TEXT: Annual reports
LINK: https://www.afrobarometer.org/about/annual-reports/

TEXT: Our network
LINK: https://www.afrobarometer.org/about/our-network/

TEXT: Funding partners
LINK: https://www.afrobarometer.org/support/our-funding-partners/

TEXT: FAQs
LINK: https://www.afrobarometer.org/about/faqs/

TEXT: Countries
LINK: https://www.afrobarometer.org/countries/

TEXT: Surveys
LINK: https://www.afrobarometer.org/surveys-and-methods/

TEXT: Survey resources and data
LINK: https://www.afrobarometer.org/surveys-and-methods/survey-resources/

TEXT: Questionnaires
LINK: https://www.afrobarometer.org/surveys-and-methods/questionnaire/

TEXT: Sampling
LINK: https://www.afrobarometer.org/surveys-and-methods/sampling/

TEXT: Survey manuals
LINK: https://www.afrobarometer.org/surveys-and-methods/survey-manuals/

TEXT: Afrobarometer calling
LINK: https://www.afrobarometer.org/surveys-and-methods/afrobarometer-calling/

TEXT: Topics
LINK: https://www.afrobarometer.org/topics/

TEXT: Democracy, freedom, and citizen engagement
LINK: https://www.afrobarometer.org/topics/democracy-freedom-citizen-engagement/

TEXT: Economy, poverty, and development
LINK: https://www.afrobarometer.org/topics/economy-poverty-development/

TEXT: Energy and infrastructure
LINK: https://www.afrobarometer.org/topics/energy-infrastructure/

TEXT: Environment and climate
LINK: https://www.afrobarometer.org/topics/environment-and-climate/

TEXT: Health, education, and social services
LINK: https://www.afrobarometer.org/topics/health-education-social-services/

TEXT: Identity, society, and gender
LINK: https://www.afrobarometer.org/topics/identity-society-gender/

TEXT: Institutions, leadership, and governance
LINK: https://www.afrobarometer.org/topics/institutions-leadership-governance/

TEXT: Regional and global relations
LINK: https://www.afrobarometer.org/topics/regional-global-relations/

TEXT: Safety and security
LINK: https://www.afrobarometer.org/topics/safety-security/

TEXT: Publications
LINK: https://www.afrobarometer.org/publications/

TEXT: All publications
LINK: https://www.afrobarometer.org/publications/

TEXT: Dispatches
LINK: https://www.afrobarometer.org/dispatches/

TEXT: Flagship reports
LINK: https://www.afrobarometer.org/publications/flagship-reports/

TEXT: Methods Notes
LINK: https://www.afrobarometer.org/publications/methods-notes/

TEXT: Pan-Africa Profiles
LINK: https://www.afrobarometer.org/pan-africa-profiles/

TEXT: Scorecards
LINK: https://www.afrobarometer.org/publications/scorecards/

TEXT: Data
LINK: https://www.afrobarometer.org/data/

TEXT: Data sets
LINK: https://www.afrobarometer.org/data/data-sets/

TEXT: Merged data
LINK: https://www.afrobarometer.org/data/merged-data/

TEXT: Codebooks
LINK: https://www.afrobarometer.org/data/codebooks/

TEXT: Impact
LINK: https://www.afrobarometer.org/impact/

TEXT: Capacity building
LINK: https://www.afrobarometer.org/impact/capacity-building/

TEXT: The Afrobarometer training video library
LINK: https://www.afrobarometer.org/impact/capacity-building-video-training-library/

TEXT: Impact stories
LINK: https://www.afrobarometer.org/impact/impact-stories/

TEXT: Informing the public discourse
LINK: https://www.afrobarometer.org/impact/informing-the-public-discourse/

TEXT: Strategic partnerships
LINK: https://www.afrobarometer.org/impact/strategicpartnerships/

TEXT: News & features
LINK: https://www.afrobarometer.org/newsandmultimedia/

TEXT: Announcements
LINK: https://www.afrobarometer.org/newsandmultimedia/announcements/

TEXT: Annual reports
LINK: https://www.afrobarometer.org/newsandmultimedia/annual-reports/

TEXT: Events
LINK: https://www.afrobarometer.org/newsandmultimedia/events/

TEXT: Featured videos
LINK: https://www.afrobarometer.org/newsandmultimedia/featured-videos/

TEXT: Flagship reports
LINK: https://www.afrobarometer.org/newsandmultimedia/flagship-reports/

TEXT: Media briefings
LINK: https://www.afrobarometer.org/newsandmultimedia/media-briefing/

TEXT: News releases
LINK: https://www.afrobarometer.org/newsandmultimedia/news-releases/

TEXT: Home
LINK: https://www.afrobarometer.org

TEXT: News & features
LINK: https://www.afrobarometer.org/newsandmultimedia/

TEXT: Matthias Krönke
LINK: https://www.afrobarometer.org/person/matthias-kronke/

TEXT: Rorisang Lekalake
LINK: https://www.afrobarometer.org/person/rorisang-lekalake/

TEXT: Asafika Mpako
LINK: https://www.afrobarometer.org/person/asafika-mpako/

TEXT: 332 days of power cuts
LINK: https://www.iol.co.za/news/south-africa/the-year-we-were-plunged-into-darkness-a-record-332-days-of-load-shedding-in-2023-and-counting-63eafd30-87c8-4f13-acd0-60071e509239#:~:text=South%20Africans%20have%20faced%20a,the%20country's%20power%20supply%20crisis.

TEXT: provide quality education
LINK: https://theconversation.com/matric-results-south-africas-record-school-pass-rates-arent-what-they-seem-whats-really-happening-in-the-education-system-221787#:~:text=Of%20these%2C%20only%20928%2C050%20were,%25)%20disappeared%20into%20the%20system.

TEXT: water infrastructure
LINK: https://businesstech.co.za/news/government/725376/the-real-reason-for-south-africas-water-crisis/

TEXT: murder rate
LINK: https://www.reuters.com/world/africa/key-issues-south-african-voters-wide-open-2024-election-2024-05-13/

TEXT: interviewed 1,800 adult South Africans via telephone
LINK: https://www.afrobarometer.org/articles/frequently-asked-questions-faqs-about-afrobarometers-pre-election-telephone-survey-in-south-africa/

TEXT: consistently
LINK: https://www.afrobarometer.org/wp-content/uploads/2023/08/News_release-Jobs-top-priority-for-South-African-youth-Afrobarometer-17aug23.pdf

TEXT: unemployment is South Africans’ leading national priority
LINK: https://www.afrobarometer.org/wp-content/uploads/2022/02/news_release-south_africans_rank_unemployment_as_the_countrys_most_urgent_priority-afrobarometer-21oct21.pdf

TEXT: previous survey findings
LINK: https://www.afrobarometer.org/wp-content/uploads/2022/02/news_release-south_africans_say_government_should_prioritize_housing-afrobarometer-9nov21.pdf

TEXT: differences in access
LINK: https://www.afrobarometer.org/wp-content/uploads/2022/02/ab_r7_dispatchno349_pap14_water_and_sanitation_in_africa.pdf

TEXT: Democracy in Africa
LINK: https://democracyinafrica.org/the-victors-of-south-africas-2024-election-will-have-a-long-to-do-list-according-to-the-people/

TEXT:
LINK: //www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fwww.afrobarometer.org%2F%3Fp%3D26418&t=A+long+to-do+list+for+the+victors+of+South+Africa%E2%80%99s+2024+election

TEXT:
LINK: //twitter.com/share?text=A+long+to-do+list+for+the+victors+of+South+Africa%E2%80%99s+2024+election&url=https%3A%2F%2Fwww.afrobarometer.org%2F%3Fp%3D26418&via=

TEXT:
LINK: //www.linkedin.com/shareArticle?mini=true&url=https%3A%2F%2Fwww.afrobarometer.org%2F%3Fp%3D26418&title=A+long+to-do+list+for+the+victors+of+South+Africa%E2%80%99s+2024+election&summary=On+29+May%2C+South+Africans+will+cast+their+ballots+for+the+seventh+time+since+the+end+of+apartheid.+Irrespective+of+who+wins+the+general+election%2C+the+new+government+will+face...&source=Afrobarometer

TEXT:
LINK: mailto:?subject=A+long+to-do+list+for+the+victors+of+South+Africa%E2%80%99s+2024+election&body=A+long+to-do+list+for+the+victors+of+South+Africa%E2%80%99s+2024+election.+https%3A%2F%2Fwww.afrobarometer.org%2F%3Fp%3D26418

TEXT: English
LINK: /search/?select-languages%5B%5D=english

TEXT: Democracy, freedom, and citizen engagement
LINK: /search/?select-topics%5B%5D=democracy-freedom-and-citizen-engagement

TEXT: Democracy
LINK: /search/?select-keywords%5B%5D=democracy

TEXT: Elections
LINK: /search/?select-keywords%5B%5D=elections

TEXT: Government performance
LINK: /search/?select-keywords%5B%5D=government-performance

TEXT: Pre-election surveys
LINK: /search/?select-keywords%5B%5D=pre-election-surveys

TEXT: South Africa
LINK: /countries/south-africa

TEXT: Southern Africa
LINK: /search/?select-regions%5B%5D=southern

TEXT: About
LINK: https://www.afrobarometer.org/about/

TEXT: Our history
LINK: https://www.afrobarometer.org/about/history/

TEXT: What we do
LINK: https://www.afrobarometer.org/about/what-we-do/

TEXT: Annual reports
LINK: https://www.afrobarometer.org/about/annual-reports/

TEXT: Our network
LINK: https://www.afrobarometer.org/about/our-network/

TEXT: Network management
LINK: https://www.afrobarometer.org/about/our-network/network-management/

TEXT: Funding partners
LINK: https://www.afrobarometer.org/support/our-funding-partners/

TEXT: FAQs
LINK: https://www.afrobarometer.org/about/faqs/

TEXT: Countries
LINK: https://www.afrobarometer.org/countries/

TEXT: Surveys
LINK: https://www.afrobarometer.org/surveys-and-methods/

TEXT: Survey resources and data
LINK: https://www.afrobarometer.org/surveys-and-methods/survey-resources/

TEXT: Questionnaires
LINK: https://www.afrobarometer.org/surveys-and-methods/questionnaire/

TEXT: Sampling
LINK: https://www.afrobarometer.org/surveys-and-methods/sampling/

TEXT: Survey manuals
LINK: https://www.afrobarometer.org/surveys-and-methods/survey-manuals/

TEXT: Afrobarometer calling
LINK: https://www.afrobarometer.org/surveys-and-methods/afrobarometer-calling/

TEXT: Topics
LINK: https://www.afrobarometer.org/topics/

TEXT: Democracy, freedom, and citizen engagement
LINK: https://www.afrobarometer.org/topics/democracy-freedom-citizen-engagement/

TEXT: Economy, poverty, and development
LINK: https://www.afrobarometer.org/topics/economy-poverty-development/

TEXT: Energy and infrastructure
LINK: https://www.afrobarometer.org/topics/energy-infrastructure/

TEXT: Environment and climate
LINK: https://www.afrobarometer.org/topics/environment-and-climate/

TEXT: Health, education, and social services
LINK: https://www.afrobarometer.org/topics/health-education-social-services/

TEXT: Identity, society, and gender
LINK: https://www.afrobarometer.org/topics/identity-society-gender/

TEXT: Institutions, leadership, and governance
LINK: https://www.afrobarometer.org/topics/institutions-leadership-governance/

TEXT: Regional and global relations
LINK: https://www.afrobarometer.org/topics/regional-global-relations/

TEXT: Safety and security
LINK: https://www.afrobarometer.org/topics/safety-security/

TEXT: Publications
LINK: https://www.afrobarometer.org/publications/

TEXT: All publications
LINK: https://www.afrobarometer.org/publications/

TEXT: Dispatches
LINK: https://www.afrobarometer.org/dispatches/

TEXT: Flagship reports
LINK: https://www.afrobarometer.org/publications/flagship-reports/

TEXT: Methods Notes
LINK: https://www.afrobarometer.org/publications/methods-notes/

TEXT: Pan-Africa Profiles
LINK: https://www.afrobarometer.org/pan-africa-profiles/

TEXT: Scorecards
LINK: https://www.afrobarometer.org/publications/scorecards/

TEXT: Data
LINK: https://www.afrobarometer.org/data/

TEXT: Data sets
LINK: https://www.afrobarometer.org/data/data-sets/

TEXT: Merged data
LINK: https://www.afrobarometer.org/data/merged-data/

TEXT: Codebooks
LINK: https://www.afrobarometer.org/data/codebooks/

TEXT: Impact
LINK: https://www.afrobarometer.org/impact/

TEXT: Capacity building
LINK: https://www.afrobarometer.org/impact/capacity-building/

TEXT: The Afrobarometer training video library
LINK: https://www.afrobarometer.org/impact/capacity-building-video-training-library/

TEXT: Impact stories
LINK: https://www.afrobarometer.org/impact/impact-stories/

TEXT: Informing the public discourse
LINK: https://www.afrobarometer.org/impact/informing-the-public-discourse/

TEXT: Strategic partnerships
LINK: https://www.afrobarometer.org/impact/strategicpartnerships/

TEXT: News & features
LINK: https://www.afrobarometer.org/newsandmultimedia/

TEXT: Announcements
LINK: https://www.afrobarometer.org/newsandmultimedia/announcements/

TEXT: Annual reports
LINK: https://www.afrobarometer.org/newsandmultimedia/annual-reports/

TEXT: Events
LINK: https://www.afrobarometer.org/newsandmultimedia/events/

TEXT: Featured videos
LINK: https://www.afrobarometer.org/newsandmultimedia/featured-videos/

TEXT: Flagship reports
LINK: https://www.afrobarometer.org/newsandmultimedia/flagship-reports/

TEXT: Media briefings
LINK: https://www.afrobarometer.org/newsandmultimedia/media-briefing/

TEXT: News releases
LINK: https://www.afrobarometer.org/newsandmultimedia/news-releases/

TEXT: Analyse online
LINK: https://www.afrobarometer.org/online-data-analysis/

TEXT: Opportunities
LINK: https://www.afrobarometer.org/careers/

TEXT: Blog
LINK: https://www.afrobarometer.org/blog/

TEXT: Contact us
LINK: https://www.afrobarometer.org/contact-us/

TEXT: Support our work
LINK: https://www.afrobarometer.org/support/

TEXT: Design and development by Soapbox
LINK: https://www.soapbox.co.uk

TEXT: Privacy policy
LINK: https://www.afrobarometer.org/privacy-policy/

TEXT:
LINK: https://twitter.com/afrobarometer

TEXT:
LINK: https://www.linkedin.com/company/afrobarometer

TEXT:
LINK: https://www.facebook.com/Afrobarometer

TEXT:
LINK: https://www.instagram.com/afrobarometer/

TEXT:
LINK: https://www.flickr.com/photos/197010833@N03/albums

TEXT:
LINK: mailto:admin@afrobarometer.org

In [10]:
for link in links:
    text = link.get_text(" ", strip=True).lower()
    href = link.get("href")

    if href and any(word in text + " " + href.lower()
                    for word in ["data", "dataset", "download", "analyse", "analysis"]):
        print("TEXT:", link.get_text(" ", strip=True))
        print("LINK:", href)
        print()

TEXT: Analyse online
LINK: https://www.afrobarometer.org/online-data-analysis/

TEXT: Survey resources and data
LINK: https://www.afrobarometer.org/surveys-and-methods/survey-resources/

TEXT: Data
LINK: https://www.afrobarometer.org/data/

TEXT: Data sets
LINK: https://www.afrobarometer.org/data/data-sets/

TEXT: Merged data
LINK: https://www.afrobarometer.org/data/merged-data/

TEXT: Codebooks
LINK: https://www.afrobarometer.org/data/codebooks/

TEXT: Survey resources and data
LINK: https://www.afrobarometer.org/surveys-and-methods/survey-resources/

TEXT: Data
LINK: https://www.afrobarometer.org/data/

TEXT: Data sets
LINK: https://www.afrobarometer.org/data/data-sets/

TEXT: Merged data
LINK: https://www.afrobarometer.org/data/merged-data/

TEXT: Codebooks
LINK: https://www.afrobarometer.org/data/codebooks/

TEXT: Analyse online
LINK: https://www.afrobarometer.org/online-data-analysis/

In [11]:
DATASETS_URL = "https://www.afrobarometer.org/data/data-sets/"

datasets_response = requests.get(
    DATASETS_URL,
    timeout=30
)

print("Status code:", datasets_response.status_code)
print("Page size:", len(datasets_response.text), "characters")

Status code: 200
Page size: 108341 characters

In [12]:
datasets_soup = BeautifulSoup(datasets_response.text, "html.parser")

print("PAGE TITLE:")
print(datasets_soup.title.get_text(strip=True))

print("\nHEADINGS:")

for heading in datasets_soup.find_all(["h1", "h2", "h3"]):
    text = heading.get_text(" ", strip=True)
    if text:
        print("-", text)

PAGE TITLE:
Data sets – Afrobarometer

HEADINGS:
- Data sets
- Mauritania Round 10 data (2025)
- Togo Round 10 data (2025)
- São Tomé and Príncipe Round 10 data (2024)
- Mali Round 10 data (2024)
- Madagascar Round 10 data (2024)
- Zimbabwe Round 10 data (2024)
- Zambia Round 10 data (2024)
- Tanzania Round 10 data (2024)
- Nigeria Round 10 data (2024)
- Malawi Round 10 data (2024)
- Request data

In [13]:
page_text = datasets_soup.get_text(" ", strip=True)

print("South Africa" in page_text)
print("2024" in page_text)
print("Round 10" in page_text)

True
True
True

In [14]:
for i, text in enumerate(datasets_soup.stripped_strings):
    if "South Africa" in text:
        print(f"[{i}] {text}")

[103] South Africa

In [15]:
elements = list(datasets_soup.stripped_strings)

for i in range(98, 108):
    print(f"[{i}] {elements[i]}")

[98] Nigeria
[99] São Tomé and Principe
[100] Senegal
[101] Seychelles
[102] Sierra Leone
[103] South Africa
[104] Sudan
[105] Tanzania
[106] The Gambia
[107] Togo

In [16]:
for link in datasets_soup.find_all("a"):
    text = link.get_text(" ", strip=True)

    if text == "South Africa":
        print("Text:", text)
        print("Link:", link.get("href"))

In [17]:
afrobarometer_data = pd.DataFrame([
    {
        "year": 2024,
        "indicator": "Unemployment",
        "group": "All respondents",
        "value": 71,
        "unit": "percent"
    },
    {
        "year": 2024,
        "indicator": "Inflation/cost of living",
        "group": "All respondents",
        "value": 21,
        "unit": "percent"
    },
    {
        "year": 2024,
        "indicator": "Poverty",
        "group": "All respondents",
        "value": 21,
        "unit": "percent"
    },
    {
        "year": 2024,
        "indicator": "Economic management",
        "group": "All respondents",
        "value": 20,
        "unit": "percent"
    },
    {
        "year": 2015,
        "indicator": "Poor economic conditions",
        "group": "All respondents",
        "value": 58,
        "unit": "percent"
    },
    {
        "year": 2024,
        "indicator": "Poor economic conditions",
        "group": "All respondents",
        "value": 79,
        "unit": "percent"
    },
    {
        "year": 2024,
        "indicator": "Unemployment",
        "group": "Age 18-35",
        "value": 77,
        "unit": "percent"
    },
    {
        "year": 2024,
        "indicator": "Unemployment",
        "group": "Age over 55",
        "value": 66,
        "unit": "percent"
    },
    {
        "year": 2024,
        "indicator": "Water supply",
        "group": "Village residents",
        "value": 30,
        "unit": "percent"
    },
    {
        "year": 2024,
        "indicator": "Water supply",
        "group": "Urban residents",
        "value": 9,
        "unit": "percent"
    },
    {
        "year": 2024,
        "indicator": "Registered to vote",
        "group": "All respondents",
        "value": 86,
        "unit": "percent"
    },
    {
        "year": 2024,
        "indicator": "Likely to vote",
        "group": "Registered respondents",
        "value": 88,
        "unit": "percent"
    },
    {
        "year": 2024,
        "indicator": "Party policies influence voting",
        "group": "Registered voters",
        "value": 66,
        "unit": "percent"
    }
])

print("Rows:", len(afrobarometer_data))
print("Columns:", list(afrobarometer_data.columns))
afrobarometer_data

Rows: 13
Columns: ['year', 'indicator', 'group', 'value', 'unit']

,year,indicator,group,value,unit
0,2024,Unemployment,All respondents,71,percent
1,2024,Inflation/cost of living,All respondents,21,percent
2,2024,Poverty,All respondents,21,percent
3,2024,Economic management,All respondents,20,percent
4,2015,Poor economic conditions,All respondents,58,percent
5,2024,Poor economic conditions,All respondents,79,percent
6,2024,Unemployment,Age 18-35,77,percent
7,2024,Unemployment,Age over 55,66,percent
8,2024,Water supply,Village residents,30,percent
9,2024,Water supply,Urban residents,9,percent
10,2024,Registered to vote,All respondents,86,percent
11,2024,Likely to vote,Registered respondents,88,percent
12,2024,Party policies influence voting,Registered voters,66,percent

In [18]:
print("Number of records:", len(afrobarometer_data))

print("\nMissing values:")
print(afrobarometer_data.isna().sum())

print("\nYears:")
print(sorted(afrobarometer_data["year"].unique()))

print("\nPercentage range:")
print(
    afrobarometer_data["value"].min(),
    "to",
    afrobarometer_data["value"].max()
)

print("\nDuplicate records:")
print(afrobarometer_data.duplicated().sum())

Number of records: 13

Missing values:
year         0
indicator    0
group        0
value        0
unit         0
dtype: int64

Years:
[np.int64(2015), np.int64(2024)]

Percentage range:
9 to 88

Duplicate records:
0

In [19]:
AFROBAROMETER_DATA_FILE = (
    AFROBAROMETER_PROCESSED_DIR
    / "south_africa_2024_survey_indicators.csv"
)

AFROBAROMETER_RAW_FILE = (
    AFROBAROMETER_RAW_DIR
    / "south_africa_2024_election_article.html"
)

afrobarometer_data.to_csv(
    AFROBAROMETER_DATA_FILE,
    index=False
)

AFROBAROMETER_RAW_FILE.write_text(
    response.text,
    encoding="utf-8"
)

print("Processed dataset saved to:")
print(AFROBAROMETER_DATA_FILE)

print("\nRaw webpage saved to:")
print(AFROBAROMETER_RAW_FILE)

Processed dataset saved to:
c:\Users\Admin\Desktop\Dirisa_1\SPU-TEAM-DIRISA\data\processed\afrobarometer\south_africa_2024_survey_indicators.csv

Raw webpage saved to:
c:\Users\Admin\Desktop\Dirisa_1\SPU-TEAM-DIRISA\data\raw\afrobarometer\south_africa_2024_election_article.html

In [20]:
saved_afrobarometer_data = pd.read_csv(AFROBAROMETER_DATA_FILE)

print("Saved file shape:", saved_afrobarometer_data.shape)
print("Saved columns:", list(saved_afrobarometer_data.columns))
print("Missing values:", saved_afrobarometer_data.isna().sum().sum())
print("Duplicate rows:", saved_afrobarometer_data.duplicated().sum())

print("\nSaved dataset:")
display(saved_afrobarometer_data)

Saved file shape: (13, 5)
Saved columns: ['year', 'indicator', 'group', 'value', 'unit']
Missing values: 0
Duplicate rows: 0

Saved dataset:

,year,indicator,group,value,unit
0,2024,Unemployment,All respondents,71,percent
1,2024,Inflation/cost of living,All respondents,21,percent
2,2024,Poverty,All respondents,21,percent
3,2024,Economic management,All respondents,20,percent
4,2015,Poor economic conditions,All respondents,58,percent
5,2024,Poor economic conditions,All respondents,79,percent
6,2024,Unemployment,Age 18-35,77,percent
7,2024,Unemployment,Age over 55,66,percent
8,2024,Water supply,Village residents,30,percent
9,2024,Water supply,Urban residents,9,percent
10,2024,Registered to vote,All respondents,86,percent
11,2024,Likely to vote,Registered respondents,88,percent
12,2024,Party policies influence voting,Registered voters,66,percent

In [21]:
pd.testing.assert_frame_equal(
    afrobarometer_data,
    saved_afrobarometer_data,
    check_dtype=False
)

print("Verification successful: saved dataset matches the original dataset.")

Verification successful: saved dataset matches the original dataset.

In [22]:
from pathlib import Path

AFROBAROMETER_SAV_FILE = (
    AFROBAROMETER_RAW_DIR
    / "SAF_R9.data_.final_.wtd_release.30May23.sav"
)

print("File path:")
print(AFROBAROMETER_SAV_FILE)

print("\nFile exists:", AFROBAROMETER_SAV_FILE.exists())

if AFROBAROMETER_SAV_FILE.exists():
    print("File size:", round(AFROBAROMETER_SAV_FILE.stat().st_size / (1024**2), 2), "MB")

File path:
c:\Users\Admin\Desktop\Dirisa_1\SPU-TEAM-DIRISA\data\raw\afrobarometer\SAF_R9.data_.final_.wtd_release.30May23.sav

File exists: True
File size: 1.53 MB

In [24]:
%pip install pyreadstat

Defaulting to user installation because normal site-packages is not writeable
Collecting pyreadstat
  Downloading pyreadstat-1.3.6-cp313-cp313-win_amd64.whl.metadata (1.3 kB)
Collecting narwhals>=2.10.1 (from pyreadstat)
  Downloading narwhals-2.26.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy in C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages (from pyreadstat) (2.3.3)
Downloading pyreadstat-1.3.6-cp313-cp313-win_amd64.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.0 MB ? eta -:--:--
   --------------- ------------------------ 0.8/2.0 MB 1.7 MB/s eta 0:00:01
   ------------------------------ --------- 1.6/2.0 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 2.0/2.0 MB 2.5 MB/s  0:00:01
Downloading narwhals-2.26.0-py3-none-any.whl (474 kB)
Installing collected packages: narwhals, pyreadstat

   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   -------------------- ------------------- 1/2 [pyreadstat]
   ---------------------------------------- 2/2 [pyreadstat]

Successfully installed narwhals-2.26.0 pyreadstat-1.3.6
Note: you may need to restart the kernel to use updated packages.

In [25]:
import pyreadstat

print("pyreadstat is ready.")

pyreadstat is ready.

In [26]:
import pyreadstat

sav_data, sav_metadata = pyreadstat.read_sav(
    AFROBAROMETER_SAV_FILE
)

print("Rows:", sav_data.shape[0])
print("Columns:", sav_data.shape[1])
print("Successfully loaded the SPSS dataset.")

Rows: 1580
Columns: 390
Successfully loaded the SPSS dataset.

In [27]:
print("Number of variables:", len(sav_metadata.column_names))

print("\nFirst 50 variables:")
for name, label in zip(
    sav_metadata.column_names[:50],
    sav_metadata.column_labels[:50]
):
    print(f"{name}: {label}")

Number of variables: 390

First 50 variables:
RESPNO: Respondent number
URBRUR: Urban or Rural Primary Sampling Unit
REGION: Province or region
EA_SVC_A: EA-SVC-A. Electricity grid in the PSU/EA
EA_SVC_B: EA-SVC-B. Piped water system in the PSU/EA
EA_SVC_C: EA-SVC-C. Sewage system in the PSU/EA
EA_SVC_D: EA-SVC-D. Mobile phone service in the PSU/EA
EA_SVC_E: EA-SVC-E.  Borehole or tubewell in PSU/EA
EA_FAC_A: EA-FAC-A. Post office in the PSU/EA
EA_FAC_B: EA-FAC-B. School in the PSU/EA
EA_FAC_C: EA-FAC-C. Police station in the PSU/EA
EA_FAC_D: EA-FAC-D. Health Clinic in the PSU/EA
EA_FAC_E: EA-FAC-E. Market stalls in the PSU/EA
EA_FAC_F: EA-FAC-F. Bank or money services in the PSU/EA
EA_FAC_F2: EA-FAC-F2. Social/govt center/office in PSU/EA
EA_FAC_G: EA-FAC-G. Paid transport in the PSU/EA
EA_SEC_A: EA-SEC-A. Police in the PSU/EA
EA_SEC_B: EA-SEC-B. Soldiers/army in the PSU/EA
EA_SEC_C: EA-SEC-C. Roadblocks by police/army in the PSU/EA
EA_SEC_D: EA-SEC-D. Customs checkpoints in the PSU/EA
EA_SEC_E: EA-SEC-E. Roadblocks by private security/local community in the PSU/EA
EA_ROAD_A: EA-ROAD-A. Road surface at start point
EA_ROAD_B: EA-ROAD-B. Road surface last 5 km
EA_ROAD_C: EA-ROAD-C. Road condition last 5 km
NOCALL_1: Reason for Unsuccessful Call Household 1
NOCALL_1Other: Reason for Unsuccessful Call Household 1 (Verbatim)
NOCALL_2: Reason for Unsuccessful Call Household 2
NOCALL_3: Reason for Unsuccessful Call Household 3
NOCALL_4: Reason for Unsuccessful Call Household 4
NOCALL_5: Reason for Unsuccessful Call Household 5
NOCALL_6: Reason for Unsuccessful Call Household 6
NOCALL_7: Reason for Unsuccessful Call Household 7
NOCALL_8: Reason for Unsuccessful Call Household 8
NOCALL_9: Reason for Unsuccessful Call Household 9
NOCALL_10: Reason for Unsuccessful Call Household 10
NOCALL_11: Reason for Unsuccessful Call Household 11
NOCALL_11OTHER: Reason for Unsuccessful Call Household 11 (Verbatim)
NOCALL_12: Reason for Unsuccessful Call Household 12
NOCALL_12OTHER: Reason for Unsuccessful Call Household 12 (Verbatim)
THISINT: This interview, gender
ADULT_CT: Number of adults in household
CALLS: Number of calls
DATEINTR: Date of interview
STRTIME: Time interview started
Q1: Q1. Age
Q2: Q2. Language spoken in home
Q2OTHER: Q2other. Language spoken in home (verbatim)
Q3: Q3. Overall direction of the country
Q4A: Q4a. Country’s present economic condition
Q4B: Q4b. Your present living conditions

In [28]:
voting_variables = [
    (name, label)
    for name, label in zip(
        sav_metadata.column_names,
        sav_metadata.column_labels
    )
    if any(
        keyword in (name + " " + label).lower()
        for keyword in [
            "vote",
            "voting",
            "election",
            "registered",
            "registration",
            "political participation"
        ]
    )
]

print("Number of potentially relevant variables:", len(voting_variables))

for name, label in voting_variables:
    print(f"{name}: {label}")

Number of potentially relevant variables: 13
Q9C: Q9c. Freedom to choose who to vote for
Q12A: Q12a. Elections ensure MPs reflect views of voters
Q12B: Q12b. Elections ensure voters remove unrepresentative leaders
Q13: Q13. Voting in the most recent national election
Q14A: Q14a. Freeness and fairness of the last national election
Q14B: Q14b. How likely powerful find out your vote
Q14C: Q14c. Last national election: fear political intimidation or violence
Q19B: Q19b. Elected officials follow voter demands vs follow own ideas
Q23B_SAF: Q23b-saf. Willing to give up regular elections
Q24: Q24. Choose leaders through elections vs other methods
Q63C: Q63c. Postpone elections during pandemic
Q96: Q96. Vote for which party
Q96OTHER: Q96other. Vote for which party (verbatim)

In [29]:
print(sav_data["REGION"].value_counts(dropna=False))

REGION
702.0    391
703.0    248
708.0    196
700.0    163
704.0    148
705.0    119
706.0    108
701.0    104
707.0    103
Name: count, dtype: int64

In [30]:
region_labels = sav_metadata.variable_value_labels.get("REGION", {})

print("REGION value labels:")
for code, label in region_labels.items():
    print(code, "=", label)

REGION value labels:
700.0 = Eastern Cape
701.0 = Free State
702.0 = Gauteng
703.0 = KwaZulu-Natal
704.0 = Limpopo
705.0 = Mpumalanga
706.0 = North West
707.0 = Northern Cape
708.0 = Western Cape

In [31]:
kzn_data = sav_data[sav_data["REGION"] == 703.0].copy()

print("KZN rows:", kzn_data.shape[0])
print("KZN columns:", kzn_data.shape[1])

KZN rows: 248
KZN columns: 390

In [32]:
print("Q13 value counts:")
print(kzn_data["Q13"].value_counts(dropna=False))

print("\nQ13 labels:")
q13_labels = sav_metadata.variable_value_labels.get("Q13", {})

for code, label in q13_labels.items():
    print(code, "=", label)

Q13 value counts:
Q13
3.0    154
0.0     78
1.0     15
8.0      1
Name: count, dtype: int64

Q13 labels:
-1.0 = Missing
0.0 = I did not vote
1.0 = I was too young to vote
2.0 = I can’t remember whether I voted
3.0 = I voted in the election
8.0 = Refused
9.0 = Don’t Know

In [33]:
selected_variables = [
    "Q13",
    "Q9C",
    "Q12A",
    "Q12B",
    "Q14A",
    "Q14B",
    "Q14C",
    "Q19B",
    "Q24",
    "Q23B_SAF",
    "URBRUR",
    "Q3",
    "Q4A",
    "Q4B"
]

missing_variables = [
    variable for variable in selected_variables
    if variable not in kzn_data.columns
]

print("Selected variables:", len(selected_variables))
print("Missing variables:", missing_variables)

Selected variables: 14
Missing variables: []

In [34]:
kzn_voter_data = kzn_data[selected_variables].copy()

print("KZN voter dataset shape:", kzn_voter_data.shape)
print("\nFirst 5 rows:")
print(kzn_voter_data.head())

KZN voter dataset shape: (248, 14)

First 5 rows:
     Q13  Q9C  Q12A  Q12B  Q14A  Q14B  Q14C  Q19B  Q24  Q23B_SAF  URBRUR   Q3  \
540  3.0  2.0   0.0   0.0   1.0   9.0   1.0   4.0  4.0       1.0     1.0  1.0
541  0.0  4.0   0.0   0.0   1.0   3.0   3.0   5.0  1.0       1.0     1.0  1.0
542  0.0  4.0   2.0   2.0   9.0   9.0   3.0   4.0  1.0       1.0     1.0  1.0
543  3.0  4.0   1.0   3.0   2.0   2.0   1.0   1.0  4.0       1.0     1.0  1.0
547  3.0  1.0   0.0   9.0   2.0   0.0   3.0   3.0  2.0       9.0     2.0  2.0

     Q4A  Q4B
540  1.0  1.0
541  1.0  1.0
542  1.0  4.0
543  1.0  1.0
547  1.0  1.0

In [35]:
KZN_AFROBAROMETER_FILE = (
    AFROBAROMETER_PROCESSED_DIR
    / "kzn_afrobarometer_round9_voter_data.csv"
)

kzn_voter_data.to_csv(
    KZN_AFROBAROMETER_FILE,
    index=False
)

print("Saved successfully:")
print(KZN_AFROBAROMETER_FILE)
print("\nFile exists:", KZN_AFROBAROMETER_FILE.exists())

Saved successfully:
c:\Users\Admin\Desktop\Dirisa_1\SPU-TEAM-DIRISA\data\processed\afrobarometer\kzn_afrobarometer_round9_voter_data.csv

File exists: True

In [36]:
for variable in selected_variables:
    print("\n" + "=" * 70)
    print(variable)
    print("Question:", sav_metadata.column_names_to_labels.get(variable))

    labels = sav_metadata.variable_value_labels.get(variable, {})
    print("Response codes:")

    for code, label in labels.items():
        print(f"  {code} = {label}")

======================================================================
Q13
Question: Q13. Voting in the most recent national election
Response codes:
  -1.0 = Missing
  0.0 = I did not vote
  1.0 = I was too young to vote
  2.0 = I can’t remember whether I voted
  3.0 = I voted in the election
  8.0 = Refused
  9.0 = Don’t Know

======================================================================
Q9C
Question: Q9c. Freedom to choose who to vote for
Response codes:
  -1.0 = Missing
  1.0 = Not at all free
  2.0 = Not very free
  3.0 = Somewhat free
  4.0 = Completely free
  8.0 = Refused
  9.0 = Don’t know

======================================================================
Q12A
Question: Q12a. Elections ensure MPs reflect views of voters
Response codes:
  -1.0 = Missing
  0.0 = Not at all well
  1.0 = Not very well
  2.0 = Fairly well
  3.0 = Very well
  8.0 = Refused
  9.0 = Don’t know
  94.0 = Not asked in this country
  997.0 = Not applicable

======================================================================
Q12B
Question: Q12b. Elections ensure voters remove unrepresentative leaders
Response codes:
  -1.0 = Missing
  0.0 = Not at all well
  1.0 = Not very well
  2.0 = Fairly well
  3.0 = Very well
  8.0 = Refused
  9.0 = Don’t know
  94.0 = Not asked in this country
  997.0 = Not applicable

======================================================================
Q14A
Question: Q14a. Freeness and fairness of the last national election
Response codes:
  -1.0 = Missing
  1.0 = Not free and fair
  2.0 = Free and fair, with major problems
  3.0 = Free and fair, but with minor problems
  4.0 = Completely free and fair
  8.0 = Do not understand question
  9.0 = Don’t know
  98.0 = Refused

======================================================================
Q14B
Question: Q14b. How likely powerful find out your vote
Response codes:
  -1.0 = Missing
  0.0 = Not at all likely
  1.0 = Not very likely
  2.0 = Somewhat likely
  3.0 = Very likely
  8.0 = Refused
  9.0 = Don’t know

======================================================================
Q14C
Question: Q14c. Last national election: fear political intimidation or violence
Response codes:
  -1.0 = Missing
  0.0 = A lot
  1.0 = Somewhat
  2.0 = A little bit
  3.0 = Not at all
  8.0 = Refused
  9.0 = Don’t know

======================================================================
Q19B
Question: Q19b. Elected officials follow voter demands vs follow own ideas
Response codes:
  -1.0 = Missing
  1.0 = Agree very strongly with 1
  2.0 = Agree with 1
  3.0 = Agree with 2
  4.0 = Agree very strongly with 2
  5.0 = Agree with neither
  8.0 = Refused
  9.0 = Don't know
  94.0 = Not asked in this country
  997.0 = Not applicable

======================================================================
Q24
Question: Q24. Choose leaders through elections vs other methods
Response codes:
  -1.0 = Missing
  1.0 = Agree very strongly with 1
  2.0 = Agree with 1
  3.0 = Agree with 2
  4.0 = Agree very strongly with 2
  5.0 = Agree with neither
  8.0 = Refused
  9.0 = Don't know

======================================================================
Q23B_SAF
Question: Q23b-saf. Willing to give up regular elections
Response codes:
  -1.0 = Missing
  1.0 = Very willing
  2.0 = Willing
  3.0 = Unwilling
  4.0 = Very unwilling
  8.0 = Refused
  9.0 = Don’t know

======================================================================
URBRUR
Question: Urban or Rural Primary Sampling Unit
Response codes:
  1.0 = Urban
  2.0 = Rural

======================================================================
Q3
Question: Q3. Overall direction of the country
Response codes:
  -1.0 = Missing
  1.0 = Going in the wrong direction
  2.0 = Going in the right direction
  8.0 = Refused
  9.0 = Don't know

======================================================================
Q4A
Question: Q4a. Country’s present economic condition
Response codes:
  -1.0 = Missing
  1.0 = Very bad
  2.0 = Fairly bad
  3.0 = Neither good nor bad
  4.0 = Fairly good
  5.0 = Very good
  8.0 = Refused
  9.0 = Don't know

======================================================================
Q4B
Question: Q4b. Your present living conditions
Response codes:
  -1.0 = Missing
  1.0 = Very bad
  2.0 = Fairly bad
  3.0 = Neither good nor bad
  4.0 = Fairly good
  5.0 = Very good
  8.0 = Refused
  9.0 = Don't know

In [37]:
# Create a readable copy of the KZN dataset
kzn_readable_data = kzn_voter_data.copy()

# Rename columns using the official Afrobarometer question labels
readable_column_names = {
    variable: sav_metadata.column_names_to_labels.get(variable, variable)
    for variable in selected_variables
}

kzn_readable_data = kzn_readable_data.rename(
    columns=readable_column_names
)

# Convert the numerical response codes into their official labels
for variable in selected_variables:
    original_question = sav_metadata.column_names_to_labels.get(
        variable, variable
    )
    
    value_labels = sav_metadata.variable_value_labels.get(variable, {})
    
    if value_labels:
        kzn_readable_data[original_question] = (
            kzn_readable_data[original_question]
            .map(value_labels)
            .fillna(kzn_readable_data[original_question])
        )

print("Readable KZN dataset shape:", kzn_readable_data.shape)
print("\nColumns:")
for column in kzn_readable_data.columns:
    print("-", column)

Readable KZN dataset shape: (248, 14)

Columns:
- Q13. Voting in the most recent national election
- Q9c. Freedom to choose who to vote for
- Q12a. Elections ensure MPs reflect views of voters
- Q12b. Elections ensure voters remove unrepresentative leaders
- Q14a. Freeness and fairness of the last national election
- Q14b. How likely powerful find out your vote
- Q14c. Last national election: fear political intimidation or violence
- Q19b. Elected officials follow voter demands vs follow own ideas
- Q24. Choose leaders through elections vs other methods
- Q23b-saf. Willing to give up regular elections
- Urban or Rural Primary Sampling Unit
- Q3. Overall direction of the country
- Q4a. Country’s present economic condition
- Q4b. Your present living conditions

In [38]:
print(kzn_readable_data.head())

    Q13. Voting in the most recent national election  \
540                          I voted in the election
541                                   I did not vote
542                                   I did not vote
543                          I voted in the election
547                          I voted in the election

    Q9c. Freedom to choose who to vote for  \
540                          Not very free
541                        Completely free
542                        Completely free
543                        Completely free
547                        Not at all free

    Q12a. Elections ensure MPs reflect views of voters  \
540                                    Not at all well
541                                    Not at all well
542                                        Fairly well
543                                      Not very well
547                                    Not at all well

    Q12b. Elections ensure voters remove unrepresentative leaders  \
540                                    Not at all well
541                                    Not at all well
542                                        Fairly well
543                                          Very well
547                                         Don’t know

    Q14a. Freeness and fairness of the last national election  \
540                                  Not free and fair
541                                  Not free and fair
542                                         Don’t know
543                 Free and fair, with major problems
547                 Free and fair, with major problems

    Q14b. How likely powerful find out your vote  \
540                                   Don’t know
541                                  Very likely
542                                   Don’t know
543                              Somewhat likely
547                            Not at all likely

    Q14c. Last national election: fear political intimidation or violence  \
540                                           Somewhat
541                                         Not at all
542                                         Not at all
543                                           Somewhat
547                                         Not at all

    Q19b. Elected officials follow voter demands vs follow own ideas  \
540                         Agree very strongly with 2
541                                 Agree with neither
542                         Agree very strongly with 2
543                         Agree very strongly with 1
547                                       Agree with 2

    Q24. Choose leaders through elections vs other methods  \
540                         Agree very strongly with 2
541                         Agree very strongly with 1
542                         Agree very strongly with 1
543                         Agree very strongly with 2
547                                       Agree with 1

    Q23b-saf. Willing to give up regular elections  \
540                                   Very willing
541                                   Very willing
542                                   Very willing
543                                   Very willing
547                                     Don’t know

    Urban or Rural Primary Sampling Unit Q3. Overall direction of the country  \
540                                Urban         Going in the wrong direction
541                                Urban         Going in the wrong direction
542                                Urban         Going in the wrong direction
543                                Urban         Going in the wrong direction
547                                Rural         Going in the right direction

    Q4a. Country’s present economic condition  \
540                                  Very bad
541                                  Very bad
542                                  Very bad
543                                  Very bad
547                                  Very bad

    Q4b. Your present living conditions
540                            Very bad
541                            Very bad
542                         Fairly good
543                            Very bad
547                            Very bad

In [39]:
print(kzn_readable_data.head())

    Q13. Voting in the most recent national election  \
540                          I voted in the election
541                                   I did not vote
542                                   I did not vote
543                          I voted in the election
547                          I voted in the election

    Q9c. Freedom to choose who to vote for  \
540                          Not very free
541                        Completely free
542                        Completely free
543                        Completely free
547                        Not at all free

    Q12a. Elections ensure MPs reflect views of voters  \
540                                    Not at all well
541                                    Not at all well
542                                        Fairly well
543                                      Not very well
547                                    Not at all well

    Q12b. Elections ensure voters remove unrepresentative leaders  \
540                                    Not at all well
541                                    Not at all well
542                                        Fairly well
543                                          Very well
547                                         Don’t know

    Q14a. Freeness and fairness of the last national election  \
540                                  Not free and fair
541                                  Not free and fair
542                                         Don’t know
543                 Free and fair, with major problems
547                 Free and fair, with major problems

    Q14b. How likely powerful find out your vote  \
540                                   Don’t know
541                                  Very likely
542                                   Don’t know
543                              Somewhat likely
547                            Not at all likely

    Q14c. Last national election: fear political intimidation or violence  \
540                                           Somewhat
541                                         Not at all
542                                         Not at all
543                                           Somewhat
547                                         Not at all

    Q19b. Elected officials follow voter demands vs follow own ideas  \
540                         Agree very strongly with 2
541                                 Agree with neither
542                         Agree very strongly with 2
543                         Agree very strongly with 1
547                                       Agree with 2

    Q24. Choose leaders through elections vs other methods  \
540                         Agree very strongly with 2
541                         Agree very strongly with 1
542                         Agree very strongly with 1
543                         Agree very strongly with 2
547                                       Agree with 1

    Q23b-saf. Willing to give up regular elections  \
540                                   Very willing
541                                   Very willing
542                                   Very willing
543                                   Very willing
547                                     Don’t know

    Urban or Rural Primary Sampling Unit Q3. Overall direction of the country  \
540                                Urban         Going in the wrong direction
541                                Urban         Going in the wrong direction
542                                Urban         Going in the wrong direction
543                                Urban         Going in the wrong direction
547                                Rural         Going in the right direction

    Q4a. Country’s present economic condition  \
540                                  Very bad
541                                  Very bad
542                                  Very bad
543                                  Very bad
547                                  Very bad

    Q4b. Your present living conditions
540                            Very bad
541                            Very bad
542                         Fairly good
543                            Very bad
547                            Very bad

In [40]:
KZN_READABLE_FILE = (
    AFROBAROMETER_PROCESSED_DIR
    / "kzn_afrobarometer_round9_readable_voter_data.csv"
)

kzn_readable_data.to_csv(
    KZN_READABLE_FILE,
    index=False
)

print("Saved successfully:")
print(KZN_READABLE_FILE)
print("\nFile exists:", KZN_READABLE_FILE.exists())

Saved successfully:
c:\Users\Admin\Desktop\Dirisa_1\SPU-TEAM-DIRISA\data\processed\afrobarometer\kzn_afrobarometer_round9_readable_voter_data.csv

File exists: True

In [41]:
# Fix encoding issues in the readable Afrobarometer dataset

for column in kzn_readable_data.columns:
    if kzn_readable_data[column].dtype == "object":
        kzn_readable_data[column] = (
            kzn_readable_data[column]
            .astype(str)
            .str.replace("â€™", "'", regex=False)
            .str.replace("â€˜", "'", regex=False)
            .str.replace("â€œ", '"', regex=False)
            .str.replace("â€", '"', regex=False)
        )

# Save the corrected readable dataset
kzn_readable_data.to_csv(
    AFROBAROMETER_PROCESSED_DIR / "kzn_afrobarometer_round9_readable_voter_data.csv",
    index=False,
    encoding="utf-8"
)

print("Encoding issues fixed and dataset saved.")

PermissionError: [Errno 13] Permission denied: 'c:\\Users\\Admin\\Desktop\\Dirisa_1\\SPU-TEAM-DIRISA\\data\\processed\\afrobarometer\\kzn_afrobarometer_round9_readable_voter_data.csv'

In [42]:
kzn_readable_data.to_csv(
    AFROBAROMETER_PROCESSED_DIR / "kzn_afrobarometer_round9_readable_voter_data.csv",
    index=False,
    encoding="utf-8"
)

print("Corrected readable dataset saved successfully.")

PermissionError: [Errno 13] Permission denied: 'c:\\Users\\Admin\\Desktop\\Dirisa_1\\SPU-TEAM-DIRISA\\data\\processed\\afrobarometer\\kzn_afrobarometer_round9_readable_voter_data.csv'

In [43]:
corrected_file = (
    AFROBAROMETER_PROCESSED_DIR
    / "kzn_afrobarometer_round9_readable_voter_data_fixed.csv"
)

kzn_readable_data.to_csv(
    corrected_file,
    index=False,
    encoding="utf-8"
)

print("Saved successfully:")
print(corrected_file)

Saved successfully:
c:\Users\Admin\Desktop\Dirisa_1\SPU-TEAM-DIRISA\data\processed\afrobarometer\kzn_afrobarometer_round9_readable_voter_data_fixed.csv

In [44]:
print("File exists:", corrected_file.exists())
print("File path:", corrected_file)

# Check for bad encoding
bad_encoding = kzn_readable_data.astype(str).apply(
    lambda column: column.str.contains(
        "â€™|â€˜|â€œ|â€",
        regex=True
    )
).any().any()

print("Bad encoding still present:", bad_encoding)

File exists: True
File path: c:\Users\Admin\Desktop\Dirisa_1\SPU-TEAM-DIRISA\data\processed\afrobarometer\kzn_afrobarometer_round9_readable_voter_data_fixed.csv
Bad encoding still present: False

In [45]:
# Read the corrected CSV back into Python
kzn_final_check = pd.read_csv(corrected_file, encoding="utf-8")

print("Rows:", kzn_final_check.shape[0])
print("Columns:", kzn_final_check.shape[1])

print("\nFirst 5 rows:")
display(kzn_final_check.head())

Rows: 248
Columns: 14

First 5 rows:

,Q13. Voting in the most recent national election,Q9c. Freedom to choose who to vote for,Q12a. Elections ensure MPs reflect views of voters,Q12b. Elections ensure voters remove unrepresentative leaders,Q14a. Freeness and fairness of the last national election,Q14b. How likely powerful find out your vote,Q14c. Last national election: fear political intimidation or violence,Q19b. Elected officials follow voter demands vs follow own ideas,Q24. Choose leaders through elections vs other methods,Q23b-saf. Willing to give up regular elections,Urban or Rural Primary Sampling Unit,Q3. Overall direction of the country,Q4a. Country’s present economic condition,Q4b. Your present living conditions
0,I voted in the election,Not very free,Not at all well,Not at all well,Not free and fair,Don’t know,Somewhat,Agree very strongly with 2,Agree very strongly with 2,Very willing,Urban,Going in the wrong direction,Very bad,Very bad
1,I did not vote,Completely free,Not at all well,Not at all well,Not free and fair,Very likely,Not at all,Agree with neither,Agree very strongly with 1,Very willing,Urban,Going in the wrong direction,Very bad,Very bad
2,I did not vote,Completely free,Fairly well,Fairly well,Don’t know,Don’t know,Not at all,Agree very strongly with 2,Agree very strongly with 1,Very willing,Urban,Going in the wrong direction,Very bad,Fairly good
3,I voted in the election,Completely free,Not very well,Very well,"Free and fair, with major problems",Somewhat likely,Somewhat,Agree very strongly with 1,Agree very strongly with 2,Very willing,Urban,Going in the wrong direction,Very bad,Very bad
4,I voted in the election,Not at all free,Not at all well,Don’t know,"Free and fair, with major problems",Not at all likely,Not at all,Agree with 2,Agree with 1,Don’t know,Rural,Going in the right direction,Very bad,Very bad