In [1]:
#1. — Setup: Province Context Panel
# Purpose:
# Set up the notebook and define the KZN province-context input
# and processed-output locations.

from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path(
    r"C:\Users\Student\Downloads\Big Data\SPU-TEAM-DIRISA"
)

CONTEXT_INPUT_DIR = (
    PROJECT_ROOT
    / "data"
    / "interim"
    / "KZN-Socioeconomic-Political-Distrust-2011-2023 Cleaned"
)

QLFS_INPUT_DIR = (
    PROJECT_ROOT
    / "data"
    / "interim"
    / "KZN_Electoral_participation Cleaned"
)

CONTEXT_OUTPUT_DIR = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "02_province_context_panel"
)

CONTEXT_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

CONTEXT_FILES = {
    "youth_distrust": (
        CONTEXT_INPUT_DIR
        / "KZN_IEC_HSRC_Youth_Distrust_2023_long_clean.csv"
    ),
    "socioeconomic": (
        CONTEXT_INPUT_DIR
        / "KZN_StatsSA_Socioeconomic_Indicators_2011_2023_clean.csv"
    ),
    "qlfs_q1_2024": (
        QLFS_INPUT_DIR
        / "P02111stQuarter2024_clean.csv"
    ),
    "qlfs_2024": (
        QLFS_INPUT_DIR
        / "P03182024_clean.csv"
    ),
    "qlfs_q1_2026": (
        QLFS_INPUT_DIR
        / "Presentation-QLFS-Q1-2026_clean.csv"
    ),
}

CONTEXT_OUTPUT = (
    CONTEXT_OUTPUT_DIR
    / "province_context_panel_2011_2023.csv"
)

print("Setup completed successfully.")
print(f"Project root: {PROJECT_ROOT}")
print(f"Context input directory: {CONTEXT_INPUT_DIR}")
print(f"QLFS input directory: {QLFS_INPUT_DIR}")
print(f"Output directory: {CONTEXT_OUTPUT_DIR}")
print()

for name, file_path in CONTEXT_FILES.items():
    print(f"{name}: {file_path}")

print()
print(f"Output file: {CONTEXT_OUTPUT}")

assert PROJECT_ROOT.exists(), "Project root does not exist."
assert CONTEXT_INPUT_DIR.exists(), "Context input directory does not exist."
assert QLFS_INPUT_DIR.exists(), "QLFS input directory does not exist."

for name, file_path in CONTEXT_FILES.items():
    assert file_path.exists(), f"{name} file not found."

print()
print("Path verification: PASSED")

Setup completed successfully.
Project root: C:\Users\Student\Downloads\Big Data\SPU-TEAM-DIRISA
Context input directory: C:\Users\Student\Downloads\Big Data\SPU-TEAM-DIRISA\data\interim\KZN-Socioeconomic-Political-Distrust-2011-2023 Cleaned
QLFS input directory: C:\Users\Student\Downloads\Big Data\SPU-TEAM-DIRISA\data\interim\KZN_Electoral_participation Cleaned
Output directory: C:\Users\Student\Downloads\Big Data\SPU-TEAM-DIRISA\data\processed\02_province_context_panel

youth_distrust: C:\Users\Student\Downloads\Big Data\SPU-TEAM-DIRISA\data\interim\KZN-Socioeconomic-Political-Distrust-2011-2023 Cleaned\KZN_IEC_HSRC_Youth_Distrust_2023_long_clean.csv
socioeconomic: C:\Users\Student\Downloads\Big Data\SPU-TEAM-DIRISA\data\interim\KZN-Socioeconomic-Political-Distrust-2011-2023 Cleaned\KZN_StatsSA_Socioeconomic_Indicators_2011_2023_clean.csv
qlfs_q1_2024: C:\Users\Student\Downloads\Big Data\SPU-TEAM-DIRISA\data\interim\KZN_Electoral_participation Cleaned\P02111stQuarter2024_clean.csv
qlfs_2024: C:\Users\Student\Downloads\Big Data\SPU-TEAM-DIRISA\data\interim\KZN_Electoral_participation Cleaned\P03182024_clean.csv
qlfs_q1_2026: C:\Users\Student\Downloads\Big Data\SPU-TEAM-DIRISA\data\interim\KZN_Electoral_participation Cleaned\Presentation-QLFS-Q1-2026_clean.csv

Output file: C:\Users\Student\Downloads\Big Data\SPU-TEAM-DIRISA\data\processed\02_province_context_panel\province_context_panel_2011_2023.csv

Path verification: PASSED

In [2]:
#2. — Load and Inspect Province Context Data
# Purpose:
# Load the socioeconomic, youth distrust and QLFS datasets so we can
# confirm their structure before building the province context panel.

context_data = {}

for name, file_path in CONTEXT_FILES.items():
    df = pd.read_csv(file_path)
    context_data[name] = df

    print(f"{name} dataset loaded successfully.")
    print(f"Rows: {len(df):,}")
    print(f"Columns: {len(df.columns)}")
    print(f"Columns: {df.columns.tolist()}")
    print()

assert set(context_data.keys()) == set(CONTEXT_FILES.keys())

print("All province context datasets loaded successfully.")
print("Datasets available:", sorted(context_data.keys()))

youth_distrust dataset loaded successfully.
Rows: 5
Columns: 6
Columns: ['geography', 'year', 'indicator', 'value', 'unit', 'source']

socioeconomic dataset loaded successfully.
Rows: 30
Columns: 7
Columns: ['geography_level', 'geography_name', 'indicator', 'year', 'value', 'unit', 'source']

qlfs_q1_2024 dataset loaded successfully.
Rows: 30
Columns: 11
Columns: ['Geography', 'Metric', 'Q1_2023', 'Q2_2023', 'Q3_2023', 'Q4_2023', 'Q1_2024', 'Qtr_to_qtr_change', 'Year_on_year_change', 'Qtr_to_qtr_percent', 'Year_on_year_percent']

qlfs_2024 dataset loaded successfully.
Rows: 8
Columns: 4
Columns: ['Province', 'Institution_type', 'Percentage', 'Total_attending_thousand']

qlfs_q1_2026 dataset loaded successfully.
Rows: 2
Columns: 5
Columns: ['Geography', 'Period', 'Indicator', 'Value_percent', 'Change_from_previous_quarter_percentage_points']

All province context datasets loaded successfully.
Datasets available: ['qlfs_2024', 'qlfs_q1_2024', 'qlfs_q1_2026', 'socioeconomic', 'youth_distrust']

In [3]:
#2. — Load and Inspect Province Context Data
# Purpose:
# Load the socioeconomic, youth distrust and QLFS datasets so we can
# confirm their structure before building the province context panel.

context_data = {}

for name, file_path in CONTEXT_FILES.items():
    df = pd.read_csv(file_path)
    context_data[name] = df

    print(f"{name} dataset loaded successfully.")
    print(f"Rows: {len(df):,}")
    print(f"Columns: {len(df.columns)}")
    print(f"Columns: {df.columns.tolist()}")
    print()

assert set(context_data.keys()) == set(CONTEXT_FILES.keys())

print("All province context datasets loaded successfully.")
print("Datasets available:", sorted(context_data.keys()))

youth_distrust dataset loaded successfully.
Rows: 5
Columns: 6
Columns: ['geography', 'year', 'indicator', 'value', 'unit', 'source']

socioeconomic dataset loaded successfully.
Rows: 30
Columns: 7
Columns: ['geography_level', 'geography_name', 'indicator', 'year', 'value', 'unit', 'source']

qlfs_q1_2024 dataset loaded successfully.
Rows: 30
Columns: 11
Columns: ['Geography', 'Metric', 'Q1_2023', 'Q2_2023', 'Q3_2023', 'Q4_2023', 'Q1_2024', 'Qtr_to_qtr_change', 'Year_on_year_change', 'Qtr_to_qtr_percent', 'Year_on_year_percent']

qlfs_2024 dataset loaded successfully.
Rows: 8
Columns: 4
Columns: ['Province', 'Institution_type', 'Percentage', 'Total_attending_thousand']

qlfs_q1_2026 dataset loaded successfully.
Rows: 2
Columns: 5
Columns: ['Geography', 'Period', 'Indicator', 'Value_percent', 'Change_from_previous_quarter_percentage_points']

All province context datasets loaded successfully.
Datasets available: ['qlfs_2024', 'qlfs_q1_2024', 'qlfs_q1_2026', 'socioeconomic', 'youth_distrust']

In [4]:
#3. — Inspect Province Context Values
# Purpose:
# Inspect the actual geography, year and indicator values so we can
# identify which records can safely contribute to the KZN context panel.

for name, df in context_data.items():

    print("=" * 70)
    print(name.upper())
    print("=" * 70)

    if name == "youth_distrust":
        print("Geography values:")
        print(df["geography"].unique())
        print()
        print("Years:")
        print(df["year"].unique())
        print()
        print("Indicators:")
        print(df["indicator"].unique())

    elif name == "socioeconomic":
        print("Geography levels:")
        print(df["geography_level"].unique())
        print()
        print("Geography names:")
        print(df["geography_name"].unique())
        print()
        print("Years:")
        print(sorted(df["year"].dropna().unique()))
        print()
        print("Indicators:")
        print(df["indicator"].unique())

    elif name == "qlfs_q1_2024":
        print("Geographies:")
        print(df["Geography"].unique())
        print()
        print("Metrics:")
        print(df["Metric"].unique())
        print()

    elif name == "qlfs_2024":
        print("Provinces:")
        print(df["Province"].unique())
        print()
        print("Institution types:")
        print(df["Institution_type"].unique())
        print()

    elif name == "qlfs_q1_2026":
        print("Geographies:")
        print(df["Geography"].unique())
        print()
        print("Periods:")
        print(df["Period"].unique())
        print()
        print("Indicators:")
        print(df["Indicator"].unique())

    print()

======================================================================
YOUTH_DISTRUST
======================================================================
Geography values:
['KwaZulu-Natal']

Years:
[2023]

Indicators:
['Dissatisfied with democracy' 'Distrust of national government'
 'Distrust of provincial government' 'Distrust of political parties'
 'Distrust of the IEC']

======================================================================
SOCIOECONOMIC
======================================================================
Geography levels:
['Province' 'Metro']

Geography names:
['KwaZulu-Natal' 'eThekwini Metropolitan']

Years:
[np.int64(2011), np.int64(2015), np.int64(2023)]

Indicators:
['Poverty headcount (P0, %)' 'Poverty gap (P1, %)'
 'Severity of poverty (P2, %)' 'Poverty share (%)'
 'Food poverty headcount (FPL, %)' 'Gini coefficient (income per capita)']

======================================================================
QLFS_Q1_2024
======================================================================
Geographies:
['KwaZulu-Natal' 'KwaZulu-Natal – Non-metro' 'KwaZulu-Natal – eThekwini']

Metrics:
['Population 15–64 yrs' 'Labour force' 'Employed' 'Unemployed'
 'Not economically active' 'Discouraged work-seekers'
 'Other (not economically active)' 'Unemployment rate'
 'Employed/population ratio (absorption)'
 'Labour force participation rate']


======================================================================
QLFS_2024
======================================================================
Provinces:
['KwaZulu-Natal']

Institution types:
['Pre-school' 'School' 'Higher education institutions' 'TVET'
 'Other colleges' 'Home Schooling' 'Other' 'Total']


======================================================================
QLFS_Q1_2026
======================================================================
Geographies:
['South Africa']

Periods:
['Q1:2026']

Indicators:
['Labour force participation rate' 'Absorption rate']

In [5]:
#4. — Inspect Usable KZN Records
# Purpose:
# Inspect the KZN province records that may enter the context panel
# before deciding how each dataset should be matched by year.

youth_df = context_data["youth_distrust"]
socioeconomic_df = context_data["socioeconomic"]
qlfs_q1_2024_df = context_data["qlfs_q1_2024"]
qlfs_2024_df = context_data["qlfs_2024"]
qlfs_q1_2026_df = context_data["qlfs_q1_2026"]

print("=" * 70)
print("YOUTH DISTRUST — KZN 2023")
print("=" * 70)
display(youth_df)

print()
print("=" * 70)
print("SOCIOECONOMIC — KZN PROVINCE ONLY")
print("=" * 70)

kzn_socioeconomic = socioeconomic_df[
    socioeconomic_df["geography_name"] == "KwaZulu-Natal"
].copy()

display(kzn_socioeconomic)

print()
print("=" * 70)
print("QLFS Q1 2024 — KZN PROVINCE ONLY")
print("=" * 70)

kzn_qlfs_q1_2024 = qlfs_q1_2024_df[
    qlfs_q1_2024_df["Geography"] == "KwaZulu-Natal"
].copy()

display(kzn_qlfs_q1_2024)

print()
print("=" * 70)
print("QLFS 2024 — KZN")
print("=" * 70)

display(qlfs_2024_df)

print()
print("=" * 70)
print("QLFS Q1 2026 — NATIONAL DATA")
print("=" * 70)

display(qlfs_q1_2026_df)

print()
print("KZN province-record inspection completed.")

======================================================================
YOUTH DISTRUST — KZN 2023
======================================================================

,geography,year,indicator,value,unit,source
0,KwaZulu-Natal,2023,Dissatisfied with democracy,85.0,%,"IEC/HSRC Online Youth Survey 2023 (n=5,086, ag..."
1,KwaZulu-Natal,2023,Distrust of national government,83.0,%,"IEC/HSRC Online Youth Survey 2023 (n=5,086, ag..."
2,KwaZulu-Natal,2023,Distrust of provincial government,80.0,%,"IEC/HSRC Online Youth Survey 2023 (n=5,086, ag..."
3,KwaZulu-Natal,2023,Distrust of political parties,77.0,%,"IEC/HSRC Online Youth Survey 2023 (n=5,086, ag..."
4,KwaZulu-Natal,2023,Distrust of the IEC,55.0,%,"IEC/HSRC Online Youth Survey 2023 (n=5,086, ag..."

======================================================================
SOCIOECONOMIC — KZN PROVINCE ONLY
======================================================================

,geography_level,geography_name,indicator,year,value,unit,source
0,Province,KwaZulu-Natal,"Poverty headcount (P0, %)",2011,56.900,%,StatsSA Poverty Trends (LBPL) by Province
1,Province,KwaZulu-Natal,"Poverty headcount (P0, %)",2015,59.600,%,StatsSA Poverty Trends (LBPL) by Province
2,Province,KwaZulu-Natal,"Poverty headcount (P0, %)",2023,49.600,%,StatsSA Poverty Trends (LBPL) by Province
3,Province,KwaZulu-Natal,"Poverty gap (P1, %)",2011,25.900,%,StatsSA Poverty Trends (LBPL) by Province
4,Province,KwaZulu-Natal,"Poverty gap (P1, %)",2015,27.100,%,StatsSA Poverty Trends (LBPL) by Province
5,Province,KwaZulu-Natal,"Poverty gap (P1, %)",2023,21.200,%,StatsSA Poverty Trends (LBPL) by Province
6,Province,KwaZulu-Natal,"Severity of poverty (P2, %)",2011,14.700,%,StatsSA Poverty Trends (LBPL) by Province
7,Province,KwaZulu-Natal,"Severity of poverty (P2, %)",2015,15.300,%,StatsSA Poverty Trends (LBPL) by Province
8,Province,KwaZulu-Natal,"Severity of poverty (P2, %)",2023,11.400,%,StatsSA Poverty Trends (LBPL) by Province
9,Province,KwaZulu-Natal,Poverty share (%),2011,24.700,%,StatsSA Poverty Trends (LBPL) by Province
10,Province,KwaZulu-Natal,Poverty share (%),2015,24.900,%,StatsSA Poverty Trends (LBPL) by Province
11,Province,KwaZulu-Natal,Poverty share (%),2023,24.800,%,StatsSA Poverty Trends (LBPL) by Province
24,Province,KwaZulu-Natal,"Food poverty headcount (FPL, %)",2011,29.100,%,StatsSA Food Poverty Headcount by Province (FPL)
25,Province,KwaZulu-Natal,"Food poverty headcount (FPL, %)",2015,31.000,%,StatsSA Food Poverty Headcount by Province (FPL)
26,Province,KwaZulu-Natal,"Food poverty headcount (FPL, %)",2023,27.300,%,StatsSA Food Poverty Headcount by Province (FPL)
27,Province,KwaZulu-Natal,Gini coefficient (income per capita),2011,0.672,index (0-1),StatsSA Income Inequality (Gini)
28,Province,KwaZulu-Natal,Gini coefficient (income per capita),2015,0.645,index (0-1),StatsSA Income Inequality (Gini)
29,Province,KwaZulu-Natal,Gini coefficient (income per capita),2023,0.604,index (0-1),StatsSA Income Inequality (Gini)

======================================================================
QLFS Q1 2024 — KZN PROVINCE ONLY
======================================================================

,Geography,Metric,Q1_2023,Q2_2023,Q3_2023,Q4_2023,Q1_2024,Qtr_to_qtr_change,Year_on_year_change,Qtr_to_qtr_percent,Year_on_year_percent
0,KwaZulu-Natal,Population 15–64 yrs,7503.0,7529.0,7556.0,7581.0,7607.0,26.0,104.0,0.3,1.4
1,KwaZulu-Natal,Labour force,3757.0,3829.0,3958.0,4053.0,4126.0,73.0,370.0,1.8,9.8
2,KwaZulu-Natal,Employed,2594.0,2642.0,2794.0,2856.0,2891.0,35.0,297.0,1.2,11.4
3,KwaZulu-Natal,Unemployed,1162.0,1187.0,1164.0,1197.0,1235.0,38.0,73.0,3.2,6.3
4,KwaZulu-Natal,Not economically active,3746.0,3701.0,3598.0,3528.0,3480.0,-48.0,-266.0,-1.3,-7.1
5,KwaZulu-Natal,Discouraged work-seekers,976.0,927.0,915.0,790.0,771.0,-19.0,-204.0,-2.4,-21.0
6,KwaZulu-Natal,Other (not economically active),2771.0,2774.0,2682.0,2738.0,2709.0,-29.0,-62.0,-1.1,-2.2
7,KwaZulu-Natal,Unemployment rate,30.9,31.0,29.4,29.5,29.9,0.4,-1.0,NaN,NaN
8,KwaZulu-Natal,Employed/population ratio (absorption),34.6,35.1,37.0,37.7,38.0,0.3,3.4,NaN,NaN
9,KwaZulu-Natal,Labour force participation rate,50.1,50.9,52.4,53.5,54.2,0.7,4.1,NaN,NaN

======================================================================
QLFS 2024 — KZN
======================================================================

,Province,Institution_type,Percentage,Total_attending_thousand
0,KwaZulu-Natal,Pre-school,1.8,NaN
1,KwaZulu-Natal,School,92.3,NaN
2,KwaZulu-Natal,Higher education institutions,3.4,NaN
3,KwaZulu-Natal,TVET,1.5,NaN
4,KwaZulu-Natal,Other colleges,0.5,NaN
5,KwaZulu-Natal,Home Schooling,0.0,NaN
6,KwaZulu-Natal,Other,0.4,NaN
7,KwaZulu-Natal,Total,NaN,3567.0

======================================================================
QLFS Q1 2026 — NATIONAL DATA
======================================================================

,Geography,Period,Indicator,Value_percent,Change_from_previous_quarter_percentage_points
0,South Africa,Q1:2026,Labour force participation rate,59.0,-0.3
1,South Africa,Q1:2026,Absorption rate,39.7,-0.9

KZN province-record inspection completed.

In [6]:
#5. — Prepare Province-Level Sources
# Purpose:
# Keep only KZN province records and identify the time coverage
# of each source before building the province context panel.

province_sources = {}

# Socioeconomic indicators — KZN province only
province_sources["socioeconomic"] = (
    socioeconomic_df[
        (socioeconomic_df["geography_level"] == "Province")
        & (socioeconomic_df["geography_name"] == "KwaZulu-Natal")
    ]
    .copy()
)

# Youth distrust — KZN only
province_sources["youth_distrust"] = (
    youth_df[
        youth_df["geography"] == "KwaZulu-Natal"
    ]
    .copy()
)

# QLFS Q1 2024 — KZN province only
province_sources["qlfs_q1_2024"] = (
    qlfs_q1_2024_df[
        qlfs_q1_2024_df["Geography"] == "KwaZulu-Natal"
    ]
    .copy()
)

for name, df in province_sources.items():
    print(f"{name}:")
    print(f"Rows: {len(df):,}")
    print(f"Columns: {len(df.columns)}")

    if name == "socioeconomic":
        print(f"Years: {sorted(df['year'].unique())}")

    elif name == "youth_distrust":
        print(f"Years: {sorted(df['year'].unique())}")

    elif name == "qlfs_q1_2024":
        print(f"Periods available: Q1 2023 to Q1 2024")

    print()

assert len(province_sources["socioeconomic"]) == 18
assert len(province_sources["youth_distrust"]) == 5
assert len(province_sources["qlfs_q1_2024"]) == 10

print("Province-level source preparation: PASSED")

socioeconomic:
Rows: 18
Columns: 7
Years: [np.int64(2011), np.int64(2015), np.int64(2023)]

youth_distrust:
Rows: 5
Columns: 6
Years: [np.int64(2023)]

qlfs_q1_2024:
Rows: 10
Columns: 11
Periods available: Q1 2023 to Q1 2024

Province-level source preparation: PASSED

In [7]:
#6. — Build Socioeconomic Province-Year Panel
# Purpose:
# Reshape the KZN socioeconomic indicators into one row per year
# so the province context panel has a consistent time structure.

socioeconomic_panel = (
    province_sources["socioeconomic"]
    .pivot_table(
        index=["geography_level", "geography_name", "year"],
        columns="indicator",
        values="value",
        aggfunc="first"
    )
    .reset_index()
)

socioeconomic_panel.columns.name = None

print("Socioeconomic province-year panel created.")
print(f"Rows: {len(socioeconomic_panel):,}")
print(f"Columns: {len(socioeconomic_panel.columns)}")
print()

print("Years:")
print(sorted(socioeconomic_panel["year"].unique()))

print()
print("Columns:")
print(socioeconomic_panel.columns.tolist())

print()
print("Panel preview:")
display(socioeconomic_panel)

assert len(socioeconomic_panel) == 3
assert socioeconomic_panel["year"].nunique() == 3
assert socioeconomic_panel["geography_name"].nunique() == 1

print()
print("Socioeconomic province-year panel: PASSED")

Socioeconomic province-year panel created.
Rows: 3
Columns: 9

Years:
[np.int64(2011), np.int64(2015), np.int64(2023)]

Columns:
['geography_level', 'geography_name', 'year', 'Food poverty headcount (FPL, %)', 'Gini coefficient (income per capita)', 'Poverty gap (P1, %)', 'Poverty headcount (P0, %)', 'Poverty share (%)', 'Severity of poverty (P2, %)']

Panel preview:

,geography_level,geography_name,year,"Food poverty headcount (FPL, %)",Gini coefficient (income per capita),"Poverty gap (P1, %)","Poverty headcount (P0, %)",Poverty share (%),"Severity of poverty (P2, %)"
0,Province,KwaZulu-Natal,2011,29.1,0.672,25.9,56.9,24.7,14.7
1,Province,KwaZulu-Natal,2015,31.0,0.645,27.1,59.6,24.9,15.3
2,Province,KwaZulu-Natal,2023,27.3,0.604,21.2,49.6,24.8,11.4

Socioeconomic province-year panel: PASSED

In [8]:
#7. — Reshape Youth Distrust Indicators
# Purpose:
# Reshape the 2023 KZN youth distrust indicators into columns
# so they can be attached to the matching province-year record.

youth_distrust_panel = (
    province_sources["youth_distrust"]
    .pivot_table(
        index=["geography", "year"],
        columns="indicator",
        values="value",
        aggfunc="first"
    )
    .reset_index()
)

youth_distrust_panel.columns.name = None

print("Youth distrust panel created.")
print(f"Rows: {len(youth_distrust_panel):,}")
print(f"Columns: {len(youth_distrust_panel.columns)}")
print()

print("Columns:")
print(youth_distrust_panel.columns.tolist())

print()
print("Panel preview:")
display(youth_distrust_panel)

assert len(youth_distrust_panel) == 1
assert youth_distrust_panel["year"].iloc[0] == 2023
assert youth_distrust_panel["geography"].iloc[0] == "KwaZulu-Natal"

print()
print("Youth distrust reshaping: PASSED")

Youth distrust panel created.
Rows: 1
Columns: 7

Columns:
['geography', 'year', 'Dissatisfied with democracy', 'Distrust of national government', 'Distrust of political parties', 'Distrust of provincial government', 'Distrust of the IEC']

Panel preview:

,geography,year,Dissatisfied with democracy,Distrust of national government,Distrust of political parties,Distrust of provincial government,Distrust of the IEC
0,KwaZulu-Natal,2023,85.0,83.0,77.0,80.0,55.0

Youth distrust reshaping: PASSED

In [9]:
#8. — Merge Youth Distrust with Socioeconomic Panel
# Purpose:
# Add the 2023 youth distrust indicators to the matching KZN
# province-year record without creating duplicate province-year rows.

province_context_panel = socioeconomic_panel.merge(
    youth_distrust_panel,
    left_on=["geography_name", "year"],
    right_on=["geography", "year"],
    how="left",
    validate="one_to_one"
)

province_context_panel = province_context_panel.drop(
    columns=["geography"]
)

print("Youth distrust merged successfully.")
print(f"Rows: {len(province_context_panel):,}")
print(f"Columns: {len(province_context_panel.columns)}")
print()

print("Years:")
print(sorted(province_context_panel["year"].unique()))

print()
print("Youth distrust availability:")
print(
    province_context_panel[
        [
            "year",
            "Dissatisfied with democracy",
            "Distrust of national government",
            "Distrust of political parties",
            "Distrust of provincial government",
            "Distrust of the IEC"
        ]
    ]
)

assert len(province_context_panel) == 3
assert province_context_panel["year"].nunique() == 3

print()
print("Youth distrust merge: PASSED")

Youth distrust merged successfully.
Rows: 3
Columns: 14

Years:
[np.int64(2011), np.int64(2015), np.int64(2023)]

Youth distrust availability:
   year  Dissatisfied with democracy  Distrust of national government  \
0  2011                          NaN                              NaN
1  2015                          NaN                              NaN
2  2023                         85.0                             83.0

   Distrust of political parties  Distrust of provincial government  \
0                            NaN                                NaN
1                            NaN                                NaN
2                           77.0                               80.0

   Distrust of the IEC
0                  NaN
1                  NaN
2                 55.0

Youth distrust merge: PASSED

In [10]:
#9. — Add QLFS Q1 2024 Context
# Purpose:
# Add the KZN Q1 2024 labour-market indicators as a dated province
# context snapshot without assigning them to earlier years.

qlfs_2024_context = (
    province_sources["qlfs_q1_2024"]
    [["Geography", "Metric", "Q1_2024"]]
    .copy()
)

qlfs_2024_context = (
    qlfs_2024_context
    .pivot_table(
        index="Geography",
        columns="Metric",
        values="Q1_2024",
        aggfunc="first"
    )
    .reset_index()
)

qlfs_2024_context.columns.name = None

print("QLFS Q1 2024 context created.")
print(f"Rows: {len(qlfs_2024_context):,}")
print(f"Columns: {len(qlfs_2024_context.columns)}")
print()

print("QLFS indicators:")
print(qlfs_2024_context.columns.tolist())

print()
print("QLFS Q1 2024 values:")
display(qlfs_2024_context)

assert len(qlfs_2024_context) == 1
assert qlfs_2024_context["Geography"].iloc[0] == "KwaZulu-Natal"

print()
print("QLFS Q1 2024 preparation: PASSED")

QLFS Q1 2024 context created.
Rows: 1
Columns: 11

QLFS indicators:
['Geography', 'Discouraged work-seekers', 'Employed', 'Employed/population ratio (absorption)', 'Labour force', 'Labour force participation rate', 'Not economically active', 'Other (not economically active)', 'Population 15–64 yrs', 'Unemployed', 'Unemployment rate']

QLFS Q1 2024 values:

,Geography,Discouraged work-seekers,Employed,Employed/population ratio (absorption),Labour force,Labour force participation rate,Not economically active,Other (not economically active),Population 15–64 yrs,Unemployed,Unemployment rate
0,KwaZulu-Natal,771.0,2891.0,38.0,4126.0,54.2,3480.0,2709.0,7607.0,1235.0,29.9

QLFS Q1 2024 preparation: PASSED

In [11]:
#10. — Add QLFS Snapshot to Province Panel
# Purpose:
# Add the Q1 2024 labour-market snapshot to the province panel
# while keeping its timing explicitly separate from the historical years.

qlfs_snapshot = qlfs_2024_context.rename(
    columns={
        "Geography": "qlfs_geography",
        "Discouraged work-seekers": "QLFS_Q1_2024_DiscouragedWorkSeekers",
        "Employed": "QLFS_Q1_2024_Employed_thousand",
        "Employed/population ratio (absorption)": "QLFS_Q1_2024_AbsorptionRate",
        "Labour force": "QLFS_Q1_2024_LabourForce_thousand",
        "Labour force participation rate": "QLFS_Q1_2024_LabourForceParticipationRate",
        "Not economically active": "QLFS_Q1_2024_NotEconomicallyActive_thousand",
        "Other (not economically active)": "QLFS_Q1_2024_OtherNotEconomicallyActive_thousand",
        "Population 15–64 yrs": "QLFS_Q1_2024_Population15_64_thousand",
        "Unemployed": "QLFS_Q1_2024_Unemployed_thousand",
        "Unemployment rate": "QLFS_Q1_2024_UnemploymentRate"
    }
)

province_context_panel = province_context_panel.assign(
    QLFS_Q1_2024_Snapshot=True
)

province_context_panel = province_context_panel.merge(
    qlfs_snapshot,
    how="cross",
    validate="many_to_one"
)

print("QLFS Q1 2024 snapshot added.")
print(f"Rows: {len(province_context_panel):,}")
print(f"Columns: {len(province_context_panel.columns)}")
print()

print("QLFS snapshot timing:")
print("Q1 2024")

print()
print("QLFS snapshot values:")
display(
    province_context_panel[
        [
            "year",
            "QLFS_Q1_2024_Snapshot",
            "QLFS_Q1_2024_Employed_thousand",
            "QLFS_Q1_2024_Unemployed_thousand",
            "QLFS_Q1_2024_UnemploymentRate",
            "QLFS_Q1_2024_AbsorptionRate",
            "QLFS_Q1_2024_LabourForceParticipationRate"
        ]
    ]
)

assert len(province_context_panel) == 3
assert province_context_panel["QLFS_Q1_2024_Snapshot"].all()

print()
print("QLFS snapshot merge: PASSED")

QLFS Q1 2024 snapshot added.
Rows: 3
Columns: 26

QLFS snapshot timing:
Q1 2024

QLFS snapshot values:

,year,QLFS_Q1_2024_Snapshot,QLFS_Q1_2024_Employed_thousand,QLFS_Q1_2024_Unemployed_thousand,QLFS_Q1_2024_UnemploymentRate,QLFS_Q1_2024_AbsorptionRate,QLFS_Q1_2024_LabourForceParticipationRate
0,2011,True,2891.0,1235.0,29.9,38.0,54.2
1,2015,True,2891.0,1235.0,29.9,38.0,54.2
2,2023,True,2891.0,1235.0,29.9,38.0,54.2

QLFS snapshot merge: PASSED

In [12]:
#10. — Store QLFS Q1 2024 Snapshot
# Purpose:
# Keep the QLFS labour-market snapshot separate from the historical
# province-year panel because it represents a specific Q1 2024 period.

qlfs_snapshot = qlfs_2024_context.rename(
    columns={
        "Geography": "QLFS_Geography",
        "Discouraged work-seekers": "QLFS_Q1_2024_DiscouragedWorkSeekers",
        "Employed": "QLFS_Q1_2024_Employed_thousand",
        "Employed/population ratio (absorption)": "QLFS_Q1_2024_AbsorptionRate",
        "Labour force": "QLFS_Q1_2024_LabourForce_thousand",
        "Labour force participation rate": "QLFS_Q1_2024_LabourForceParticipationRate",
        "Not economically active": "QLFS_Q1_2024_NotEconomicallyActive_thousand",
        "Other (not economically active)": "QLFS_Q1_2024_OtherNotEconomicallyActive_thousand",
        "Population 15–64 yrs": "QLFS_Q1_2024_Population15_64_thousand",
        "Unemployed": "QLFS_Q1_2024_Unemployed_thousand",
        "Unemployment rate": "QLFS_Q1_2024_UnemploymentRate"
    }
)

print("QLFS Q1 2024 snapshot prepared.")
print(f"Rows: {len(qlfs_snapshot):,}")
print(f"Columns: {len(qlfs_snapshot.columns):,}")
print()

print("QLFS snapshot:")
display(qlfs_snapshot)

assert len(qlfs_snapshot) == 1
assert qlfs_snapshot["QLFS_Geography"].iloc[0] == "KwaZulu-Natal"

print()
print("QLFS snapshot preparation: PASSED")

QLFS Q1 2024 snapshot prepared.
Rows: 1
Columns: 11

QLFS snapshot:

,QLFS_Geography,QLFS_Q1_2024_DiscouragedWorkSeekers,QLFS_Q1_2024_Employed_thousand,QLFS_Q1_2024_AbsorptionRate,QLFS_Q1_2024_LabourForce_thousand,QLFS_Q1_2024_LabourForceParticipationRate,QLFS_Q1_2024_NotEconomicallyActive_thousand,QLFS_Q1_2024_OtherNotEconomicallyActive_thousand,QLFS_Q1_2024_Population15_64_thousand,QLFS_Q1_2024_Unemployed_thousand,QLFS_Q1_2024_UnemploymentRate
0,KwaZulu-Natal,771.0,2891.0,38.0,4126.0,54.2,3480.0,2709.0,7607.0,1235.0,29.9

QLFS snapshot preparation: PASSED

In [13]:
#11. — Prepare Province Context Output
# Purpose:
# Combine the historical province-year panel with the clearly labelled
# QLFS Q1 2024 snapshot before final validation and saving.

province_context_output = province_context_panel.copy()

for column in qlfs_snapshot.columns:
    province_context_output[column] = qlfs_snapshot[column].iloc[0]

print("Province context output prepared.")
print(f"Rows: {len(province_context_output):,}")
print(f"Columns: {len(province_context_output.columns):,}")
print()

print("Historical years:")
print(sorted(province_context_output["year"].unique()))

print()
print("QLFS snapshot period: Q1 2024")

assert len(province_context_output) == 3
assert province_context_output["year"].tolist() == [2011, 2015, 2023]
assert province_context_output["QLFS_Geography"].eq("KwaZulu-Natal").all()

print()
print("Province context output preparation: PASSED")

Province context output prepared.
Rows: 3
Columns: 27

Historical years:
[np.int64(2011), np.int64(2015), np.int64(2023)]

QLFS snapshot period: Q1 2024

Province context output preparation: PASSED

In [15]:
#12. — Validate Province Context Panel
# Purpose:
# Verify the province-year grain, KZN coverage and QLFS snapshot
# before saving the completed province context panel.

print("Province context validation:")
print(f"Rows: {len(province_context_output):,}")
print(f"Unique years: {province_context_output['year'].nunique():,}")
print(f"Unique province: {province_context_output['geography_name'].nunique():,}")

print()
print("Duplicate province-year records:")
print(
    province_context_output
    .duplicated(subset=["geography_name", "year"])
    .sum()
)

print()
print("Missing values by year:")
display(
    province_context_output[
        ["year", "geography_name"]
    ].assign(
        MissingValues=province_context_output.isna().sum(axis=1)
    )
)

assert len(province_context_output) == 3
assert province_context_output["geography_name"].eq("KwaZulu-Natal").all()
assert province_context_output["year"].nunique() == 3
assert province_context_output.duplicated(
    subset=["geography_name", "year"]
).sum() == 0

print()
print("Province context validation: PASSED")

Province context validation:
Rows: 3
Unique years: 3
Unique province: 1

Duplicate province-year records:
0

Missing values by year:

   year geography_name  MissingValues
0  2011  KwaZulu-Natal              5
1  2015  KwaZulu-Natal              5
2  2023  KwaZulu-Natal              0

Province context validation: PASSED

The socioeconomic data covers 2011, 2015, and 2023, with values expected for each of these years. The youth distrust dataset contains observations only for 2023, so there are no equivalent 2011 or 2015 KZN observations. After merging the datasets into the province-year panel, we record the youth distrust values for 2011 and 2015 as `NaN`, while the 2023 values contain the available observations. We keep these values as `NaN` because missing data represents an unavailable observation, while `0% distrust` would represent an actual measured value. We apply the same approach to the QLFS snapshot, which is specifically from Q1 2024, so we treat those values as 2024 observations rather than assigning them to 2011, 2015, or 2023. During validation, the dataset shows five missing values for 2011 and 2015, so we will identify the specific five columns containing these missing values to confirm that they correspond only to the youth-distrust indicators before finalising Notebook 02.

In [16]:
#13. — Save Province Context Panel
# Purpose:
# Save the validated KZN province context panel so it can be used
# as a processed input for the later merging stage.

province_context_output.to_csv(
    CONTEXT_OUTPUT,
    index=False
)

print("Province context panel saved successfully.")
print(f"Output file: {CONTEXT_OUTPUT}")
print(f"Rows saved: {len(province_context_output):,}")
print(f"Columns saved: {len(province_context_output.columns):,}")

assert CONTEXT_OUTPUT.exists(), "Output file was not cr
print()
print("Save validation: PASSED")

Province context panel saved successfully.
Output file: C:\Users\Student\Downloads\Big Data\SPU-TEAM-DIRISA\data\processed\02_province_context_panel\province_context_panel_2011_2023.csv
Rows saved: 3
Columns saved: 27

Save validation: PASSED