In [3]:
from pathlib import Path
import pandas as pd

# Set the source and output paths for the ward economic context.
# We first verify the dataset's actual grain before allowing it into the ward pipeline.

source_path = Path(
    r"C:\Users\Student\Downloads\Big Data\SPU-TEAM-DIRISA\data\interim\KZN_Voter_Prediction_2021-2022 Cleaned\StatsSA_Ward_Product_2022_clean.xlsx"
)

output_dir = Path(
    r"C:\Users\Student\Downloads\Big Data\SPU-TEAM-DIRISA\data\processed\04_ward_economic_context"
)

output_dir.mkdir(parents=True, exist_ok=True)

print("Source exists:", source_path.exists())
print("Output folder:", output_dir)

Source exists: True
Output folder: C:\Users\Student\Downloads\Big Data\SPU-TEAM-DIRISA\data\processed\04_ward_economic_context

In [4]:
# Inspect the workbook sheets and basic structure before using the economic data.
# This helps us confirm whether the data is actually reported at ward level.

excel_file = pd.ExcelFile(source_path)

print("Sheets found:", excel_file.sheet_names)

for sheet in excel_file.sheet_names:
    preview = pd.read_excel(source_path, sheet_name=sheet, nrows=5)
    print(f"\n--- {sheet} ---")
    print("Shape preview:", preview.shape)
    print("Columns:")
    print(preview.columns.tolist())
    display(preview.head())

Sheets found: ['Table 1', 'Table 2']

--- Table 1 ---
Shape preview: (2, 1)
Columns:
['November 2025']

                                      November 2025
0  Ward Level Small Area Population Estimates, 2022
1                                    Technical Note

--- Table 2 ---
Shape preview: (5, 5)
Columns:
['The  right-hand  side  portion  of  Figure  2  above,  also  demonstrates that  no  convergence  is achieved by the first raking pass in the remaining 167 wards where the small area estimates of population size are higher from ward to ward compared to the corresponding Census 2022 figures. Here the SAEs in these wards overstate the population size found in Census 2022. This  extends  to  municipal  level,  and  further  to  provincial  and  national  levels  compared  to Census 2022. For reasons of compression, the overestimates are summed up by province, showing an overall margin of error of 0,69% nationally, ranging from a low of 0,29% to a high of 1,50% between the provinces. Table 2 below, gives a summary of the incidence of this error margin,  computed as the  percentage ratio between  the “extra”  persons added  by the first raking pass and the number of persons found in Census 2022.', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']

,"The right-hand side portion of Figure 2 above, also demonstrates that no convergence is achieved by the first raking pass in the remaining 167 wards where the small area estimates of population size are higher from ward to ward compared to the corresponding Census 2022 figures. Here the SAEs in these wards overstate the population size found in Census 2022. This extends to municipal level, and further to provincial and national levels compared to Census 2022. For reasons of compression, the overestimates are summed up by province, showing an overall margin of error of 0,69% nationally, ranging from a low of 0,29% to a high of 1,50% between the provinces. Table 2 below, gives a summary of the incidence of this error margin, computed as the percentage ratio between the “extra” persons added by the first raking pass and the number of persons found in Census 2022.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,Table 2: Overestimation of population size fro...,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN
2,Provinces,No. of\nwards,“Extra” persons added\nby first raking pass,Census\n2022,"Margin of error,\n%"
3,KwaZulu-Natal,40,67 970,12 423 907,"0,55"
4,Eastern Cape,25,54 781,7 230 204,"0,76"

This is why we performed the grain check before merging the data. We now have enough evidence to make the decision. `StatsSA_Ward_Product_2022_clean.xlsx` is not a ward-level data table. Table 1 contains only the title “Ward Level Small Area Population Estimates, 2022” and a technical note, while Table 2 provides an explanatory summary of population overestimation aggregated at provincial level. The KZN row contains only a provincial summary showing 40 wards, extra persons, Census 2022 population, and margin of error. There is no ward identifier, municipality code, ward code, or ward-level observation table available in the workbook. We will therefore not build `ward_economic_context_2022.csv` from this file because it would represent province-level technical information as ward-level economic context and would not match the grain of the eventual master dataset. For Group 4, `04_Ward_Economic_Context.ipynb` will therefore be marked as conditional and not built from this source. We will document this exclusion and create Cell 03 to formally record the grain decision in the notebook.

In [5]:
# The workbook contains a technical note and province-level summary, not ward-level records.
# We exclude it from the ward context table rather than introducing the wrong geographic grain.

ward_level_confirmed = False

print("Ward-level grain confirmed:", ward_level_confirmed)
print("Decision: StatsSA_Ward_Product_2022_clean.xlsx excluded from the ward economic context.")

Ward-level grain confirmed: False
Decision: StatsSA_Ward_Product_2022_clean.xlsx excluded from the ward economic context.